SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
/***********************************************************************
	TITLE: STANDARD API INTERFACE REPORT

DATE				VER		CREATEDBY   PURPOSE
21-OCT-2021		1.0		JAM			FOR INTERFACE CHECKING 
22-OCT-2021		1.1		JarekLim		Create In UAT https://jiralfl.atlassian.net/browse/WMS-18234
01-Apr-2022		1.2     gywong			Modified https://jiralfl.atlassian.net/browse/WMS-19292
01-June-2022    1.3     JarekLim        Added Query column for IT reference checking  https://jiralfl.atlassian.net/browse/WMS-19745
01-June-2022    1.3     JAM             Added new condition WSC.HTTPSTATUSCODE<>'200'  https://jiralfl.atlassian.net/browse/WMS-22853
26-Sept-2023    1.4     Crisnah     Added wolinbound_log table for extracting incoming payload https://jiralfl.atlassian.net/browse/WMS-23741
************************************************************************/
-- Test:   EXEC BI.nsp_STD_InterfaceReportAPI 'YLEO','5246','','2021-04-01','2021-10-01'
-- Test:   EXEC BI.nsp_STD_InterfaceReportAPI '','','','',''
CREATE     PROC [BI].[nsp_STD_InterfaceReportAPI]
			@PARAM_GENERIC_STORERKEY NVARCHAR(30)=''
			, @PARAM_GENERIC_DATASTREAM NVARCHAR(10)=''
			, @PARAM_GENERIC_ORDERNO NVARCHAR(50)= ''
			, @PARAM_GENERIC_TRANSACTIONDATEFROM DATETIME=''
			, @PARAM_GENERIC_TRANSACTIONDATETO DATETIME=''
AS
BEGIN
 SET NOCOUNT ON;  -- keeps the output generated to a minimum 
   SET ANSI_NULLS OFF;
   SET QUOTED_IDENTIFIER OFF;
   SET CONCAT_NULL_YIELDS_NULL OFF;

	IF ISNULL(@PARAM_GENERIC_StorerKey, '') = ''
		SET @PARAM_GENERIC_StorerKey = ''

DECLARE @nRowCnt INT = 0
       , @Proc      NVARCHAR(128) = 'nsp_STD_InterfaceReportAPI'
       , @cParamOut NVARCHAR(4000)= ''
       , @cParamIn  NVARCHAR(4000)= '{ "PARAM_GENERIC_StorerKey":"'    +@PARAM_GENERIC_StorerKey+'"'
                                    + '"PARAM_GENERIC_DATASTREAM":"'    +@PARAM_GENERIC_DATASTREAM+'"'
												+ '"PARAM_GENERIC_ORDERNO":"'    +@PARAM_GENERIC_ORDERNO+'"'
                                    + '"PARAM_GENERIC_TRANSACTIONDATEFROM":"'+CONVERT(NVARCHAR(19),@PARAM_GENERIC_TRANSACTIONDATEFROM)+'",'
                                    + '"PARAM_GENERIC_TRANSACTIONDATETO":"'+CONVERT(NVARCHAR(19),@PARAM_GENERIC_TRANSACTIONDATETO,121)+'"'
                                    + ' }'

DECLARE  @tVarLogId TABLE (LogId INT);
   INSERT dbo.ExecutionLog (ClientId, SP, ParamIn) OUTPUT INSERTED.LogId INTO @tVarLogId VALUES (@PARAM_GENERIC_StorerKey, @Proc, @cParamIn);

	DECLARE @Stmt NVARCHAR(MAX) = ''

DECLARE
	@C_ITFDESCR NVARCHAR(200)	-- interface DESCR from WOL_ItfConfig
	, @C_CTR INTEGER			-- INCREMENTING COUNTER IN LOOP CONDITION
	, @C_SQL NVARCHAR(1000)		-- SQL STRING
	, @C_TABLE NVARCHAR(100)	-- TABLE NAME VALUE
	, @C_COLS NVARCHAR(1000)	-- COLUMNS TO CAPTURE PER TABLE NAME
	, @C_WSDTCOUNT INTEGER		-- COUNT OF DATA FROM TEMP TABLE LIST
	, @C_PKEY NVARCHAR(50)		-- PRIMARY/REFERENCE KEY COLUMN NAME EACH TABLE
	, @C_QRY NVARCHAR(500)		-- QUERY PRINT RESULT
   , @C_DIR NVARCHAR(500)		-- INBOUND / OUTBOUND

	(select @C_ITFDESCR=DESCR, @C_DIR=ITFTYPE from WOL_ItfConfig WITH (NOLOCK) WHERE DATASTREAM=@PARAM_GENERIC_DATASTREAM)

	IF DATEDIFF(HOUR,@PARAM_GENERIC_TRANSACTIONDATEFROM,@PARAM_GENERIC_TRANSACTIONDATETO) > 24
	   BEGIN -- CHECKPOINT: TO LIMIT DATETIME RANGE TO EQUAL OR LESS THAN 24 HRS
			SET @PARAM_GENERIC_TRANSACTIONDATETO = dateadd(day,1,@PARAM_GENERIC_TRANSACTIONDATEFROM) 
	   END

	IF OBJECT_ID ('tempdb..#TMP_WSDTITF') IS NOT NULL 
		BEGIN
			DROP TABLE #TMP_WSDTITF
		END
	-- TEMP TABLE COLLECTING IMPT FIELDS FROM WSDT TABLE
	CREATE TABLE [#TMP_WSDTITF] (
	 ITF_DATASTREAM [NVARCHAR](10) NULL			--@PARAM_GENERIC_DATASTREAM
	 , ITF_TYPE [NVARCHAR](100) NULL				--@C_ITFDESCR
    , ITF_WSDTKEY [NVARCHAR] (10) NULL			--WSDTKEY
	 , ITF_DIRECTION [NVARCHAR](20) NULL			--WSDT HEADER FLAG
    , ITF_BATCHNO [NVARCHAR] (100) NULL			--WSDT BATCH NO
    , ITF_ORDERGRP [NVARCHAR] (50) NULL			--WSDT GROUP ID
	 , ITF_ORDERNO [NVARCHAR] (50) NULL			--WSDT PRIMARY KEYS / @PARAM_GENERIC_ORDERNO
	 , ITF_REFCOLUMN [NVARCHAR] (50) NULL		--WSDT REFERENCE COLUMN NAME / TBL_PKEY
    , ITF_STATUS [NVARCHAR] (10) NULL			--WSDT STATUS
	 , ITF_TRANSACTIONDATE [DATETIME] NULL		--WSDT ADD DATE
	 , ITF_ERRMSG [NVARCHAR] (500) NULL			--WSDT ERRMSG
	 , ITF_QUERY [NVARCHAR] (500) NULL --QUERY FOR IT CHECKING
   )


	-- SELECT * FROM #TMP_WSDTTBL
	-- select * from phwms..codelkup where listname='LOGIRPTITF'
SET @C_WSDTCOUNT = (SELECT COUNT(*) FROM phwms.dbo.CODELKUP WITH (NOLOCK) where listname='LOGIRPTITF')
SET @C_CTR = 1

WHILE (@C_CTR <= @C_WSDTCOUNT) -- START LOOP HERE
	BEGIN
		SET @C_TABLE = (SELECT Description FROM phwms.dbo.CODELKUP  C WITH (NOLOCK) WHERE listname='LOGIRPTITF' AND CAST(code AS INT)=@C_CTR)
		SET @C_COLS = (SELECT Long FROM phwms.dbo.CODELKUP WITH (NOLOCK) where listname='LOGIRPTITF' AND CAST(code AS INT)=@C_CTR)	
		SET @C_PKEY = (SELECT UDF01 FROM phwms.dbo.CODELKUP WITH (NOLOCK) where listname='LOGIRPTITF' AND CAST(code AS INT)=@C_CTR)
			-- INSERT FROM TEMP TABLE HERE
			IF ISNULL(@PARAM_GENERIC_ORDERNO,'') <> '' -- IF ORDER NO. IS NOT BLANK, CONDITION: PRIMARYKEY BASED
				BEGIN
					SET @C_QRY = 'SELECT ''''' + @PARAM_GENERIC_DATASTREAM + ''''',''''' 
						+ @C_ITFDESCR + ''''',''''' + @C_PKEY + ''''',' + @C_COLS 
						+ ',WSDT_STATUS,ADDDATE,ERRMSG FROM ' + @C_TABLE 
						+ ' WITH (NOLOCK) where datastream=''''' + @PARAM_GENERIC_DATASTREAM 
						+ ''''' AND ' + @C_PKEY + '=''''' + @PARAM_GENERIC_ORDERNO 
						+ ''''''
						
					SET @C_SQL = 'INSERT INTO #TMP_WSDTITF (ITF_DATASTREAM,ITF_TYPE,ITF_REFCOLUMN,ITF_WSDTKEY,ITF_DIRECTION,ITF_BATCHNO
									 ,ITF_ORDERGRP,ITF_ORDERNO,ITF_STATUS,ITF_TRANSACTIONDATE,ITF_ERRMSG,ITF_QUERY)
									 SELECT ''' + @PARAM_GENERIC_DATASTREAM + ''',''' + @C_ITFDESCR + ''',''' + @C_PKEY + ''','
									 + @C_COLS + ',WSDT_STATUS,ADDDATE,ERRMSG,'''+@C_QRY+''' 
									 FROM ' + @C_TABLE + ' WITH (NOLOCK) where datastream=''' + @PARAM_GENERIC_DATASTREAM + ''' AND ' +
									 @C_PKEY + '=''' + @PARAM_GENERIC_ORDERNO + ''''
				END
			ELSE	-- IF ORDER NO. IS BLANK, CONDITION: DATETIME RANGE BASED
				BEGIN
					SET @C_QRY = 'SELECT ''''' + @PARAM_GENERIC_DATASTREAM + ''''',''''' 
						+ @C_ITFDESCR + ''''',''''' + @C_PKEY + ''''',' + @C_COLS 
						+ ',WSDT_STATUS,ADDDATE,ERRMSG ' + 'FROM ' + @C_TABLE 
						+ ' WITH (NOLOCK) where datastream=''''' + @PARAM_GENERIC_DATASTREAM 
						+ ''''' AND ADDDATE BETWEEN ''''' 
						+ CONVERT(NVARCHAR(30),@PARAM_GENERIC_TRANSACTIONDATEFROM,121) 
						+ ''''' AND ''''' + CONVERT(NVARCHAR(30),@PARAM_GENERIC_TRANSACTIONDATETO,121) 
						+ ''''''

					SET @C_SQL = 'INSERT INTO #TMP_WSDTITF (ITF_DATASTREAM,ITF_TYPE,ITF_REFCOLUMN,ITF_WSDTKEY,ITF_DIRECTION,ITF_BATCHNO
									 ,ITF_ORDERGRP,ITF_ORDERNO,ITF_STATUS,ITF_TRANSACTIONDATE,ITF_ERRMSG,ITF_QUERY)
									 SELECT ''' + @PARAM_GENERIC_DATASTREAM + ''',''' + @C_ITFDESCR + ''',''' + @C_PKEY + ''','
									 + @C_COLS + ',WSDT_STATUS,ADDDATE,ERRMSG,'''+@C_QRY+'''  
									 FROM ' + @C_TABLE + ' WITH (NOLOCK) where datastream=''' + @PARAM_GENERIC_DATASTREAM + ''' AND 
									 ADDDATE BETWEEN ''' + CONVERT(NVARCHAR(30),@PARAM_GENERIC_TRANSACTIONDATEFROM,121) + 
									 ''' AND ''' + CONVERT(NVARCHAR(30),@PARAM_GENERIC_TRANSACTIONDATETO,121) + ''''
				END
			PRINT (@C_SQL)
			EXECUTE (@C_SQL)
		SET @C_CTR = @C_CTR + 1
	END

-- SELECT * FROM #TMP_WSDTITF
   SELECT TOP 1 @STMT = ITF_QUERY FROM #TMP_WSDTITF

	 SELECT
		TW.ITF_TYPE as 'Interface Type'
		, TW.ITF_DATASTREAM as 'DataStream'
		, TW.ITF_DIRECTION as 'Header Flag'
		, TW.ITF_WSDTKEY AS 'WSDTKey'
		, CASE WHEN @C_DIR='I' THEN CASE WHEN ISNULL(WI.Direction,'')='' THEN WI2.Direction ELSE WI.Direction END ELSE WO.Direction END AS 'Direction'
		, TW.ITF_REFCOLUMN AS 'Reference Column.'
		, TW.ITF_ORDERNO AS 'Reference No.'
		, TW.ITF_ORDERGRP AS 'Group ID'
		, CASE WHEN @C_DIR='I' THEN CASE WHEN ISNULL(WI.BATCHNO,'')='' THEN WI2.BATCHNO ELSE WI.BATCHNO END ELSE WO.BATCHNO END AS 'BatchNo.'
		, TW.ITF_STATUS AS 'WSDT_Status'
		, CASE WHEN @C_DIR='I' THEN CASE WHEN ISNULL(WI.STATUS,'')='' THEN WI2.STATUS ELSE WI.STATUS END ELSE WO.STATUS END AS 'WOL_Status'
		, TW.ITF_TRANSACTIONDATE AS 'Transaction Date'
		, TW.ITF_ERRMSG as 'Error Msg'
		, WSC.WSC_RESPONSESTRING as 'WSC_ResponseString'
		, CASE WHEN @C_DIR='I' THEN CASE WHEN ISNULL(WI.WSDATA,'')='' THEN WI2.WSDATA ELSE WI.WSDATA END ELSE WO.WSDATA END as 'Payload' 
		, TW.ITF_QUERY AS 'QUERY'
	FROM #TMP_WSDTITF TW WITH (nolock) 
	LEFT JOIN BI.V_DTS_woloutbound_log WO WITH (NOLOCK) 
	ON WO.wsdtkey=TW.ITF_WSDTKEY AND WO.datastream=TW.ITF_DATASTREAM 
	LEFT JOIN BI.V_DTS_wolINbound_log WI WITH (NOLOCK) 
	ON WI.wsdtkey=TW.ITF_WSDTKEY AND WI.datastream=TW.ITF_DATASTREAM 
	LEFT JOIN BI.V_DTS_wolINbound_log WI2 WITH (NOLOCK) 
	ON WI2.BATCHNO=TW.ITF_BATCHNO AND WI2.datastream=TW.ITF_DATASTREAM 
	LEFT JOIN BI.V_DTS_WSC_ResponseLog WSC WITH (NOLOCK) 
	ON TW.ITF_DATASTREAM=WSC.datastream AND TW.ITF_WSDTKEY=WSC.wsdtkey --AND TW.ITF_BATCHNO=WSC.BATCHNO --REMOVE
										  
	AND WSC.HTTPSTATUSCODE<>'200' --GET RESULT ONLY IF NOT SUCCESSFUL
	ORDER BY 12

   
SET @nRowCnt = @@ROWCOUNT;

   SET @cParamOut = '{ "Stmt": "'+@Stmt+'" }'; -- for dynamic SQL only
   UPDATE dbo.ExecutionLog SET TimeEnd = GETDATE(), RowCnt = @nRowCnt, ParamOut = @cParamOut
   WHERE LogId = (SELECT TOP 1 LogId FROM @tVarLogId);

END

GO