SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO


CREATE  View [dbo].[V_BACKENDSHIP_ERRORS] AS 
      SELECT distinct MBOL.MBOLKEY ,  MBOL.EffectiveDate LAST_ATTEMPT, MBOL.ShipCounter NUMBER_ATTEMPTS, orderdetail.orderkey ORDERKEY
      FROM ORDERDETAIL WITH (NOLOCK)
      JOIN PICKDETAIL WITH (NOLOCK, INDEX(PICKDETAIL_OrderDetStatus)) ON (PICKDETAIL.OrderKey = ORDERDETAIL.OrderKey AND
                                         PICKDETAIL.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER )
      JOIN  MBOLDETAIL (NOLOCK) ON MBOLDETAIL.MBOLKey = ORDERDETAIL.MBOLKey AND MBOLDETAIL.OrderKey = ORDERDETAIL.OrderKey
      JOIN  MBOL (NOLOCK) ON (MBOL.MBOLKey = MBOLDETAIL.MBOLKey)
      WHERE PICKDETAIL.Status < '9' AND  MBOL.Status = '9' and mbol.ShipCounter >1



GO