SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO


CREATE  View [dbo].[V_BACKENDSHIP_QUEUE] AS 
      SELECT  MBOL.MBOLKEY ,  MBOL.EffectiveDate, MBOL.ShipCounter ATTEMPTS, count(*) NUMBER_OF_LINES
      FROM ORDERDETAIL WITH (NOLOCK)
      JOIN PICKDETAIL WITH (NOLOCK, INDEX(PICKDETAIL_OrderDetStatus)) ON (PICKDETAIL.OrderKey = ORDERDETAIL.OrderKey AND
                                         PICKDETAIL.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER )
      JOIN  MBOLDETAIL (NOLOCK) ON MBOLDETAIL.MBOLKey = ORDERDETAIL.MBOLKey AND MBOLDETAIL.OrderKey = ORDERDETAIL.OrderKey
      JOIN  MBOL (NOLOCK) ON (MBOL.MBOLKey = MBOLDETAIL.MBOLKey)
      WHERE PICKDETAIL.Status < '9' AND   MBOL.Status = '9'  AND 
      ( MBOL.ShipCounter = 1 or MBOL.ShipCounter is null or Mbol.ShipCounter = ' ')
      GROUP BY MBOL.MBOLKEY ,  MBOL.EffectiveDate, MBOL.ShipCounter



GO