SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
CREATE VIEW [dbo].[V_BILL_STOCKMOVEMENT] 
AS 
SELECT [StorerKey]
, [Sku]
, [Lot]
, [Qty]
, [EffectiveDate]
, [AddWho]
FROM [BILL_STOCKMOVEMENT] (NOLOCK) 

GO