SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
CREATE VIEW [dbo].[V_HOSTINTERFACE] 
AS 
SELECT [hikey]
, [hiprocess]
, [hidescrip]
, [hifile1]
, [hifile2]
, [hifile3]
, [hifile4]
, [hifile5]
, [hifile6]
, [hifile1type]
, [hifile2type]
, [hifile3type]
, [hifile4type]
, [hifile5type]
, [hifile6type]
, [hilogfile]
, [hidopost]
, [hiusetimer]
, [hitimerinterval]
, [hiimpexp]
, [hidirectdwimport]
, [hidefaultstorer]
, [hierasefiles]
, [hirevheader]
, [hirevdetail]
, [hirevsubdetail]
, [hiheader]
, [hidetail]
, [hisubdetail]
, [hirevother1]
, [hirevother2]
, [hirevother3]
, [hiother1]
, [hiother2]
, [hiother3]
, [hipreruncommand]
, [hipostruncommand]
, [hiprintdoc1]
, [hiprintdoc2]
, [hiprintdoc3]
, [hiprintdoc4]
, [hiprintdoc5]
, [hiprintdoc6]
, [hiprinter1]
, [hiprinter2]
, [hiprinter3]
, [hiprinter4]
, [hiprinter5]
, [hiprinter6]
, [Autocreatepalheader]
, [hiAutoShipPallet]
, [Autocreatectrheader]
, [hiAutoShipContainer]
, [hidoOP]
, [hiOPKey]
, [HiAddSku]
, [HiAddStorer]
FROM [HOSTINTERFACE] (NOLOCK) 

GO