SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
CREATE VIEW [dbo].[V_IDS_INV_001]
AS
SELECT LOC.Facility, 
		Facility.Descr AS 'facility_Descr',			
		LOTXLOCXID.StorerKey AS 'Storer', 			
		STORER.Company AS 'company',
		SKU.SUSR3 AS 'principal',			
		CODE_PRINCIPAL.CODE_DESC AS 'principal_desc',
		LOTXLOCXID.SKU, 
		SKU.MANUFACTURERSKU, 
		SKU.RETAILSKU,
	   SKU.ALTSKU, 
		SKU.Descr,
		(SKU.BUSR1 + SKU.BUSR2) AS 'second_lang_Descr',
		UPPER(SKU.Class) AS 'class',
		UPPER(SKU.SKUgroup) AS 'groupcode',
		CODE_SKUGROUP.CODE_DESC AS 'groupcode_desc',
		UPPER(SKU.ABC) AS 'abc',
		CODE_ABC.CODE_DESC AS 'abc_desc',
		UPPER(SKU.itemclass) AS 'itemclass',
		CODE_ITEMCLASS.CODE_DESC AS 'itemclass_desc',
		UPPER(SKU.BUSR3) AS 'classification',
		CODE_SKUFLAG.CODE_DESC AS 'classification_desc',
		UPPER(SKU.BUSR5) AS 'productgroup',
		SKU.BUSR8 AS 'poison_flag',
		SKU.BUSR9 AS 'condition',
		SKU.ShelfLife AS 'shelflife',
		LOTxLOCxID.Qty, 
		LOTxLOCxID.QtyAllocated, 
		LOTxLOCxID.QtyPicked, 
		LOTxLOCxID.QtyPickInProcess,
		ISNULL(ON_HOLD.QtyOnhold, 0) AS 'QtyOnhold',
		SKU.Price,
		SKU.Cost,
		SKU.LOTTABLE01LABEL AS 'L1_LABEL',
		CODE_LOTTABLE01.CODE_DESC AS 'L1_LABEL_DESC',
		LOTATTRIBUTE.LOTTABLE01 AS 'L1',
		SKU.LOTTABLE02LABEL AS 'L2_LABEL',
		CODE_LOTTABLE02.CODE_DESC AS 'L2_LABEL_DESC',
		LOTATTRIBUTE.LOTTABLE02 AS 'L2',
		SKU.LOTTABLE03LABEL AS 'L3_LABEL',
		CODE_LOTTABLE03.CODE_DESC AS 'L3_LABEL_DESC',
		LOTATTRIBUTE.LOTTABLE03 AS 'L3',
		SKU.LOTTABLE04LABEL AS 'L4_LABEL',
		CODE_LOTTABLE04.CODE_DESC AS 'L4_LABEL_DESC',
		LOTATTRIBUTE.LOTTABLE04 AS 'L4',
		SKU.LOTTABLE05LABEL AS 'L5_LABEL',
		CODE_LOTTABLE05.CODE_DESC AS 'L5_LABEL_DESC',
		LOTATTRIBUTE.LOTTABLE05 AS 'L5',
		UPPER(SKU.Packkey) AS 'Packkey',
		PACK.PACKUOM3 AS 'Master unit',
		CODE_UOM3.CODE_DESC AS 'Master_unit_DESC',
		PACK.QTY AS 'MU_UNITS',
		PACK.PACKUOM2 AS 'INNER UOM',
		CODE_UOM2.CODE_DESC AS 'INNER_UOM_DESC',
		PACK.INNERPACK AS 'INNER_UOM_QTY',
		PACK.PACKUOM1 AS 'CASE_UOM',
		CODE_UOM1.CODE_DESC AS 'CASE_UOM_DESC',
		PACK.CASECNT AS 'CASE_UOM_QTY',
		PACK.PACKUOM4 AS 'PL_UOM',
		CODE_UOM4.CODE_DESC AS 'PL_UOM_DESC',
		PACK.Pallet AS 'PL_UOM_QTY',
		PACK.PalletTI AS 'UNITS_PER_LAYER',
		PACK.PalletHI AS 'LAYERS_PER_PL',
		SKU.Length AS 'MU_LENGTH',
		SKU.Width AS 'MU_WIDTH',
		SKU.Height AS 'MU_HEIGHT',
		PACK.LengthUOM2 AS 'LENGTH',
		PACK.WidthUOM2 AS 'WIDTH',
		PACK.HeightUOM2 AS 'HEIGHT',
		PACK.CubeUOM2 AS 'CUBE',
		SKU.STDGROSSWGT AS 'STD_GROSS_WEIGHT',
		SKU.STDNETWGT AS 'STD_NET_WEIGHT',
		SKU.STDCUBE AS 'STD_CUBE',
		LOTxLOCxID.Lot AS 'SYS_LOT_NO',
		LOTxLOCxID.Loc AS 'LOCATION', 
		LOC.PutawayZONe AS 'LOC_ZONE',
		PUTAWAYZONE.ZONeCategory AS 'LOC_ZONE_CATEGORY',
		LOC.ChargingPallet AS 'LOC_CHARGING_PALLET',
		UPPER(LOC.LocatiONFlag) AS 'LOC_FLAG',
		LOC.CubicCapacity AS 'LOC_CUBIC_CAPACITY',
		LOC.WeightCapacity AS 'LOC_WEIGHT_CAPACITY',
		LOTxLOCxID.ID AS 'MUID',
		(LOTXLOCXID.Qty - 
			LOTXLOCXID.Qtyallocated - 
				LOTXLOCXID.Qtypicked - 
					LOTXLOCXID.Qtypickinprocess - 
						ISNULL(ON_HOLD.QtyONhold, 0)) AS 'Qtyavailable'
FROM dbo.LOTXLOCXID LOTXLOCXID (NOLOCK) 
JOIN dbo.LOTATTRIBUTE LOTATTRIBUTE (NOLOCK, INDEX(pklotattribute))
ON LOTXLOCXID.Lot = LOTATTRIBUTE.Lot
JOIN LOT (NOLOCK)
	ON LOTXLOCXID.Lot = LOT.Lot
JOIN LOC (NOLOCK)
	ON LOTXLOCXID.Loc = LOC.Loc
JOIN FACILITY (NOLOCK)
	ON LOC.Facility = FACILITY.Facility
JOIN PUTAWAYZONE (NOLOCK)
	ON LOC.PutawayZONe = PUTAWAYZONE.PutawayZONe
JOIN SKU (NOLOCK)
	ON LOTXLOCXID.Storerkey = SKU.Storerkey
		AND LOTXLOCXID.SKU = SKU.SKU
JOIN STORER (NOLOCK)
	ON LOTXLOCXID.Storerkey = STORER.Storerkey
JOIN PACK (NOLOCK)
	ON SKU.Packkey = PACK.Packkey
LEFT OUTER JOIN (
						SELECT LOTXLOCXID.SKU, LOTXLOCXID.LOT, 
									 LOTXLOCXID.LOC, 
									 LOTXLOCXID.ID, 
									 SUM(LOTXLOCXID.QTY) AS QTYONhold
						FROM LOTXLOCXID (NOLOCK) 
						JOIN LOC (NOLOCK) ON LOTXLOCXID.loc = LOC.loc
						 AND LOC.locatiONflag = 'HOLD'
						JOIN ID (NOLOCK)
							ON LOTXLOCXID.ID = ID.ID
						 AND ID.Status = 'HOLD'	
						JOIN LOT (NOLOCK)
							ON LOTXLOCXID.Lot = LOT.Lot
						 AND LOT.QtyONhold > 0
						GROUP BY LOTXLOCXID.SKU, LOTXLOCXID.lot, LOTXLOCXID.loc, LOTXLOCXID.id
						HAVING SUM(LOTXLOCXID.QTY) > 0) AS ON_HOLD
	 ON LOTXLOCXID.Lot = ON_HOLD.Lot
  AND LOTXLOCXID.Loc = ON_HOLD.Loc
	AND LOTXLOCXID.ID = ON_HOLD.ID
	AND LOTXLOCXID.SKU = ON_HOLD.SKU
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'PRINCIPAL') AS CODE_PRINCIPAL
	ON SKU.SUSR3 = CODE_PRINCIPAL.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'SKUGROUP') AS CODE_SKUGROUP
	ON SKU.SKUgroup = CODE_SKUGROUP.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'ABC') AS CODE_ABC
	ON SKU.ABC = CODE_ABC.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'ITEMCLASS') AS CODE_ITEMCLASS
	ON SKU.ItemClass = CODE_ITEMCLASS.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'SKUFLAG') AS CODE_SKUFLAG
	ON SKU.BUSR3 = CODE_SKUFLAG.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'LOTTABLE01') AS CODE_LOTTABLE01
	ON SKU.LOTTABLE01LABEL = CODE_LOTTABLE01.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'LOTTABLE02') AS CODE_LOTTABLE02
	ON SKU.LOTTABLE02LABEL = CODE_LOTTABLE02.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'LOTTABLE03') AS CODE_LOTTABLE03
	ON SKU.LOTTABLE03LABEL = CODE_LOTTABLE03.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'LOTTABLE04') AS CODE_LOTTABLE04
	ON SKU.LOTTABLE04LABEL = CODE_LOTTABLE04.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'LOTTABLE05') AS CODE_LOTTABLE05
	ON SKU.LOTTABLE05LABEL = CODE_LOTTABLE05.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'QUANTITY') AS CODE_UOM1
	ON PACK.PACKUOM1 = CODE_UOM1.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'QUANTITY') AS CODE_UOM2
	ON PACK.PACKUOM2 = CODE_UOM2.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'QUANTITY') AS CODE_UOM3
	ON PACK.PACKUOM3 = CODE_UOM3.CODE
LEFT OUTER JOIN (SELECT CODE, Description AS 'CODE_DESC'
					  FROM CODELKUP (NOLOCK)
					  WHERE Listname = 'QUANTITY') AS CODE_UOM4
	ON PACK.PACKUOM4 = CODE_UOM4.CODE
WHERE LOTXLOCXID.QTY > 0




GO