SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO

CREATE VIEW [dbo].[V_Index]
AS 
   select TABLE_NAME, CONSTRAINT_NAME,  ORDINAL_POSITION , COLUMN_NAME
   from INFORMATION_SCHEMA.KEY_COLUMN_USAGE




GO