SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO









CREATE VIEW [dbo].[V_Inventory]
AS 
	SELECT LOC.FACILITY, 
STORER.STORERKEY,
STORER.COMPANY,
SKU.SKU, 
SKU.DESCR,
SUM(LOTxLOCxID.QTY) - SUM(LOTxLOCxID.QtyAllocated) - SUM(LOTxLOCxID.QtyPicked) AS 'Qty',
'Available' AS 'Status',
MAX(SKU.StdCube) AS 'Cube',
MAX(SKU.STDGROSSWGT) AS 'Weight',
LOTATTRIBUTE.Lottable02 AS 'Batch#',
LOTATTRIBUTE.Lottable04 As 'ExpiryDate',
LOTATTRIBUTE.Lottable05 AS 'ReceiptDate',
DateAdd(day, CAST(MAX(ISNULL(SKU.BUSR2,0)) as int) * -1 , LOTATTRIBUTE.Lottable04) As'SaleByDate'
FROM SKU (NOLOCK)
JOIN STORER (NOLOCK) ON (SKU.STORERKEY = STORER.STORERKEY)
JOIN LOTxLOCxID (NOLOCK) ON (LOTxLOCxID.StorerKey = SKU.StorerKey AND
                             LOTxLOCxID.SKU = SKU.SKU)
JOIN LOTATTRIBUTE (NOLOCK) ON (LOTATTRIBUTE.LOT = LOTxLOCxID.LOT)
JOIN LOC (NOLOCK) ON (LOC.LOC = LOTxLOCxID.LOC)
JOIN LOT (NOLOCK) ON (LOT.LOT = LOTxLOCxID.LOT)
JOIN ID  (NOLOCK) ON (ID.ID = LOTxLOCxID.ID)
WHERE LOT.STATUS = 'OK' AND
LOC.STATUS = 'OK' AND
ID.STATUS  = 'OK' AND 
LOC.LocationFlag = 'NONE' AND
LOTxLOCxID.Qty > 0
GROUP BY LOC.FACILITY, 
STORER.STORERKEY,
STORER.COMPANY,
SKU.SKU, 
SKU.DESCR,
LOTATTRIBUTE.Lottable02,
LOTATTRIBUTE.Lottable04,
LOTATTRIBUTE.Lottable05
UNION
SELECT LOC.FACILITY, 
STORER.STORERKEY,
STORER.COMPANY,
SKU.SKU, 
SKU.DESCR,
SUM(LOTxLOCxID.QTY) - SUM(LOTxLOCxID.QtyAllocated) - SUM(LOTxLOCxID.QtyPicked) AS 'Qty',
'Hold' AS 'Status',
MAX(SKU.StdCube) AS 'Cube',
MAX(SKU.STDGROSSWGT) AS 'Weight',
LOTATTRIBUTE.Lottable02 AS 'Batch#',
LOTATTRIBUTE.Lottable04 As 'ExpiryDate',
LOTATTRIBUTE.Lottable05 AS 'ReceiptDate',
DateAdd(day, CAST(MAX(ISNULL(SKU.BUSR2,0)) as int) * -1 , LOTATTRIBUTE.Lottable04) As'SaleByDate'
FROM SKU (NOLOCK)
JOIN STORER (NOLOCK) ON (SKU.STORERKEY = STORER.STORERKEY)
JOIN LOTxLOCxID (NOLOCK) ON (LOTxLOCxID.StorerKey = SKU.StorerKey AND
                             LOTxLOCxID.SKU = SKU.SKU)
JOIN LOTATTRIBUTE (NOLOCK) ON (LOTATTRIBUTE.LOT = LOTxLOCxID.LOT)
JOIN LOC (NOLOCK) ON (LOC.LOC = LOTxLOCxID.LOC)
JOIN LOT (NOLOCK) ON (LOT.LOT = LOTxLOCxID.LOT)
JOIN ID  (NOLOCK) ON (ID.ID = LOTxLOCxID.ID)
WHERE (LOT.STATUS <> 'OK' OR
LOC.STATUS <> 'OK' OR
ID.STATUS  <> 'OK' OR 
LOC.LocationFlag <> 'NONE') AND
LOTxLOCxID.Qty > 0
GROUP BY LOC.FACILITY, 
STORER.STORERKEY,
STORER.COMPANY,
SKU.SKU, 
SKU.DESCR,
LOTATTRIBUTE.Lottable02,
LOTATTRIBUTE.Lottable04,
LOTATTRIBUTE.Lottable05








GO