SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO

/***************************************************************************/
/* View: V_JReportPrinting_Params                                          */
/* Creation Date: 10/02/2020                                               */
/* Copyright: LF Logistics                                                 */
/* Written by: WLChooi                                                     */
/*                                                                         */
/* Purpose: For Exceed to print report from JReport                        */
/*        : This view is to show Module, ReportType and its corresponding  */
/*        : parameters                                                     */
/*                                                                         */
/* Called By: isp_GetJReportURL                                            */
/*          :                                                              */
/* GitLab Version: 1.2                                                     */
/*                                                                         */
/* Version: 7.0                                                            */
/*                                                                         */
/* Data Modifications:                                                     */
/*                                                                         */
/* Updates:                                                                */
/* Date        Author   Ver   Purposes                                     */
/* 2021-08-11  WLChooi  1.1   WMS-17206 - Cater for Module = PACKING_AUTO  */
/*                            (WL01)                                       */
/* 2023-01-12  WLChooi  1.2   DevOps Combine Script                        */
/* 2023-01-12  WLChooi  1.2   WMS-21438 - Add PARAM_WMS_c_Username for     */
/*                            RECEIPT - PTWYRPT, TALLYSHT (WL03)           */
/***************************************************************************/

CREATE   VIEW [dbo].[V_JReportPrinting_Params] AS
--Packing Module - START
SELECT Module      = 'PACKING'
      ,ReportType  = 'CarrierLbl' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING'
      ,ReportType  = 'CtnMnfLbl' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING'
      ,ReportType  = 'CTNMARKLBL' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING'
      ,ReportType  = 'PACKLIST' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING'
      ,ReportType  = 'PACKLIST02' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING'
      ,ReportType  = 'PackSKULBL' 
      ,Param01     = 'PARAM_WMS_c_SKU' ,Param01Type = 'NVARCHAR(20)'   
      ,Param02     = 'PARAM_WMS_n_Qty' ,Param02Type = 'INT'
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING'
      ,ReportType  = 'SSCCLABEL' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING'
      ,ReportType  = 'PACKDISPCY' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING'
      ,ReportType  = 'DespatchTk' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING'
      ,ReportType  = 'ConsoDptTk' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING'
      ,ReportType  = 'UCCLABEL' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL   
SELECT Module      = 'PACKING'
      ,ReportType  = 'UCCLBCONSO' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
--Packing Module - END

--Packing_Auto Module - WL01 - START
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'CarrierLbl' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'CtnMnfLbl' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'CTNMARKLBL' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'PACKLIST' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'PACKLIST02' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'PackSKULBL' 
      ,Param01     = 'PARAM_WMS_c_SKU' ,Param01Type = 'NVARCHAR(20)'   
      ,Param02     = 'PARAM_WMS_n_Qty' ,Param02Type = 'INT'
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'SSCCLABEL' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'PACKDISPCY' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'DespatchTk' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'ConsoDptTk' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'UCCLABEL' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
UNION ALL   
SELECT Module      = 'PACKING_AUTO'
      ,ReportType  = 'UCCLBCONSO' 
      ,Param01     = 'PARAM_WMS_c_Pickslipno' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_CartonFrom' ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_CartonTo'   ,Param03Type = 'INT'
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = ''
--Packing_Auto Module - WL01 - END

--Receipt Module - START
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'PRNTASN' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'AUDTRAIL' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'CASELBL' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'COLLBL' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'GRNFLTHRU' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'GRNXDOCK' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'SHPINB' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'PREPTWY' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'PRETALSHT' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'GINRPT' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'GINCTN' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'GRNRPT' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'GRNCTN' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'RTNTALSHT' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'TALLYSHT' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_c_Username'   ,Param02Type = 'NVARCHAR(250)'   --WL03
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'PTWYRPT' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_c_Username'   ,Param02Type = 'NVARCHAR(250)'   --WL03
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'PTWYSUMM' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'PTWYDET' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'RCPDET' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'RCPDETMTX' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'RCPLOCSUMM' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'RCPSUMM' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'RCVFORM' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'SHELFLF12' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'SHELFLF18' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'PreRecv' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey'        ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_ReceiptLineStart'  ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_ReceiptLineEnd'    ,Param03Type = 'INT'
      ,Param04     = ''                     ,Param04Type = ''
      ,Param05     = ''                     ,Param05Type = ''
      ,Param06     = ''                     ,Param06Type = ''
      ,Param07     = ''                     ,Param07Type = ''
      ,Param08     = ''                     ,Param08Type = ''
      ,Param09     = ''                     ,Param09Type = ''
      ,Param10     = ''                     ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'PostRecv' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey'        ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_ReceiptLineStart'  ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_ReceiptLineEnd'    ,Param03Type = 'INT'
      ,Param04     = ''                     ,Param04Type = ''
      ,Param05     = ''                     ,Param05Type = ''
      ,Param06     = ''                     ,Param06Type = ''
      ,Param07     = ''                     ,Param07Type = ''
      ,Param08     = ''                     ,Param08Type = ''
      ,Param09     = ''                     ,Param09Type = ''
      ,Param10     = ''                     ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'PreRecv2' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey'        ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_ReceiptLineStart'  ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_ReceiptLineEnd'    ,Param03Type = 'INT'
      ,Param04     = ''                     ,Param04Type = ''
      ,Param05     = ''                     ,Param05Type = ''
      ,Param06     = ''                     ,Param06Type = ''
      ,Param07     = ''                     ,Param07Type = ''
      ,Param08     = ''                     ,Param08Type = ''
      ,Param09     = ''                     ,Param09Type = ''
      ,Param10     = ''                     ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'PostRecv2' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey'        ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'PARAM_WMS_n_ReceiptLineStart'  ,Param02Type = 'INT'
      ,Param03     = 'PARAM_WMS_n_ReceiptLineEnd'    ,Param03Type = 'INT'
      ,Param04     = ''                     ,Param04Type = ''
      ,Param05     = ''                     ,Param05Type = ''
      ,Param06     = ''                     ,Param06Type = ''
      ,Param07     = ''                     ,Param07Type = ''
      ,Param08     = ''                     ,Param08Type = ''
      ,Param09     = ''                     ,Param09Type = ''
      ,Param10     = ''                     ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'SORTSHT' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'STORADDLBL' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'TRUCKSHT' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'RECEIPT'
      ,ReportType  = 'WARRANRCPT' 
      ,Param01     = 'PARAM_WMS_c_Receiptkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''              ,Param02Type = ''
      ,Param03     = ''              ,Param03Type = ''
      ,Param04     = ''              ,Param04Type = ''
      ,Param05     = ''              ,Param05Type = ''
      ,Param06     = ''              ,Param06Type = ''
      ,Param07     = ''              ,Param07Type = ''
      ,Param08     = ''              ,Param08Type = ''
      ,Param09     = ''              ,Param09Type = ''
      ,Param10     = ''              ,Param10Type = '' 
--Receipt Module - END

--Loadplan Module - START
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'ALLOCDISPC' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'CTNLBL' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'CASELBL' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PLISTBATCH' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'CTNRSUM' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'DELNOTE' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'DISPCYRPT' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'EXORDPSLIP' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'INDNBPSLIP' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'INDBPSLIP' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'INDSLIST' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'LPCTRLLIST' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'LPTSKBATCH' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'LPTSKBSUMM' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'LPREPLEN' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'LOADSHEET' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PACKSUMM' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PLISTNIKE' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'OUTLBL' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PACKEXPORT' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PACKSHEET' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PICKLABEL' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PLISTC' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PLISTCTM' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PLISTN' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PLISTNTM' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PLISTXDOCK' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PICKSUMM' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'POSTPICKCC' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'AUTOPPKLBL' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'SHIPMNFST' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'SORTLIST' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'STKOUTRPT' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'STKOUTSUMM' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'PRNTRFORD' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'LPLABEL' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'LOADSHEET' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'BATMNFEST' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'DISCMNFEST' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'LOADPLAN'
      ,ReportType  = 'RETLDSHEET' 
      ,Param01     = 'PARAM_WMS_c_Loadkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
--Loadplan Module - END
--Wave Module - START
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'PLIST_WAVE' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'NIKEPPLIST' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'POPUPRPFPA' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'MVTKTFPA' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'POPUPWPFPA' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'DPUCCPKRPL' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'DPSHORTALC' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'WAVLOADSHT' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'WAVPLISTC' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'WAVPICKSUM' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'WAVELPDET' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
UNION ALL   
SELECT Module      = 'WAVE'
      ,ReportType  = 'WAVELPSUM' 
      ,Param01     = 'PARAM_WMS_c_Wavekey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = ''
--Wave Module - END

--MBOL Module - START
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'CARTONLBL' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'DO' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'DRIVER' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'PENDINGDO' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'MANDET' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'MANDETSKU' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'MANSUM' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'LOADMANI' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'MBOLPOD' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'MBOL' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'PICKLIST' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'PACKDESUMM' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'DELORDER' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'PACKLIST' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'CNCTMINVO' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'AUSCTMINVO' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'CNPACKLIST' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'AUSPACKLST' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'VICSBOL' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'STPACKLSTF' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'STPACKLSTM' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'GOL' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'DR' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 
UNION ALL   
SELECT Module      = 'MBOL'
      ,ReportType  = 'NIKEPODRPT' 
      ,Param01     = 'PARAM_WMS_c_Mbolkey' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = ''           ,Param02Type = ''
      ,Param03     = ''           ,Param03Type = ''
      ,Param04     = ''           ,Param04Type = ''
      ,Param05     = ''           ,Param05Type = ''
      ,Param06     = ''           ,Param06Type = ''
      ,Param07     = ''           ,Param07Type = ''
      ,Param08     = ''           ,Param08Type = ''
      ,Param09     = ''           ,Param09Type = ''
      ,Param10     = ''           ,Param10Type = '' 

--MBOL Module - END

--Testing
/*SELECT Module      = 'RECEIPT'
      ,ReportType  = 'TALLYSHT' 
      ,Param01     = 'dt_StartDate' ,Param01Type = 'NVARCHAR(10)'
      ,Param02     = 'dt_EndDate' ,Param02Type = ''
      ,Param03     = '' ,Param03Type = ''
      ,Param04     = '' ,Param04Type = ''
      ,Param05     = '' ,Param05Type = ''
      ,Param06     = '' ,Param06Type = ''
      ,Param07     = '' ,Param07Type = ''
      ,Param08     = '' ,Param08Type = ''
      ,Param09     = '' ,Param09Type = ''
      ,Param10     = '' ,Param10Type = '' */

GO