SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
CREATE VIEW [dbo].[V_LoadPlanDetail]   
AS   
SELECT [LoadKey]  
, [LoadLineNumber]  
, [OrderKey]  
, [ExternOrderKey]  
, [ConsigneeKey]  
, [CustomerName]  
, [Priority]  
, [OrderDate]  
, [DeliveryDate]  
, [DeliveryPlace]  
, [Type]  
, [Door]  
, [Stop]  
, [Route]  
, [Weight]  
, [Cube]  
, [Status]  
, [CaseCnt]  
, [NoOfOrdLines]  
, [Rdd]  
, [AddDate]  
, [AddWho]  
, [EditDate]  
, [EditWho]  
, [ArchiveCop]  
, [TrafficCop]  
, [UserDefine01]  
, [UserDefine02]  
, [UserDefine03]  
, [UserDefine04]  
, [UserDefine05]  
, [UserDefine06]  
, [UserDefine07]  
, [UserDefine08]  
, [UserDefine09]  
, [UserDefine10]  
, [ExternLoadKey]  
, [ExternLineNo]  
FROM [LoadPlanDetail] (NOLOCK)   
GO