SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO

CREATE VIEW DBO.V_MBOL_SUM
AS SELECT MBOL.Mbolkey,
          NoofOrders = COUNT(DISTINCT MBOLDETAIL.orderkey) 
   FROM MBOL WITH (NOLOCK)
   LEFT JOIN MBOLDETAIL WITH (NOLOCK) ON MBOL.Mbolkey = MBOLDETAIL.Mbolkey
   GROUP BY MBOL.Mbolkey

GO