SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO

CREATE VIEW [dbo].[V_MCF]  
AS  
SELECT STORERKEY, SKU,  
   SUM(CASE WHEN LEFT(SKUxLOC.LOC,2) = '8A' 
                 THEN QTY-QTYPICKED-QTYALLOCATED ELSE 0 END) AS [QTY8A],  
   SUM(CASE WHEN LEFT(SKUxLOC.LOC,2) = '8Y' THEN QTY-QTYPICKED-QTYALLOCATED ELSE 0 END) AS [QTY8Y],  
   SUM(CASE WHEN LEFT(SKUxLOC.LOC,2) = '8K' THEN QTY-QTYPICKED-QTYALLOCATED ELSE 0 END) AS [QTY8K],  
   SUM(CASE WHEN LEFT(SKUxLOC.LOC,2) = '11' THEN QTY-QTYPICKED-QTYALLOCATED ELSE 0 END) AS [QTY11],  
   SUM(CASE WHEN LEFT(SKUxLOC.LOC,2) = '8F' THEN QTY-QTYPICKED-QTYALLOCATED ELSE 0 END) AS [QTY8F],  
   SUM(CASE WHEN LEFT(SKUxLOC.LOC,2) NOT IN ('11', '8A', '8Y', '8K', '8F') THEN QTY-(QTYPICKED+QTYALLOCATED) ELSE 0 END) AS [OTHERS]  
FROM SKUxLOC (NOLOCK)  
JOIN LOC (NOLOCK) ON SKUxLOC.LOC = LOC.LOC  
WHERE SKUxLOC.STORERKEY = '11315'  
AND 1 = CASE WHEN LOC.PutawayZone Like '%XD%' AND LOC.LocationFlag <> 'DAMAGE' THEN 1  
        WHEN LOC.LocationFlag IN ('HOLD', 'DAMAGE') THEN 2  
        ELSE 1  
        END  
GROUP BY STORERKEY, SKU 



GO