SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
CREATE VIEW [dbo].[V_PACK] 
AS 
SELECT [PackKey]
, [PackDescr]
, [PackUOM1]
, [CaseCnt]
, [ISWHQty1]
, [ReplenishUOM1]
, [ReplenishZone1]
, [CartonizeUOM1]
, [LengthUOM1]
, [WidthUOM1]
, [HeightUOM1]
, [CubeUOM1]
, [PackUOM2]
, [InnerPack]
, [ISWHQty2]
, [ReplenishUOM2]
, [ReplenishZone2]
, [CartonizeUOM2]
, [LengthUOM2]
, [WidthUOM2]
, [HeightUOM2]
, [CubeUOM2]
, [PackUOM3]
, [Qty]
, [ISWHQty3]
, [ReplenishUOM3]
, [ReplenishZone3]
, [CartonizeUOM3]
, [LengthUOM3]
, [WidthUOM3]
, [HeightUOM3]
, [CubeUOM3]
, [PackUOM4]
, [Pallet]
, [ISWHQty4]
, [ReplenishUOM4]
, [ReplenishZone4]
, [CartonizeUOM4]
, [LengthUOM4]
, [WidthUOM4]
, [HeightUOM4]
, [CubeUOM4]
, [PalletWoodLength]
, [PalletWoodWidth]
, [PalletWoodHeight]
, [PalletTI]
, [PalletHI]
, [PackUOM5]
, [Cube]
, [ISWHQty5]
, [PackUOM6]
, [GrossWgt]
, [ISWHQty6]
, [PackUOM7]
, [NetWgt]
, [ISWHQty7]
, [PackUOM8]
, [OtherUnit1]
, [ISWHQty8]
, [ReplenishUOM8]
, [ReplenishZone8]
, [CartonizeUOM8]
, [LengthUOM8]
, [WidthUOM8]
, [HeightUOM8]
, [PackUOM9]
, [OtherUnit2]
, [ISWHQty9]
, [ReplenishUOM9]
, [ReplenishZone9]
, [CartonizeUOM9]
, [LengthUOM9]
, [WidthUOM9]
, [HeightUOM9]
, [AddDate]
, [AddWho]
, [EditDate]
, [EditWho]
, [TrafficCop]
, [ArchiveCop]
, [Timestamp]
FROM [PACK] (NOLOCK) 

GO