SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
CREATE VIEW [dbo].[V_PHY_INV2A_ID] 
AS 
SELECT [StorerKey]
, [Sku]
, [Id]
, [QtyTeamA]
, [QtyLOTxLOCxID]
FROM [PHY_INV2A_ID] (NOLOCK) 

GO