SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
CREATE VIEW [dbo].[V_PHY_INV2A_LOT] 
AS 
SELECT [StorerKey]
, [Sku]
, [Lot]
, [QtyTeamA]
, [QtyLOTxLOCxID]
FROM [PHY_INV2A_LOT] (NOLOCK) 

GO