SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
  
    
CREATE VIEW [dbo].[V_RECEIPTDETAIL]     
AS     
SELECT [ReceiptKey]    
, [ReceiptLineNumber]    
, [ExternReceiptKey]    
, [ExternLineNo]    
, [StorerKey]    
, [POKey]    
, [Sku]    
, [AltSku]    
, [Id]    
, [Status]    
, [DateReceived]    
, [QtyExpected]    
, [QtyAdjusted]    
, [QtyReceived]    
, [UOM]    
, [PackKey]    
, [VesselKey]    
, [VoyageKey]    
, [XdockKey]    
, [ContainerKey]    
, [ToLoc]    
, [ToLot]    
, [ToId]    
, [ConditionCode]    
, [Lottable01]    
, [Lottable02]    
, [Lottable03]    
, [Lottable04]    
, [Lottable05]   
, [Lottable06]  
, [Lottable07]  
, [Lottable08]  
, [Lottable09]  
, [Lottable10]  
, [Lottable11]  
, [Lottable12]  
, [Lottable13]  
, [Lottable14]  
, [Lottable15]   
, [CaseCnt]    
, [InnerPack]    
, [Pallet]    
, [Cube]    
, [GrossWgt]    
, [NetWgt]    
, [OtherUnit1]    
, [OtherUnit2]    
, [UnitPrice]    
, [ExtendedPrice]    
, [EffectiveDate]    
, [AddDate]    
, [AddWho]    
, [EditDate]    
, [EditWho]    
, [TrafficCop]    
, [ArchiveCop]    
, [TariffKey]    
, [FreeGoodQtyExpected]    
, [FreeGoodQtyReceived]    
, [SubReasonCode]    
, [FinalizeFlag]    
, [DuplicateFrom]    
, [BeforeReceivedQty]    
, [PutawayLoc]    
, [ExportStatus]    
, [SplitPalletFlag]    
, [POLineNumber]    
, [LoadKey]    
, [ExternPoKey]    
, [UserDefine01]    
, [UserDefine02]    
, [UserDefine03]    
, [UserDefine04]    
, [UserDefine05]    
, [UserDefine06]    
, [UserDefine07]    
, [UserDefine08]    
, [UserDefine09]    
, [UserDefine10]    
, [ReceiptKey] + [ReceiptLineNumber] as SourceKey    
, Channel
, Channel_ID
FROM [RECEIPTDETAIL] (NOLOCK)     
    
  

GO