SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO

CREATE   VIEW [dbo].[V_RouteMaster]
AS
SELECT *
FROM [RouteMaster] WITH (NOLOCK)

--SELECT TOP 30 * FROM V_RouteMaster ORDER BY 1 DESC

GO