SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO

CREATE VIEW [dbo].[V_WorkOrderJobDetailSummary] 
AS 
SELECT JobKey
      ,WorkStation = (SELECT TOP 1 WORKORDERJOB.WorkStation FROM WORKORDERJOB WITH (NOLOCK)
							 WHERE WORKORDERJOB.JobKey = WORKORDERJOBDETAIL.JobKey
						    ORDER BY WORKORDERJOB.Serialkey)
		,DueDate		 = (SELECT MIN(WORKORDERREQUEST.DueDate) FROM WORKORDERJOB WITH (NOLOCK)
							 JOIN  WORKORDERREQUEST WITH (NOLOCK) ON (WORKORDERJOB.WorkOrderkey = WORKORDERREQUEST.WorkOrderkey)
							 WHERE WORKORDERJOB.JobKey = WORKORDERJOBDETAIL.JobKey)
		,EstWastage  = (SELECT ISNULL(SUM(WORKORDERREQUESTINPUTS.QtyRequired - WORKORDERREQUESTINPUTS.Qty),0) FROM WORKORDERJOB WITH (NOLOCK)
							 JOIN  WORKORDERREQUESTINPUTS WITH (NOLOCK) ON (WORKORDERJOB.WorkOrderkey = WORKORDERREQUESTINPUTS.WorkOrderkey)
                      JOIN  SKU WITH (NOLOCK) ON (WORKORDERREQUESTINPUTS.Storerkey = SKU.Storerkey)
                                              AND(WORKORDERREQUESTINPUTS.Sku = SKU.Sku)
							 WHERE WORKORDERJOB.JobKey = WORKORDERJOBDETAIL.JobKey)
		,NoOfTasks   = (SELECT COUNT(1) FROM TASKDETAIL WITH (NOLOCK)
							 WHERE TASKDETAIL.SourceType = 'VAS' 
							 AND LEFT(TASKDETAIL.Sourcekey,10) = WORKORDERJOBDETAIL.JobKey
                                                         AND TASKDETAIL.Status <> 'X')
		,NoOfPendingTasks   = (SELECT COUNT(1) FROM TASKDETAIL WITH (NOLOCK)
									  WHERE TASKDETAIL.SourceType = 'VAS' 
									  AND LEFT(TASKDETAIL.Sourcekey,10) = WORKORDERJOBDETAIL.JobKey
									  AND TASKDETAIL.Status = '0')
		,NoOfCompletedTasks = (SELECT COUNT(1) FROM TASKDETAIL WITH (NOLOCK)
									  WHERE TASKDETAIL.SourceType = 'VAS' 
									  AND LEFT(TASKDETAIL.Sourcekey,10) = WORKORDERJOBDETAIL.JobKey
									  AND TASKDETAIL.Status = '9')
FROM WORKORDERJOBDETAIL WITH (NOLOCK) 

GO