SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
/*************************************************************************/                                                                                                                                                                                    
/* Stored Procedure: lsp_Kit_Duplicate                                   */                                                                                                                                                                                    
/* Creation Date: 28-FEB-2018                                            */                                                                                                                                                                                    
/* Copyright: LFL                                                        */                                                                                                                                                                                    
/* Written by:                                                           */                                                                                                                                                                                    
/*                                                                       */                                                                                                                                                                                    
/* Purpose:                                                              */                                                                                                                                                                                    
/*                                                                       */                                                                                                                                                                                    
/* Called By:                                                            */                                                                                                                                                                                    
/*                                                                       */                                                                                                                                                                                    
/*                                                                       */                                                                                                                                                                                    
/* Version: 1.0                                                          */                                                                                                                                                                                    
/*                                                                       */                                                                                                                                                                                    
/* Data Modifications:                                                   */                                                                                                                                                                                    
/*                                                                       */                                                                                                                                                                                    
/* Updates:                                                              */                                                                                                                                                                                    
/* Date         Author   Ver  Purposes                                   */  
/* 2021-02-05   mingle01 1.1  Add Big Outer Begin try/Catch             */
/*                            Execute Login if @c_UserName<>SUSER_SNAME()*/                                                                                                                                                                                   
/*************************************************************************/                                                                                                                                                                                    
CREATE PROCEDURE [WM].[lsp_Kit_Duplicate]  (                                                                                                                                                                                                                   
   @c_StorerKey      NVARCHAR(15),                                                                                                                                                                                                                             
   @c_KitKey         NVARCHAR(10),  
   @c_NewKitKey      NVARCHAR(10) OUTPUT,                                                                                                                                                                                                                           
   @b_Success        int = 1 OUTPUT,                                                                                                                                                                                                                           
   @n_Err            int = 0 OUTPUT,                                                                                                                                                                                                                           
   @c_Errmsg         NVARCHAR(250) = '' OUTPUT,                                                                                                                                                                                                                
   @c_UserName       NVARCHAR(128) = '' )                                                                                                                                                                                                                      
AS                                                                                                                                                                                                                                                             
BEGIN                                                                                                                                                                                                                                                          
   SET NOCOUNT ON                                                                                                                                           
   SET ANSI_NULLS OFF                                                                                                                                       
   SET QUOTED_IDENTIFIER OFF                                                                                                                                
   SET CONCAT_NULL_YIELDS_NULL OFF                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
   DECLARE @n_Continue     INT = '1'                                                                                                                                                                                                                           
         , @n_Count        INT = 0                                                                                                                                                                                                                             
         , @c_KitStatus    NVARCHAR(10) = ''                                                                                                                                                                                                                   
         , @n_ComponentQty INT = 0                                                                                                                                                                                                                             
         , @n_ParentQty    INT = 0                                                                                                                                                                                                                             
         , @n_Remainder    INT = 0                                                                                                                                                                                                                             
         , @n_BOMQty       INT = 0                                                                                                                                                                                                                             
         , @c_NewKitLineNo NVARCHAR(5)  = ''                                                                                                                                                                                                                   
        -- , @c_NewKitKey    NVARCHAR(10) = ''                                                                                                                                                                                                                   
         , @c_UOM          NVARCHAR(10) = ''                                                                                                                                                                                                                   
         , @c_MUID_Enable  NVARCHAR(10) = '0'                                                                                                                                                                                                                  
         , @c_ID           NVARCHAR(18) = ''                                                                                                                                                                                                                   
         , @c_KitLineNumber  NVARCHAR(5) = ''                                                                                                                                                                                                                  
         , @c_Type           NVARCHAR(5) = ''                                                                                                                                                                                                                  
         , @c_ActionFlag     NVARCHAR(1) = '0'                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
   SET @b_Success = 1                                                                                                                                                                                                                                          
   SET @c_ErrMsg = ''  
   SET @c_NewKitKey = ''                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
   SET @n_Err = 0      
                                                                                                                                                                                                                                           
   --(mingle01) - START
   IF SUSER_SNAME() <> @c_UserName
   BEGIN
      EXEC [WM].[lsp_SetUser] 
            @c_UserName = @c_UserName  OUTPUT
         ,  @n_Err      = @n_Err       OUTPUT
         ,  @c_ErrMsg   = @c_ErrMsg    OUTPUT
               
      IF @n_Err <> 0 

      BEGIN
         GOTO EXIT_SP
      END 

       EXECUTE AS LOGIN = @c_UserName
   END
   --(mingle01) - END

   --(mingle01) - START
   BEGIN TRY
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
      BEGIN TRAN                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
      SET @c_KitStatus = ''                                                                                                                                                                                                                                       
      SELECT @c_StorerKey = k.StorerKey,                                                                                                                                                                                                                          
             @c_KitStatus = k.[Status],                                                                                                                                                                                                                           
             @c_ActionFlag = k.ActionFlag                                                                                                                                                                                                                         
      FROM KIT AS k WITH(NOLOCK)                                                                                                                                                                                                                                  
      WHERE k.KITKey = @c_KitKey                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
      IF @c_KitStatus = ''                                                                                                                                                                                                                                        
      BEGIN                                                                                                                                                                                                                                                       
         SET @n_continue = 3                                                                                                                                                                                                                                      
         SET @n_Err = 554051                                                                                                                                                                                                                                      
         SET @c_ErrMsg = 'NSQL' + CONVERT(CHAR(6), @n_Err) +                                                                                                                                                                                                      
               ': KIT Not Found (lsp_Kit_Duplicate)'                                                                                                                                                                                                              
         GOTO EXIT_SP                                                                                                                                                                                                                                             
      END                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
      IF @c_KitStatus <> '9'                                                                                                                                                                                                                                      
      BEGIN                                                                                                                                                                                                                                                       
         SET @n_continue = 3                                                                                                                                                                                                                                      
         SET @n_Err = 554052                                                                                                                                                                                                                                      
         SET @c_ErrMsg = 'NSQL' + CONVERT(CHAR(6), @n_Err) +                                                                                                                                                                                                      
               ': Please Finalize KIT before you proceed, no duplicate allow (lsp_Kit_Duplicate)'                                                                                                                                                                 
         GOTO EXIT_SP                                                                                                                                                                                                                                             
      END                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
      IF @c_ActionFlag > '5'                                                                                                                                                                                                                                      
      BEGIN                                                                                                                                                                                                                                                       
         SET @n_continue = 3                                                                                                                                                                                                                                      
         SET @n_Err = 554053                                                                                                                                                                                                                                      
         SET @c_ErrMsg = 'NSQL' + CONVERT(CHAR(6), @n_Err) +                                                                                                                                                                                                      
               ': This already duplicated, no duplicate allow. (lsp_Kit_Duplicate)'                                                                                                                                                                               
         GOTO EXIT_SP                                                                                                                                                                                                                                             
      END                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
      IF NOT EXISTS(SELECT 1 FROM KITDETAIL AS k WITH (NOLOCK)                                                                                                                                                                                                    
                    WHERE k.KITKey = @c_KitKey)                                                                                                                                                                                                                   
      BEGIN                                                                                                                                                                                                                                                       
         SET @n_continue = 3                                                                                                                                                                                                                                            
         SET @n_Err = 554054                                                                                                                                                                                                                                      
         SET @c_ErrMsg = 'NSQL' + CONVERT(CHAR(6), @n_Err) +                                                                                                                                                                                                      
               ': No Kit Detail Found (lsp_Kit_Duplicate)'                                                                                                                                                                                                        
         GOTO EXIT_SP                                                                                                                                                                                                                                             
      END                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
      IF NOT EXISTS(SELECT 1 FROM KITDETAIL AS k WITH (NOLOCK)                                                                                                                                                                                                    
                    WHERE k.KITKey = @c_KitKey                                                                                                                                                                                                                    
                    AND   k.[Type] = 'T'                                                                                                                                                                                                                          
                    AND   k.ExpectedQty > k.Qty)                                                                                                                                                                                                                  
      BEGIN                                                                                                                                                                                                                                                       
         SET @n_continue = 3                                                                                                                                                                                                                                      
         SET @n_Err = 554055                                                                                                                                                                                                                                      
         SET @c_ErrMsg = 'NSQL' + CONVERT(CHAR(6), @n_Err) +                                                                                                                                                                                                      
               ': No Outstanding, no duplicate allow. (lsp_Kit_Duplicate)'                                                                                                                                                                                        
         GOTO EXIT_SP                                                                                                                                                                                                                                             
      END                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
      SET @c_NewKitKey = ''                                                                                                                                                                                                                                       
      EXEC nspg_GetKey                                                                                                                                                                                                                                            
         @KeyName = 'KITTING',                                                                                                                                                                                                                                    
         @fieldlength = 10,                                                                                                                                                                                                                                       
         @keystring = @c_NewKitKey OUTPUT,                                                                                                                                                                                                                        
         @b_Success = @b_Success OUTPUT,                                                                                                                                                                                                                          
         @n_err = @n_err OUTPUT,                                                                                                                                                                                                                                  
         @c_errmsg = @c_errmsg OUTPUT                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
      IF @b_Success = 1                                                                                                                                                                                                                                           
      BEGIN                                                                                                                                                                                                                                                       
         INSERT INTO KIT (KITKey, StorerKey, ToStorerKey, [Type], ReasonCode,                                                                                                                                                                                     
                     CustomerRefNo, Remarks, [Status])                                                                                                                                                                                                            
         SELECT @c_NewKitKey, StorerKey, ToStorerKey, [Type], ReasonCode,                                                                                                                                                                                         
                     CustomerRefNo, Remarks, '0'                                                                                                                                                                                                                  
         FROM KIT WITH (NOLOCK)                                                                                                                                                                                                                                   
         WHERE KITKey = @c_KitKey                                                                                                                                                                                                                                 
         IF @@ERROR <> 0                                                                                                                                                                                                                                          
         BEGIN                                                                                                                                                                                                                                                    
            SET @n_continue = 3                                                                                                                                                                                                                                   
            SET @n_Err = 554056                                                                                                                                                                                                                                   
            SET @c_ErrMsg = 'NSQL' + CONVERT(CHAR(6), @n_Err) +                                                                                                                                                                                                   
                  ': Insert into KIT Fail (lsp_Kit_Duplicate)'                                                                                                                                                                                                    
            GOTO EXIT_SP                                                                                                                                                                                                                                          
         END                                                                                                                                                                                                                                                      
      END                                                                                                                                                                                                                                                         
      ELSE                                                                                                                                                                                                                                                        
      BEGIN                                                                                                                                                                                                                                                       
         SET @n_continue = 3                                                                                                                                                                                                                                      
         SET @n_Err = 554057                                                                                                                                                                                                                                      
         SET @c_ErrMsg = 'NSQL' + CONVERT(CHAR(6), @n_Err) +                                                                                                                                                                                                      
               ': Generate KitKey Failed (lsp_Kit_Duplicate)'                                                                                                                                                                                                     
         GOTO EXIT_SP                                                                                                                                                                                                                                             
      END                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
      INSERT INTO KITDETAIL                                                                                                                                                                                                                                       
      (                                                                                                                                                                                                                                                           
         KITKey,        KITLineNumber, [Type],                                                                                                                                                                                                                    
         StorerKey,     Sku,           Lot,                                                                                                                                                                                                                       
         Loc,           Id,            ExpectedQty,                                                                                                                                                                                                               
         Qty,           PackKey,       UOM,                                                                                                                                                                                                                       
         [Status],      ExternKitKey,  ExternLineNo,                                                                                                                                                                                                              
         LOTTABLE01,    LOTTABLE02,    LOTTABLE03,                                                                                                                                                                                                                
         LOTTABLE04,    LOTTABLE05,    Lottable06,                                                                                                                                                                                                                
         Lottable07,    Lottable08,    Lottable09,                                                                                                                                                                                                                
         Lottable10,    Lottable11,    Lottable12,                                                                                                                                                                                                                
         Lottable13,    Lottable14,    Lottable15                                                                                                                                                                                                                 
      )                                                                                                                                                                                                                                                           
      SELECT                                                                                                                                                                                                                                                      
         @c_NewKitKey,  KITLineNumber, [Type],                                                                                                                                                                                                                    
         StorerKey,     Sku,           Lot,                                                                                                                                                                                                                       
         Loc,           Id,            CASE WHEN ExpectedQty > Qty THEN ExpectedQty - Qty ELSE 0 END,                                                                                                                                                             
         Qty=0,         PackKey,       UOM,                                                                                                                                                                                                                       
         [Status]='0',  ExternKitKey,  ExternLineNo,                                                                                                                                                                                                              
         LOTTABLE01,    LOTTABLE02,    LOTTABLE03,                                                                                                                                                                                                                
         LOTTABLE04,    LOTTABLE05,    Lottable06,                                                                                                                                                                                                                
         Lottable07,    Lottable08,    Lottable09,                                                                                                                                                                                                                
         Lottable10,    Lottable11,    Lottable12,                                                                                                                                                                                                                
         Lottable13,    Lottable14,    Lottable15                                                                                                                                                                                                                 
      FROM KITDETAIL AS k WITH (NOLOCK)                                                                                                                                                                                                                           
      WHERE k.KITKey = @c_KitKey                                                                                                                                                                                                                                  
      IF @@ERROR <> 0                                                                                                                                                                                                                                             
      BEGIN                                                                                                                                                                                                                                                       
         SET @n_continue = 3                                                                                                                                                                                                                                      
         SET @n_Err = 554058                                                                                                                                                                                                                                      
         SET @c_ErrMsg = 'NSQL' + CONVERT(CHAR(6), @n_Err) +                                                                                                                                                                                                      
               ': Insert into KIT Detail Fail (lsp_Kit_Duplicate)'                                                                                                                                                                                                
         GOTO EXIT_SP                                                                                                                                                                                                                                             
      END                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
   END TRY
   BEGIN CATCH
      SET @n_Continue = 3
      SET @c_ErrMsg = ERROR_MESSAGE()
      GOTO EXIT_SP
   END CATCH
   --(mingle01) - END
EXIT_SP:                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
   IF @n_Continue = 3                                                                                                                                                                                                                                          
   BEGIN                                                                                                                                                                                                                                                       
      SET @b_Success = 0                                                                                                                                                                                                                                       
      ROLLBACK TRAN                                                                                                                                                                                                                                            
   END                                                                                                                                                                                                                                                         
   ELSE                                                                                                                                                                                                                                                        
   BEGIN                                                                                                                                                                                                                                                       
      SET @b_Success = 1                                                                                                                                                                                                                                       
      COMMIT TRAN                                                                                                                                                                                                                                              
   END                                                                                                                                                                                                                                                         
   REVERT                                                                                                                                                                                                                                                      
END                                                                                                                                                                                                                                                            

GO