SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
/************************************************************************/
/* Stored Procedure: nsp_GetPickSlipOrders115                           */
/* Creation Date: 07.JAN.2021                                           */
/* Copyright:                                                           */
/* Written by: CSCHONG                                                  */
/*                                                                      */
/* Remarks: WMS-15943 - [PH] - Adidas Ecom - Consolidated Pickslip      */
/*                                                                      */
/* Purpose: To speed up picking process, picklists are generated by     */
/*          Pick Zone and locationcategory                              */
/*                                                                      */
/* Called By: r_dw_print_pickorder115_wave                              */
/*                                                                      */
/* PVCS Version: 1.9                                                    */
/*                                                                      */
/* Version: 5.4                                                         */
/*                                                                      */
/* Data Modifications:                                                  */
/*                                                                      */
/* Updates:                                                             */
/* Date         Author   Ver  Purposes                                  */
/************************************************************************/
CREATE PROC [dbo].[isp_GetPickSlipOrders115_Wave]
            @c_Sourcekey   NVARCHAR(10)
         ,  @c_Sourcetype  NVARCHAR(10) = ''
AS
BEGIN
   SET NOCOUNT ON
   SET ANSI_NULLS OFF
   SET QUOTED_IDENTIFIER OFF
   SET CONCAT_NULL_YIELDS_NULL OFF

   DECLARE  
           @n_StartTCnt       INT
         , @n_Continue        INT 
         , @b_Success         INT
         , @n_Err             INT
         , @c_Errmsg          NVARCHAR(255)

         , @n_NoOfReqPSlip    INT
         , @c_Loadkey         NVARCHAR(10)
         , @c_Orderkey        NVARCHAR(10)
         , @c_OrderGroup      NVARCHAR(20)
         , @c_PickSlipNo      NVARCHAR(10)
         , @c_PickHeaderKey   NVARCHAR(10)

         , @c_ConsoOrderkey   NVARCHAR(30)
         , @c_CSCompany       NVARCHAR(45)
         , @c_CSCompanies     NVARCHAR(400)

         , @c_SortLocType     NVARCHAR(10)   
         , @c_PickZone        NVARCHAR(10)
         , @c_PickType        NVARCHAR(10)
         , @c_LocationType    NVARCHAR(10)
         , @c_LogicalLocation NVARCHAR(10)
         , @c_Storerkey       NVARCHAR(15)
         , @c_Sku             NVARCHAR(20)
         , @c_SkuDescr        NVARCHAR(60)
         , @c_Loc             NVARCHAR(10)
         , @c_ID              NVARCHAR(20)
         , @n_Qty             INT
         , @n_QtyInPLT        INT
         , @n_QtyInCS         INT
         , @n_QtyInEA         INT
         , @n_QtyRemain       INT
         , @c_Lot02Label      NVARCHAR(20)
         , @c_Lot04Label      NVARCHAR(20)
         , @c_Lottable02      NVARCHAR(18)
         , @dt_Lottable04     DATETIME
         , @n_Pallet          FLOAT
         , @n_CaseCnt         FLOAT

         , @c_PrintedFlag     CHAR(1)

         , @c_PickDetailKey   NVARCHAR(10)
         , @c_OrderLineNumber NVARCHAR(5)

         , @n_PageNo          INT
         , @n_PageGroup       INT
         , @n_RowPerPage      FLOAT

         ,@c_OHType           NVARCHAR(20)
         ,@c_Salesman         NVARCHAR(45)
         ,@c_LocCategory      NVARCHAR(30)
         ,@c_facility         NVARCHAR(10)
         ,@c_GetPickdetailkey NVARCHAR(10) = ''
         ,@c_GetStorerkey     NVARCHAR(20)

   SET @n_StartTCnt= @@TRANCOUNT
   SET @n_Continue = 1
   SET @b_Success  = 1
   SET @n_Err      = 0
   SET @c_Errmsg   = ''
   SET @n_RowPerPage = 20.00

   WHILE @@TRANCOUNT > 0 
   BEGIN
      COMMIT TRAN
   END 

    CREATE TABLE #TMP_PCK115
      (  LoadKey          NVARCHAR(10),
         PickSlipNo       NVARCHAR(10) NULL,       
         OrderKey         NVARCHAR(10),
         OHType           NVARCHAR(30) NULL,
         PickZone         NVARCHAR(10) NULL, 
         LOC              NVARCHAR(10) NULL,
         Logicalloc       NVARCHAR(18) NULL,
         SKU              NVARCHAR(20),
         SkuDesc          NVARCHAR(60),
         ID               NVARCHAR(18) NULL,  
         Salesman         NVARCHAR(45) NULL,
         LocCategory      NVARCHAR(20) NULL,
         PrintedFlag      NVARCHAR(1) NULL,  
         Facility         NVARCHAR(10)  NULL,
         Qty              int,
         Wavekey          NVARCHAR(20), 
         ConsoOrderkey   NVARCHAR(30)  NOT NULL,
         Pickdetailkey   NVARCHAR(20) NULL,
         Storerkey       NVARCHAR(20) NULL
                     )

   --IF @c_Sourcetype = 'WP'
   --BEGIN
      SELECT @c_GetStorerkey = OH.Storerkey
      FROM ORDERS     OH WITH (NOLOCK)
      JOIN WAVEDETAIL WD WITH (NOLOCK) ON (OH.Orderkey = WD.Orderkey)
      WHERE WD.Wavekey = @c_Sourcekey


      DECLARE CUR_LOADORD CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
      SELECT DISTINCT 
             OH.Loadkey
        --    ,OH.OrderGroup
            ,OH.Storerkey
      FROM ORDERS     OH WITH (NOLOCK)
      JOIN WAVEDETAIL WD WITH (NOLOCK) ON (OH.Orderkey = WD.Orderkey)
      WHERE WD.Wavekey = @c_Sourcekey
      AND   OH.Loadkey <> '' 
      ORDER BY OH.Loadkey
            -- , OH.OrderGroup
   --END
   --ELSE
   --BEGIN

   --   SELECT @c_GetStorerkey = OH.Storerkey
   --   FROM ORDERS     OH WITH (NOLOCK)
   --   WHERE OH.Loadkey = @c_Sourcekey

   --   DECLARE CUR_LOADORD CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
   --   SELECT DISTINCT 
   --          Loadkey
   --         --,OrderGroup
   --         ,Storerkey
   --   FROM ORDERS WITH (NOLOCK)
   --   WHERE Loadkey = @c_Sourcekey
   --   --ORDER BY OrderGroup
   --END
   
   OPEN CUR_LOADORD
   
   FETCH NEXT FROM CUR_LOADORD INTO @c_Loadkey, @c_Storerkey

   WHILE @@FETCH_STATUS <> -1
   BEGIN

      DECLARE CUR_PICK CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
      SELECT        
            ISNULL(RTRIM(LOC.LogicalLocation),'')    AS logicalloc,                                   
            ISNULL(ORDERS.type, '')           AS OHTYPE,  
            ISNULL(RTRIM(LOC.PickZone),'')    AS Pickzone,  
            ORDERS.Storerkey,    
            PickDetail.sku,                         
            ISNULL(Sku.Descr,'') AS SkuDescr, 
            PickDetail.loc,   
            PickDetail.id,
            SUM(PickDetail.qty)  AS Qty,
            ISNULL(ORDERS.Salesman, '')  AS Salesman,             
            ISNULL(RTRIM(LOC.LocationCategory),'') AS LocCategory,                              
            ISNULL(ORDERS.Facility,'') AS Facility,            
            pickdetail.PickDetailKey             
       FROM pickdetail     WITH (NOLOCK)
       JOIN ORDERS         WITH (NOLOCK) ON pickdetail.orderkey = orders.orderkey
       JOIN lotattribute   WITH (NOLOCK) ON pickdetail.lot = lotattribute.lot
       JOIN loadplandetail WITH (NOLOCK) ON pickdetail.orderkey = loadplandetail.orderkey
       JOIN orderdetail    WITH (NOLOCK) ON pickdetail.orderkey = orderdetail.orderkey 
                                        AND pickdetail.orderlinenumber = orderdetail.orderlinenumber        
       JOIN storer         WITH (NOLOCK) ON pickdetail.storerkey = storer.storerkey
       JOIN sku            WITH (NOLOCK) ON pickdetail.sku = sku.sku and pickdetail.storerkey = sku.storerkey
       JOIN pack           WITH (NOLOCK) ON pickdetail.packkey = pack.packkey
       JOIN loc            WITH (NOLOCK) ON pickdetail.loc = loc.loc
      WHERE ORDERS.Loadkey  = @c_Loadkey
      AND   ORDERS.Storerkey= @c_Storerkey
      GROUP BY PickDetail.OrderKey,                            
              ISNULL(ORDERS.Type, ''),
              ISNULL(ORDERS.Salesman, ''),   
              ISNULL(RTRIM(LOC.PickZone),''),
              ISNULL(RTRIM(LOC.LogicalLocation),''),
              ISNULL(RTRIM(LOC.LocationCategory),''),
              ISNULL(ORDERS.Facility,''),
              PickDetail.loc,   
              PickDetail.id,         
              PickDetail.sku,                         
              ISNULL(Sku.Descr,''),
              pickdetail.PickDetailKey,
              ORDERS.Storerkey                  
      ORDER BY ISNULL(RTRIM(LOC.PickZone),'')
              ,ISNULL(RTRIM(LOC.LocationCategory),'') 
              ,PickDetail.Loc
              ,ORDERS.Storerkey
              ,PickDetail.Sku
            
      OPEN CUR_PICK
   
      FETCH NEXT FROM CUR_PICK INTO   @c_LogicalLocation
                                    , @c_OHType
                                    , @c_PickZone
                                    , @c_Storerkey
                                    , @c_Sku
                                    , @c_SkuDescr
                                    , @c_Loc
                                    , @c_ID
                                    , @n_Qty
                                    , @c_salesman
                                    , @c_LocCategory
                                    , @c_Facility  
                                    , @c_GetPickdetailkey                  
      WHILE @@FETCH_STATUS <> -1
      BEGIN
         SET @c_SortLocType = @c_LocationType

         IF @c_LocationType NOT IN ( 'CASE', 'PICK' )
         BEGIN
            SET @c_SortLocType = 'BULK'
         END

       --  SET @n_TotalQty = @n_Qty


         WHILE @n_Qty > 0
         BEGIN
            SET @n_QtyInPLT = 0
            SET @n_QtyInCS  = 0
            SET @n_QtyInEA  = 0
            SET @n_QtyRemain= 0
            SET @c_PickType = ''

           -- SET @n_TotalCases = 0


            IF @c_SortLocType = 'BULK'
            BEGIN
               SET @n_QtyInPLT = CASE WHEN @n_Pallet > 0 THEN @n_Qty/@n_Pallet ELSE 0 END
               IF @n_QtyInPLT > 0 
               BEGIN
                  SET @c_PickType = 'FP'
                  SET @n_QtyRemain = (@n_QtyInPLT * @n_Pallet)

                  --IF @n_ShowTotalCases = 1
                  --BEGIN
                  --   SELECT @n_TotalCases = @n_QtyRemain / @n_CaseCnt
                  --END
                  --ELSE
                  --BEGIN
                  --   SET @n_TotalCases = 0
                  --END

               END
               ELSE
               BEGIN
                  SET @n_QtyInCS = CASE WHEN @n_CaseCnt > 0 THEN @n_Qty/@n_CaseCnt ELSE 0 END
                  IF @n_QtyInCS > 0
                  BEGIN
                     SET @c_PickType = 'PPFC'
                     SET @n_QtyRemain = (@n_QtyInCS * @n_CaseCnt)

                     --IF @n_ShowTotalCases = 1
                     --BEGIN
                     --   SELECT @n_TotalCases = @n_QtyRemain / @n_CaseCnt
                     --END
                     --ELSE
                     --BEGIN
                     --   SET @n_TotalCases = 0
                     --END

                  END
                  ELSE
                  BEGIN
                     SET @c_PickType = 'PPLC'
                     SET @n_QtyInEA   = @n_Qty
                     SET @n_QtyRemain = @n_Qty
                    -- SET @n_TotalCases = 0

                  END
               END
            END
            ELSE 
            IF @c_SortLocType = 'CASE'
            BEGIN
               SET @n_QtyInCS = CASE WHEN @n_CaseCnt > 0 THEN @n_Qty/@n_CaseCnt ELSE 0 END
               IF @n_QtyInCS > 0
               BEGIN
                  SET @c_PickType = 'FC'
                  SET @n_QtyRemain = (@n_QtyInCS * @n_CaseCnt)

                  --IF @n_ShowTotalCases = 1
                  --BEGIN
                  --   SELECT @n_TotalCases = @n_QtyRemain / @n_CaseCnt
                  --END
                  --ELSE
                  --BEGIN
                  --   SET @n_TotalCases = 0
                  --END

               END
               ELSE
               BEGIN
                  SET @c_PickType = 'LC'
                  SET @n_QtyInEA   = @n_Qty
                  SET @n_QtyRemain = @n_Qty
                  --SET @n_TotalCases = 0

               END
            END
            ELSE 
            IF @c_SortLocType = 'PICK'
            BEGIN
               SET @c_PickType = 'PK'
               SET @n_QtyInEA   = @n_Qty
               SET @n_QtyRemain = @n_Qty

               --SET @n_TotalCases = 0
            END

            SET @c_ConsoOrderkey = RTRIM(@c_PickType) + RTRIM(@c_PickZone) + RTRIM(@c_LocCategory)

            INSERT INTO #TMP_PCK115
         (  PickSlipNo,          LoadKey,         OrderKey,       OHType,
            Salesman,            PickZone,        Logicalloc,     LocCategory,         
            Facility,            LOC,             ID,             SKU,
            SkuDesc,             Qty,             PrintedFlag ,Wavekey,ConsoOrderkey,Pickdetailkey,Storerkey) 
            VALUES 
               ( ''  
               , @c_Loadkey   
               , ''
               , @c_OHType
               , @c_Salesman
               , @c_PickZone 
               , @c_LogicalLocation
               , @c_LocCategory 
               , @c_facility
               , @c_Loc
               , @c_ID  
               , @c_Sku
               , @c_SkuDescr
               , @n_Qty
               , 'N'
               , @c_Sourcekey
               , @c_ConsoOrderkey 
               , @c_GetPickdetailkey 
               , @c_Storerkey
               
               )
            SET @n_Qty = @n_Qty - @n_QtyRemain
         END 
         
         FETCH NEXT FROM CUR_PICK INTO   @c_LogicalLocation
                                       , @c_OHType
                                       , @c_PickZone
                                       , @c_Storerkey
                                       , @c_Sku
                                       , @c_SkuDescr
                                       , @c_Loc
                                       , @c_ID
                                       , @n_Qty
                                       , @c_salesman
                                       , @c_LocCategory
                                       , @c_Facility  
                                       , @c_GetPickdetailkey       
      END
      CLOSE CUR_PICK
      DEALLOCATE CUR_PICK

      FETCH NEXT FROM CUR_LOADORD INTO @c_Loadkey, @c_Storerkey 
   END
   CLOSE CUR_LOADORD
   DEALLOCATE CUR_LOADORD

   IF NOT EXISTS (SELECT 1
                  FROM #TMP_PCK115
               )
   BEGIN
      GOTO QUIT_SP
   END
   
   SET @n_NoOfReqPSlip  = 0

   SELECT @n_NoOfReqPSlip = COUNT(DISTINCT TPK.Loadkey + TPK.ConsoOrderkey)
   FROM #TMP_PCK115 TPK
   WHERE NOT EXISTS ( SELECT 1
                      FROM PICKHEADER PH WITH (NOLOCK) 
                      WHERE PH.ExternOrderKey =  TPK.Loadkey 
                      AND PH.ConsoOrderkey = TPK.ConsoOrderKey
                    )

   IF @n_NoOfReqPSlip > 0 
   BEGIN
      EXECUTE nspg_GetKey 
              'PICKSLIP'
            , 9
            , @c_PickSlipNo   OUTPUT
            , @b_Success      OUTPUT
            , @n_Err          OUTPUT
            , @c_Errmsg       OUTPUT
            , 0
            , @n_NoOfReqPSlip

      IF @b_success <> 1 
      BEGIN
         SET @n_Continue = 3
         GOTO QUIT_SP
      END
   END

   DECLARE CUR_PSLIP CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
   SELECT DISTINCT
          TPK.Loadkey
         ,TPK.PickZone
         ,TPK.LocCategory
         ,TPK.ConsoOrderkey
         ,PickHeaderkey = ISNULL(RTRIM(PH.PickHeaderKey),'')
   FROM #TMP_PCK115 TPK
   LEFT JOIN PICKHEADER PH WITH (NOLOCK) ON (TPK.Loadkey = PH.ExternOrderKey)
                                         AND(TPK.ConsoOrderkey = PH.ConsoOrderKey)
   ORDER BY TPK.Loadkey
         ,  TPK.PickZone
         ,  TPK.LocCategory
         ,  TPK.ConsoOrderkey
         ,  ISNULL(RTRIM(PH.PickHeaderKey),'')

   OPEN CUR_PSLIP
   
   FETCH NEXT FROM CUR_PSLIP INTO @c_Loadkey
                                 ,@c_PickZone
                                 ,@c_LocCategory
                                 ,@c_ConsoOrderkey
                                 ,@c_PickHeaderKey

   WHILE @@FETCH_STATUS <> -1
   BEGIN
      BEGIN TRAN
      IF @c_PickHeaderKey = ''
      BEGIN
         SET @c_PickHeaderKey = 'P' + @c_PickSlipNo

         INSERT INTO PICKHEADER (PickHeaderKey, ExternOrderKey, ConsoOrderkey, PickType, Zone, TrafficCop)
         VALUES (@c_PickHeaderKey, @c_LoadKey, @c_ConsoOrderkey, '0', 'LB', NULL)

         SET @n_err = @@ERROR
         IF @n_err <> 0
         BEGIN
            SET @n_Continue = 3
            GOTO QUIT_SP
         END

         SET @c_PickSlipNo = RIGHT('000000000' + CONVERT(NVARCHAR(9), CONVERT(INT, @c_PickSlipNo) + 1),9)

         SET @c_PrintedFlag = 'N'
      END
      ELSE
      BEGIN
         UPDATE PICKHEADER WITH (ROWLOCK)
         SET PickType = '1'
            ,EditWho = SUSER_NAME()
            ,EditDate= GETDATE()
            ,TrafficCop = NULL
         FROM PICKHEADER
         WHERE PickHeaderKey = @c_PickHeaderKey

         SET @n_err = @@ERROR
         IF @n_err <> 0
         BEGIN
            SET @n_Continue = 3
            GOTO QUIT_SP
         END

         SET @c_PrintedFlag = 'Y'
      END

      DECLARE CUR_PD CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
      SELECT DISTINCT 
              PD.PickDetailKey
            , PD.Orderkey
            , PD.OrderLineNumber
            --, TPK.PickType
            --, TPK.Pallet
            --, TPK.CaseCnt
            , TPK.Qty   
      FROM #TMP_PCK115 TPK
      JOIN ORDERS     OH   WITH (NOLOCK) ON (TPK.Loadkey  = OH.Loadkey)
      JOIN PICKDETAIL PD   WITH (NOLOCK) ON (OH.Orderkey  = PD.Orderkey)
                                         AND(TPK.Storerkey= PD.Storerkey)
                                         AND(TPK.Sku = PD.Sku)
                                         AND(TPK.Loc = PD.Loc)
                                         AND(TPK.ID  = PD.ID)
                                         AND(TPK.Pickdetailkey =  PD.PickDetailKey )
      JOIN LOC         LOC WITH (NOLOCK) ON (TPK.Loc  = LOC.Loc)
                                         AND(TPK.LocCategory = LOC.LocationCategory)
                                         AND(TPK.PickZone = LOC.PickZone)
      WHERE TPK.Loadkey = @c_Loadkey
      AND   TPK.ConsoOrderkey = @c_ConsoOrderkey
      ORDER BY PD.PickDetailKey

      OPEN CUR_PD
   
      FETCH NEXT FROM CUR_PD INTO @c_PickDetailkey
                                 ,@c_Orderkey
                                 ,@c_OrderLineNumber
                                 --,@c_PickType
                                 --,@n_Pallet
                                 --,@n_CaseCnt
                                 ,@n_Qty

      WHILE @@FETCH_STATUS <> -1
      BEGIN
         --IF @c_PickType = 'FP' AND @n_Qty < @n_Pallet 
         --BEGIN
         --   GOTO NEXT_PD
         --END

         --IF @c_PickType IN ( 'PPFC', 'FC') AND @n_Qty < @n_CaseCnt
         --BEGIN
         --   GOTO NEXT_PD
         --END
         
         --IF @c_PickType IN ( 'PPLC', 'LC') AND @n_Qty >= @n_CaseCnt
         --BEGIN
         --   GOTO NEXT_PD
         --END

         IF EXISTS ( SELECT 1
                     FROM REFKEYLOOKUP WITH (NOLOCK)
                     WHERE Pickdetailkey = @c_PickDetailKey
                  )
         BEGIN
            UPDATE REFKEYLOOKUP WITH (ROWLOCK)
            SET PickSlipNo = @c_PickHeaderKey
               ,EditWho = SUSER_NAME()
               ,EditDate= GETDATE()
               ,ArchiveCop = NULL
            WHERE PickDetailKey = @c_PickDetailKey
            AND PickSlipNo <> @c_PickHeaderKey
         END
         ELSE
         BEGIN
            INSERT INTO REFKEYLOOKUP (Pickdetailkey, Pickslipno, Orderkey, OrderLineNumber, Loadkey)
            VALUES (@c_PickDetailkey, @c_PickHeaderKey, @c_OrderKey, @c_OrderLineNumber, @c_loadkey)
         END

         SET @n_err = @@ERROR
         IF @n_err <> 0
         BEGIN
            SET @n_Continue = 3
            GOTO QUIT_SP
         END

         IF EXISTS ( SELECT 1
                     FROM PICKDETAIL WITH (NOLOCK)
                     WHERE PickDetailKey = @c_PickDetailKey
                     AND PickSlipNo <> @c_PickHeaderKey
                    )
         BEGIN
            UPDATE PICKDETAIL WITH (ROWLOCK)
            SET PickSlipNo = @c_PickHeaderKey
               ,EditWho = SUSER_NAME()
               ,EditDate= GETDATE()
               ,ArchiveCop = NULL
            WHERE PickDetailKey = @c_PickDetailKey

            SET @n_err = @@ERROR
            IF @n_err <> 0
            BEGIN
               SET @n_Continue = 3
               GOTO QUIT_SP
            END
         END
         NEXT_PD:
         FETCH NEXT FROM CUR_PD INTO @c_PickDetailkey
                                    ,@c_Orderkey
                                    ,@c_OrderLineNumber
                                    --,@c_PickType
                                    --,@n_Pallet
                                    --,@n_CaseCnt
                                    ,@n_Qty
      END
      CLOSE CUR_PD
      DEALLOCATE CUR_PD

      UPDATE #TMP_PCK115
      SET PickSlipNo  = @c_PickHeaderKey
         ,PrintedFlag = @c_PrintedFlag
      WHERE Loadkey   = @c_Loadkey
      AND ConsoOrderkey  = @c_ConsoOrderkey

      WHILE @@TRANCOUNT > 0 
      BEGIN
         COMMIT TRAN
      END
          
      FETCH NEXT FROM CUR_PSLIP INTO @c_Loadkey
                                    ,@c_PickZone
                                    ,@c_LocCategory
                                    ,@c_ConsoOrderkey
                                    ,@c_PickHeaderKey

   END
   CLOSE CUR_PSLIP
   DEALLOCATE CUR_PSLIP
   

QUIT_SP:
   IF CURSOR_STATUS( 'LOCAL', 'CUR_LOADORD') in (0 , 1)  
   BEGIN
      CLOSE CUR_LOADORD
      DEALLOCATE CUR_LOADORD
   END

   IF CURSOR_STATUS( 'LOCAL', 'CUR_CS') in (0 , 1)  
   BEGIN
      CLOSE CUR_CS
      DEALLOCATE CUR_CS
   END

   IF CURSOR_STATUS( 'LOCAL', 'CUR_PSLIP') in (0 , 1)  
   BEGIN
      CLOSE CUR_PSLIP
      DEALLOCATE CUR_PSLIP
   END

   IF CURSOR_STATUS( 'LOCAL', 'CUR_PICK') in (0 , 1)  
   BEGIN
      CLOSE CUR_PICK
      DEALLOCATE CUR_PICK
   END

   IF CURSOR_STATUS( 'LOCAL', 'CUR_PD') in (0 , 1)  
   BEGIN
      CLOSE CUR_PD
      DEALLOCATE CUR_PD
   END

   IF @n_Continue = 3
   BEGIN
      IF @@TRANCOUNT > 0
      BEGIN
         ROLLBACK TRAN
      END 
   END
   ELSE
   BEGIN
      WHILE @@TRANCOUNT > @n_StartTCnt
      BEGIN
         COMMIT TRAN
      END
   END

   WHILE @@TRANCOUNT < @n_StartTCnt
   BEGIN
      BEGIN TRAN
   END

      
   SELECT * FROM #TMP_PCK115  
    DROP Table #TMP_PCK115 
END -- procedure

GO