SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
CREATE PROCEDURE [dbo].[ispCountSheetValidation] 
	@c_StartSKU 		 NVARCHAR(20),
	@c_EndSKU   		 NVARCHAR(20),
	@c_StartItemClass  NVARCHAR(10),
	@c_EndItemClass	 NVARCHAR(10),
	@c_StartStorer		   NVARCHAR(15),
	@c_EndStorer		 NVARCHAR(15),
	@c_StartLoc			 NVARCHAR(10),
	@c_EndLoc			 NVARCHAR(10),
	@c_StartZone		 NVARCHAR(10),
	@c_EndZone			 NVARCHAR(10)
AS
BEGIN
   SET NOCOUNT ON 
   SET QUOTED_IDENTIFIER OFF 
   SET CONCAT_NULL_YIELDS_NULL OFF

SELECT  SKU.StorerKey, SKU.SKUGROUP, SKU.SKU, SKU.DESCR, LOTxLOCxID.LOC, 
	LOTATTRIBUTE.LOTTABLE01, LOTATTRIBUTE.LOTTABLE04,
	SYSQTY=SUM(LOTxLOCxID.QTY), CCQTY=0, FUJIQTY=0
INTO   #COMPARE
FROM   SKU (NOLOCK), LOTxLOCxID (NOLOCK), LOTATTRIBUTE (NOLOCK), LOC (NOLOCK)
WHERE  SKU.STORERKEY BETWEEN @c_StartStorer AND @c_EndStorer
AND    SKU.STORERKEY = LOTxLOCxID.STORERKEY
AND    SKU.SKU = LOTxLOCxID.SKU
AND    LOTxLOCxID.LOT = LOTATTRIBUTE.LOT
AND    LOTxLOCxID.LOC = LOC.LOC
AND    LOTxLOCxID.QTY > 0
AND    SKU.ItemClass BETWEEN @c_StartItemClass AND @c_EndItemClass
AND    LOTxLOCxID.LOC BETWEEN @c_StartLoc AND @c_EndLoc
AND    LOC.PutawayZone BETWEEN @c_StartZone AND @c_EndZone
GROUP BY SKU.StorerKey, SKU.SKUGROUP, SKU.SKU, SKU.DESCR, LOTxLOCxID.LOC, 
	LOTATTRIBUTE.LOTTABLE01, LOTATTRIBUTE.LOTTABLE04

DECLARE CUR1 CURSOR FAST_FORWARD READ_ONLY FOR
   SELECT SKU.StorerKey, SKU.SKUGROUP, SKU.SKU, SKU.DESCR, CCDETAIL.LOC, 
	ISNULL(CCDETAIL.LOTTABLE01, ''), CCDETAIL.LOTTABLE04,
	SUM(QTY)
	FROM   SKU (NOLOCK), CCDETAIL (NOLOCK), LOC (NOLOCK)
	WHERE  SKU.STORERKEY BETWEEN @c_StartStorer AND @c_EndStorer
	AND    SKU.STORERKEY = CCDETAIL.STORERKEY
	AND    SKU.SKU = CCDETAIL.SKU
	AND    CCDETAIL.QTY > 0
	AND    CCDETAIL.LOC = LOC.LOC
	AND    SKU.ItemClass BETWEEN @c_StartItemClass AND @c_EndItemClass
	AND    CCDETAIL.LOC BETWEEN @c_StartLoc AND @c_EndLoc
	AND    LOC.PutawayZone BETWEEN @c_StartZone AND @c_EndZone
	GROUP BY SKU.StorerKey, SKU.SKUGROUP, SKU.SKU, SKU.DESCR, CCDETAIL.LOC, 
		CCDETAIL.LOTTABLE01, CCDETAIL.LOTTABLE04

OPEN CUR1

DECLARE @c_SKUGroup NVARCHAR(10),
		  @c_SKU      NVARCHAR(20),
		  @c_DESCR	  NVARCHAR(60),
		  @c_LOC      NVARCHAR(10),
		  @c_Lottable01 NVARCHAR(18),
	     @d_Lottable04 datetime,
		  @n_Qty        int,
		  @c_StorerKey  NVARCHAR(15)

FETCH NEXT FROM CUR1 INTO @c_StorerKey, @c_SKUGroup,  @c_SKU, @c_DESCR, @c_LOC, @c_Lottable01, @d_Lottable04, @n_Qty

WHILE @@FETCH_STATUS <> -1
BEGIN
   IF EXISTS ( SELECT SKU FROM #COMPARE WHERE STORERKEY = @c_StorerKey AND SKU = @c_SKU 
					AND LOC = @c_LOC 
					AND Lottable01 = @c_Lottable01
					AND Lottable04 = @d_Lottable04 )
	BEGIN
		UPDATE #COMPARE
			SET CCQty = CCQty + @n_Qty
		WHERE STORERKEY = @c_StorerKey
			AND SKU = @c_SKU 
			AND LOC = @c_LOC 
			AND Lottable01 = @c_Lottable01
			AND Lottable04 = @d_Lottable04
	END
	ELSE
	BEGIN
		INSERT INTO #COMPARE (StorerKey, SKU, SKUGroup, Descr, LOC, Lottable01, Lottable04, SysQty, CCQty, FUJIQty)
			VALUES (@c_StorerKey, @c_SKU, @c_SKUGroup, @c_Descr, @c_LOC, @c_Lottable01, @d_Lottable04, 0, @n_Qty, 0)
	END
	FETCH NEXT FROM CUR1 INTO @c_StorerKey, @c_SKUGroup ,  @c_SKU, @c_DESCR, @c_LOC, @c_Lottable01, @d_Lottable04, @n_Qty
END
CLOSE CUR1
DEALLOCATE CUR1

SELECT * FROM #COMPARE
ORDER BY SKUGROUP, SKU, LOC

DROP TABLE #COMPARE
END


GO