SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
/************************************************************************/
/* Stored Procedure: nsp_GetPickSlipOrders26                            */
/* Creation Date: 02.May.2008                                           */
/* Copyright: IDS                                                       */
/* Written by: June                                                     */
/*                                                                      */
/* Remarks: SOS103017 - IDSPH ULP                                       */
/*                                                                      */
/* Purpose: To speed up picking process, picklists are generated by     */
/*          Pick Zone and distribute to few pickers to do the picking.  */
/*                                                                      */
/* Called By: r_dw_print_pickorder26                                    */
/*                                                                      */
/* PVCS Version: 1.9                                                    */
/*                                                                      */
/* Version: 5.4                                                         */
/*                                                                      */
/* Data Modifications:                                                  */
/*                                                                      */
/* Updates:                                                             */
/* Date         Author   Ver  Purposes                                  */
/* 2008/11/13   TLTING   1.1  Do not reassign Pickslipno for reprint    */
/*                            (tlting01)                                */
/* 14-09-2009   TLTING   1.2  ID field length   (tlting01)              */
/* 20-03-2013   NJOW01   1.3  272601- ColPal Consol PickList            */
/* 04-09-2013   YTWan    1.4  SOS#288327:New Consolidate PickList(Wan01)*/
/* 10-SEP-2013  YTWan    1.5  SOS#288327 - fixed (Wan02)                */
/* 10-SEP-2013  YTWan    1.6  SOS#288327 - CR (Wan03)                   */
/* 08-OCT-2013  NJOW02   1.7  SOS#291540 - Fix empty pickzone to update */
/*                            pickslip# to pickdetail.                  */
/* 27-OCT-2014  NJOW03   1.8  324333-Add load plan route and storer     */
/* 10-NOV-2014  Leong    1.9  SOS# 325653 - Add ISNULL check.           */
/* 11-NOV-2014  NJOW04   2.0  324333-pickslip no by consignee           */
/* 19-JAN-2015  CSCHONG  2.1  328091-Add new field ordergroup (CS01)    */
/* 28-APR-2015  NJOW05   2.2  339791-Add trfroom                        */
/* 18-Sep-2015  CSCHONG  2.3  SOS#352276 (CS01)                         */
/* 01-Feb-2018  CSCHONG  2.4  WMS-3815- New report config (CS03)        */
/************************************************************************/

CREATE PROC [dbo].[nsp_GetPickSlipOrders26] (@c_loadkey NVARCHAR(10))
 AS
BEGIN
    SET CONCAT_NULL_YIELDS_NULL OFF
    SET QUOTED_IDENTIFIER OFF
    SET ANSI_NULLS OFF
    SET NOCOUNT ON

    DECLARE @c_pickheaderkey        NVARCHAR(10),
				@n_continue             int,
				@n_starttcnt			   int,
				@c_errmsg					NVARCHAR(255),
				@b_success					int,
				@n_err						int,
				@c_sku						NVARCHAR(20),
				@c_SkuDescr					NVARCHAR(60),
				@c_Loc						NVARCHAR(10),
				@c_LogicalLoc				NVARCHAR(18),
				@c_LocType					NVARCHAR(10),
				@c_ID							NVARCHAR(18),     -- tlting01
				@c_orderkey					NVARCHAR(10),
				@c_PickslipNo				NVARCHAR(10),
				@c_PrintedFlag				NVARCHAR(1),
				@c_PrevPickslipNo			NVARCHAR(10),
				@c_PickUOM					NVARCHAR(5),
				@c_PickZone					NVARCHAR(10),
				@c_C_Company				NVARCHAR(45),    --(Wan01)
				--@c_Prev_C_Company       NVARCHAR(45), --NJOW03
				@c_PickType					NVARCHAR(30),
				@c_PickDetailkey			NVARCHAR(10),
				@c_OrderLineNumber		NVARCHAR(5),
				@d_LoadDate					datetime,
				@c_Lottable02				NVARCHAR(18),
				@d_Lottable04				datetime,
				@n_Palletcnt				int,
				@n_Cartoncnt				int,
				@n_EA							int,                --(Wan01)
				@n_TotalCarton				FLOAT,            --(Wan01)
				@n_Pallet					int,
				@n_Casecnt					int,
				@n_Qty						int,
				@n_PageNo					int,
				@c_TotalPage				int,
				@b_debug						int  ,
				@c_WaveKey					NVARCHAR(10),    -- (tlting01)
				@c_Lottable02label		NVARCHAR(30),
				@c_Lottable04Label		NVARCHAR(30),
				@c_Storerkey				NVARCHAR(15),
				@c_Route						NVARCHAR(10), --NJOW03
				@c_Consigneekey			NVARCHAR(15), --NJOW04
				@c_OrderGrp					NVARCHAR(20),  --CS01
				@n_CntOrderGrp				INT,           --CS01 
				@c_OrdGrpFlag				NVARCHAR(1),   --CS01
				@c_RLoadkey					NVARCHAR(20),  --CS01
				@c_TrfRoom					NVARCHAR(10), --NJOW05
				@c_LEXTLoadKey				NVARCHAR(20),   --(CS01)
				@c_LPriority				NVARCHAR(10),   --(CS01)
				@c_LPuserdefDate01		datetime        --(CS01)
				,@n_innerpack           FLOAT           --(CS03)
				,@n_showField           INT             --(CS03)
				,@n_innercnt            FLOAT           --(CS03)

   DECLARE @t_Result Table (
				Loadkey         NVARCHAR(10),
				Pickslipno      NVARCHAR(10),
				PickType        NVARCHAR(30),
				LoadingDate     Datetime,
				PickZone        NVARCHAR(10),
				C_Company       NVARCHAR(45),        --(Wan01)
				Loc             NVARCHAR(10),
				Logicalloc      NVARCHAR(18),
				SKU             NVARCHAR(20),
				Descr           NVARCHAR(60),
				Palletcnt       int,
				Cartoncnt       int,
				EA              INT,                 --(Wan01)
				TotalCarton     FLOAT,               --(Wan01)
				ID              NVARCHAR(18),        -- tlting01
				Lottable02      NVARCHAR(18),
				Lottable04      Datetime,
				ReprintFlag     NVARCHAR(1),
				PageNo          int,
				TotalPage       int,
				Route           NVARCHAR(10), --NJOW03
				Storerkey       NVARCHAR(15), --NJOW03
				Consigneekey    NVARCHAR(15), --NJOW04
				OrderGrpFlag    NVARCHAR(1),  --CS01
				OrderGrp        NVARCHAR(20), --CS01
				TrfRoom         NVARCHAR(10) NULL, --NJOW05
				LEXTLoadKey     NVARCHAR(20) NULL, --(CS01)
				LPriority       NVARCHAR(10) NULL, --(CS01)
				LPuserdefDate01 datetime, --(CS01)
				rowid           int IDENTITY(1,1),
				showfield       INT,
            InnerPack       FLOAT )        --(CS03)

 SELECT @n_continue = 1, @n_starttcnt=@@TRANCOUNT
 SELECT @b_Debug = 0

 IF EXISTS(SELECT 1 FROM PickHeader (NOLOCK) WHERE ExternOrderKey = @c_loadkey AND Zone = 'LB')
   SELECT @c_PrintedFlag = 'Y'
 ELSE
   SELECT @c_PrintedFlag = 'N'
   

 BEGIN TRAN

 -- Uses PickType as a Printed Flag
 UPDATE PickHeader
 SET   PickType = '1',
       TrafficCop = NULL
 WHERE ExternOrderKey = @c_loadkey
 AND   Zone = 'LB'
 AND   PickType = '0'
 IF @@ERROR <> 0
 BEGIN
   SELECT @n_continue = 3
   SELECT @c_errmsg = CONVERT(NVARCHAR(250),@n_err), @n_err=73000
   SELECT @c_errmsg='NSQL'+CONVERT(NVARCHAR(5),@n_err)+': Update Failed On Table Pickheader Table. (nsp_GetPickSlipOrders26)' + ' ( ' + ' SQLSvr MESSAGE=' + LTRIM(RTRIM(@c_errmsg)) + ' ) '
 END


 IF @n_continue = 1 OR @n_continue = 2
 BEGIN
  DECLARE pickslip_cur CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
   SELECT Loadplan.Loadkey
         ,LOC.LocationType
         ,Loadplan.AddDate
         --(Wan01) - START
         -- CASE WHEN UPPER(LOC.LocationType) = 'CASE' OR UPPER(LOC.LocationType) = 'PICK'
         --      THEN LOC.PickZone ELSE 'BULK' END,
         ,ISNULL(RTRIM(LOC.PickZone),'')
         ,ISNULL(RTRIM(ORDERS.C_Company),'')
         --(Wan01) - END
         ,Pickdetail.Loc
         ,LOC.LogicalLocation
         ,Pickdetail.Sku
         ,MAX(SKU.Descr)
         ,Pickdetail.ID
         ,LA.Lottable02
         ,LA.Lottable04
         ,PACK.Pallet
         ,PACK.Casecnt
         ,SUM(PickDetail.Qty)
         ,ISNULL(RTRIM(LOADPLAN.Route),'') --NJOW03
         ,ORDERS.Storerkey --NJOW03
         ,ORDERS.Consigneekey --NJOW04
         ,CASE WHEN ISNULL(CLR.Code,'') = '' THEN 'N' ELSE 'Y' END AS showordergrp         --CS01
         ,LOADPLAN.Trfroom --NJOW05
         ,Loadplan.Externloadkey AS LEXTLoadKey                                   --(CS01) 
         ,Loadplan.Priority AS LPriority                                          --(CS01)
         ,Loadplan.LPuserdefDate01 AS LPuserdefDate01    --(CS01)
         ,PACK.innerpack                                 --CS03
   FROM  Pickdetail WITH (NOLOCK)
   JOIN  ORDERS          WITH (NOLOCK) ON (PICKDETAIL.Orderkey = ORDERS.Orderkey)         --(Wan01)
   JOIN  LoadplanDetail WITH (NOLOCK) ON LoadplanDetail.Orderkey = PickDetail.Orderkey
   JOIN  Loadplan WITH (NOLOCK) ON Loadplan.Loadkey = LoadplanDetail.Loadkey
   JOIN  LOC WITH (NOLOCK) ON LOC.Loc = Pickdetail.Loc
   JOIN  SKU WITH (NOLOCK) ON SKU.Storerkey = PickDetail.Storerkey AND SKU.SKU = PickDetail.SKU
   JOIN  PACK WITH (NOLOCK) ON PACK.Packkey = SKU.Packkey
   JOIN  Lotattribute LA WITH (NOLOCK) ON LA.Lot = PickDetail.Lot
   LEFT OUTER JOIN Codelkup CLR (NOLOCK) ON (ORDERS.Storerkey = CLR.Storerkey AND CLR.Code = 'SHOWORDERGRP'                                      --CS01
                                 AND CLR.Listname = 'REPORTCFG' AND CLR.Long = 'r_dw_print_pickorder26' AND ISNULL(CLR.Short,'') <> 'N')         --CS01
   WHERE Loadplan.Loadkey = @c_Loadkey
   -- AND   Pickdetail.Pickslipno > ''
   AND   Pickdetail.Status < '5'
   GROUP BY Loadplan.Loadkey
         ,  LOC.LocationType
         ,  Loadplan.AddDate
         --(Wan01) - START
         -- CASE WHEN UPPER(LOC.LocationType) = 'CASE' OR UPPER(LOC.LocationType) = 'PICK'
         --      THEN LOC.PickZone ELSE 'BULK' END,
         ,ISNULL(RTRIM(LOC.PickZone),'')
         ,ISNULL(RTRIM(ORDERS.C_Company),'')
         --(Wan01) - END
         ,  Pickdetail.Loc
         ,  LOC.LogicalLocation
         ,  Pickdetail.Sku
         ,  Pickdetail.ID
         ,  LA.Lottable02
         ,  LA.Lottable04
         ,  PACK.Pallet
         ,  PACK.Casecnt
         ,  ISNULL(RTRIM(LOADPLAN.Route),'')  --NJOW03
         ,  ORDERS.Storerkey --NJOW03
         ,  ORDERS.Consigneekey --NJOW04
         ,CASE WHEN ISNULL(CLR.Code,'') = '' THEN 'N' ELSE 'Y' END  --CS01 
         ,LOADPLAN.Trfroom --NJOW05
         ,Loadplan.Externloadkey                                --(CS01) 
         ,Loadplan.Priority                                     --(CS01)
         ,Loadplan.LPuserdefDate01                              --(CS01) 
         ,PACK.innerpack                                 --CS03
   ORDER BY --(Wan01) - START
         ISNULL(RTRIM(LOC.PickZone),''),
         -- CASE WHEN UPPER(LOC.locationType) = 'CASE' OR UPPER(LOC.LocationType) = 'PICK' THEN '1' ELSE '2' END,
         -- CASE WHEN UPPER(LOC.locationType) = 'CASE' OR UPPER(LOC.LocationType) = 'PICK' THEN LOC.PickZone
         -- ELSE 'BULK' END,
         --(Wan01) - END
        LOC.LogicalLocation, Pickdetail.Loc, Pickdetail.SKU

  OPEN pickslip_cur

  FETCH NEXT FROM pickslip_cur INTO @c_Loadkey, @c_LocType, @d_LoadDate, @c_PickZone, @c_C_Company, @c_Loc, @c_LogicalLoc, -- (Wan01) Add C_COmpany
              @c_SKU, @c_SkuDescr, @c_ID, @c_Lottable02, @d_Lottable04, @n_Pallet, @n_Casecnt, @n_Qty, @c_Route, @c_Storerkey, @c_Consigneekey,@c_ordGrpflag, --CS01
              @c_TrfRoom, --NJOW05
              @c_LEXTLoadKey,@c_LPriority,@c_LPuserdefDate01,@n_innerpack          --(CS01)   --Cs03

  WHILE (@@FETCH_STATUS <> -1) AND (@n_continue = 1 OR @n_continue = 2)
  BEGIN
   SET @n_Palletcnt = 0
   SET @n_Cartoncnt = 0
   SET @n_EA        = 0          --(Wan01)
   SET @n_TotalCarton = 0.00     --(Wan01)


   --(Wan01) - START
      SET @n_TotalCarton = CASE WHEN @n_Casecnt > 0 THEN @n_Qty / @n_Casecnt
                                ELSE 0
                                END

      IF UPPER(@c_PickZone) <> 'BULK'
      BEGIN
         SET @c_PickType = 'PICKING AREA'
         --(Wan03) -- START
         --SET @n_EA = CASE WHEN @c_LocType = 'PICK' THEN @n_Qty ELSE 0 END
         --SET @n_Cartoncnt = CASE WHEN @c_LocType = 'CASE'   AND @n_CaseCnt > 0
         --                        THEN @n_Qty / @n_CaseCnt ELSE 0 END
         --SET @n_Palletcnt = CASE WHEN @c_LocType = 'PALLET' AND @n_Pallet > 0
         --                        THEN @n_Qty/@n_Pallet ELSE 0 END
      END
      ELSE
      BEGIN
         IF @n_Qty >= @n_Pallet
         BEGIN
            SET @c_PickType = 'FULL PALLET PICK'
            --SET @n_Palletcnt = CASE WHEN @n_Pallet > 0 THEN FLOOR(@n_Qty / @n_Pallet) ELSE 0 END    --(Wan03)
         END
         ELSE
         BEGIN
            SET @c_PickType = 'CASE PICK'
            --SET @n_Cartoncnt = CASE WHEN @n_CaseCnt > 0 THEN FLOOR(@n_Qty / @n_CaseCnt) ELSE 0 END  --(Wan03)
         END
      END
      --(Wan03) - START
      SET @n_Palletcnt = CASE WHEN @n_Pallet > 0 THEN @n_Qty/@n_Pallet ELSE 0 END
      SET @n_Cartoncnt = CASE WHEN @n_CaseCnt> 0 THEN (@n_Qty - (@n_Palletcnt * @n_Pallet))/@n_CaseCnt ELSE 0 END
      SET @n_EA        = @n_Qty - (@n_Palletcnt * @n_Pallet) - (@n_Cartoncnt * @n_CaseCnt)
      --(Wan03) - END
      SET @n_innercnt = CASE WHEN @n_innerpack > 0 and @n_CaseCnt> 0 THEN ( (@n_Qty - (@n_Cartoncnt * @n_CaseCnt)) / @n_innerpack) ELSE 0 END
   --(Wan01) - END
    /* (Wan01) - START
   IF UPPER(@c_LocType) = 'CASE' OR UPPER(@c_LocType) = 'PICK'
   BEGIN
    SET @c_PickType = 'PICKING AREA'

    IF @n_Casecnt > 0
    BEGIN
     SET @n_Cartoncnt = FLOOR(@n_Qty / @n_Casecnt)
     SET @n_TotalCarton = @n_Cartoncnt
    END
   END
   ELSE
   BEGIN -- Full Pallet Pick / Case Pick
    IF @n_Qty >= @n_Pallet
    BEGIN
     SET @c_PickType = 'FULL PALLET PICK'

     IF @n_Pallet > 0
     BEGIN
      SET @n_Palletcnt = FLOOR(@n_Qty / @n_Pallet)

      IF @n_Casecnt > 0
       SET @n_Cartoncnt = FLOOR((@n_Qty - (@n_Palletcnt * @n_Pallet)) / @n_Casecnt)
     END
     ELSE
     BEGIN
      IF @n_Casecnt > 0
       SET @n_Cartoncnt = FLOOR(@n_Qty / @n_Casecnt)
     END

     IF @n_Casecnt > 0
     BEGIN
      SET @n_TotalCarton = FLOOR(@n_Qty / @n_Casecnt)
     END
    END
    ELSE
    BEGIN
     SET @c_PickType = 'CASE PICK'

     IF @n_Casecnt > 0
     BEGIN
      SET @n_Cartoncnt = FLOOR(@n_Qty / @n_Casecnt)
      SET @n_TotalCarton = @n_Cartoncnt
     END
    END
   END -- Full Pallet Pick / Case Pick
   (Wan01) - END */
   
      --CS03 Start
   
   SET @n_showField = 0
   
   SELECT @n_showfield  = CASE WHEN ISNULL(short,'0') ='Y' THEN 1 ELSE 0 END       --(CS01)
   FROM CODELKUP WITH (NOLOCK)
   WHERE ListName = 'REPORTCFG'
   AND   Storerkey= @c_Storerkey
   AND   Long = 'r_dw_print_pickorder26'
   AND Code = 'showfield'
   AND   ISNULL(Short,'') <> 'N'
   --(CS03 End) - END

   INSERT INTO @t_Result (Loadkey, Pickslipno, PickType, LoadingDate, PickZone, Loc, LogicalLoc, SKU, Descr,
            Palletcnt, Cartoncnt, TotalCarton, ID, Lottable02, Lottable04,
            ReprintFlag, PageNo, TotalPage, C_Company, EA, Route, Storerkey, Consigneekey,OrderGrpFlag, TrfRoom,     --(Wan01)  --CS01
            LEXTLoadKey,LPriority,LPuserdefDate01,showfield,InnerPack)         --(CS01)     --Cs03
   VALUES (@c_Loadkey, '', @c_PickType, @d_LoadDate, @c_PickZone, @c_LOC, @c_LogicalLoc, @c_SKU, @c_SkuDescr,
           @n_Palletcnt, @n_Cartoncnt, @n_TotalCarton, @c_ID, @c_Lottable02, @d_Lottable04, @c_PrintedFlag, 0, 0
          ,@c_C_Company, @n_EA, @c_Route, @c_Storerkey, @c_Consigneekey,@c_OrdGrpFlag, @c_TrfRoom,                -- (Wan01)  --CS01
          @c_LEXTLoadKey,@c_LPriority,@c_LPuserdefDate01,@n_showField,@n_innercnt)          --(CS01)    --(CS03)

   FETCH NEXT FROM pickslip_cur INTO @c_Loadkey, @c_LocType, @d_LoadDate, @c_PickZone, @c_C_Company, @c_Loc, @c_LogicalLoc,  -- (Wan01) Add C_COmpany
               @c_SKU, @c_SkuDescr, @c_ID, @c_Lottable02, @d_Lottable04, @n_Pallet, @n_Casecnt, @n_Qty, @c_Route, @c_Storerkey, @c_Consigneekey,@c_ordGrpflag,
               @c_TrfRoom, --NJOW05               
               @c_LEXTLoadKey,@c_LPriority,@c_LPuserdefDate01,@n_innerpack            --(CS01)   --(CS03)
  END /* While */

  CLOSE pickslip_cur
  DEALLOCATE pickslip_cur
 END /* @n_Continue = 1 */

 IF @b_Debug = 1
 BEGIN
  SELECT * FROM @t_Result

   SELECT PickType, PickZone, Consigneekey
   FROM   @t_Result
   WHERE  Pickslipno = ''
   GROUP BY PickType, PickZone, Consigneekey
   ORDER BY CASE WHEN PickType = 'PICKING AREA' THEN '1'
         WHEN PickType = 'FULL PALLET PICK' THEN '2' ELSE '3' END, Consigneekey
 END

 IF @n_continue = 1 OR @n_continue = 2
 BEGIN
  DECLARE PickType_cur CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
   SELECT PickType, PickZone, Consigneekey
   FROM   @t_Result
   WHERE  Pickslipno = ''
   GROUP BY PickType, PickZone, Consigneekey
   ORDER BY CASE WHEN PickType = 'PICKING AREA' THEN '1'
         WHEN PickType = 'FULL PALLET PICK' THEN '2' ELSE '3' END, Consigneekey

  OPEN PickType_cur

  FETCH NEXT FROM PickType_cur INTO @c_PickType, @c_PickZone, @c_Consigneekey

   WHILE (@@FETCH_STATUS <> -1) AND (@n_continue = 1 OR @n_continue = 2)
  BEGIN
         SET @c_pickheaderkey = ''
         SET @c_WaveKey = ''

         IF @c_PickZone = 'BULK'
         BEGIN
            IF @c_PickType = 'FULL PALLET PICK'
            BEGIN
               SELECT @c_pickheaderkey = PickHeaderKey
               FROM  PickHeader (NOLOCK)
               WHERE ExternOrderKey = @c_loadkey
                AND  WaveKey = RTRIM(@c_PickZone) + '_P'
                AND  Zone = 'LB'
                AND  ConsoOrderkey = @c_Consigneekey --NJOW04

               SELECT @c_WaveKey = RTRIM(@c_PickZone) + '_P'  -- tlting01
            END
            ELSE
            BEGIN
               SELECT @c_pickheaderkey = PickHeaderKey
               FROM  PickHeader (NOLOCK)
               WHERE ExternOrderKey = @c_loadkey
                AND  WaveKey = RTRIM(@c_PickZone) + '_C'
                AND  Zone = 'LB'
                AND  ConsoOrderkey = @c_Consigneekey --NJOW04
                
               SELECT @c_WaveKey = RTRIM(@c_PickZone) + '_C'  -- tlting01
            END
         END
         ELSE
         BEGIN
            SELECT @c_pickheaderkey = PickHeaderKey
            FROM  PickHeader (NOLOCK)
            WHERE ExternOrderKey = @c_loadkey
             AND  WaveKey = @c_PickZone
             AND  Zone = 'LB'
             AND  ConsoOrderkey = @c_Consigneekey --NJOW04

            SELECT @c_WaveKey = RTRIM(@c_PickZone)  -- tlting01
         END

   -- Only insert the First Pickslip# in PickHeader
   IF ISNULL(RTRIM(@c_pickheaderkey), '') = ''
   BEGIN
      EXECUTE nspg_GetKey
       'PICKSLIP',
       9,
       @c_pickheaderkey  OUTPUT,
       @b_success       OUTPUT,
       @n_err           OUTPUT,
       @c_errmsg        OUTPUT

      SELECT @c_pickheaderkey = 'P' + @c_pickheaderkey

    INSERT INTO PICKHEADER
    (PickHeaderKey,    OrderKey,    ExternOrderKey, PickType, Zone, TrafficCop, WaveKey, ConsoOrderkey)
    VALUES
    (@c_pickheaderkey, '',      @c_LoadKey,     '0',      'LB',  '', @c_WaveKey, @c_Consigneekey )   -- @c_PickZone)

      SELECT @n_err = @@ERROR
      IF @n_err <> 0
      BEGIN
        SELECT @n_continue = 3
       SELECT @c_errmsg = CONVERT(NVARCHAR(250),@n_err), @n_err=73001
        SELECT @c_errmsg='NSQL'+CONVERT(NVARCHAR(5),@n_err)+': Insert Failed On Table PICKHEADER. (nsp_GetPickSlipOrders26)' + ' ( ' + ' SQLSvr MESSAGE=' + LTRIM(RTRIM(@c_errmsg)) + ' ) '
      END
   END

   IF @n_Continue = 1 OR @n_Continue = 2
   BEGIN
    UPDATE @t_Result
    SET    PickSlipno = @c_pickheaderkey
    WHERE  Pickslipno = ''
    AND    PickType = @c_PickType
    AND    PickZone = @c_PickZone
    AND    Consigneekey = @c_Consigneekey --NJOW04

    -- Get PickDetail records for each Pick Ticket (Picking Area / Full Pallet / Case Pick)
    DECLARECURSOR_PickDet:
    IF @c_PickType = 'PICKING AREA'
    BEGIN
     DECLARE PickDet_cur CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
      SELECT PickDetail.Pickdetailkey, PickDetail.Orderkey, PickDetail.OrderLineNumber
      FROM   PickDetail WITH (NOLOCK)
      JOIN   LoadPlanDetail WITH (NOLOCK) ON LoadPlanDetail.Orderkey = PickDetail.Orderkey
      JOIN   LOC WITH (NOLOCK) ON LOC.Loc = Pickdetail.Loc
      JOIN   ORDERS WITH (NOLOCK) ON LoadPlanDetail.Orderkey = ORDERS.Orderkey --NJOW04
      WHERE  LoadPlanDetail.Loadkey = @c_Loadkey
      --AND    (LOC.LocationType = 'CASE' OR LOC.LocationType = 'PICK' OR LOC.LocationType = 'PALLET')  --(Wan02)
      AND    (LOC.LocationType = 'CASE' OR LOC.LocationType = 'PICK' OR LOC.LocationType = 'PALLET' OR ISNULL(LOC.PickZone,'')='')  --(NJOW02)
      AND    LOC.PickZone = @c_PickZone
      AND    Pickdetail.Status < '5'
      AND    ORDERS.Consigneekey = @c_Consigneekey --NJOW04
      ORDER BY Pickdetailkey
    END
    ELSE IF @c_PickType = 'FULL PALLET PICK'
    BEGIN
     DECLARE PickDet_cur CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
      SELECT PickDetail.Pickdetailkey, PickDetail.Orderkey, PickDetail.OrderLineNumber
      FROM   PickDetail WITH (NOLOCK)
      JOIN   LoadPlanDetail WITH (NOLOCK) ON LoadPlanDetail.Orderkey = PickDetail.Orderkey
      JOIN   LotAttribute LA WITH (NOLOCK) ON LA.Lot = PickDetail.Lot
      JOIN   ORDERS WITH (NOLOCK) ON LoadPlanDetail.Orderkey = ORDERS.Orderkey --NJOW04
      JOIN   @t_Result RESULT ON PickDetail.SKU = RESULT.SKU
               AND PickDetail.Loc = RESULT.Loc
               AND PickDetail.ID = RESULT.ID
               AND ISNULL(LA.Lottable02,'') = ISNULL(RESULT.Lottable02,'')-- SOS# 325653
               AND ISNULL(LA.Lottable04,'') = ISNULL(RESULT.Lottable04,'')-- SOS# 325653              
               AND RESULT.Consigneekey = ORDERS.Consigneekey --NJOW04 
      WHERE  LoadPlanDetail.Loadkey = @c_Loadkey
      AND    RESULT.PickType = 'FULL PALLET PICK'
      AND    Pickdetail.Status < '5'
      AND    ORDERS.Consigneekey = @c_Consigneekey --NJOW04
      ORDER BY Pickdetailkey
    END -- 'Full Pallet Pick'
    ELSE IF @c_PickType = 'CASE PICK'
    BEGIN
     DECLARE PickDet_cur CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
      SELECT PickDetail.Pickdetailkey, PickDetail.Orderkey, PickDetail.OrderLineNumber
      FROM   PickDetail WITH (NOLOCK)
      JOIN   LoadPlanDetail WITH (NOLOCK) ON LoadPlanDetail.Orderkey = PickDetail.Orderkey
      JOIN   LotAttribute LA WITH (NOLOCK) ON LA.Lot = PickDetail.Lot
      JOIN   ORDERS WITH (NOLOCK) ON LoadPlanDetail.Orderkey = ORDERS.Orderkey --NJOW04
      JOIN   @t_Result RESULT ON PickDetail.SKU = RESULT.SKU
               AND PickDetail.Loc = RESULT.Loc
               AND PickDetail.ID = RESULT.ID
               AND ISNULL(LA.Lottable02,'') = ISNULL(RESULT.Lottable02,'')-- SOS# 325653
               AND ISNULL(LA.Lottable04,'') = ISNULL(RESULT.Lottable04,'')-- SOS# 325653
               AND RESULT.Consigneekey = ORDERS.Consigneekey --NJOW04 
      WHERE  LoadPlanDetail.Loadkey = @c_Loadkey
      AND    RESULT.PickType = 'CASE PICK'
      AND    Pickdetail.Status < '5'
      AND    ORDERS.Consigneekey = @c_Consigneekey --NJOW04
      ORDER BY Pickdetailkey
    END -- 'CASE PICK'

      OPEN PickDet_cur
      SELECT @n_err = @@ERROR

      IF @n_err = 16905
      BEGIN
         CLOSE PickDet_cur
         DEALLOCATE PickDet_cur
         GOTO DECLARECURSOR_PickDet
      END

      IF @n_err = 16915
      BEGIN
         CLOSE PickDet_cur
         DEALLOCATE PickDet_cur
         GOTO DECLARECURSOR_PickDet
      END

      IF @n_err = 16916
      BEGIN
         GOTO EXIT_SP
      END

    FETCH NEXT FROM PickDet_cur INTO @c_Pickdetailkey, @c_Orderkey, @c_OrderLineNumber

     WHILE (@@FETCH_STATUS <> -1) AND (@n_continue = 1 OR @n_continue = 2)
    BEGIN
     IF NOT EXISTS (SELECT 1 FROM RefKeyLookup WITH (NOLOCK) WHERE Pickdetailkey = @c_PickDetailkey)
     BEGIN
      INSERT INTO RefkeyLookup (Pickdetailkey, Pickslipno, Orderkey, OrderLineNumber, Loadkey)
      VALUES (@c_PickDetailkey, @c_pickheaderkey, @c_OrderKey, @c_OrderLineNumber, @c_loadkey)

        IF @@ERROR <> 0
        BEGIN
          SELECT @n_continue = 3
         SELECT @c_errmsg = CONVERT(NVARCHAR(250),@n_err), @n_err=73001
          SELECT @c_errmsg='NSQL'+CONVERT(NVARCHAR(5),@n_err)+': Insert Failed On Table RefkeyLookup. (nsp_GetPickSlipOrders26)' + ' ( ' + ' SQLSvr MESSAGE=' + LTRIM(RTRIM(@c_errmsg)) + ' ) '
        END

      IF (@n_continue = 1 OR @n_continue = 2)
      BEGIN
       UPDATE PICKDETAIL WITH (ROWLOCK)
       SET    PickSlipNo = @c_pickheaderkey, TrafficCop = Null
       WHERE  PickDetailkey = @c_PickDetailkey
         IF @@ERROR <> 0
         BEGIN
           SELECT @n_continue = 3
          SELECT @c_errmsg = CONVERT(NVARCHAR(250),@n_err), @n_err=73001
           SELECT @c_errmsg='NSQL'+CONVERT(NVARCHAR(5),@n_err)+': Update Failed On Table PICKDETAIL. (nsp_GetPickSlipOrders26)' + ' ( ' + ' SQLSvr MESSAGE=' + LTRIM(RTRIM(@c_errmsg)) + ' ) '
         END
      END
     END

     FETCH NEXT FROM PickDet_cur INTO @c_Pickdetailkey, @c_Orderkey, @c_OrderLineNumber
    END

    CLOSE pickdet_cur
    DEALLOCATE pickdet_cur
   END -- Continue = 1

   FETCH NEXT FROM PickType_cur INTO @c_PickType, @c_PickZone, @c_Consigneekey
  END -- While : Get Pickslip#
  CLOSE PickType_cur
  DEALLOCATE PickType_cur
 END

SET @c_OrderGrp = ''
  /*CS01 Start*/
  DECLARE C_OrdGrp CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
      SELECT Distinct loadkey
       FROM   @t_Result
      ORDER BY loadkey

   OPEN C_OrdGrp

  FETCH NEXT FROM C_OrdGrp INTO @c_Rloadkey

   WHILE @@FETCH_STATUS <> -1
   BEGIN

   FETCH NEXT FROM C_OrdGrp INTO @c_RLoadkey

   SELECT @n_CntOrderGrp = COUNT(DISTINCT ord.ordergroup)
   FROM Orders Ord WITH (NOLOCK)
   WHERE Ord.Loadkey = @c_RLoadkey

   IF @n_CntOrderGrp = 1
     BEGIN
      
       SELECT @c_OrderGrp = Ord.OrderGroup
       FROM Orders ord WITH (NOLOCK)
       WHERE Ord.loadkey =  @c_RLoadkey 
     END

   UPDATE @t_Result
   SET OrderGrp = @c_OrderGrp
   WHERE loadkey = @c_RLoadkey
  
   END

   CLOSE C_OrdGrp
   DEALLOCATE C_OrdGrp
    
   /*CS01 End*/

 IF @n_continue = 1 OR @n_continue = 2
 BEGIN
  -- Assign Page No
  SET @c_PrevPickslipNo = ''
  SET @c_TotalPage = 0
  --SET @c_Prev_C_Company = '@' --NJOW03
    SET @n_PageNo = 1

      DECLARE C_PageNo CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
      SELECT Distinct PickslipNo
--             c_Company  --NJOW03
      FROM   @t_Result
      ORDER BY PickslipNo
               --c_Company  --NJOW03
      OPEN C_PageNo

      FETCH NEXT FROM C_PageNo INTO @c_PickslipNo
                                    --@c_C_Company   --NJOW03

      WHILE @@FETCH_STATUS <> -1
      BEGIN
         IF @c_PickslipNo <> @c_PrevPickslipNo
            --OR @c_C_Company <> @c_Prev_C_Company --NJOW03
         BEGIN
             -- SET @n_PageNo = 1

             WHILE 1 = 1
             BEGIN
                IF NOT EXISTS (SELECT 1 FROM @t_Result
                               WHERE PickslipNo = @c_PickslipNo
                               AND   PageNo = 0)
                               --AND   c_Company = @c_C_Company)  --NJOW03
              BEGIN
                 SET RowCount 0
                   BREAK
                END

                SET RowCount 20

                UPDATE @t_Result
                SET   PageNo = @n_PageNo
                WHERE PickslipNo = @c_PickslipNo
                AND   PageNo = 0
                --AND   c_Company = @c_C_Company --NJOW03


                SET  @n_PageNo    = @n_PageNo + 1
                SET  @c_TotalPage = @c_TotalPage + 1
                SET  RowCount 0
             END -- end while 1=1
         END

         SET @c_PrevPickslipNo = @c_PickslipNo --NJOW03
         --SET @c_Prev_C_Company = @c_C_Company  --NJOW03

         FETCH NEXT FROM C_PageNo INTO @c_PickslipNo
                                       --@c_C_Company  --NJOW03
      END

      CLOSE C_PageNo
      DEALLOCATE C_PageNo

  

  -- Update Totalpage
      UPDATE @t_Result
      SET   TotalPage = @c_TotalPage
      WHERE TotalPage = 0

  SELECT TOP 1 @c_Storerkey = Storerkey
  FROM ORDERS (NOLOCK)
  WHERE Loadkey = @c_Loadkey

  SELECT @c_Lottable02label = Description
  FROM CODELKUP (NOLOCK)
  WHERE Code = 'Lottable02'
  AND Listname = 'RPTCOLHDR'
  AND Storerkey = @c_Storerkey

  SELECT @c_Lottable04label = Description
  FROM CODELKUP (NOLOCK)
  WHERE Code = 'Lottable04'
  AND Listname = 'RPTCOLHDR'
  AND Storerkey = @c_Storerkey

  IF ISNULL(@c_Lottable02label,'') = ''
     SET @c_Lottable02label = 'Batch No'

  IF ISNULL(@c_Lottable04label,'') = ''
     SET @c_Lottable04label = 'Exp Date'

-- (Wan01) --START
--  SELECT *, SUSER_SNAME(), @c_Lottable02label, @c_Lottable04label FROM @t_Result
--  ORDER BY PickslipNo, PageNo, RowID
   SELECT Loadkey
      ,  Pickslipno
      ,  PickType
      ,  LoadingDate
      ,  PickZone
      ,  Loc
      ,  Logicalloc
      ,  SKU
      ,  Descr
      ,  Palletcnt
      ,  Cartoncnt
      ,  TotalCarton
      ,  ID
      ,  Lottable02
      ,  Lottable04
      ,  ReprintFlag
      ,  PageNo
      ,  TotalPage
      ,  rowid
      ,  SUSER_SNAME()
      ,  @c_Lottable02label
      ,  @c_Lottable04label
      ,  C_Company
      ,  EA
      , Route --NJOW03
      , Storerkey --NJOW03
      , OrderGrpFlag  --CS01 
      , OrderGrp   --CS01
      , TrfRoom --NJOW05
      ,LEXTLoadKey,LPriority,LPuserdefDate01 --(CS01)
      ,showfield,InnerPack
   FROM @t_Result
   ORDER BY PickslipNo, PageNo, RowID
-- (Wan01) --END
 END

EXIT_SP:
  IF @n_continue=3  -- Error Occured - Process And Return
  BEGIN
     IF @@TRANCOUNT = 1 and @@TRANCOUNT >= @n_starttcnt
     BEGIN
        ROLLBACK TRAN
     END
     ELSE
     BEGIN
        WHILE @@TRANCOUNT > @n_starttcnt
        BEGIN
           COMMIT TRAN
        END
     END
     EXECUTE nsp_logerror @n_err, @c_errmsg, 'Generation of Pick Slip'
     RAISERROR (@c_errmsg, 16, 1) WITH SETERROR    -- SQL2012
  END
  ELSE
  BEGIN
     WHILE @@TRANCOUNT > @n_starttcnt
     BEGIN
        COMMIT TRAN
     END
  END
END

GO