SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO

CREATE PROC [dbo].[nspALTBL06]
			@c_lot NVARCHAR(10) ,
			@c_uom NVARCHAR(10) ,
			@c_HostWHCode NVARCHAR(10),
			@c_Facility NVARCHAR(5),
			@n_uombase int ,
			@n_qtylefttofulfill int
AS
BEGIN 
   SET NOCOUNT ON 
    
   

-- Added by YokeBeen on 8-May-2003 - (FBR11022) IDSHK TBL Project
-- Allocation Strategy

DECLARE  CURSOR_CANDIDATES CURSOR FAST_FORWARD READ_ONLY
FOR SELECT LOTxLOCxID.LOC, LOTxLOCxID.ID,
			  QTYAVAILABLE = (LOTxLOCxID.QTY - LOTxLOCxID.QTYALLOCATED - LOTxLOCxID.QTYPICKED), '1'
FROM LOTxLOCxID (NOLOCK), LOC (NOLOCK), ID (NOLOCK), SKUxLOC (NOLOCK)
WHERE LOTxLOCxID.Lot = @c_lot
AND LOTxLOCxID.Loc = LOC.LOC
AND LOTxLOCxID.Loc = SKUxLOC.Loc
AND LOTxLOCxID.Sku = SKUxLOC.Sku
AND LOTxLOCxID.ID = ID.ID
AND ID.Status <> 'HOLD' 
AND LOC.Facility = @c_Facility 
AND LOC.Locationflag <> 'HOLD'
AND LOC.Locationflag <> 'DAMAGE'
AND (LOTxLOCxID.QTY - LOTxLOCxID.QTYALLOCATED - LOTxLOCxID.QTYPICKED) >= @n_uombase
AND LOC.Status <> 'HOLD'
ORDER BY LOC.LogicalLocation, LOC.LOC 
END

GO