SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO

CREATE PROC  [dbo].[nspPRstdA6]  -- rename from IDSMY:nspPRstd06  
@c_storerkey NVARCHAR(15) ,  
@c_sku NVARCHAR(20) ,  
@c_lot NVARCHAR(10) ,  
@c_lottable01 NVARCHAR(18) ,  
@c_lottable02 NVARCHAR(18) ,  
@c_lottable03 NVARCHAR(18) ,  
@d_lottable04 datetime ,  
@d_lottable05 datetime ,  
@c_uom NVARCHAR(10),   
@c_facility NVARCHAR(10)  ,  -- added By Ricky for IDSV5  
@n_uombase int ,  
@n_qtylefttofulfill int  
AS  
BEGIN  
  
   IF dbo.fnc_LTrim(dbo.fnc_RTrim(@c_lot)) IS NOT NULL  
   BEGIN  
      DECLARE  PREALLOCATE_CURSOR_CANDIDATES CURSOR FAST_FORWARD READ_ONLY FOR   
      SELECT LOT.STORERKEY,LOT.SKU,LOT.LOT ,  
      QTYAVAILABLE = (LOT.QTY - LOT.QTYALLOCATED - LOT.QTYPICKED - LOT.QTYPREALLOCATED)  
      FROM LOT (NOLOCK), LOTXLOCXID (NOLOCK), LOC (NOLOCK)   
      WHERE LOTXLOCXID.Lot = LOT.LOT  
 AND LOTXLOCXID.LOC = LOC.LOC  
 AND LOC.Facility = @c_facility  
 AND LOT.LOT = @c_lot  
      ORDER BY LOT.LOT   
   END  
ELSE  
BEGIN  
   DECLARE  PREALLOCATE_CURSOR_CANDIDATES CURSOR FAST_FORWARD READ_ONLY FOR   
   SELECT LOT.STORERKEY,LOT.SKU,LOT.LOT  ,  
   --QTYAVAILABLE = (LOT.QTY - LOT.QTYALLOCATED - LOT.QTYPICKED - LOT.QTYPREALLOCATED - QTYONHOLD)  /*SOS293982 - Logic fixed*/
   QTYAVAILABLE = (SUM(LOTxLOCxID.QTY) - SUM(LOTxLOCxID.QTYALLOCATED) - SUM(LOTxLOCxID.QTYPICKED) - MAX(LOT.QTYPREALLOCATED) ) /*SOS293982 - Logic fixed*/         
   FROM LOT (NOLOCK), LOTATTRIBUTE (NOLOCK), LOTXLOCXID (NOLOCK), LOC (NOLOCK)   
   WHERE LOT.LOT = LOTATTRIBUTE.LOT    
   AND LOTXLOCXID.Lot = LOT.LOT  
   AND LOTXLOCXID.LOT = LOTATTRIBUTE.LOT  
   AND LOTXLOCXID.LOC = LOC.LOC  
   AND LOC.Facility = @c_facility  
   AND LOT.STORERKEY = @c_storerkey  
   AND LOT.SKU = @c_sku  
   AND LOT.STATUS = "OK"  
   AND (LOT.QTY - LOT.QTYALLOCATED - LOT.QTYPICKED - LOT.QTYPREALLOCATED - QTYONHOLD) > 0  
   GROUP By LOT.STORERKEY, LOT.SKU, LOT.LOT, Lotattribute.Lottable04, LOTATTRIBUTE.LOT /*SOS293982 - Logic fixed*/
   HAVING SUM(LOTxLOCxID.QTY) - SUM(LOTxLOCxID.QTYALLOCATED) - SUM(LOTxLOCxID.QTYPICKED) - MAX(LOT.QTYPREALLOCATED) > 0 /*SOS293982 - Logic fixed*/
   ORDER BY LOTATTRIBUTE.LOTTABLE04, LOTATTRIBUTE.LOT  
END  
END  


GO