SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
/* 2001/10/02 CS IDSHK FBR063 Added Facility */

CREATE PROCEDURE    [dbo].[nspSUPOD06]
@c_lot NVARCHAR(10) ,
@c_uom NVARCHAR(10) ,
@c_HostWHCode NVARCHAR(10),
@c_Facility NVARCHAR(5),
@n_uombase int ,
@n_qtylefttofulfill int
AS
BEGIN
   SET NOCOUNT ON 
   SET QUOTED_IDENTIFIER OFF 
   SET CONCAT_NULL_YIELDS_NULL OFF
DECLARE  CURSOR_CANDIDATES CURSOR FAST_FORWARD READ_ONLY FOR 
SELECT LOTxLOCxID.LOC, LOTxLOCxID.ID,
       QTYAVAILABLE = (LOTxLOCxID.QTY - LOTxLOCxID.QTYALLOCATED - LOTxLOCxID.QTYPICKED),
       LocType = '1'
FROM LOTxLOCxID (NOLOCK), LOC (NOLOCK), ID (NOLOCK), SKUxLOC (NOLOCK)
WHERE LOTxLOCxID.Lot = @c_lot
AND LOTxLOCxID.Loc = LOC.LOC
AND LOTxLOCxID.Loc = SKUxLOC.Loc
AND LOTxLOCxID.Sku = SKUxLOC.Sku
AND LOTxLOCxID.ID = ID.ID
AND ID.Status <> "HOLD"
AND LOC.Locationflag <> "HOLD"
AND LOC.Locationflag <> "DAMAGE"
AND (LOTxLOCxID.QTY - LOTxLOCxID.QTYALLOCATED - LOTxLOCxID.QTYPICKED) >= @n_uombase
AND LOC.Status <> "HOLD"
AND SKUxLOC.LocationType NOT IN ("PICK", "CASE", "IDZ", "FLOW")
AND LOC.LocationType <> "IDZ" 
AND LOC.LocationType <> "FLOW"
AND LOC.Facility = @c_Facility
UNION
SELECT LOTxLOCxID.LOC, LOTxLOCxID.ID,
       QTYAVAILABLE = (LOTxLOCxID.QTY - LOTxLOCxID.QTYALLOCATED - LOTxLOCxID.QTYPICKED),
       LocType = '2'
FROM LOTxLOCxID (NOLOCK), LOC (NOLOCK), SKUxLOC (NOLOCK)
WHERE LOTxLOCxID.Lot = @c_lot
AND LOTxLOCxID.Loc = LOC.LOC
AND LOTxLOCxID.Storerkey = SKUxLOC.Storerkey
AND LOTxLOCxID.Sku = SKUxLOC.Sku
AND LOTxLOCxID.Loc = SKUxLOC.Loc
AND SKUxLOC.LocationType IN ("PICK", "CASE")
AND LOC.Locationflag <> "HOLD"
AND LOC.Locationflag <> "DAMAGE"
AND LOC.Status <> "HOLD"
AND (LOTxLOCxID.QTY - LOTxLOCxID.QTYALLOCATED - LOTxLOCxID.QTYPICKED) > 0
AND LOC.LocationType <> "IDZ" 
AND LOC.LocationType <> "FLOW"
AND LOC.Facility = @c_Facility
ORDER BY LocType, LOTxLOCxID.LOC
END

GO