CREATE TABLE [bi].[ordersum]
(
    [OrderKey] nvarchar(10) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL,
    [ExternOrderKey] nvarchar(50) NOT NULL,
    [DeliveryDate] date NOT NULL,
    [ConsigneeKey] nvarchar(15) NOT NULL,
    [C_City] nvarchar(45) NOT NULL,
    [Status] nvarchar(10) NOT NULL,
    [Type] nvarchar(10) NOT NULL,
    [OrderGroup] nvarchar(20) NOT NULL,
    [AddDate] smalldatetime NOT NULL,
    [EditDate] smalldatetime NOT NULL,
    [ModifyDate] smalldatetime NOT NULL DEFAULT (getdate()),
    [AllocDate] smalldatetime NULL,
    [PickDate] smalldatetime NULL,
    [ShipDate] smalldatetime NULL,
    [CancDate] smalldatetime NULL,
    [Lines] bigint NOT NULL,
    [Units] bigint NOT NULL,
    [PickDet_Lines] bigint NOT NULL,
    [Orders_Open] bigint NOT NULL,
    [Lines_Open] bigint NOT NULL,
    [Units_Open] bigint NOT NULL,
    [Orders_ALLOC] bigint NOT NULL,
    [Lines_ALLOC] bigint NOT NULL,
    [Units_ALLOC] bigint NOT NULL,
    [Orders_Pick_Packed] bigint NOT NULL,
    [Lines_Pick_Packed] bigint NOT NULL,
    [Units_Pick_Packed] bigint NOT NULL,
    [Orders_Shipped] bigint NOT NULL,
    [Lines_Shipped] bigint NOT NULL,
    [Units_Shipped] bigint NOT NULL,
    [Orders_Cancelled] bigint NOT NULL,
    [Lines_Cancelled] bigint NOT NULL,
    [Units_Cancelled] bigint NOT NULL,
    [PickDetails_Inserted] bigint NOT NULL,
    [Orders_OverRun] bigint NULL,
    [Orders_PendBuildLoad] int NOT NULL,
    [MBOL_NotValid] int NOT NULL,
    [MBOLKey] nvarchar(10) NOT NULL,
    [LoadKey] nvarchar(10) NOT NULL,
    [Facility] nvarchar(5) NOT NULL,
    [ShipperKey] nvarchar(15) NOT NULL,
    [DocType] nvarchar(1) NOT NULL,
    [TrackingNo] nvarchar(30) NOT NULL,
    [ECOM_PRESALE_FLAG] nvarchar(2) NOT NULL,
    [PreSale] bit NOT NULL,
    [ECOM_SINGLE_FLAG] nvarchar(1) NOT NULL,
    [UserDefine01] nvarchar(20) NOT NULL,
    [UserDefine02] nvarchar(20) NOT NULL,
    [UserDefine03] nvarchar(20) NOT NULL,
    CONSTRAINT [PK_OrderSum] PRIMARY KEY ([OrderKey])
);
GO
