CREATE TABLE [ptl].[lightmode]
(
    [LightModeNo] int NOT NULL,
    [Description] nvarchar(100) NULL DEFAULT (' '),
    [L1_Enabled] varchar(10) NULL DEFAULT ('Enabled'),
    [L1_Status] varchar(20) NULL DEFAULT ('On'),
    [L1_Color] varchar(20) NULL DEFAULT ('White'),
    [L1_SEG] varchar(20) NULL DEFAULT ('On'),
    [L1_BUZ] varchar(20) NULL DEFAULT ('Flash'),
    [L2_Enabled] varchar(10) NULL DEFAULT ('Disabled'),
    [L2_Status] varchar(20) NULL DEFAULT ('On'),
    [L2_Color] varchar(20) NULL DEFAULT ('White'),
    [L2_SEG] varchar(20) NULL DEFAULT ('On'),
    [L2_BUZ] varchar(20) NULL DEFAULT ('Flash'),
    [L3_Enabled] varchar(10) NULL DEFAULT ('Disabled'),
    [L3_Status] varchar(20) NULL DEFAULT ('On'),
    [L3_Color] varchar(20) NULL DEFAULT ('White'),
    [L3_SEG] varchar(20) NULL DEFAULT ('On'),
    [L3_BUZ] varchar(20) NULL DEFAULT ('Flash'),
    [L4_Enabled] varchar(10) NULL DEFAULT ('Disabled'),
    [L4_FnKeyDecrement] char(10) NULL DEFAULT ('Use'),
    [L4_FnKey] char(10) NULL DEFAULT ('Use'),
    [L4_ConfirmButton] char(10) NULL DEFAULT ('Use'),
    [L5_Enabled] varchar(10) NULL DEFAULT ('Disabled'),
    [L5_Status] varchar(20) NULL DEFAULT ('On'),
    [L5_Color] varchar(20) NULL DEFAULT ('White'),
    [L5_SEG] varchar(20) NULL DEFAULT ('On'),
    [L5_BUZ] varchar(20) NULL DEFAULT ('Flash'),
    [ma_Enabled] varchar(10) NULL DEFAULT ('Disabled'),
    [ma_qty_rvs] varchar(10) NULL DEFAULT ('Not used'),
    [me_Enabled] varchar(10) NULL DEFAULT ('Disabled'),
    [me_app_timing] varchar(2) NULL DEFAULT ('0'),
    [me_Digit1] varchar(1) NULL DEFAULT ('0'),
    [me_Digit2] varchar(1) NULL DEFAULT ('0'),
    [me_Digit3] varchar(1) NULL DEFAULT ('0'),
    [me_Digit4] varchar(1) NULL DEFAULT ('0'),
    [me_Digit5] varchar(1) NULL DEFAULT ('0'),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    CONSTRAINT [PK_LightMode] PRIMARY KEY ([LightModeNo])
);
GO
