CREATE TABLE [dbo].[abcanalysis]
(
    [SerialKey] bigint IDENTITY(1,1) NOT NULL,
    [Facility] nvarchar(5) NOT NULL DEFAULT (' '),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Description] nvarchar(60) NULL,
    [SKUStatus] nvarchar(10) NULL,
    [SKUGroup] nvarchar(10) NULL,
    [SKUClass] nvarchar(10) NULL,
    [ItemClass] nvarchar(10) NULL,
    [SKUCost] money NULL,
    [SKUCube] numeric(18, 3) NULL,
    [BUSR1] nvarchar(30) NULL,
    [BUSR2] nvarchar(30) NULL,
    [BUSR3] nvarchar(30) NULL,
    [BUSR4] nvarchar(200) NULL,
    [BUSR5] nvarchar(30) NULL,
    [SUSR1] nvarchar(18) NULL,
    [SUSR2] nvarchar(18) NULL,
    [SUSR3] nvarchar(18) NULL,
    [SUSR4] nvarchar(18) NULL,
    [SUSR5] nvarchar(18) NULL,
    [SKUChangeFlag] nvarchar(10) NULL,
    [SKUABCStatus] nvarchar(10) NULL DEFAULT ('0'),
    [PackKey] nvarchar(10) NULL DEFAULT (''),
    [CaseCnt] numeric(18, 0) NULL DEFAULT ((0.00)),
    [Pallet] numeric(18, 0) NULL DEFAULT ((0.00)),
    [CubeUOM3] numeric(18, 5) NULL,
    [Qty] int NULL DEFAULT ((0)),
    [PickFaceSizeMethod] nvarchar(10) NULL,
    [ABC] nvarchar(10) NULL,
    [CalcABC] nvarchar(10) NULL,
    [NewABC] nvarchar(10) NULL,
    [SkuRank] decimal(18, 0) NULL DEFAULT ((0.00)),
    [NoOfPick] decimal(18, 0) NULL DEFAULT ((0.00)),
    [PercentageOfPick] numeric(18, 3) NULL DEFAULT ((0.00)),
    [AvgDailyPick] decimal(18, 2) NULL DEFAULT ((0.00)),
    [ActivePickDays] decimal(18, 0) NULL DEFAULT ((0.00)),
    [DaysOfActivity] int NULL DEFAULT ((0)),
    [TotalPickedQty] int NULL DEFAULT ((0)),
    [ABCEA] nvarchar(10) NULL,
    [CalcPieceABC] nvarchar(10) NULL,
    [NewPieceABC] nvarchar(10) NULL,
    [PieceRank] decimal(18, 0) NULL DEFAULT ((0.00)),
    [NoOfPiecePick] decimal(18, 0) NULL DEFAULT ((0.00)),
    [AvgDailyPiecePick] decimal(18, 2) NULL DEFAULT ((0.00)),
    [PiecePickQty] decimal(18, 2) NULL DEFAULT ((0.00)),
    [AvgDailyPiecePickQty] decimal(18, 2) NULL DEFAULT ((0.00)),
    [NoOfPieceLoc] decimal(18, 0) NULL DEFAULT ((0.00)),
    [PieceStdev] decimal(18, 2) NULL DEFAULT ((0.00)),
    [PieceQtyLocMin] decimal(18, 2) NULL DEFAULT ((0.00)),
    [PieceQtyLocMinInCS] decimal(18, 0) NULL DEFAULT ((0.00)),
    [AvgPieceQtyLocLimit] decimal(18, 0) NULL DEFAULT ((0.00)),
    [ABCCS] nvarchar(10) NULL,
    [CalcCaseABC] nvarchar(10) NULL,
    [NewCaseABC] nvarchar(10) NULL,
    [CaseRank] decimal(18, 0) NULL,
    [NoOfCasePick] numeric(18, 0) NULL DEFAULT ((0.00)),
    [AvgDailyCasePick] decimal(18, 2) NULL DEFAULT ((0.00)),
    [CasePickQty] decimal(18, 2) NULL DEFAULT ((0.00)),
    [AvgDailyCasePickQty] decimal(18, 2) NULL DEFAULT ((0.00)),
    [NoOfCaseLoc] decimal(18, 0) NULL DEFAULT ((0.00)),
    [CaseStdev] decimal(18, 2) NULL DEFAULT ((0.00)),
    [CaseQtyLocMin] decimal(18, 2) NULL DEFAULT ((0.00)),
    [CaseQtyLocMininCS] decimal(18, 0) NULL DEFAULT ((0.00)),
    [AvgCaseQtyLocLimit] decimal(18, 0) NULL DEFAULT ((0.00)),
    [ABCPL] nvarchar(10) NULL,
    [CalcBulkABC] nvarchar(10) NULL,
    [NewBulkABC] nvarchar(10) NULL,
    [BulkRank] decimal(18, 0) NULL DEFAULT ((0.00)),
    [NoOfBulkPick] numeric(18, 0) NULL,
    [AvgDailyBulkPick] decimal(18, 2) NULL DEFAULT ((0.00)),
    [NoOfBulkLoc] decimal(18, 0) NULL DEFAULT ((0.00)),
    [FinalizedFlag] nvarchar(1) NULL DEFAULT ('N'),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [BulkPickQty] decimal(18, 2) NULL DEFAULT ('0'),
    [AvgDailyBulkPickQty] decimal(18, 2) NULL DEFAULT ('0.00'),
    [PickPct] decimal(18, 2) NULL DEFAULT ('0.00'),
    [PiecePickPct] decimal(18, 2) NULL DEFAULT ('0.00'),
    [CasePickPct] decimal(18, 2) NULL DEFAULT ('0.00'),
    [BulkPickPct] decimal(18, 2) NULL DEFAULT ('0.00'),
    CONSTRAINT [PK_ABCAnalysis] PRIMARY KEY ([SerialKey])
);
GO

CREATE INDEX [IX_ABCAnalysis] ON [dbo].[abcanalysis] ([Facility], [StorerKey], [Sku]);
GO