CREATE TABLE [dbo].[abctran]
(
    [ABCTranKey] nvarchar(10) NOT NULL,
    [Facility] nvarchar(5) NOT NULL DEFAULT (' '),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [OldABC] nvarchar(10) NULL,
    [NewABC] nvarchar(10) NULL,
    [CalcABC] nvarchar(10) NULL,
    [SkuRank] decimal(18, 0) NULL DEFAULT ((0.00)),
    [NoOfPick] decimal(18, 0) NULL DEFAULT ((0.00)),
    [PercentageOfPick] numeric(18, 3) NULL DEFAULT ((0.00)),
    [AvgDailyPick] decimal(18, 2) NULL DEFAULT ((0.00)),
    [ActivePickDays] decimal(18, 0) NULL DEFAULT ((0.00)),
    [DaysOfActivity] int NULL DEFAULT ((0)),
    [ABCEA] nvarchar(10) NULL,
    [NewPieceABC] nvarchar(10) NULL,
    [CalcPieceABC] nvarchar(10) NULL,
    [PieceRank] decimal(18, 0) NULL DEFAULT ((0.00)),
    [NoOfPiecePick] decimal(18, 0) NULL DEFAULT ((0.00)),
    [AvgDailyPiecePick] decimal(18, 2) NULL DEFAULT ((0.00)),
    [PiecePickQty] decimal(18, 2) NULL DEFAULT ((0.00)),
    [AvgDailyPiecePickQty] decimal(18, 2) NULL DEFAULT ((0.00)),
    [NoOfPieceLoc] decimal(18, 0) NULL DEFAULT ((0.00)),
    [PieceStdev] decimal(18, 2) NULL DEFAULT ((0.00)),
    [PieceQtyLocMin] decimal(18, 2) NULL DEFAULT ((0.00)),
    [PieceQtyLocMinInCS] decimal(18, 0) NULL DEFAULT ((0.00)),
    [AvgPieceQtyLocLimit] decimal(18, 0) NULL DEFAULT ((0.00)),
    [ABCCS] nvarchar(10) NULL,
    [NewCaseABC] nvarchar(10) NULL,
    [CalcCaseABC] nvarchar(10) NULL,
    [CaseRank] decimal(18, 0) NULL,
    [NoOfCasePick] numeric(18, 0) NULL DEFAULT ((0.00)),
    [AvgDailyCasePick] decimal(18, 2) NULL DEFAULT ((0.00)),
    [CasePickQty] decimal(18, 2) NULL DEFAULT ((0.00)),
    [AvgDailyCasePickQty] decimal(18, 2) NULL DEFAULT ((0.00)),
    [NoOfCaseLoc] decimal(18, 0) NULL DEFAULT ((0.00)),
    [CaseStdev] decimal(18, 2) NULL DEFAULT ((0.00)),
    [CaseQtyLocMin] decimal(18, 2) NULL DEFAULT ((0.00)),
    [CaseQtyLocMininCS] decimal(18, 0) NULL DEFAULT ((0.00)),
    [AvgCaseQtyLocLimit] decimal(18, 0) NULL DEFAULT ((0.00)),
    [ABCPL] nvarchar(10) NULL,
    [NewBulkABC] nvarchar(10) NULL,
    [CalcBulkABC] nvarchar(10) NULL,
    [BulkRank] decimal(18, 0) NULL DEFAULT ((0.00)),
    [NoOfBulkPick] numeric(18, 0) NULL,
    [AvgDailyBulkPick] decimal(18, 2) NULL DEFAULT ((0.00)),
    [NoOfBulkLoc] decimal(18, 0) NULL DEFAULT ((0.00)),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    CONSTRAINT [PK_ABCTran] PRIMARY KEY ([ABCTranKey])
);
GO

CREATE INDEX [IX_ABCTran] ON [dbo].[abctran] ([Facility], [StorerKey], [Sku]);
GO