CREATE TABLE [dbo].[accumulatedcharges]
(
    [AccumulatedChargesKey] nvarchar(10) NOT NULL,
    [Descrip] nvarchar(100) NOT NULL DEFAULT (' '),
    [Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [PrintCount] int NOT NULL DEFAULT ((0)),
    [ServiceKey] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Lot] nvarchar(10) NOT NULL DEFAULT (' '),
    [ID] nvarchar(18) NOT NULL DEFAULT (' '),
    [UOMShow] nvarchar(10) NOT NULL DEFAULT (' '),
    [TariffKey] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [TariffDetailKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [TaxGroupKey] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [Rate] decimal(22, 6) NOT NULL DEFAULT ((1.0)),
    [Base] nvarchar(1) NOT NULL DEFAULT ('Q'),
    [MasterUnits] decimal(12, 6) NOT NULL DEFAULT ((1.0)),
    [SystemGeneratedCharge] decimal(28, 6) NOT NULL DEFAULT ((0.0)),
    [Debit] decimal(28, 6) NOT NULL DEFAULT ((0.0)),
    [Credit] decimal(28, 6) NOT NULL DEFAULT ((0.0)),
    [BilledUnits] decimal(21, 7) NOT NULL DEFAULT ((0.0)),
    [ChargeType] nvarchar(10) NOT NULL,
    [LineType] nvarchar(5) NOT NULL DEFAULT ('N'),
    [BillFromDate] datetime NOT NULL DEFAULT (getdate()),
    [BillThruDate] datetime NOT NULL DEFAULT (getdate()),
    [SourceKey] nvarchar(20) NOT NULL DEFAULT (' '),
    [SourceType] nvarchar(30) NOT NULL DEFAULT (' '),
    [AccessorialDetailKey] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [GLDistributionKey] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [InvoiceBatch] nvarchar(10) NOT NULL DEFAULT (' '),
    [InvoiceKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [CostRate] decimal(22, 6) NULL DEFAULT ((1.0)),
    [CostBase] nvarchar(1) NULL DEFAULT ('Q'),
    [CostMasterUnits] decimal(12, 6) NULL DEFAULT ((1.0)),
    [CostUOMShow] nvarchar(10) NULL DEFAULT (' '),
    [CostSystemGeneratedCharge] decimal(28, 6) NULL DEFAULT ((0.0)),
    [Cost] decimal(28, 6) NULL DEFAULT ((0.0)),
    [CostUnits] decimal(21, 6) NULL DEFAULT ((0.0)),
    [TrafficCop] nvarchar(1) NULL,
    [ReferenceKey] nvarchar(10) NULL DEFAULT (' '),
    [InvoiceDate] datetime NULL,
    CONSTRAINT [PK_AccumulatedChargesKey] PRIMARY KEY ([AccumulatedChargesKey]),
    CONSTRAINT [FK_AccChg_AccDet_01] FOREIGN KEY ([AccessorialDetailKey]) REFERENCES [dbo].[AccessorialDetail] ([AccessorialDetailkey]),
    CONSTRAINT [FK_AccChg_GLDist_01] FOREIGN KEY ([GLDistributionKey]) REFERENCES [dbo].[GLDistribution] ([GLDistributionKey]),
    CONSTRAINT [FK_AccChg_SERVICE_01] FOREIGN KEY ([ServiceKey]) REFERENCES [dbo].[Services] ([Servicekey]),
    CONSTRAINT [FK_AccChg_STORER_01] FOREIGN KEY ([StorerKey]) REFERENCES [dbo].[STORER] ([StorerKey]),
    CONSTRAINT [FK_AccChg_Tariff_01] FOREIGN KEY ([TariffKey]) REFERENCES [dbo].[Tariff] ([TariffKey]),
    CONSTRAINT [FK_AccChg_TaxGroup_01] FOREIGN KEY ([TaxGroupKey]) REFERENCES [dbo].[TaxGroup] ([TaxGroupKey]),
    CONSTRAINT [CK_AccChg_ChargeType] CHECK ([ChargeType]='SP' OR [ChargeType]='AC' OR [ChargeType]='MT' OR [ChargeType]='DO' OR [ChargeType]='DI' OR [ChargeType]='MR' OR [ChargeType]='MO' OR [ChargeType]='MH' OR [ChargeType]='MI' OR [ChargeType]='RS' OR [ChargeType]='IS' OR [ChargeType]='HO' OR [ChargeType]='HI' OR [ChargeType]='CO' OR [ChargeType]='CI'),
    CONSTRAINT [CK_AccChg_CostBase] CHECK ([CostBase]='R' OR [CostBase]='P' OR [CostBase]='F' OR [CostBase]='C' OR [CostBase]='G' OR [CostBase]='Q'),
    CONSTRAINT [CK_AccChg_Credit] CHECK ([Credit]>=(0.0)),
    CONSTRAINT [CK_AccChg_Debit] CHECK ([Debit]>=(0.0)),
    CONSTRAINT [CK_AccChg_MasterUnits] CHECK ([MasterUnits]>(0.0)),
    CONSTRAINT [CK_AccChg_SysGenCharge] CHECK ([SystemGeneratedCharge]>=(0.0)),
    CONSTRAINT [CK_AccChg_Base] CHECK ([Base]='R' OR [Base]='P' OR [Base]='F' OR [Base]='C' OR [Base]='G' OR [Base]='Q'),
    CONSTRAINT [CK_AccChg_BilledUnits] CHECK ([BilledUnits]>=(0.0))
);
GO
