CREATE TABLE [dbo].[adjustmentdetail]
(
    [AdjustmentKey] nvarchar(10) NOT NULL,
    [AdjustmentLineNumber] nvarchar(5) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Loc] nvarchar(10) NOT NULL DEFAULT (' '),
    [Lot] nvarchar(10) NOT NULL DEFAULT (' '),
    [Id] nvarchar(18) NOT NULL DEFAULT (' '),
    [ReasonCode] nvarchar(10) NOT NULL DEFAULT ('0'),
    [UOM] nvarchar(10) NOT NULL DEFAULT (' '),
    [PackKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [Qty] int NOT NULL DEFAULT ((0)),
    [CaseCnt] int NOT NULL DEFAULT ((0)),
    [InnerPack] int NOT NULL DEFAULT ((0)),
    [Pallet] int NOT NULL DEFAULT ((0)),
    [Cube] float NOT NULL DEFAULT ((0)),
    [GrossWgt] float NOT NULL DEFAULT ((0)),
    [NetWgt] float NOT NULL DEFAULT ((0)),
    [OtherUnit1] float NOT NULL DEFAULT ((0)),
    [OtherUnit2] float NOT NULL DEFAULT ((0)),
    [ItrnKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [TimeStamp] timestamp NULL,
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [FinalizedFlag] nvarchar(1) NULL DEFAULT ('N'),
    [Lottable01] nvarchar(18) NULL DEFAULT (' '),
    [Lottable02] nvarchar(18) NULL DEFAULT (' '),
    [Lottable03] nvarchar(18) NULL DEFAULT (' '),
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [UCCNo] nvarchar(20) NULL DEFAULT (''),
    [Lottable06] nvarchar(30) NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [Channel] nvarchar(20) NULL DEFAULT (''),
    [Channel_ID] bigint NULL DEFAULT ((0)),
    [SerialNo] nvarchar(50) NOT NULL DEFAULT (''),
    [PalletType] nvarchar(10) NOT NULL DEFAULT (''),
    CONSTRAINT [PKAdjustmentDetail] PRIMARY KEY ([AdjustmentKey], [AdjustmentLineNumber]),
    CONSTRAINT [FK_ADJUSTMENTDETAIL_SKU_01] FOREIGN KEY ([StorerKey], [Sku]) REFERENCES [dbo].[SKU] ([StorerKey], [Sku])
);
GO
