CREATE TABLE [dbo].[bill_accumulatedcharges]
(
    [Ident] int IDENTITY(0,1) NOT NULL,
    [AccumulatedChargesKey] nvarchar(10) NULL,
    [Descrip] nvarchar(100) NULL,
    [Status] nvarchar(1) NULL,
    [PrintCount] int NULL,
    [ServiceKey] nvarchar(10) NULL,
    [StorerKey] nvarchar(15) NULL,
    [Sku] nvarchar(20) NULL,
    [Lot] nvarchar(10) NULL,
    [ID] nvarchar(18) NULL,
    [UOMShow] nvarchar(10) NULL,
    [TariffKey] nvarchar(10) NULL,
    [TariffDetailKey] nvarchar(10) NULL,
    [TaxGroupKey] nvarchar(10) NULL,
    [Rate] decimal(22, 6) NULL,
    [Base] nvarchar(1) NULL,
    [MasterUnits] decimal(12, 6) NULL,
    [SystemGeneratedCharge] decimal(28, 6) NULL,
    [Debit] decimal(28, 6) NULL,
    [Credit] decimal(28, 6) NULL,
    [BilledUnits] decimal(21, 7) NULL,
    [ChargeType] nvarchar(10) NULL,
    [LineType] nvarchar(5) NULL,
    [BillFromDate] datetime NULL,
    [BillThruDate] datetime NULL,
    [SourceKey] nvarchar(20) NULL,
    [SourceType] nvarchar(30) NULL,
    [AccessorialDetailKey] nvarchar(10) NULL,
    [GLDistributionKey] nvarchar(10) NULL,
    [InvoiceBatch] nvarchar(10) NULL,
    [InvoiceKey] nvarchar(10) NULL,
    [CostRate] decimal(22, 6) NULL,
    [CostBase] nvarchar(1) NULL,
    [CostMasterUnits] decimal(12, 6) NULL,
    [CostUOMShow] nvarchar(10) NULL,
    [CostSystemGeneratedCharge] decimal(28, 6) NULL,
    [Cost] decimal(28, 6) NULL,
    [CostUnits] decimal(21, 6) NULL,
    [TrafficCop] nvarchar(1) NULL,
    [ReferenceKey] nvarchar(10) NULL,
    [ITRNSourceKey] nvarchar(20) NULL DEFAULT (' '),
    [ITRNSourceType] nvarchar(30) NULL DEFAULT (' '),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname())
);
GO
