CREATE TABLE [dbo].[bol]
(
    [BolKey] nvarchar(10) NOT NULL,
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [ExternBolKey] nvarchar(30) NOT NULL DEFAULT (' '),
    [OriginCountry] nvarchar(30) NOT NULL DEFAULT (' '),
    [DestinationCountry] nvarchar(30) NOT NULL DEFAULT (' '),
    [VesselQualifier] nvarchar(10) NOT NULL DEFAULT ('VM'),
    [Vessel] nvarchar(30) NOT NULL DEFAULT (' '),
    [PlaceOfLoadingQualifier] nvarchar(10) NOT NULL DEFAULT (' '),
    [PlaceOfLoading] nvarchar(30) NOT NULL DEFAULT (' '),
    [PlaceOfdischargeQualifier] nvarchar(10) NOT NULL DEFAULT (' '),
    [PlaceOfDischarge] nvarchar(30) NOT NULL DEFAULT (' '),
    [PlaceOfdeliveryQualifier] nvarchar(10) NOT NULL DEFAULT (' '),
    [PlaceOfdelivery] nvarchar(30) NOT NULL DEFAULT (' '),
    [TransMethod] nvarchar(30) NOT NULL DEFAULT (' '),
    [VoyageNumber] nvarchar(30) NOT NULL DEFAULT (' '),
    [DepartureDate] datetime NOT NULL DEFAULT (getdate()),
    [ArrivalDate] datetime NOT NULL DEFAULT (getdate()),
    [ArrivalDateFinalDestination] datetime NOT NULL DEFAULT (getdate()),
    [BookingReference] nvarchar(30) NOT NULL DEFAULT (' '),
    [OtherReference] nvarchar(30) NOT NULL DEFAULT (' '),
    [CarrierKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [CarrierAgent] nvarchar(30) NOT NULL DEFAULT (' '),
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Shipper] nvarchar(15) NULL DEFAULT (' '),
    [Consignee] nvarchar(15) NULL DEFAULT (' '),
    [BillTo] nvarchar(15) NULL DEFAULT (' '),
    [PreCarriage] nvarchar(30) NULL DEFAULT (' '),
    [PlaceReceipt] nvarchar(30) NULL DEFAULT (' '),
    [ShipperReference] nvarchar(30) NULL DEFAULT (' '),
    [ForwarderReference] nvarchar(30) NULL DEFAULT (' '),
    CONSTRAINT [PKBOL] PRIMARY KEY ([BolKey])
);
GO
