CREATE TABLE [dbo].[booking_in]
(
    [BookingNo] int NOT NULL,
    [Facility] nvarchar(5) NULL DEFAULT (''),
    [BookingDate] datetime NOT NULL,
    [EndTime] datetime NOT NULL,
    [Duration] datetime NOT NULL,
    [Loc] nvarchar(10) NOT NULL,
    [Type] nvarchar(10) NULL DEFAULT (''),
    [ALTReference] nvarchar(30) NULL DEFAULT (''),
    [SCAC] nvarchar(10) NULL DEFAULT (''),
    [ReferenceNo] nvarchar(30) NULL DEFAULT (''),
    [POKey] nvarchar(18) NOT NULL DEFAULT (' '),
    [ReceiptKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [ContainerNo] nvarchar(30) NOT NULL DEFAULT (' '),
    [ArrivedTime] datetime NULL,
    [SignInTime] datetime NULL,
    [UnloadTime] datetime NULL,
    [DepartTime] datetime NULL,
    [DriverName] nvarchar(30) NULL,
    [UserDefine01] nvarchar(20) NULL DEFAULT (''),
    [UserDefine02] nvarchar(20) NULL DEFAULT (''),
    [UserDefine03] nvarchar(20) NULL DEFAULT (''),
    [UserDefine04] nvarchar(20) NULL DEFAULT (''),
    [UserDefine05] nvarchar(20) NULL DEFAULT (''),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (''),
    [UserDefine10] nvarchar(10) NULL DEFAULT (''),
    [UOMQty] int NOT NULL DEFAULT ((0)),
    [Qty] int NOT NULL DEFAULT ((0)),
    [NumberOfSKU] int NOT NULL DEFAULT ((0)),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Remark] nvarchar(2000) NULL,
    [SpecialHandling] nvarchar(20) NULL,
    [DropType] nvarchar(10) NULL,
    [Drop01] nvarchar(12) NULL,
    [Drop02] nvarchar(12) NULL,
    [Drop03] nvarchar(12) NULL,
    [Drop04] nvarchar(12) NULL,
    [Drop05] nvarchar(12) NULL,
    [SupplierCode] nvarchar(15) NOT NULL DEFAULT (''),
    CONSTRAINT [PK_Booking_In] PRIMARY KEY ([BookingNo]),
    CONSTRAINT [FK_Booking_In_LOC] FOREIGN KEY ([Loc]) REFERENCES [dbo].[LOC] ([Loc])
);
GO
