CREATE TABLE [dbo].[booking_audit]
(
    [RowRef] int IDENTITY(1,1) NOT NULL,
    [BookingNo] int NULL,
    [BookingType] nvarchar(10) NULL,
    [Facility] nvarchar(5) NULL DEFAULT (''),
    [BookingDate] datetime NULL,
    [EndTime] datetime NULL,
    [Duration] datetime NULL,
    [Loc] nvarchar(10) NULL,
    [Type] nvarchar(10) NULL DEFAULT (''),
    [ALTReference] nvarchar(30) NULL DEFAULT (''),
    [SCAC] nvarchar(10) NULL DEFAULT (''),
    [ReferenceNo] nvarchar(30) NULL DEFAULT (''),
    [POKey] nvarchar(10) NULL DEFAULT (' '),
    [ReceiptKey] nvarchar(10) NULL DEFAULT (' '),
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [ContainerNo] nvarchar(30) NULL DEFAULT (' '),
    [ArrivedTime] datetime NULL,
    [SignInTime] datetime NULL,
    [UnloadTime] datetime NULL,
    [DepartTime] datetime NULL,
    [DriverName] nvarchar(30) NULL,
    [UserDefine01] nvarchar(20) NULL DEFAULT (''),
    [UserDefine02] nvarchar(20) NULL DEFAULT (''),
    [UserDefine03] nvarchar(20) NULL DEFAULT (''),
    [UserDefine04] nvarchar(20) NULL DEFAULT (''),
    [UserDefine05] nvarchar(20) NULL DEFAULT (''),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (''),
    [UserDefine10] nvarchar(10) NULL DEFAULT (''),
    [UOMQty] int NULL DEFAULT ((0)),
    [Qty] int NULL DEFAULT ((0)),
    [NumberOfSKU] int NULL DEFAULT ((0)),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [Remark] nvarchar(2000) NULL,
    [SpecialHandling] nvarchar(20) NULL,
    [RouteAuth] nvarchar(30) NULL DEFAULT (''),
    [LicenseNo] nvarchar(20) NULL,
    [LoadKey] nvarchar(10) NULL DEFAULT (' '),
    [MbolKey] nvarchar(10) NULL DEFAULT (' '),
    [CBOLKey] int NULL,
    [VehicleContainer] nvarchar(30) NULL DEFAULT (''),
    CONSTRAINT [PK_Booking_Audit] PRIMARY KEY ([RowRef])
);
GO
