CREATE TABLE [dbo].[booking_out]
(
    [BookingNo] int NOT NULL,
    [RouteAuth] nvarchar(30) NULL DEFAULT (''),
    [Facility] nvarchar(5) NULL DEFAULT (''),
    [BookingDate] datetime NOT NULL DEFAULT (getdate()),
    [EndTime] datetime NOT NULL,
    [Duration] datetime NOT NULL,
    [Loc] nvarchar(10) NOT NULL,
    [Type] nvarchar(10) NULL DEFAULT (''),
    [SCAC] nvarchar(10) NULL DEFAULT (''),
    [DriverName] nvarchar(30) NULL,
    [LicenseNo] nvarchar(20) NULL,
    [LoadKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [MbolKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [CBOLKey] int NULL,
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [ALTReference] nvarchar(30) NULL DEFAULT (''),
    [VehicleContainer] nvarchar(30) NULL DEFAULT (''),
    [UserDefine01] nvarchar(20) NULL DEFAULT (''),
    [UserDefine02] nvarchar(20) NULL DEFAULT (''),
    [UserDefine03] nvarchar(20) NULL DEFAULT (''),
    [UserDefine04] nvarchar(20) NULL DEFAULT (''),
    [UserDefine05] nvarchar(20) NULL DEFAULT (''),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (''),
    [UserDefine10] nvarchar(10) NULL DEFAULT (''),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [ArrivedTime] datetime NULL,
    [SignInTime] datetime NULL,
    [UnloadTime] datetime NULL,
    [DepartTime] datetime NULL,
    [CallTime] datetime NULL,
    [Loc2] nvarchar(10) NULL,
    [VehicleType] nvarchar(20) NULL,
    [Carrierkey] nvarchar(18) NULL,
    [FinalizeFlag] nvarchar(1) NOT NULL DEFAULT ('N'),
    [ToLoc] nvarchar(10) NULL DEFAULT (''),
    [Banner] nvarchar(100) NULL,
    [SubBanner] nvarchar(100) NULL,
    [Wave] nvarchar(20) NULL,
    [ShipmentGroupProfile] nvarchar(100) NULL,
    [ShipmentGroup] nvarchar(100) NULL,
    CONSTRAINT [PK_Booking_Out] PRIMARY KEY ([BookingNo]),
    CONSTRAINT [FK_Booking_Out_LOC] FOREIGN KEY ([Loc]) REFERENCES [dbo].[LOC] ([Loc])
);
GO

CREATE INDEX [IX_BOOKING_OUT] ON [dbo].[booking_out] ([MbolKey], [LicenseNo], [DriverName], [Status]);
GO