CREATE TABLE [dbo].[brokerage]
(
    [BrokerageKey] bigint IDENTITY(1,1) NOT NULL,
    [BrokerageMasterKey] nvarchar(20) NOT NULL DEFAULT (' '),
    [BrokerageExternKey] nvarchar(20) NOT NULL DEFAULT (' '),
    [Storerkey] nvarchar(15) NOT NULL,
    [BrokerageDate] datetime NULL DEFAULT (NULL),
    [SellersReference] nvarchar(18) NULL DEFAULT (' '),
    [BuyersReference] nvarchar(18) NULL DEFAULT (' '),
    [OtherReference] nvarchar(18) NULL DEFAULT (' '),
    [DocType] nvarchar(10) NULL DEFAULT (' '),
    [SellerName] nvarchar(45) NULL DEFAULT (' '),
    [SellerAddress1] nvarchar(45) NULL DEFAULT (' '),
    [SellerAddress2] nvarchar(45) NULL DEFAULT (' '),
    [SellerAddress3] nvarchar(45) NULL DEFAULT (' '),
    [SellerAddress4] nvarchar(45) NULL DEFAULT (' '),
    [SellerCity] nvarchar(45) NULL DEFAULT (' '),
    [SellerState] nvarchar(45) NULL DEFAULT (' '),
    [SellerZip] nvarchar(18) NULL DEFAULT (' '),
    [SellerPhone] nvarchar(18) NULL DEFAULT (' '),
    [SellerVat] nvarchar(18) NULL DEFAULT (' '),
    [SellerCountry] nvarchar(30) NULL DEFAULT (' '),
    [BuyerName] nvarchar(45) NULL DEFAULT (' '),
    [BuyerAddress1] nvarchar(45) NULL DEFAULT (' '),
    [BuyerAddress2] nvarchar(45) NULL DEFAULT (' '),
    [BuyerAddress3] nvarchar(45) NULL DEFAULT (' '),
    [BuyerAddress4] nvarchar(45) NULL DEFAULT (' '),
    [BuyerCity] nvarchar(45) NULL DEFAULT (' '),
    [BuyerState] nvarchar(45) NULL DEFAULT (' '),
    [BuyerZip] nvarchar(18) NULL DEFAULT (' '),
    [BuyerPhone] nvarchar(18) NULL DEFAULT (' '),
    [BuyerVat] nvarchar(18) NULL DEFAULT (' '),
    [BuyerCountry] nvarchar(30) NULL DEFAULT (' '),
    [DestinationCountry] nvarchar(30) NULL DEFAULT (' '),
    [Vessel] nvarchar(30) NULL DEFAULT (' '),
    [VesselDate] datetime NULL DEFAULT (NULL),
    [PlaceOfLoading] nvarchar(18) NULL DEFAULT (' '),
    [PlaceOfDischarge] nvarchar(18) NULL DEFAULT (' '),
    [PlaceOfDelivery] nvarchar(18) NULL DEFAULT (' '),
    [IncoTerms] nvarchar(10) NULL DEFAULT (' '),
    [Pmtterm] nvarchar(10) NULL DEFAULT (' '),
    [TransMethod] nvarchar(10) NULL DEFAULT (' '),
    [TermsNote] nvarchar(18) NULL DEFAULT (' '),
    [Signatory] nvarchar(18) NULL DEFAULT (' '),
    [PlaceofIssue] nvarchar(18) NULL DEFAULT (' '),
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [Notes] nvarchar(1024) NULL DEFAULT (' '),
    [LoadingDate] datetime NULL DEFAULT (NULL),
    [ReasonCode] nvarchar(20) NULL DEFAULT (' '),
    [BillOfLadingNo] nvarchar(30) NULL DEFAULT (' '),
    [InvoiceNo] nvarchar(30) NULL DEFAULT (' '),
    [InvoiceDate] datetime NULL DEFAULT (NULL),
    [WeightUOM] nvarchar(10) NULL DEFAULT (' '),
    [GrossWeight] float NULL DEFAULT ('0'),
    [NetWeight] float NULL DEFAULT ('0'),
    [Currency] nvarchar(10) NULL DEFAULT (' '),
    [InvoiceQty] int NULL DEFAULT (' '),
    [InvoiceAmount] float NULL DEFAULT ('0'),
    [CarrierCode] nvarchar(30) NULL DEFAULT (' '),
    [CarrierName] nvarchar(30) NULL DEFAULT (' '),
    [QtyUOM] nvarchar(10) NULL DEFAULT (' '),
    [Userdefine01] nvarchar(30) NULL DEFAULT (' '),
    [Userdefine02] nvarchar(30) NULL DEFAULT (' '),
    [Userdefine03] nvarchar(30) NULL DEFAULT (' '),
    [Userdefine04] nvarchar(30) NULL DEFAULT (' '),
    [Userdefine05] nvarchar(30) NULL DEFAULT (' '),
    [Userdefine06] datetime NULL,
    [Userdefine07] datetime NULL,
    [Userdefine08] nvarchar(30) NULL DEFAULT (' '),
    [Userdefine09] nvarchar(30) NULL DEFAULT (' '),
    [Userdefine10] nvarchar(30) NULL DEFAULT (' '),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] varchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] varchar(128) NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Transmitflag] int NULL DEFAULT ('0'),
    [VesselNum] nvarchar(150) NULL DEFAULT (''),
    [MasterWayBill] nvarchar(150) NULL DEFAULT (''),
    [HouseWayBill] nvarchar(150) NULL DEFAULT (''),
    CONSTRAINT [PK_Brokerage] PRIMARY KEY ([BrokerageKey])
);
GO

CREATE INDEX [IDX_B_BrokerageExternKey] ON [dbo].[brokerage] ([BrokerageExternKey]);
GO
CREATE INDEX [IDX_B_BrokerageMasterKey] ON [dbo].[brokerage] ([BrokerageMasterKey]);
GO
CREATE INDEX [IDX_B_StorerKey] ON [dbo].[brokerage] ([Storerkey]);
GO