CREATE TABLE [dbo].[casemanifest]
(
    [CaseId] nvarchar(20) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Loc] nvarchar(10) NOT NULL DEFAULT ('UNKNOWN'),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [ExpectedReceiptKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [ExpectedPOKey] nvarchar(18) NOT NULL DEFAULT (' '),
    [ReceivedReceiptKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [ReceivedPOKey] nvarchar(18) NOT NULL DEFAULT (' '),
    [ReceiptDate] datetime NOT NULL DEFAULT (getdate()),
    [ExpectedClpOrderKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [ShippedClpOrderKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [Qty] int NOT NULL DEFAULT ((0)),
    [ShipStatus] nvarchar(10) NOT NULL DEFAULT ('0'),
    [Shipdate] datetime NOT NULL DEFAULT (getdate()),
    [OSDCode] nvarchar(10) NOT NULL DEFAULT (' '),
    [OSDQTY] int NOT NULL DEFAULT ((0)),
    [ID] nvarchar(18) NOT NULL DEFAULT (' '),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [TimeStamp] nvarchar(18) NULL,
    CONSTRAINT [PKCASEMANIFEST] PRIMARY KEY ([CaseId]),
    CONSTRAINT [FK_CASEMANIFEST_LOC_01] FOREIGN KEY ([Loc]) REFERENCES [dbo].[LOC] ([Loc]),
    CONSTRAINT [FK_CASEMANIFEST_SKU_01] FOREIGN KEY ([StorerKey], [Sku]) REFERENCES [dbo].[SKU] ([StorerKey], [Sku]),
    CONSTRAINT [CK_CASEMANIFEST_CaseId] CHECK (NOT [CaseId]=' '),
    CONSTRAINT [CK_CASMAN_ShipStatus] CHECK ([ShipStatus]>='0' AND [ShipStatus]<='9'),
    CONSTRAINT [CK_CASMAN_Status] CHECK ([Status]>='0' AND [Status]<='9')
);
GO
