CREATE TABLE [dbo].[cbol]
(
    [CBOLKey] int NOT NULL,
    [CBOLReference] nvarchar(30) NULL DEFAULT (''),
    [Facility] nvarchar(5) NULL DEFAULT ('F1'),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [Type] nvarchar(10) NOT NULL DEFAULT ((0)),
    [RoutingDate] datetime NOT NULL DEFAULT (getdate()),
    [PickupDate] datetime NOT NULL DEFAULT (getdate()),
    [DepartureDate] datetime NOT NULL DEFAULT (getdate()),
    [ArivalDate] datetime NOT NULL DEFAULT (getdate()),
    [CancelDate] datetime NOT NULL DEFAULT (getdate()),
    [RoutingCIDNo] nvarchar(30) NULL DEFAULT (''),
    [SCAC] nvarchar(10) NULL DEFAULT (''),
    [ProNumber] nvarchar(30) NULL DEFAULT (''),
    [VehicleContainer] nvarchar(30) NULL DEFAULT (''),
    [SealNo] nvarchar(8) NULL DEFAULT (''),
    [CountedBy] nvarchar(10) NULL DEFAULT (''),
    [ChargeCollected] nvarchar(10) NULL DEFAULT (''),
    [TrailerLoadBy] nvarchar(10) NULL DEFAULT (''),
    [Carrierkey] nvarchar(15) NOT NULL DEFAULT (''),
    [CTNTYPE1] nvarchar(30) NULL DEFAULT (''),
    [CTNTYPE2] nvarchar(30) NULL DEFAULT (''),
    [UserDefine01] nvarchar(20) NULL DEFAULT (''),
    [UserDefine02] nvarchar(20) NULL DEFAULT (''),
    [UserDefine03] nvarchar(20) NULL DEFAULT (''),
    [UserDefine04] nvarchar(20) NULL DEFAULT (''),
    [UserDefine05] nvarchar(20) NULL DEFAULT (''),
    [UserDefine06] datetime NULL DEFAULT (getdate()),
    [UserDefine07] datetime NULL DEFAULT (getdate()),
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (''),
    [UserDefine10] nvarchar(10) NULL DEFAULT (''),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Consigneekey] nvarchar(15) NOT NULL DEFAULT (''),
    CONSTRAINT [PK_CBOL] PRIMARY KEY ([CBOLKey])
);
GO
