CREATE TABLE [dbo].[ccdetail]
(
    [CCKey] nvarchar(10) NOT NULL,
    [CCDetailKey] nvarchar(10) NOT NULL,
    [CCSheetNo] nvarchar(10) NOT NULL DEFAULT (' '),
    [TagNo] nvarchar(10) NOT NULL DEFAULT (' '),
    [Storerkey] nvarchar(10) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Lot] nvarchar(10) NOT NULL DEFAULT (' '),
    [Loc] nvarchar(10) NOT NULL DEFAULT (' '),
    [Id] nvarchar(18) NOT NULL DEFAULT (' '),
    [SystemQty] int NOT NULL DEFAULT ((0)),
    [Qty] int NOT NULL DEFAULT ((0)),
    [Lottable01] nvarchar(18) NULL,
    [Lottable02] nvarchar(18) NULL,
    [Lottable03] nvarchar(18) NULL,
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [FinalizeFlag] nvarchar(1) NULL DEFAULT ('N'),
    [Qty_Cnt2] int NOT NULL DEFAULT ((0)),
    [Lottable01_Cnt2] nvarchar(18) NULL,
    [Lottable02_Cnt2] nvarchar(18) NULL,
    [Lottable03_Cnt2] nvarchar(18) NULL,
    [Lottable04_Cnt2] datetime NULL,
    [Lottable05_Cnt2] datetime NULL,
    [FinalizeFlag_Cnt2] nvarchar(1) NULL DEFAULT ('N'),
    [Qty_Cnt3] int NULL DEFAULT ((0)),
    [Lottable01_Cnt3] nvarchar(18) NULL,
    [Lottable02_Cnt3] nvarchar(18) NULL,
    [Lottable03_Cnt3] nvarchar(18) NULL,
    [Lottable04_Cnt3] datetime NULL,
    [Lottable05_Cnt3] datetime NULL,
    [FinalizeFlag_Cnt3] nvarchar(1) NULL DEFAULT ('N'),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [StatusMsg] nvarchar(255) NOT NULL DEFAULT (' '),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Timestamp] timestamp NOT NULL,
    [RefNo] nvarchar(20) NULL DEFAULT (' '),
    [EditDate_Cnt1] datetime NULL,
    [EditWho_Cnt1] nvarchar(18) NULL,
    [EditDate_Cnt2] datetime NULL,
    [EditWho_Cnt2] nvarchar(18) NULL,
    [EditDate_Cnt3] datetime NULL,
    [EditWho_Cnt3] nvarchar(18) NULL,
    [Counted_Cnt1] nvarchar(1) NULL DEFAULT ('0'),
    [Counted_Cnt2] nvarchar(1) NULL DEFAULT ('0'),
    [Counted_Cnt3] nvarchar(1) NULL DEFAULT ('0'),
    [Lottable06] nvarchar(30) NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [Lottable06_Cnt2] nvarchar(30) NULL DEFAULT (''),
    [Lottable07_Cnt2] nvarchar(30) NULL DEFAULT (''),
    [Lottable08_Cnt2] nvarchar(30) NULL DEFAULT (''),
    [Lottable09_Cnt2] nvarchar(30) NULL DEFAULT (''),
    [Lottable10_Cnt2] nvarchar(30) NULL DEFAULT (''),
    [Lottable11_Cnt2] nvarchar(30) NULL DEFAULT (''),
    [Lottable12_Cnt2] nvarchar(30) NULL DEFAULT (''),
    [Lottable13_Cnt2] datetime NULL,
    [Lottable14_Cnt2] datetime NULL,
    [Lottable15_Cnt2] datetime NULL,
    [Lottable06_Cnt3] nvarchar(30) NULL DEFAULT (''),
    [Lottable07_Cnt3] nvarchar(30) NULL DEFAULT (''),
    [Lottable08_Cnt3] nvarchar(30) NULL DEFAULT (''),
    [Lottable09_Cnt3] nvarchar(30) NULL DEFAULT (''),
    [Lottable10_Cnt3] nvarchar(30) NULL DEFAULT (''),
    [Lottable11_Cnt3] nvarchar(30) NULL DEFAULT (''),
    [Lottable12_Cnt3] nvarchar(30) NULL DEFAULT (''),
    [Lottable13_Cnt3] datetime NULL,
    [Lottable14_Cnt3] datetime NULL,
    [Lottable15_Cnt3] datetime NULL,
    CONSTRAINT [PKCCDETAIL] PRIMARY KEY ([CCDetailKey])
);
GO

CREATE INDEX [IX_CCDetail_01] ON [dbo].[ccdetail] ([RefNo], [Storerkey], [Sku]);
GO
CREATE INDEX [IX_CCDetail_02] ON [dbo].[ccdetail] ([CCSheetNo], [Loc], [Status], [RefNo]);
GO
CREATE INDEX [IX_CCDetail_CCKey] ON [dbo].[ccdetail] ([CCKey], [CCDetailKey]);
GO
CREATE INDEX [IX_CCDetail_CCKey_LOC] ON [dbo].[ccdetail] ([CCKey], [Loc]);
GO