CREATE TABLE [dbo].[cloudprintconfig]
(
    [PrintClientID] nvarchar(100) NOT NULL,
    [Region] nvarchar(20) NULL DEFAULT (''),
    [Country] nvarchar(50) NULL DEFAULT (''),
    [State] nvarchar(50) NULL DEFAULT (''),
    [WarehouseID] nvarchar(20) NULL DEFAULT (''),
    [Descr] nvarchar(200) NOT NULL DEFAULT (''),
    [CloudPrintAPI] nvarchar(200) NOT NULL DEFAULT (''),
    [ActiveFlag] int NOT NULL DEFAULT ((0)),
    [LogLevel] int NOT NULL DEFAULT ((2)),
    [UpdatePIDIntv] int NOT NULL DEFAULT ((10)),
    [TaskPendingDuration] int NOT NULL DEFAULT ((10)),
    [PriorityMode] int NOT NULL DEFAULT ((0)),
    [ThreadCount] int NOT NULL DEFAULT ((10)),
    [ThreadCountP1] int NOT NULL DEFAULT ((0)),
    [ThreadCountP2] int NOT NULL DEFAULT ((0)),
    [ThreadCountP3] int NOT NULL DEFAULT ((0)),
    [ThreadCountP4] int NOT NULL DEFAULT ((0)),
    [ThreadCountP5] int NOT NULL DEFAULT ((0)),
    [ThreadCountP6] int NOT NULL DEFAULT ((0)),
    [ThreadCountP7] int NOT NULL DEFAULT ((0)),
    [ThreadCountP8] int NOT NULL DEFAULT ((0)),
    [ThreadCountP9] int NOT NULL DEFAULT ((0)),
    [ThreadCountP10] int NOT NULL DEFAULT ((0)),
    [ThreadCountP11] int NOT NULL DEFAULT ((0)),
    [ThreadCountP12] int NOT NULL DEFAULT ((0)),
    [ThreadCountP13] int NOT NULL DEFAULT ((0)),
    [ThreadCountP14] int NOT NULL DEFAULT ((0)),
    [ThreadCountP15] int NOT NULL DEFAULT ((0)),
    [ThreadCountP16] int NOT NULL DEFAULT ((0)),
    [ThreadCountP17] int NOT NULL DEFAULT ((0)),
    [ThreadCountP18] int NOT NULL DEFAULT ((0)),
    [ThreadCountP19] int NOT NULL DEFAULT ((0)),
    [ThreadCountP20] int NOT NULL DEFAULT ((0)),
    [CPCProcTimeOut] int NOT NULL DEFAULT ((30)),
    [CPCKillTimeoutProc] int NOT NULL DEFAULT ((1)),
    [CPCAutoReprocess] int NOT NULL DEFAULT ((1)),
    [EmailSMTPServer] nvarchar(100) NOT NULL DEFAULT ('apmmail.maersk.net'),
    [EmailSMTPPort] int NOT NULL DEFAULT ((25)),
    [EmailLogin] nvarchar(30) NOT NULL DEFAULT (''),
    [EmailPassword] nvarchar(30) NOT NULL DEFAULT (''),
    [EmailSubject] nvarchar(200) NOT NULL DEFAULT ('CPCSvc Notification'),
    [EmailFrom] nvarchar(50) NOT NULL DEFAULT ('noreply@maersk.com'),
    [EmailTo] nvarchar(500) NOT NULL DEFAULT (''),
    [EmailCC] nvarchar(500) NOT NULL DEFAULT (''),
    [EmailMaxPerMin] int NOT NULL DEFAULT ('5'),
    [CurrVersion] nvarchar(30) NOT NULL DEFAULT (''),
    [LastRunIP] nvarchar(50) NOT NULL DEFAULT (''),
    [LastRunDate] datetime NULL,
    [LastSeenDate] datetime NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    CONSTRAINT [PK_CloudPrintConfig] PRIMARY KEY ([PrintClientID])
);
GO
