CREATE TABLE [dbo].[cloudprinttask_log]
(
    [ID] bigint NOT NULL,
    [PrintClientID] nvarchar(100) NOT NULL,
    [CmdType] nvarchar(10) NOT NULL,
    [B64Command] nvarchar(MAX) NOT NULL,
    [B64FileSrc] nvarchar(1000) NOT NULL,
    [IP] nvarchar(20) NOT NULL,
    [Port] nvarchar(5) NOT NULL,
    [Timeout] int NOT NULL,
    [PrinterName] nvarchar(500) NOT NULL,
    [RefDocType] nvarchar(20) NULL,
    [RefDocID] nvarchar(20) NULL,
    [RefJobID] nvarchar(20) NULL,
    [RefDesc] nvarchar(500) NULL,
    [Priority] int NOT NULL,
    [ThreadId] nvarchar(20) NULL,
    [MsgRecvDate] datetime NULL,
    [ThreadStartTime] datetime NULL,
    [ThreadEndTime] datetime NULL,
    [Status] nvarchar(1) NOT NULL,
    [ErrMsg] nvarchar(1000) NULL,
    [Try] int NOT NULL,
    [PaperSizeWxH] nvarchar(15) NOT NULL,
    [DCropWidth] nvarchar(10) NULL,
    [DCropHeight] nvarchar(10) NULL,
    [IsLandScape] nvarchar(1) NULL,
    [IsColor] nvarchar(1) NULL,
    [IsDuplex] nvarchar(1) NULL,
    [IsCollate] nvarchar(1) NULL,
    [PrintCopy] nvarchar(5) NULL,
    [MoveToArchive] nvarchar(1) NULL,
    [AddDate] datetime NULL,
    [AddWho] nvarchar(128) NULL,
    [EditDate] datetime NULL,
    [EditWho] nvarchar(128) NULL,
    CONSTRAINT [PK_CloudPrintTask_Log] PRIMARY KEY ([ID])
);
GO
