CREATE TABLE [dbo].[cloudprinttask]
(
    [ID] bigint IDENTITY(1,1) NOT NULL,
    [PrintClientID] nvarchar(100) NOT NULL DEFAULT (''),
    [CmdType] nvarchar(10) NOT NULL DEFAULT (''),
    [B64Command] nvarchar(MAX) NOT NULL DEFAULT (''),
    [B64FileSrc] nvarchar(1000) NOT NULL DEFAULT (''),
    [IP] nvarchar(20) NOT NULL DEFAULT (''),
    [Port] nvarchar(5) NOT NULL DEFAULT (''),
    [Timeout] int NOT NULL DEFAULT ('30000'),
    [PrinterName] nvarchar(500) NOT NULL DEFAULT (''),
    [RefDocType] nvarchar(20) NULL DEFAULT (''),
    [RefDocID] nvarchar(20) NULL DEFAULT (''),
    [RefJobID] nvarchar(20) NULL DEFAULT (''),
    [RefDesc] nvarchar(500) NULL DEFAULT (''),
    [Priority] int NOT NULL DEFAULT ('0'),
    [ThreadId] nvarchar(20) NULL DEFAULT (''),
    [MsgRecvDate] datetime NULL,
    [ThreadStartTime] datetime NULL,
    [ThreadEndTime] datetime NULL,
    [Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [ErrMsg] nvarchar(1000) NULL DEFAULT (''),
    [Try] int NOT NULL DEFAULT ((0)),
    [PaperSizeWxH] nvarchar(15) NOT NULL DEFAULT (''),
    [DCropWidth] nvarchar(10) NULL DEFAULT ('0'),
    [DCropHeight] nvarchar(10) NULL DEFAULT ('0'),
    [IsLandScape] nvarchar(1) NULL DEFAULT ('0'),
    [IsColor] nvarchar(1) NULL DEFAULT ('0'),
    [IsDuplex] nvarchar(1) NULL DEFAULT ('0'),
    [IsCollate] nvarchar(1) NULL DEFAULT ('0'),
    [PrintCopy] nvarchar(5) NULL DEFAULT ('1'),
    [MoveToArchive] nvarchar(1) NULL DEFAULT ('1'),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    CONSTRAINT [PK_CloudPrintTask] PRIMARY KEY ([ID])
);
GO
