CREATE TABLE [dbo].[del_orders]
(
    [OrderKey] nvarchar(10) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL,
    [ExternOrderKey] nvarchar(50) NOT NULL,
    [OrderDate] datetime NOT NULL,
    [DeliveryDate] datetime NOT NULL,
    [Priority] nvarchar(10) NOT NULL,
    [ConsigneeKey] nvarchar(15) NOT NULL,
    [C_contact1] nvarchar(100) NULL,
    [C_Contact2] nvarchar(100) NULL,
    [C_Company] nvarchar(100) NULL,
    [C_Address1] nvarchar(45) NULL,
    [C_Address2] nvarchar(45) NULL,
    [C_Address3] nvarchar(45) NULL,
    [C_Address4] nvarchar(45) NULL,
    [C_City] nvarchar(45) NULL,
    [C_State] nvarchar(45) NULL,
    [C_Zip] nvarchar(18) NULL,
    [C_Country] nvarchar(30) NULL,
    [C_ISOCntryCode] nvarchar(10) NULL,
    [C_Phone1] nvarchar(18) NULL,
    [C_Phone2] nvarchar(18) NULL,
    [C_Fax1] nvarchar(18) NULL,
    [C_Fax2] nvarchar(18) NULL,
    [C_vat] nvarchar(18) NULL,
    [BuyerPO] nvarchar(20) NULL,
    [BillToKey] nvarchar(15) NOT NULL,
    [B_contact1] nvarchar(100) NULL,
    [B_Contact2] nvarchar(100) NULL,
    [B_Company] nvarchar(100) NULL,
    [B_Address1] nvarchar(45) NULL,
    [B_Address2] nvarchar(45) NULL,
    [B_Address3] nvarchar(45) NULL,
    [B_Address4] nvarchar(45) NULL,
    [B_City] nvarchar(45) NULL,
    [B_State] nvarchar(45) NULL,
    [B_Zip] nvarchar(18) NULL,
    [B_Country] nvarchar(30) NULL,
    [B_ISOCntryCode] nvarchar(10) NULL,
    [B_Phone1] nvarchar(18) NULL,
    [B_Phone2] nvarchar(18) NULL,
    [B_Fax1] nvarchar(18) NULL,
    [B_Fax2] nvarchar(18) NULL,
    [B_Vat] nvarchar(18) NULL,
    [IncoTerm] nvarchar(10) NULL,
    [PmtTerm] nvarchar(10) NULL,
    [OpenQty] int NULL,
    [Status] nvarchar(10) NOT NULL,
    [DischargePlace] nvarchar(30) NULL,
    [DeliveryPlace] nvarchar(30) NULL,
    [IntermodalVehicle] nvarchar(30) NOT NULL,
    [CountryOfOrigin] nvarchar(30) NULL,
    [CountryDestination] nvarchar(30) NULL,
    [UpdateSource] nvarchar(10) NOT NULL,
    [Type] nvarchar(10) NOT NULL,
    [OrderGroup] nvarchar(20) NOT NULL,
    [Door] nvarchar(10) NOT NULL,
    [Route] nvarchar(10) NOT NULL,
    [Stop] nvarchar(10) NOT NULL,
    [Notes] nvarchar(4000) NULL,
    [EffectiveDate] datetime NOT NULL,
    [AddDate] datetime NOT NULL,
    [AddWho] nvarchar(128) NOT NULL,
    [EditDate] datetime NOT NULL,
    [EditWho] nvarchar(128) NOT NULL,
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [ContainerType] nvarchar(20) NULL,
    [ContainerQty] int NULL,
    [BilledContainerQty] int NULL,
    [SOStatus] nvarchar(10) NULL,
    [MBOLKey] nvarchar(10) NULL,
    [InvoiceNo] nvarchar(20) NULL,
    [InvoiceAmount] float NULL,
    [Salesman] nvarchar(30) NULL,
    [GrossWeight] float NULL,
    [Capacity] float NULL,
    [PrintFlag] nvarchar(1) NULL,
    [LoadKey] nvarchar(10) NULL,
    [Rdd] nvarchar(30) NULL,
    [Notes2] nvarchar(4000) NULL,
    [SequenceNo] int NULL,
    [Rds] nvarchar(1) NULL,
    [SectionKey] nvarchar(10) NULL,
    [Facility] nvarchar(5) NULL,
    [PrintDocDate] datetime NULL,
    [LabelPrice] nvarchar(20) NULL,
    [POKey] nvarchar(10) NULL,
    [ExternPOKey] nvarchar(20) NULL,
    [XDockFlag] nvarchar(1) NOT NULL,
    [UserDefine01] nvarchar(20) NULL,
    [UserDefine02] nvarchar(20) NULL,
    [UserDefine03] nvarchar(20) NULL,
    [UserDefine04] nvarchar(20) NULL,
    [UserDefine05] nvarchar(20) NULL,
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL,
    [UserDefine09] nvarchar(10) NULL,
    [UserDefine10] nvarchar(10) NULL,
    [Issued] nvarchar(1) NULL,
    [DeliveryNote] nvarchar(10) NULL,
    [PODCust] datetime NULL,
    [PODArrive] datetime NULL,
    [PODReject] datetime NULL,
    [PODUser] nvarchar(18) NULL,
    [xdockpokey] nvarchar(20) NULL,
    [SpecialHandling] nvarchar(1) NULL,
    [RoutingTool] nvarchar(30) NULL,
    [MarkforKey] nvarchar(15) NOT NULL DEFAULT (''),
    [M_Contact1] nvarchar(100) NULL,
    [M_Contact2] nvarchar(100) NULL,
    [M_Company] nvarchar(100) NULL,
    [M_Address1] nvarchar(45) NULL,
    [M_Address2] nvarchar(45) NULL,
    [M_Address3] nvarchar(45) NULL,
    [M_Address4] nvarchar(45) NULL,
    [M_City] nvarchar(45) NULL,
    [M_State] nvarchar(45) NULL,
    [M_Zip] nvarchar(18) NULL,
    [M_Country] nvarchar(30) NULL,
    [M_ISOCntryCode] nvarchar(10) NULL,
    [M_Phone1] nvarchar(18) NULL,
    [M_Phone2] nvarchar(18) NULL,
    [M_Fax1] nvarchar(18) NULL,
    [M_Fax2] nvarchar(18) NULL,
    [M_vat] nvarchar(18) NULL,
    [ShipperKey] nvarchar(15) NULL DEFAULT (' '),
    [DocType] nvarchar(1) NULL DEFAULT (''),
    [TrackingNo] nvarchar(40) NULL DEFAULT (''),
    [ECOM_PRESALE_FLAG] nvarchar(2) NULL,
    [ECOM_SINGLE_Flag] nvarchar(1) NULL,
    [CurrencyCode] nvarchar(20) NULL,
    [RTNTrackingNo] nvarchar(40) NULL,
    [BizUnit] nvarchar(50) NULL,
    [ECOM_OAID] nvarchar(128) NULL DEFAULT (''),
    [ECOM_Platform] nvarchar(30) NULL DEFAULT (''),
    CONSTRAINT [PK_DEL_ORDERS] PRIMARY KEY ([OrderKey])
);
GO
