CREATE TABLE [dbo].[del_po]
(
    [POKey] nvarchar(18) NOT NULL,
    [ExternPOKey] nvarchar(20) NULL,
    [PoGroup] nvarchar(20) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL,
    [PODate] datetime NULL,
    [SellersReference] nvarchar(18) NULL,
    [BuyersReference] nvarchar(18) NULL,
    [OtherReference] nvarchar(18) NULL,
    [POType] nvarchar(10) NULL,
    [SellerName] nvarchar(45) NULL,
    [SellerAddress1] nvarchar(45) NULL,
    [SellerAddress2] nvarchar(45) NULL,
    [SellerAddress3] nvarchar(45) NULL,
    [SellerAddress4] nvarchar(45) NULL,
    [SellerCity] nvarchar(45) NULL,
    [SellerState] nvarchar(45) NULL,
    [SellerZip] nvarchar(18) NULL,
    [SellerPhone] nvarchar(18) NULL,
    [SellerVat] nvarchar(18) NULL,
    [BuyerName] nvarchar(45) NULL,
    [BuyerAddress1] nvarchar(45) NULL,
    [BuyerAddress2] nvarchar(45) NULL,
    [BuyerAddress3] nvarchar(45) NULL,
    [BuyerAddress4] nvarchar(45) NULL,
    [BuyerCity] nvarchar(45) NULL,
    [BuyerState] nvarchar(45) NULL,
    [BuyerZip] nvarchar(18) NULL,
    [BuyerPhone] nvarchar(18) NULL,
    [BuyerVAT] nvarchar(18) NULL,
    [OriginCountry] nvarchar(30) NULL,
    [DestinationCountry] nvarchar(30) NULL,
    [Vessel] nvarchar(30) NULL,
    [VesselDate] datetime NULL,
    [PlaceOfLoading] nvarchar(18) NULL,
    [PlaceOfDischarge] nvarchar(18) NULL,
    [PlaceofDelivery] nvarchar(18) NULL,
    [IncoTerms] nvarchar(10) NULL,
    [Pmtterm] nvarchar(10) NULL,
    [TransMethod] nvarchar(10) NULL,
    [TermsNote] nvarchar(18) NULL,
    [Signatory] nvarchar(18) NULL,
    [PlaceofIssue] nvarchar(18) NULL,
    [OpenQty] int NULL,
    [Status] nvarchar(10) NOT NULL,
    [Notes] nvarchar(4000) NULL,
    [EffectiveDate] datetime NOT NULL,
    [AddDate] datetime NOT NULL,
    [AddWho] nvarchar(128) NOT NULL,
    [EditDate] datetime NOT NULL,
    [EditWho] nvarchar(128) NOT NULL,
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [ExternStatus] nvarchar(10) NULL,
    [LoadingDate] datetime NULL,
    [ReasonCode] nvarchar(20) NULL,
    [UserDefine01] nvarchar(30) NULL,
    [UserDefine02] nvarchar(30) NULL,
    [UserDefine03] nvarchar(30) NULL,
    [UserDefine04] nvarchar(30) NULL,
    [UserDefine05] nvarchar(30) NULL,
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(30) NULL,
    [UserDefine09] nvarchar(30) NULL,
    [UserDefine10] nvarchar(30) NULL,
    [xdockpokey] nvarchar(20) NULL,
    [SellerCompany] nvarchar(45) NULL,
    [SellerCountry] nvarchar(30) NULL,
    [SellerContact1] nvarchar(30) NULL,
    [SellerContact2] nvarchar(30) NULL,
    [SellerPhone2] nvarchar(18) NULL,
    [SellerEmail1] nvarchar(60) NULL,
    [SellerEmail2] nvarchar(60) NULL,
    [SellerFax1] nvarchar(18) NULL,
    [SellerFax2] nvarchar(18) NULL,
    CONSTRAINT [PK_DEL_PO] PRIMARY KEY ([POKey])
);
GO
