CREATE TABLE [dbo].[ec_receipt]
(
    [ReceiptKey] nvarchar(10) NOT NULL,
    [ExternReceiptKey] nvarchar(20) NOT NULL DEFAULT (' '),
    [ReceiptGroup] nvarchar(20) NOT NULL DEFAULT (' '),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [ReceiptDate] datetime NULL DEFAULT (getdate()),
    [POKey] nvarchar(18) NULL DEFAULT (' '),
    [CarrierKey] nvarchar(15) NULL,
    [CarrierName] nvarchar(30) NULL,
    [CarrierAddress1] nvarchar(45) NULL,
    [CarrierAddress2] nvarchar(45) NULL,
    [CarrierCity] nvarchar(45) NULL,
    [CarrierState] nvarchar(45) NULL,
    [CarrierZip] nvarchar(10) NULL,
    [CarrierReference] nvarchar(18) NULL,
    [WarehouseReference] nvarchar(18) NULL,
    [OriginCountry] nvarchar(30) NULL,
    [DestinationCountry] nvarchar(30) NULL,
    [VehicleNumber] nvarchar(18) NULL,
    [VehicleDate] nvarchar(18) NULL,
    [PlaceOfLoading] nvarchar(18) NULL,
    [PlaceOfDischarge] nvarchar(18) NULL,
    [PlaceofDelivery] nvarchar(18) NULL,
    [IncoTerms] nvarchar(10) NULL,
    [TermsNote] nvarchar(18) NULL,
    [ContainerKey] nvarchar(18) NULL,
    [Signatory] nvarchar(18) NULL,
    [PlaceofIssue] nvarchar(18) NULL,
    [OpenQty] int NULL DEFAULT ((0)),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [Notes] nvarchar(4000) NULL,
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [ContainerType] nvarchar(20) NULL,
    [ContainerQty] int NULL,
    [BilledContainerQty] int NULL DEFAULT ((0)),
    [RECType] nvarchar(10) NULL DEFAULT ('NORMAL'),
    [ASNStatus] nvarchar(10) NULL DEFAULT ('0'),
    [ASNReason] nvarchar(10) NULL DEFAULT (' '),
    [Facility] nvarchar(15) NULL,
    [MBOLKey] nvarchar(10) NULL,
    [Appointment_No] nvarchar(10) NULL,
    [LoadKey] nvarchar(10) NULL,
    [xDockFlag] nvarchar(1) NULL DEFAULT ((0)),
    [UserDefine01] nvarchar(30) NULL DEFAULT (' '),
    [PROCESSTYPE] nvarchar(1) NULL,
    [UserDefine02] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine09] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(30) NULL DEFAULT (' '),
    [DOCTYPE] nvarchar(1) NULL,
    [RoutingTool] nvarchar(30) NULL,
    [CTNTYPE1] nvarchar(30) NULL,
    [CTNTYPE2] nvarchar(30) NULL,
    [CTNTYPE3] nvarchar(30) NULL,
    [CTNTYPE4] nvarchar(30) NULL,
    [CTNTYPE5] nvarchar(30) NULL,
    [CTNTYPE6] nvarchar(30) NULL,
    [CTNTYPE7] nvarchar(30) NULL,
    [CTNTYPE8] nvarchar(30) NULL,
    [CTNTYPE9] nvarchar(30) NULL,
    [CTNTYPE10] nvarchar(30) NULL,
    [PACKTYPE1] nvarchar(30) NULL,
    [PACKTYPE2] nvarchar(30) NULL,
    [PACKTYPE3] nvarchar(30) NULL,
    [PACKTYPE4] nvarchar(30) NULL,
    [PACKTYPE5] nvarchar(30) NULL,
    [PACKTYPE6] nvarchar(30) NULL,
    [PACKTYPE7] nvarchar(30) NULL,
    [PACKTYPE8] nvarchar(30) NULL,
    [PACKTYPE9] nvarchar(30) NULL,
    [PACKTYPE10] nvarchar(30) NULL,
    [CTNCNT1] int NULL,
    [CTNCNT2] int NULL,
    [CTNCNT3] int NULL,
    [CTNCNT4] int NULL,
    [CTNCNT5] int NULL,
    [CTNCNT6] int NULL,
    [CTNCNT7] int NULL,
    [CTNCNT8] int NULL,
    [CTNCNT9] int NULL,
    [CTNCNT10] int NULL,
    [CTNQTY1] int NULL,
    [CTNQTY2] int NULL,
    [CTNQTY3] int NULL,
    [CTNQTY4] int NULL,
    [CTNQTY5] int NULL,
    [CTNQTY6] int NULL,
    [CTNQTY7] int NULL,
    [CTNQTY8] int NULL,
    [CTNQTY9] int NULL,
    [CTNQTY10] int NULL,
    [NoOfMasterCtn] int NULL,
    [NoOfTTLUnit] int NULL,
    [NoOfPallet] int NULL,
    [Weight] float NOT NULL DEFAULT ((0)),
    [WeightUnit] nvarchar(20) NULL,
    [Cube] float NOT NULL DEFAULT ((0)),
    [CubeUnit] nvarchar(20) NULL,
    [GIS_ControlNo] nvarchar(20) NULL,
    [Cust_ISA_ControlNo] nvarchar(20) NULL DEFAULT (''),
    [Cust_GIS_ControlNo] nvarchar(20) NULL DEFAULT (''),
    [GIS_ProcessTime] datetime NULL,
    [Cust_EDIAckTime] datetime NULL,
    [FinalizeDate] datetime NOT NULL DEFAULT (getdate()),
    [SellerName] nvarchar(45) NULL DEFAULT (''),
    [SellerCompany] nvarchar(45) NULL DEFAULT (''),
    [SellerAddress1] nvarchar(45) NULL DEFAULT (''),
    [SellerAddress2] nvarchar(45) NULL DEFAULT (''),
    [SellerAddress3] nvarchar(45) NULL DEFAULT (''),
    [SellerAddress4] nvarchar(45) NULL DEFAULT (''),
    [SellerCity] nvarchar(45) NULL DEFAULT (''),
    [SellerState] nvarchar(45) NULL DEFAULT (''),
    [SellerZip] nvarchar(18) NULL DEFAULT (''),
    [SellerCountry] nvarchar(30) NULL DEFAULT (''),
    [SellerContact1] nvarchar(30) NULL DEFAULT (''),
    [SellerContact2] nvarchar(30) NULL DEFAULT (''),
    [SellerPhone1] nvarchar(18) NULL DEFAULT (''),
    [SellerPhone2] nvarchar(18) NULL DEFAULT (''),
    [SellerEmail1] nvarchar(60) NULL DEFAULT (''),
    [SellerEmail2] nvarchar(60) NULL DEFAULT (''),
    [SellerFax1] nvarchar(18) NULL DEFAULT (''),
    [SellerFax2] nvarchar(18) NULL DEFAULT (''),
    [PCCDeliveryTime] nvarchar(30) NULL,
    [RefReceiptKey] nvarchar(50) NULL,
    CONSTRAINT [PKECRECEIPT] PRIMARY KEY ([ReceiptKey]),
    CONSTRAINT [CK_EC_RECEIPT_Status] CHECK (rtrim([Status]) like '[0-9]')
);
GO

CREATE INDEX [IX_EC_RECEIPT_ExternReceiptKey] ON [dbo].[ec_receipt] ([StorerKey], [ExternReceiptKey]);
GO