CREATE TABLE [dbo].[facility]
(
    [Facility] nvarchar(5) NOT NULL,
    [Descr] nvarchar(50) NOT NULL,
    [UserDefine01] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine06] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine07] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine08] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine09] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine11] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine12] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine13] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine14] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine15] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine16] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine17] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine18] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine19] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine20] nvarchar(30) NULL DEFAULT (' '),
    [Addwho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [TMS_Interface] nvarchar(1) NULL DEFAULT (' '),
    [Address1] nvarchar(45) NULL,
    [Address2] nvarchar(45) NULL,
    [Address3] nvarchar(45) NULL,
    [Address4] nvarchar(45) NULL,
    [City] nvarchar(45) NULL,
    [State] nvarchar(45) NULL,
    [Zip] nvarchar(18) NULL,
    [Country] nvarchar(30) NULL,
    [ISOCntryCode] nvarchar(10) NULL,
    [Contact1] nvarchar(30) NULL,
    [Contact2] nvarchar(30) NULL,
    [Phone1] nvarchar(18) NULL,
    [Phone2] nvarchar(18) NULL,
    [Fax1] nvarchar(18) NULL,
    [Fax2] nvarchar(18) NULL,
    [Email1] nvarchar(60) NULL,
    [Email2] nvarchar(60) NULL,
    [TimeZone] nvarchar(128) NULL,
    [Type] nvarchar(20) NOT NULL DEFAULT (' '),
    [SqFeet] int NOT NULL DEFAULT ((0)),
    [Longitude] nvarchar(10) NULL DEFAULT (' '),
    [Latitude] nvarchar(10) NULL DEFAULT (' '),
    [NoOfDoors] int NULL DEFAULT ('0'),
    [LeaseType] nvarchar(10) NULL,
    [OperationHours] nvarchar(20) NULL,
    [FacilityFor] nvarchar(10) NULL DEFAULT (''),
    [SiteID] nvarchar(20) NULL,
    [BondedFacility] nvarchar(5) NULL,
    [PalletTypeInUse] nvarchar(10) NOT NULL DEFAULT ('No'),
    [CheckDigitLengthForLocation] nvarchar(2) NOT NULL DEFAULT (''),
    CONSTRAINT [PK_FACILITY] PRIMARY KEY ([Facility])
);
GO
