CREATE TABLE [dbo].[gui]
(
    [InvoiceNo] nvarchar(10) NOT NULL,
    [Storerkey] nvarchar(15) NOT NULL,
    [ExternOrderKey] nvarchar(50) NOT NULL,
    [IndicatorFlag] nvarchar(1) NULL,
    [TotalSalesAmt] money NULL DEFAULT ((0)),
    [TotalTaxAmt] money NULL DEFAULT ((0)),
    [GUICheckNo] nvarchar(10) NULL,
    [PaymentDueDate] datetime NULL,
    [ATMBankCode] nvarchar(3) NULL DEFAULT (' '),
    [ATMBankAcc] nvarchar(20) NULL DEFAULT (' '),
    [TTBankCode] nvarchar(3) NULL DEFAULT (' '),
    [TTBankAcc] nvarchar(20) NULL DEFAULT (' '),
    [SalesOrg] nvarchar(4) NULL DEFAULT (' '),
    [Division] nvarchar(2) NULL DEFAULT (' '),
    [BillDate] datetime NULL DEFAULT (' '),
    [PayerCode] nvarchar(10) NULL DEFAULT (' '),
    [TaxID] nvarchar(10) NULL DEFAULT (' '),
    [BillingNo] nvarchar(10) NULL DEFAULT (' '),
    [DivisionName] nvarchar(20) NULL DEFAULT (' '),
    [BillToKey] nvarchar(15) NULL DEFAULT (' '),
    [BillToName] nvarchar(80) NULL DEFAULT (' '),
    [BillToAddr1] nvarchar(45) NULL DEFAULT (' '),
    [BillToAddr2] nvarchar(45) NULL DEFAULT (' '),
    [BillToTel] nvarchar(18) NULL DEFAULT (' '),
    [ShipToKey] nvarchar(15) NULL DEFAULT (' '),
    [ShipToName] nvarchar(80) NULL DEFAULT (' '),
    [ShipToAddr1] nvarchar(45) NULL DEFAULT (' '),
    [ShipToAddr2] nvarchar(45) NULL DEFAULT (' '),
    [ShipToTel] nvarchar(18) NULL DEFAULT (' '),
    [PaymentTerm] nvarchar(10) NULL DEFAULT (' '),
    [SalesRep] nvarchar(10) NULL DEFAULT (' '),
    [SalesRepName] nvarchar(45) NULL DEFAULT (' '),
    [CustServTel] nvarchar(18) NULL DEFAULT (' '),
    [CustPONo] nvarchar(20) NULL DEFAULT (' '),
    [NoofCopy] nvarchar(1) NULL DEFAULT (' '),
    [TotalQty] nvarchar(12) NULL DEFAULT (' '),
    [Notes] nvarchar(60) NULL DEFAULT (' '),
    [BillToName2] nvarchar(80) NULL DEFAULT (' '),
    [ShipToName2] nvarchar(80) NULL DEFAULT (' '),
    [DONumber] nvarchar(10) NULL DEFAULT (' '),
    [Status] nvarchar(1) NULL DEFAULT (' '),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [ArchiveCop] nvarchar(1) NULL,
    [Remarks] nvarchar(20) NULL DEFAULT (' '),
    [TotDiscAmount] money NULL DEFAULT ((0)),
    [UserDefine01] nvarchar(80) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(80) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(80) NULL DEFAULT (' '),
    [PrintFlag] nvarchar(1) NULL DEFAULT ('N'),
    [UserDefine04] nvarchar(80) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(80) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(80) NULL DEFAULT (' '),
    [UserDefine09] nvarchar(80) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(80) NULL DEFAULT (' '),
    [SalesArea] nvarchar(20) NULL DEFAULT (' '),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    CONSTRAINT [PK_GUI_InvoiceNo] PRIMARY KEY ([InvoiceNo], [Storerkey], [ExternOrderKey])
);
GO

CREATE INDEX [IX_GUI_ExternOrderkey] ON [dbo].[gui] ([ExternOrderKey], [Storerkey]);
GO