CREATE TABLE [dbo].[hostinterface]
(
    [hikey] nvarchar(10) NOT NULL,
    [hiprocess] nvarchar(20) NOT NULL,
    [hidescrip] nvarchar(45) NOT NULL DEFAULT (' '),
    [hifile1] nvarchar(80) NOT NULL DEFAULT (' '),
    [hifile2] nvarchar(80) NOT NULL DEFAULT (' '),
    [hifile3] nvarchar(80) NOT NULL DEFAULT (' '),
    [hifile4] nvarchar(80) NOT NULL DEFAULT (' '),
    [hifile5] nvarchar(80) NOT NULL DEFAULT (' '),
    [hifile6] nvarchar(80) NOT NULL DEFAULT (' '),
    [hifile1type] nvarchar(15) NOT NULL DEFAULT (' '),
    [hifile2type] nvarchar(15) NOT NULL DEFAULT (' '),
    [hifile3type] nvarchar(15) NOT NULL DEFAULT (' '),
    [hifile4type] nvarchar(15) NOT NULL DEFAULT (' '),
    [hifile5type] nvarchar(15) NOT NULL DEFAULT (' '),
    [hifile6type] nvarchar(15) NOT NULL DEFAULT (' '),
    [hilogfile] nvarchar(80) NOT NULL DEFAULT (' '),
    [hidopost] nvarchar(1) NOT NULL DEFAULT ('Y'),
    [hiusetimer] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hitimerinterval] int NOT NULL DEFAULT ((0)),
    [hiimpexp] nvarchar(10) NOT NULL DEFAULT ('I'),
    [hidirectdwimport] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hidefaultstorer] nvarchar(10) NOT NULL DEFAULT (' '),
    [hierasefiles] nvarchar(1) NOT NULL DEFAULT ('Y'),
    [hirevheader] nvarchar(45) NULL,
    [hirevdetail] nvarchar(45) NULL,
    [hirevsubdetail] nvarchar(45) NULL,
    [hiheader] nvarchar(45) NULL,
    [hidetail] nvarchar(45) NULL,
    [hisubdetail] nvarchar(45) NULL,
    [hirevother1] nvarchar(45) NULL,
    [hirevother2] nvarchar(45) NULL,
    [hirevother3] nvarchar(45) NULL,
    [hiother1] nvarchar(45) NULL,
    [hiother2] nvarchar(45) NULL,
    [hiother3] nvarchar(45) NULL,
    [hipreruncommand] nvarchar(75) NULL,
    [hipostruncommand] nvarchar(75) NULL,
    [hiprintdoc1] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hiprintdoc2] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hiprintdoc3] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hiprintdoc4] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hiprintdoc5] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hiprintdoc6] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hiprinter1] nvarchar(75) NOT NULL DEFAULT (' '),
    [hiprinter2] nvarchar(75) NOT NULL DEFAULT (' '),
    [hiprinter3] nvarchar(75) NOT NULL DEFAULT (' '),
    [hiprinter4] nvarchar(75) NOT NULL DEFAULT (' '),
    [hiprinter5] nvarchar(75) NOT NULL DEFAULT (' '),
    [hiprinter6] nvarchar(75) NOT NULL DEFAULT (' '),
    [Autocreatepalheader] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hiAutoShipPallet] nvarchar(1) NOT NULL DEFAULT ('N'),
    [Autocreatectrheader] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hiAutoShipContainer] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hidoOP] nvarchar(1) NOT NULL DEFAULT ('N'),
    [hiOPKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [HiAddSku] nvarchar(1) NOT NULL DEFAULT ('N'),
    [HiAddStorer] nvarchar(1) NOT NULL DEFAULT ('N'),
    CONSTRAINT [PKHOSTINTERFACE] PRIMARY KEY ([hikey])
);
GO
