CREATE TABLE [dbo].[houseairwaybill]
(
    [HAWBKEY] nvarchar(15) NOT NULL,
    [MAWBKEY] nvarchar(15) NOT NULL DEFAULT (' '),
    [ConsigneeKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [C_contact1] nvarchar(30) NULL,
    [C_Contact2] nvarchar(30) NULL,
    [C_Company] nvarchar(30) NULL,
    [C_Address1] nvarchar(30) NULL,
    [C_Address2] nvarchar(30) NULL,
    [C_Address3] nvarchar(30) NULL,
    [C_Address4] nvarchar(30) NULL,
    [C_City] nvarchar(30) NULL,
    [C_State] nvarchar(2) NULL,
    [C_Zip] nvarchar(18) NULL,
    [C_Country] nvarchar(30) NULL,
    [C_ISOCntryCode] nvarchar(10) NULL,
    [C_Phone1] nvarchar(18) NULL,
    [C_Phone2] nvarchar(18) NULL,
    [C_Fax1] nvarchar(18) NULL,
    [C_Fax2] nvarchar(18) NULL,
    [ShipperKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [S_contact1] nvarchar(30) NULL,
    [S_Contact2] nvarchar(30) NULL,
    [S_Company] nvarchar(30) NULL,
    [S_Address1] nvarchar(30) NULL,
    [S_Address2] nvarchar(30) NULL,
    [S_Address3] nvarchar(30) NULL,
    [S_Address4] nvarchar(30) NULL,
    [S_City] nvarchar(30) NULL,
    [S_State] nvarchar(2) NULL,
    [S_Zip] nvarchar(18) NULL,
    [S_Country] nvarchar(30) NULL,
    [S_ISOCntryCode] nvarchar(10) NULL,
    [S_Phone1] nvarchar(18) NULL,
    [S_Phone2] nvarchar(18) NULL,
    [S_Fax1] nvarchar(18) NULL,
    [S_Fax2] nvarchar(18) NULL,
    [AgentKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [A_contact1] nvarchar(30) NULL,
    [A_Contact2] nvarchar(30) NULL,
    [A_Company] nvarchar(30) NULL,
    [A_Address1] nvarchar(30) NULL,
    [A_Address2] nvarchar(30) NULL,
    [A_Address3] nvarchar(30) NULL,
    [A_Address4] nvarchar(30) NULL,
    [A_City] nvarchar(30) NULL,
    [A_State] nvarchar(2) NULL,
    [A_Zip] nvarchar(18) NULL,
    [A_Country] nvarchar(30) NULL,
    [A_ISOCntryCode] nvarchar(10) NULL,
    [A_Phone1] nvarchar(18) NULL,
    [A_Phone2] nvarchar(18) NULL,
    [A_Fax1] nvarchar(18) NULL,
    [A_Fax2] nvarchar(18) NULL,
    [AccountingInfo] nvarchar(4000) NULL,
    [Currency] nvarchar(10) NULL DEFAULT ('USD'),
    [WtValPPD] nvarchar(10) NULL DEFAULT (' '),
    [WtValCol] nvarchar(10) NULL DEFAULT (' '),
    [OtherPPD] nvarchar(10) NULL DEFAULT (' '),
    [OtherCol] nvarchar(10) NULL DEFAULT (' '),
    [DeclaredValueForCustoms] nvarchar(30) NULL DEFAULT ('As Per Invoice'),
    [PlaceOfLoading] nvarchar(18) NULL DEFAULT (' '),
    [RouteTO01] nvarchar(18) NULL DEFAULT (' '),
    [RouteTO02] nvarchar(18) NULL DEFAULT (' '),
    [RouteTO03] nvarchar(18) NULL DEFAULT (' '),
    [Carrier01] nvarchar(18) NULL DEFAULT (' '),
    [Carrier02] nvarchar(18) NULL DEFAULT (' '),
    [Carrier03] nvarchar(18) NULL DEFAULT (' '),
    [AirportOfDestination] nvarchar(18) NULL DEFAULT (' '),
    [FlightDate01] nvarchar(18) NOT NULL DEFAULT (' '),
    [FlightDate02] nvarchar(18) NOT NULL DEFAULT (' '),
    [AmountOfInsurance] nvarchar(18) NOT NULL DEFAULT (' '),
    [HandlingInfo] nvarchar(4000) NULL,
    [ChargeDesc01] nvarchar(10) NOT NULL DEFAULT (' '),
    [PPDCharge01] float NOT NULL DEFAULT ((0)),
    [COLLCharge01] float NOT NULL DEFAULT ((0)),
    [ChargeDesc02] nvarchar(10) NOT NULL DEFAULT (' '),
    [PPDCharge02] float NOT NULL DEFAULT ((0)),
    [COLLCharge02] float NOT NULL DEFAULT ((0)),
    [ChargeDesc03] nvarchar(10) NOT NULL DEFAULT (' '),
    [PPDCharge03] float NOT NULL DEFAULT ((0)),
    [COLLCharge03] float NOT NULL DEFAULT ((0)),
    [ChargeDesc04] nvarchar(10) NOT NULL DEFAULT (' '),
    [PPDCharge04] float NOT NULL DEFAULT ((0)),
    [COLLCharge04] float NOT NULL DEFAULT ((0)),
    [ChargeDesc05] nvarchar(10) NOT NULL DEFAULT (' '),
    [PPDCharge05] float NOT NULL DEFAULT ((0)),
    [COLLCharge05] float NOT NULL DEFAULT ((0)),
    [ChargeDesc06] nvarchar(10) NOT NULL DEFAULT (' '),
    [PPDCharge06] float NOT NULL DEFAULT ((0)),
    [COLLCharge06] float NOT NULL DEFAULT ((0)),
    [PPDChargeTotal] float NOT NULL DEFAULT ((0)),
    [CollChargeTotal] float NOT NULL DEFAULT ((0)),
    [TotalCharge] float NOT NULL DEFAULT ((0)),
    [TotalPkgReceived] float NOT NULL DEFAULT ((0)),
    [TotalGrossWgt] float NOT NULL DEFAULT ((0)),
    [AlternateCurrency] nvarchar(10) NOT NULL DEFAULT ('USD'),
    [ConversionRate] float NOT NULL DEFAULT ((1)),
    [Notes] nvarchar(4000) NULL,
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [TimeStamp] timestamp NULL,
    CONSTRAINT [PKHouseAirWayBill] PRIMARY KEY ([HAWBKEY]),
    CONSTRAINT [CK_HAWB_Status] CHECK (rtrim([Status]) like '[0-9]')
);
GO
