CREATE TABLE [dbo].[inventoryqcdetail]
(
    [QC_Key] nvarchar(10) NOT NULL,
    [QCLineNo] nvarchar(5) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL,
    [SKU] nvarchar(20) NOT NULL,
    [PackKey] nvarchar(10) NOT NULL,
    [UOM] nvarchar(10) NOT NULL,
    [OriginalQty] numeric(18, 0) NOT NULL DEFAULT ((0)),
    [Qty] numeric(18, 0) NOT NULL DEFAULT ((0)),
    [FromLoc] nvarchar(10) NOT NULL,
    [FromLot] nvarchar(10) NOT NULL,
    [FromID] nvarchar(18) NOT NULL,
    [ToQty] numeric(18, 0) NOT NULL DEFAULT ((0)),
    [ToID] nvarchar(18) NOT NULL DEFAULT (' '),
    [ToLoc] nvarchar(10) NOT NULL DEFAULT (' '),
    [Reason] nvarchar(10) NOT NULL DEFAULT (' '),
    [Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [FinalizeFlag] nvarchar(1) NULL DEFAULT ('N'),
    [Channel] nvarchar(20) NULL DEFAULT (''),
    [Channel_ID] bigint NULL DEFAULT ((0)),
    [FromPalletType] nvarchar(10) NOT NULL DEFAULT (''),
    [ToPalletType] nvarchar(10) NOT NULL DEFAULT (''),
    CONSTRAINT [PK_InventoryQCDetail] PRIMARY KEY ([QC_Key], [QCLineNo]),
    CONSTRAINT [FK_InventoryQCDetail_SKU_01] FOREIGN KEY ([StorerKey], [SKU]) REFERENCES [dbo].[SKU] ([StorerKey], [Sku])
);
GO
