CREATE TABLE [dbo].[itrn]
(
    [ItrnKey] nvarchar(10) NOT NULL,
    [ItrnSysId] int NULL,
    [TranType] nvarchar(10) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL,
    [Sku] nvarchar(20) NOT NULL,
    [Lot] nvarchar(10) NOT NULL,
    [FromLoc] nvarchar(10) NOT NULL,
    [FromID] nvarchar(18) NOT NULL,
    [ToLoc] nvarchar(10) NOT NULL,
    [ToID] nvarchar(18) NOT NULL,
    [SourceKey] nvarchar(20) NULL,
    [SourceType] nvarchar(30) NULL,
    [Status] nvarchar(10) NULL,
    [LOTTABLE01] nvarchar(18) NOT NULL DEFAULT (' '),
    [LOTTABLE02] nvarchar(18) NOT NULL DEFAULT (' '),
    [LOTTABLE03] nvarchar(18) NOT NULL DEFAULT (' '),
    [LOTTABLE04] datetime NULL,
    [LOTTABLE05] datetime NULL,
    [CaseCnt] int NOT NULL DEFAULT ((0)),
    [InnerPack] int NOT NULL DEFAULT ((0)),
    [Qty] int NOT NULL DEFAULT ((0)),
    [Pallet] int NOT NULL DEFAULT ((0)),
    [Cube] float NOT NULL DEFAULT ((0)),
    [GrossWgt] float NOT NULL DEFAULT ((0)),
    [NetWgt] float NOT NULL DEFAULT ((0)),
    [OtherUnit1] float NOT NULL DEFAULT ((0)),
    [OtherUnit2] float NOT NULL DEFAULT ((0)),
    [PackKey] nvarchar(10) NULL,
    [UOM] nvarchar(10) NULL,
    [UOMCalc] int NULL,
    [UOMQty] int NULL,
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Lottable06] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable07] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable08] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable09] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable10] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable11] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable12] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [MoveRefKey] nvarchar(10) NULL DEFAULT (''),
    [Channel] nvarchar(20) NULL DEFAULT (''),
    [Channel_ID] bigint NULL DEFAULT ((0)),
    [PalletType] nvarchar(10) NOT NULL DEFAULT (''),
    CONSTRAINT [PKItrn] PRIMARY KEY ([ItrnKey])
);
GO

CREATE INDEX [IX_ITRN_EffectiveDate] ON [dbo].[itrn] ([TranType], [EffectiveDate]);
GO
CREATE INDEX [IX_ITRN_SourceKey] ON [dbo].[itrn] ([SourceKey], [SourceType]);
GO