CREATE TABLE [dbo].[itrnserialno]
(
    [ITrnSerialNoKey] bigint IDENTITY(1,1) NOT NULL,
    [ITrnKey] nvarchar(10) NOT NULL,
    [TranType] nvarchar(10) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL,
    [SKU] nvarchar(20) NOT NULL,
    [SerialNo] nvarchar(30) NOT NULL,
    [QTY] int NOT NULL,
    [SourceKey] nvarchar(20) NOT NULL,
    [SourceType] nvarchar(30) NOT NULL,
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [TrafficCop] nchar(1) NULL,
    [ArchiveCop] nchar(1) NULL,
    [Lot] nvarchar(20) NOT NULL DEFAULT (' '),
    [Loc] nvarchar(20) NOT NULL DEFAULT (' '),
    [ID] nvarchar(36) NOT NULL DEFAULT (' '),
    [LOTTABLE01] nvarchar(36) NOT NULL DEFAULT (' '),
    [LOTTABLE02] nvarchar(36) NOT NULL DEFAULT (' '),
    [LOTTABLE03] nvarchar(36) NOT NULL DEFAULT (' '),
    [LOTTABLE04] datetime NULL,
    [LOTTABLE05] datetime NULL,
    [Lottable06] nvarchar(60) NOT NULL DEFAULT (' '),
    [Lottable07] nvarchar(60) NOT NULL DEFAULT (' '),
    [Lottable08] nvarchar(60) NOT NULL DEFAULT (' '),
    [Lottable09] nvarchar(60) NOT NULL DEFAULT (' '),
    [Lottable10] nvarchar(60) NOT NULL DEFAULT (' '),
    [Lottable11] nvarchar(60) NOT NULL DEFAULT (' '),
    [Lottable12] nvarchar(60) NOT NULL DEFAULT (' '),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [Channel] nvarchar(40) NULL,
    [Channel_ID] bigint NULL,
    [UCCNo] nvarchar(40) NOT NULL DEFAULT (' '),
    CONSTRAINT [PK_ITrnSerialNo] PRIMARY KEY ([ITrnSerialNoKey])
);
GO
