CREATE TABLE [dbo].[kit]
(
    [KITKey] nvarchar(10) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [ToStorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Type] nvarchar(12) NOT NULL DEFAULT (' '),
    [OpenQty] int NOT NULL DEFAULT ((0)),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [EffectiveDate] datetime NULL DEFAULT (getdate()),
    [ReasonCode] nvarchar(10) NULL,
    [CustomerRefNo] nvarchar(20) NULL,
    [Remarks] nvarchar(200) NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Timestamp] timestamp NOT NULL,
    [GenerateHOCharges] nvarchar(10) NULL,
    [GenerateIS_HiCharges] nvarchar(10) NULL,
    [Facility] nvarchar(5) NULL DEFAULT ('F1'),
    [USRDEF1] nvarchar(18) NULL DEFAULT (' '),
    [USRDEF2] nvarchar(18) NULL DEFAULT (' '),
    [USRDEF3] nvarchar(18) NULL DEFAULT (' '),
    [ActionFlag] nvarchar(1) NULL DEFAULT ('0'),
    [ExternKitKey] nvarchar(20) NULL DEFAULT (' '),
    [USRDEF4] nvarchar(30) NULL DEFAULT (''),
    [USRDEF5] nvarchar(30) NULL DEFAULT (''),
    [USRDEF6] datetime NULL,
    [USRDEF7] datetime NULL,
    [USRDEF8] nvarchar(30) NULL DEFAULT (''),
    [USRDEF9] nvarchar(30) NULL DEFAULT (''),
    [USRDEF10] nvarchar(30) NULL DEFAULT (' '),
    [USRDEF11] nvarchar(30) NULL DEFAULT (' '),
    [USRDEF12] nvarchar(30) NULL DEFAULT (' '),
    [USRDEF13] nvarchar(30) NULL DEFAULT (' '),
    [USRDEF14] datetime NULL,
    [USRDEF15] datetime NULL,
    [ExternStatus] nvarchar(30) NULL DEFAULT (' '),
    CONSTRAINT [PK_KIT] PRIMARY KEY ([KITKey])
);
GO
