CREATE TABLE [dbo].[kitdetail]
(
    [KITKey] nvarchar(10) NOT NULL,
    [KITLineNumber] nvarchar(5) NOT NULL,
    [Type] nvarchar(5) NOT NULL DEFAULT ('F'),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Lot] nvarchar(10) NOT NULL DEFAULT (' '),
    [Loc] nvarchar(10) NOT NULL DEFAULT (' '),
    [Id] nvarchar(18) NOT NULL DEFAULT (' '),
    [ExpectedQty] int NOT NULL DEFAULT ((0)),
    [Qty] int NOT NULL DEFAULT ((0)),
    [PackKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [UOM] nvarchar(10) NOT NULL DEFAULT ('EA'),
    [LOTTABLE01] nvarchar(18) NULL DEFAULT (' '),
    [LOTTABLE02] nvarchar(18) NULL DEFAULT (' '),
    [LOTTABLE03] nvarchar(18) NULL DEFAULT (' '),
    [LOTTABLE04] datetime NULL,
    [LOTTABLE05] datetime NULL,
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [EffectiveDate] datetime NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Timestamp] timestamp NOT NULL,
    [ExternKitKey] nvarchar(20) NULL DEFAULT (' '),
    [ExternLineNo] nvarchar(10) NULL DEFAULT (' '),
    [Lottable06] nvarchar(30) NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [Channel] nvarchar(20) NOT NULL DEFAULT (''),
    [Channel_ID] bigint NOT NULL DEFAULT ((0)),
    [PalletType] nvarchar(10) NOT NULL DEFAULT (''),
    CONSTRAINT [PK_KITDETAIL] PRIMARY KEY ([KITKey], [KITLineNumber], [Type])
);
GO
