CREATE TABLE [dbo].[loadplan]
(
    [LoadKey] nvarchar(10) NOT NULL,
    [CaseCnt] int NULL DEFAULT ((0)),
    [PalletCnt] int NULL DEFAULT ((0)),
    [Weight] float NULL DEFAULT ((0)),
    [Cube] float NULL DEFAULT ((0)),
    [CustCnt] int NULL DEFAULT ((0)),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [TruckSize] nvarchar(10) NULL,
    [SuperOrderFlag] nvarchar(1) NULL,
    [SectionKey] nvarchar(3) NULL,
    [CarrierKey] nvarchar(15) NULL,
    [Route] nvarchar(10) NULL,
    [TrfRoom] nvarchar(10) NULL,
    [DummyRoute] nvarchar(1) NULL,
    [MBOLKey] nvarchar(10) NULL,
    [OrderCnt] int NULL DEFAULT ((0)),
    [facility] nvarchar(5) NULL DEFAULT ('F1'),
    [PROCESSFLAG] nvarchar(1) NULL DEFAULT ('N'),
    [Return_Weight] float NULL DEFAULT ((0)),
    [Return_Cube] float NULL DEFAULT ((0)),
    [Vehicle_Type] nvarchar(20) NULL,
    [Driver] nvarchar(45) NULL,
    [Delivery_Zone] nvarchar(10) NULL,
    [Truck_Type] nvarchar(10) NULL,
    [Load_Userdef1] nvarchar(4000) NULL,
    [Load_Userdef2] nvarchar(4000) NULL,
    [weightlimit] float NULL DEFAULT ((0.0)),
    [volumelimit] float NULL DEFAULT ((0.0)),
    [AllocatedCube] float NULL DEFAULT ((0.0)),
    [AllocatedWeight] float NULL DEFAULT ((0.0)),
    [AllocatedCaseCnt] int NULL DEFAULT ((0)),
    [AllocatedPalletCnt] int NULL DEFAULT ((0)),
    [AllocatedOrderCnt] int NULL DEFAULT ((0)),
    [AllocatedCustCnt] int NULL DEFAULT ((0)),
    [lpuserdefdate01] datetime NULL,
    [FinalizeFlag] nvarchar(1) NULL DEFAULT ('N'),
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [ExternLoadKey] nvarchar(30) NULL DEFAULT (' '),
    [CtnTyp1] nvarchar(10) NULL DEFAULT ((0)),
    [CtnTyp2] nvarchar(10) NULL DEFAULT ((0)),
    [CtnTyp3] nvarchar(10) NULL DEFAULT ((0)),
    [CtnTyp4] nvarchar(10) NULL DEFAULT ((0)),
    [CtnTyp5] nvarchar(10) NULL DEFAULT ((0)),
    [CtnCnt1] int NULL DEFAULT ((0)),
    [CtnCnt2] int NULL DEFAULT ((0)),
    [CtnCnt3] int NULL DEFAULT ((0)),
    [CtnCnt4] int NULL DEFAULT ((0)),
    [CtnCnt5] int NULL DEFAULT ((0)),
    [TotCtnWeight] float NULL DEFAULT ((0)),
    [TotCtnCube] float NULL DEFAULT ((0)),
    [CartonGroup] nvarchar(10) NULL DEFAULT (''),
    [Priority] nvarchar(10) NOT NULL DEFAULT ('9'),
    [DispatchPalletPickMethod] nvarchar(10) NOT NULL DEFAULT ('1'),
    [DispatchCasePickMethod] nvarchar(10) NOT NULL DEFAULT ('1'),
    [DispatchPiecePickMethod] nvarchar(10) NOT NULL DEFAULT ('1'),
    [LoadPickMethod] nvarchar(10) NOT NULL DEFAULT (''),
    [MBOLGroupMethod] nvarchar(10) NULL,
    [DefaultStrategykey] nvarchar(1) NULL,
    [BookingNo] int NULL,
    [OTM_DispatchDate] datetime NOT NULL DEFAULT (''),
    [PickupDate] datetime NULL,
    CONSTRAINT [PK_LoadPlan] PRIMARY KEY ([LoadKey]),
    CONSTRAINT [CK_LoadPlan_Loadkey_Numeric] CHECK (isnumeric([Loadkey])=(1))
);
GO

CREATE INDEX [IX_LoadPlan_UserDefine10] ON [dbo].[loadplan] ([UserDefine10], [LoadKey]);
GO