CREATE TABLE [dbo].[mailq]
(
    [Qid] int IDENTITY(1,1) NOT NULL,
    [mailitem_id] int NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL,
    [UniqueKey] nvarchar(100) NOT NULL,
    [UniqueKeyName] nvarchar(1024) NOT NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] sysname NOT NULL DEFAULT (suser_sname()),
    [AddObj] nvarchar(128) NOT NULL DEFAULT (isnull(object_name(@@procid),'')),
    [SendTo] varchar(4000) NULL,
    [Cc] varchar(4000) NULL,
    [Bcc] varchar(4000) NULL,
    [Subject] nvarchar(255) NULL,
    [Header] nvarchar(2000) NOT NULL,
    [Footer] nvarchar(2000) NOT NULL,
    [THColor] char(6) NOT NULL,
    [R01Name] nvarchar(128) NOT NULL,
    [R01] nvarchar(1000) NOT NULL,
    [R02Name] nvarchar(128) NOT NULL,
    [R02] nvarchar(1000) NOT NULL,
    [R03Name] nvarchar(128) NOT NULL,
    [R03] nvarchar(1000) NOT NULL,
    [R04Name] nvarchar(128) NOT NULL,
    [R04] nvarchar(1000) NOT NULL,
    [R05Name] nvarchar(128) NOT NULL,
    [R05] nvarchar(1000) NOT NULL,
    [R06Name] nvarchar(128) NOT NULL,
    [R06] nvarchar(1000) NOT NULL,
    [R07Name] nvarchar(128) NOT NULL,
    [R07] nvarchar(1000) NOT NULL,
    [R08Name] nvarchar(128) NOT NULL,
    [R08] nvarchar(1000) NOT NULL,
    [R09Name] nvarchar(128) NOT NULL,
    [R09] nvarchar(1000) NOT NULL,
    [R10Name] nvarchar(128) NOT NULL,
    [R10] nvarchar(1000) NOT NULL,
    [R11Name] nvarchar(128) NOT NULL,
    [R11] nvarchar(1000) NOT NULL,
    [R12Name] nvarchar(128) NOT NULL,
    [R12] nvarchar(1000) NOT NULL,
    [R13Name] nvarchar(128) NOT NULL,
    [R13] nvarchar(1000) NOT NULL,
    [R14Name] nvarchar(128) NOT NULL,
    [R14] nvarchar(1000) NOT NULL,
    [R15Name] nvarchar(128) NOT NULL,
    [R15] nvarchar(1000) NOT NULL,
    [C01Align] char(1) NOT NULL,
    [C01Name] nvarchar(128) NOT NULL,
    [C02Align] char(1) NOT NULL,
    [C02Name] nvarchar(128) NOT NULL,
    [C03Align] char(1) NOT NULL,
    [C03Name] nvarchar(128) NOT NULL,
    [C04Align] char(1) NOT NULL,
    [C04Name] nvarchar(128) NOT NULL,
    [C05Align] char(1) NOT NULL,
    [C05Name] nvarchar(128) NOT NULL,
    [C06Align] char(1) NOT NULL,
    [C06Name] nvarchar(128) NOT NULL,
    [C07Align] char(1) NOT NULL,
    [C07Name] nvarchar(128) NOT NULL,
    [C08Align] char(1) NOT NULL,
    [C08Name] nvarchar(128) NOT NULL,
    [C09Align] char(1) NOT NULL,
    [C09Name] nvarchar(128) NOT NULL,
    [C10Align] char(1) NOT NULL,
    [C10Name] nvarchar(128) NOT NULL,
    [C11Align] char(1) NOT NULL,
    [C11Name] nvarchar(128) NOT NULL,
    [C12Align] char(1) NOT NULL,
    [C12Name] nvarchar(128) NOT NULL,
    [C13Align] char(1) NOT NULL,
    [C13Name] nvarchar(128) NOT NULL,
    [C14Align] char(1) NOT NULL,
    [C14Name] nvarchar(128) NOT NULL,
    [C15Align] char(1) NOT NULL,
    [C15Name] nvarchar(128) NOT NULL,
    [C01Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C02Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C03Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C04Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C05Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C06Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C07Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C08Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C09Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C10Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C11Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C12Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C13Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C14Agg] nvarchar(25) NOT NULL DEFAULT (''),
    [C15Agg] nvarchar(25) NOT NULL DEFAULT (''),
    CONSTRAINT [DBMail_mail_id_MustBeUnique] PRIMARY KEY ([Qid]),
    CONSTRAINT [MailQ_C01AggMusthaveValidFunc] CHECK ([C01Agg]='' OR [C01Agg]='VARP' OR [C01Agg]='VAR' OR [C01Agg]='STRING_AGG' OR [C01Agg]='STDEVP' OR [C01Agg]='STDEV' OR [C01Agg]='MIN' OR [C01Agg]='MAX' OR [C01Agg]='GROUPING_ID' OR [C01Agg]='GROUPING' OR [C01Agg]='COUNT_BIG' OR [C01Agg]='COUNT' OR [C01Agg]='CHECKSUM_AGG' OR [C01Agg]='SUM' OR [C01Agg]='AVG' OR [C01Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C02AggMusthaveValidFunc] CHECK ([C02Agg]='' OR [C02Agg]='VARP' OR [C02Agg]='VAR' OR [C02Agg]='STRING_AGG' OR [C02Agg]='STDEVP' OR [C02Agg]='STDEV' OR [C02Agg]='MIN' OR [C02Agg]='MAX' OR [C02Agg]='GROUPING_ID' OR [C02Agg]='GROUPING' OR [C02Agg]='COUNT_BIG' OR [C02Agg]='COUNT' OR [C02Agg]='CHECKSUM_AGG' OR [C02Agg]='SUM' OR [C02Agg]='AVG' OR [C02Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C03AggMusthaveValidFunc] CHECK ([C03Agg]='' OR [C03Agg]='VARP' OR [C03Agg]='VAR' OR [C03Agg]='STRING_AGG' OR [C03Agg]='STDEVP' OR [C03Agg]='STDEV' OR [C03Agg]='MIN' OR [C03Agg]='MAX' OR [C03Agg]='GROUPING_ID' OR [C03Agg]='GROUPING' OR [C03Agg]='COUNT_BIG' OR [C03Agg]='COUNT' OR [C03Agg]='CHECKSUM_AGG' OR [C03Agg]='SUM' OR [C03Agg]='AVG' OR [C03Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C04AggMusthaveValidFunc] CHECK ([C04Agg]='' OR [C04Agg]='VARP' OR [C04Agg]='VAR' OR [C04Agg]='STRING_AGG' OR [C04Agg]='STDEVP' OR [C04Agg]='STDEV' OR [C04Agg]='MIN' OR [C04Agg]='MAX' OR [C04Agg]='GROUPING_ID' OR [C04Agg]='GROUPING' OR [C04Agg]='COUNT_BIG' OR [C04Agg]='COUNT' OR [C04Agg]='CHECKSUM_AGG' OR [C04Agg]='SUM' OR [C04Agg]='AVG' OR [C04Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C05AggMusthaveValidFunc] CHECK ([C05Agg]='' OR [C05Agg]='VARP' OR [C05Agg]='VAR' OR [C05Agg]='STRING_AGG' OR [C05Agg]='STDEVP' OR [C05Agg]='STDEV' OR [C05Agg]='MIN' OR [C05Agg]='MAX' OR [C05Agg]='GROUPING_ID' OR [C05Agg]='GROUPING' OR [C05Agg]='COUNT_BIG' OR [C05Agg]='COUNT' OR [C05Agg]='CHECKSUM_AGG' OR [C05Agg]='SUM' OR [C05Agg]='AVG' OR [C05Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C06AggMusthaveValidFunc] CHECK ([C06Agg]='' OR [C06Agg]='VARP' OR [C06Agg]='VAR' OR [C06Agg]='STRING_AGG' OR [C06Agg]='STDEVP' OR [C06Agg]='STDEV' OR [C06Agg]='MIN' OR [C06Agg]='MAX' OR [C06Agg]='GROUPING_ID' OR [C06Agg]='GROUPING' OR [C06Agg]='COUNT_BIG' OR [C06Agg]='COUNT' OR [C06Agg]='CHECKSUM_AGG' OR [C06Agg]='SUM' OR [C06Agg]='AVG' OR [C06Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C07AggMusthaveValidFunc] CHECK ([C07Agg]='' OR [C07Agg]='VARP' OR [C07Agg]='VAR' OR [C07Agg]='STRING_AGG' OR [C07Agg]='STDEVP' OR [C07Agg]='STDEV' OR [C07Agg]='MIN' OR [C07Agg]='MAX' OR [C07Agg]='GROUPING_ID' OR [C07Agg]='GROUPING' OR [C07Agg]='COUNT_BIG' OR [C07Agg]='COUNT' OR [C07Agg]='CHECKSUM_AGG' OR [C07Agg]='SUM' OR [C07Agg]='AVG' OR [C07Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C08AggMusthaveValidFunc] CHECK ([C08Agg]='' OR [C08Agg]='VARP' OR [C08Agg]='VAR' OR [C08Agg]='STRING_AGG' OR [C08Agg]='STDEVP' OR [C08Agg]='STDEV' OR [C08Agg]='MIN' OR [C08Agg]='MAX' OR [C08Agg]='GROUPING_ID' OR [C08Agg]='GROUPING' OR [C08Agg]='COUNT_BIG' OR [C08Agg]='COUNT' OR [C08Agg]='CHECKSUM_AGG' OR [C08Agg]='SUM' OR [C08Agg]='AVG' OR [C08Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C09AggMusthaveValidFunc] CHECK ([C09Agg]='' OR [C09Agg]='VARP' OR [C09Agg]='VAR' OR [C09Agg]='STRING_AGG' OR [C09Agg]='STDEVP' OR [C09Agg]='STDEV' OR [C09Agg]='MIN' OR [C09Agg]='MAX' OR [C09Agg]='GROUPING_ID' OR [C09Agg]='GROUPING' OR [C09Agg]='COUNT_BIG' OR [C09Agg]='COUNT' OR [C09Agg]='CHECKSUM_AGG' OR [C09Agg]='SUM' OR [C09Agg]='AVG' OR [C09Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C10AggMusthaveValidFunc] CHECK ([C10Agg]='' OR [C10Agg]='VARP' OR [C10Agg]='VAR' OR [C10Agg]='STRING_AGG' OR [C10Agg]='STDEVP' OR [C10Agg]='STDEV' OR [C10Agg]='MIN' OR [C10Agg]='MAX' OR [C10Agg]='GROUPING_ID' OR [C10Agg]='GROUPING' OR [C10Agg]='COUNT_BIG' OR [C10Agg]='COUNT' OR [C10Agg]='CHECKSUM_AGG' OR [C10Agg]='SUM' OR [C10Agg]='AVG' OR [C10Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C11AggMusthaveValidFunc] CHECK ([C11Agg]='' OR [C11Agg]='VARP' OR [C11Agg]='VAR' OR [C11Agg]='STRING_AGG' OR [C11Agg]='STDEVP' OR [C11Agg]='STDEV' OR [C11Agg]='MIN' OR [C11Agg]='MAX' OR [C11Agg]='GROUPING_ID' OR [C11Agg]='GROUPING' OR [C11Agg]='COUNT_BIG' OR [C11Agg]='COUNT' OR [C11Agg]='CHECKSUM_AGG' OR [C11Agg]='SUM' OR [C11Agg]='AVG' OR [C11Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C12AggMusthaveValidFunc] CHECK ([C12Agg]='' OR [C12Agg]='VARP' OR [C12Agg]='VAR' OR [C12Agg]='STRING_AGG' OR [C12Agg]='STDEVP' OR [C12Agg]='STDEV' OR [C12Agg]='MIN' OR [C12Agg]='MAX' OR [C12Agg]='GROUPING_ID' OR [C12Agg]='GROUPING' OR [C12Agg]='COUNT_BIG' OR [C12Agg]='COUNT' OR [C12Agg]='CHECKSUM_AGG' OR [C12Agg]='SUM' OR [C12Agg]='AVG' OR [C12Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C13AggMusthaveValidFunc] CHECK ([C13Agg]='' OR [C13Agg]='VARP' OR [C13Agg]='VAR' OR [C13Agg]='STRING_AGG' OR [C13Agg]='STDEVP' OR [C13Agg]='STDEV' OR [C13Agg]='MIN' OR [C13Agg]='MAX' OR [C13Agg]='GROUPING_ID' OR [C13Agg]='GROUPING' OR [C13Agg]='COUNT_BIG' OR [C13Agg]='COUNT' OR [C13Agg]='CHECKSUM_AGG' OR [C13Agg]='SUM' OR [C13Agg]='AVG' OR [C13Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C14AggMusthaveValidFunc] CHECK ([C14Agg]='' OR [C14Agg]='VARP' OR [C14Agg]='VAR' OR [C14Agg]='STRING_AGG' OR [C14Agg]='STDEVP' OR [C14Agg]='STDEV' OR [C14Agg]='MIN' OR [C14Agg]='MAX' OR [C14Agg]='GROUPING_ID' OR [C14Agg]='GROUPING' OR [C14Agg]='COUNT_BIG' OR [C14Agg]='COUNT' OR [C14Agg]='CHECKSUM_AGG' OR [C14Agg]='SUM' OR [C14Agg]='AVG' OR [C14Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [MailQ_C15AggMusthaveValidFunc] CHECK ([C15Agg]='' OR [C15Agg]='VARP' OR [C15Agg]='VAR' OR [C15Agg]='STRING_AGG' OR [C15Agg]='STDEVP' OR [C15Agg]='STDEV' OR [C15Agg]='MIN' OR [C15Agg]='MAX' OR [C15Agg]='GROUPING_ID' OR [C15Agg]='GROUPING' OR [C15Agg]='COUNT_BIG' OR [C15Agg]='COUNT' OR [C15Agg]='CHECKSUM_AGG' OR [C15Agg]='SUM' OR [C15Agg]='AVG' OR [C15Agg]='APPROX_COUNT_DISTINCT'),
    CONSTRAINT [DBMail_OutMailMustHaveAtleastOneRecipient] CHECK (NOT ([SendTo] IS NULL AND [Cc] IS NULL AND [Bcc] IS NULL)),
    CONSTRAINT [DBMail_OutMailRecipientCannotBeEmpty] CHECK (((datalength(isnull([SendTo],''))+datalength(isnull([Cc],'')))+datalength(isnull([Bcc],'')))<>(0)),
    CONSTRAINT [DBMail_OutMailSubjectCannotBeEmpty] CHECK (datalength(isnull([subject],''))<>(0))
);
GO
