CREATE TABLE [dbo].[mailqsms]
(
    [Qid] int IDENTITY(1,1) NOT NULL,
    [mail_id] int NULL,
    [UniqueKey] nvarchar(15) NOT NULL DEFAULT (''),
    [UniqueKeyName] nvarchar(255) NOT NULL,
    [StorerKey] nvarchar(20) NOT NULL DEFAULT (''),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] sysname NOT NULL DEFAULT (suser_sname()),
    [AddSource] nvarchar(128) NOT NULL DEFAULT (isnull(object_name(@@procid),'')),
    [R01Name] nvarchar(128) NULL DEFAULT (''),
    [R01] nvarchar(1000) NOT NULL DEFAULT (''),
    [R02Name] nvarchar(128) NOT NULL DEFAULT (''),
    [R02] nvarchar(1000) NOT NULL DEFAULT (''),
    [R03Name] nvarchar(128) NOT NULL DEFAULT (''),
    [R03] nvarchar(1000) NOT NULL DEFAULT (''),
    [R04Name] nvarchar(128) NOT NULL DEFAULT (''),
    [R04] nvarchar(1000) NOT NULL DEFAULT (''),
    [R05Name] nvarchar(128) NOT NULL DEFAULT (''),
    [R05] nvarchar(1000) NOT NULL DEFAULT (''),
    [R06Name] nvarchar(128) NOT NULL DEFAULT (''),
    [R06] nvarchar(1000) NOT NULL DEFAULT (''),
    [R07Name] nvarchar(128) NOT NULL DEFAULT (''),
    [R07] nvarchar(1000) NOT NULL DEFAULT (''),
    [R08Name] nvarchar(128) NOT NULL DEFAULT (''),
    [R08] nvarchar(1000) NOT NULL DEFAULT (''),
    [R09Name] nvarchar(128) NOT NULL DEFAULT (''),
    [R09] nvarchar(1000) NOT NULL DEFAULT (''),
    [R10Name] nvarchar(128) NOT NULL DEFAULT (''),
    [R10] nvarchar(1000) NOT NULL DEFAULT (''),
    CONSTRAINT [MailQSMS_mail_id_MustBeUnique] PRIMARY KEY ([Qid]),
    CONSTRAINT [MailQSMS_OutMailUniqueKeyMustBeValid] CHECK ([UniqueKey]<>'')
);
GO
