CREATE TABLE [dbo].[mbol]
(
    [MbolKey] nvarchar(10) NOT NULL,
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [ExternMbolKey] nvarchar(60) NULL DEFAULT (' '),
    [OriginCountry] nvarchar(30) NOT NULL DEFAULT (' '),
    [DestinationCountry] nvarchar(30) NOT NULL DEFAULT (' '),
    [VesselQualifier] nvarchar(10) NOT NULL DEFAULT ('VM'),
    [Vessel] nvarchar(30) NOT NULL DEFAULT (' '),
    [PlaceOfLoadingQualifier] nvarchar(10) NOT NULL DEFAULT (' '),
    [PlaceOfLoading] nvarchar(30) NOT NULL DEFAULT (' '),
    [PlaceOfdischargeQualifier] nvarchar(10) NOT NULL DEFAULT (' '),
    [PlaceOfDischarge] nvarchar(30) NOT NULL DEFAULT (' '),
    [PlaceOfdeliveryQualifier] nvarchar(10) NOT NULL DEFAULT (' '),
    [PlaceOfdelivery] nvarchar(30) NOT NULL DEFAULT (' '),
    [TransMethod] nvarchar(30) NOT NULL DEFAULT (' '),
    [VoyageNumber] nvarchar(30) NOT NULL DEFAULT (' '),
    [DepartureDate] datetime NOT NULL DEFAULT (getdate()),
    [ArrivalDate] datetime NOT NULL DEFAULT (getdate()),
    [ArrivalDateFinalDestination] datetime NOT NULL DEFAULT (getdate()),
    [BookingReference] nvarchar(30) NOT NULL DEFAULT (' '),
    [OtherReference] nvarchar(30) NOT NULL DEFAULT (' '),
    [CarrierKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [Carrieragent] nvarchar(30) NOT NULL DEFAULT (' '),
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [TimeStamp] nvarchar(18) NULL,
    [DRIVERName] nvarchar(30) NULL,
    [LoadingDate] datetime NULL,
    [CustomerReceivedDate] datetime NULL,
    [Remarks] nvarchar(4000) NULL DEFAULT (' '),
    [TotalInvoiceValue] float NULL DEFAULT (' '),
    [GrossWeight] float NULL DEFAULT ((0)),
    [Capacity] float NULL DEFAULT ((0)),
    [InvoiceAmount] float NULL DEFAULT ((0)),
    [Weight] float NULL DEFAULT ((0)),
    [Cube] float NULL DEFAULT ((0)),
    [CustCnt] int NULL DEFAULT ((0)),
    [PalletCnt] int NULL DEFAULT ((0)),
    [CaseCnt] int NULL DEFAULT ((0)),
    [Facility] nvarchar(5) NULL DEFAULT ('F1'),
    [COD_Status] nvarchar(1) NULL DEFAULT ('0'),
    [DepotStatus] nvarchar(10) NULL DEFAULT ('0'),
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [ShipCounter] int NULL DEFAULT ((0)),
    [CTNTYPE] nvarchar(30) NULL,
    [NoofContainer] int NULL,
    [CTNTYPE1] nvarchar(30) NULL,
    [CTNTYPE2] nvarchar(30) NULL,
    [CTNTYPE3] nvarchar(30) NULL,
    [CTNTYPE4] nvarchar(30) NULL,
    [CTNTYPE5] nvarchar(30) NULL,
    [CTNTYPE6] nvarchar(30) NULL,
    [CTNTYPE7] nvarchar(30) NULL,
    [CTNTYPE8] nvarchar(30) NULL,
    [CTNTYPE9] nvarchar(30) NULL,
    [CTNTYPE10] nvarchar(30) NULL,
    [PACKTYPE1] nvarchar(30) NULL,
    [PACKTYPE2] nvarchar(30) NULL,
    [PACKTYPE3] nvarchar(30) NULL,
    [PACKTYPE4] nvarchar(30) NULL,
    [PACKTYPE5] nvarchar(30) NULL,
    [PACKTYPE6] nvarchar(30) NULL,
    [PACKTYPE7] nvarchar(30) NULL,
    [PACKTYPE8] nvarchar(30) NULL,
    [PACKTYPE9] nvarchar(30) NULL,
    [PACKTYPE10] nvarchar(30) NULL,
    [CTNCNT1] int NULL,
    [CTNCNT2] int NULL,
    [CTNCNT3] int NULL,
    [CTNCNT4] int NULL,
    [CTNCNT5] int NULL,
    [CTNCNT6] int NULL,
    [CTNCNT7] int NULL,
    [CTNCNT8] int NULL,
    [CTNCNT9] int NULL,
    [CTNCNT10] int NULL,
    [CTNQTY1] int NULL,
    [CTNQTY2] int NULL,
    [CTNQTY3] int NULL,
    [CTNQTY4] int NULL,
    [CTNQTY5] int NULL,
    [CTNQTY6] int NULL,
    [CTNQTY7] int NULL,
    [CTNQTY8] int NULL,
    [CTNQTY9] int NULL,
    [CTNQTY10] int NULL,
    [NoOfMasterCtn] int NULL,
    [NoOfPrepacks] int NULL,
    [NoofReshippableCarton] int NULL,
    [NoofCartonPacked] int NULL,
    [NoofIDSCarton] int NULL,
    [NoofCustomerCarton] int NULL,
    [NoofPallets] int NULL,
    [CartonWeight] float NOT NULL DEFAULT ((0)),
    [WeightUnit] nvarchar(20) NULL,
    [CartonCube] float NOT NULL DEFAULT ((0)),
    [CubeUnit] nvarchar(20) NULL,
    [ConsigneeAccountCode] nvarchar(15) NULL DEFAULT (' '),
    [ContainerNo] nvarchar(11) NULL DEFAULT (' '),
    [Equipment] nvarchar(10) NULL DEFAULT (' '),
    [ShipperAccountCode] nvarchar(15) NULL DEFAULT (' '),
    [NotifyAccountCode] nvarchar(15) NULL DEFAULT (' '),
    [SealNo] nvarchar(20) NULL DEFAULT (' '),
    [GIS_ControlNo] nvarchar(20) NULL DEFAULT (''),
    [Cust_ISA_ControlNo] nvarchar(20) NULL DEFAULT (''),
    [Cust_GIS_ControlNo] nvarchar(20) NULL DEFAULT (''),
    [GIS_ProcessTime] datetime NULL,
    [Cust_EDIAckTime] datetime NULL,
    [CBOLKey] bigint NULL,
    [CBOLLineNumber] nvarchar(5) NULL,
    [ShipDate] datetime NOT NULL DEFAULT (getdate()),
    [FinalizeFlag] nvarchar(1) NOT NULL DEFAULT ('N'),
    [ValidatedFlag] nchar(1) NULL DEFAULT ('N'),
    [Route] nvarchar(10) NULL,
    [Vehicle_Type] nvarchar(20) NULL,
    [Delivery_Zone] nvarchar(10) NULL,
    [OTMShipmentID] nvarchar(20) NULL DEFAULT (''),
    CONSTRAINT [PKMBOL] PRIMARY KEY ([MbolKey]),
    CONSTRAINT [CK_MBOL_Status] CHECK ([Status]='0' OR [Status]='5' OR [Status]='7' OR [Status]='9')
);
GO

CREATE INDEX [IX_MBOL_ExternMbolKey] ON [dbo].[mbol] ([ExternMbolKey]);
GO
CREATE INDEX [IX_MBOL_status] ON [dbo].[mbol] ([Status], [ShipCounter], [EffectiveDate]);
GO