CREATE TABLE [dbo].[mboldetail]
(
    [MbolKey] nvarchar(10) NOT NULL,
    [MbolLineNumber] nvarchar(5) NOT NULL,
    [ContainerKey] nvarchar(20) NOT NULL DEFAULT (' '),
    [OrderKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [PalletKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [Description] nvarchar(30) NOT NULL DEFAULT (' '),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [TimeStamp] nvarchar(18) NULL,
    [GrossWeight] float NULL DEFAULT ((0)),
    [Capacity] float NULL DEFAULT ((0)),
    [InvoiceNo] nvarchar(10) NULL,
    [UPSINum] nvarchar(12) NULL,
    [PCMNum] nvarchar(12) NULL,
    [ExternReason] nvarchar(60) NULL,
    [InvoiceStatus] nvarchar(10) NULL,
    [InvoiceAmount] float NULL DEFAULT ((0)),
    [DeliveryTime] datetime NULL,
    [OfficialReceipt] nvarchar(12) NULL,
    [ITS] nvarchar(10) NULL,
    [LoadKey] nvarchar(10) NULL,
    [Weight] float NULL DEFAULT ((0)),
    [Cube] float NULL DEFAULT ((0)),
    [OrderDate] datetime NULL,
    [ExternOrderKey] nvarchar(50) NULL,
    [DeliveryDate] datetime NULL,
    [DeliveryStatus] nvarchar(1) NULL DEFAULT ('0'),
    [TotalCartons] float NULL DEFAULT ((0)),
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [CtnCnt1] int NULL DEFAULT ((0)),
    [CtnCnt2] int NULL DEFAULT ((0)),
    [CtnCnt3] int NULL DEFAULT ((0)),
    [CtnCnt4] int NULL DEFAULT ((0)),
    [CtnCnt5] int NULL DEFAULT ((0)),
    [TotCtnCube] float NULL DEFAULT ((0)),
    [TotCtnWeight] float NULL DEFAULT ((0)),
    [DriverName] nvarchar(150) NULL DEFAULT (''),
    [VehicleNo] nvarchar(150) NULL DEFAULT (''),
    [TruckType] nvarchar(50) NULL DEFAULT (''),
    [ServiceProvider] nvarchar(50) NULL DEFAULT (''),
    CONSTRAINT [PKMBOLDETAIL] PRIMARY KEY ([MbolKey], [MbolLineNumber])
);
GO

CREATE INDEX [MBOLDETAIL5] ON [dbo].[mboldetail] ([OrderKey]);
GO