CREATE TABLE [dbo].[orderdetail]
(
    [OrderKey] nvarchar(10) NOT NULL,
    [OrderLineNumber] nvarchar(5) NOT NULL,
    [OrderDetailSysId] int NULL DEFAULT (rand()*(2147483647)),
    [ExternOrderKey] nvarchar(50) NOT NULL DEFAULT (' '),
    [ExternLineNo] nvarchar(20) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [ManufacturerSku] nvarchar(20) NOT NULL DEFAULT (' '),
    [RetailSku] nvarchar(20) NOT NULL DEFAULT (' '),
    [AltSku] nvarchar(20) NOT NULL DEFAULT (' '),
    [OriginalQty] int NOT NULL DEFAULT ((0)),
    [OpenQty] int NOT NULL DEFAULT ((0)),
    [ShippedQty] int NOT NULL DEFAULT ((0)),
    [AdjustedQty] int NOT NULL DEFAULT ((0)),
    [QtyPreAllocated] int NOT NULL DEFAULT ((0)),
    [QtyAllocated] int NOT NULL DEFAULT ((0)),
    [QtyPicked] int NOT NULL DEFAULT ((0)),
    [UOM] nvarchar(10) NOT NULL DEFAULT (' '),
    [PackKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [PickCode] nvarchar(10) NOT NULL DEFAULT (' '),
    [CartonGroup] nvarchar(10) NOT NULL DEFAULT (' '),
    [Lot] nvarchar(10) NOT NULL DEFAULT (' '),
    [ID] nvarchar(18) NOT NULL DEFAULT (' '),
    [Facility] nvarchar(5) NOT NULL DEFAULT (' '),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [UnitPrice] float NULL DEFAULT ((0)),
    [Tax01] float NULL DEFAULT ((0)),
    [Tax02] float NULL DEFAULT ((0)),
    [ExtendedPrice] float NULL DEFAULT ((0)),
    [UpdateSource] nvarchar(10) NOT NULL DEFAULT ('0'),
    [Lottable01] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable02] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable03] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [TariffKey] nvarchar(10) NULL,
    [FreeGoodQty] int NULL DEFAULT ((0)),
    [GrossWeight] float NULL DEFAULT ((0)),
    [Capacity] float NULL DEFAULT ((0)),
    [LoadKey] nvarchar(10) NULL,
    [MBOLKey] nvarchar(10) NULL,
    [QtyToProcess] int NULL DEFAULT ((0)),
    [MinShelfLife] int NULL DEFAULT ((0)),
    [UserDefine01] nvarchar(18) NULL,
    [UserDefine02] nvarchar(18) NULL,
    [UserDefine03] nvarchar(18) NULL,
    [UserDefine04] nvarchar(18) NULL,
    [UserDefine05] nvarchar(18) NULL,
    [UserDefine06] nvarchar(18) NULL,
    [UserDefine07] nvarchar(18) NULL,
    [UserDefine08] nvarchar(18) NULL,
    [UserDefine09] nvarchar(18) NULL,
    [POkey] nvarchar(20) NULL,
    [ExternPOKey] nvarchar(20) NULL,
    [UserDefine10] nvarchar(18) NULL,
    [EnteredQTY] int NULL DEFAULT ((0)),
    [ConsoOrderKey] nvarchar(30) NULL,
    [ExternConsoOrderKey] nvarchar(30) NULL DEFAULT (' '),
    [ConsoOrderLineNo] nvarchar(5) NULL DEFAULT (''),
    [Lottable06] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [Notes] nvarchar(500) NULL DEFAULT (''),
    [Notes2] nvarchar(500) NULL DEFAULT (''),
    [Channel] nvarchar(20) NULL DEFAULT (''),
    [HashValue] tinyint NULL DEFAULT ((1)),
    [SalesChannel] nvarchar(50) NULL DEFAULT (''),
    [CancelReasonCode] nvarchar(60) NULL,
    CONSTRAINT [PKOrderDetail] PRIMARY KEY ([OrderKey], [OrderLineNumber]),
    CONSTRAINT [CK_ORDERDETAIL_QtyAllocated] CHECK ([QtyAllocated]>=(0) AND [QtyAllocated]<=([OpenQty]+[FreeGoodQty])),
    CONSTRAINT [CK_ORDERDETAIL_QtyPicked] CHECK ([QtyPicked]>=(0) AND [QtyPicked]<=([OpenQty]+[FreeGoodQty])),
    CONSTRAINT [CK_ORDERDETAIL_QtyPreAlloc] CHECK ([QtyPreAllocated]>=(0)),
    CONSTRAINT [CK_ORDERDETAIL_QtyPreAllocated] CHECK ((([QtyPreAllocated]+[QtyPicked])+[QtyAllocated])<=([OpenQty]+[FreeGoodQty])),
    CONSTRAINT [CK_ORDERDETAIL_Status] CHECK ([Status]='CANC' OR ([Status]='9' OR ([Status]='8' OR ([Status]='7' OR ([Status]='6' OR ([Status]='5' OR ([Status]='4' OR ([Status]='3' OR ([Status]='2' OR ([Status]='1' OR [Status]='0'))))))))))
);
GO

CREATE INDEX [IX_ORDERDETAIL_ConsoOrderKey] ON [dbo].[orderdetail] ([ConsoOrderKey], [ConsoOrderLineNo]);
GO
CREATE INDEX [IX_ORDERDETAIL_ExtOrdKey] ON [dbo].[orderdetail] ([ExternOrderKey], [ExternLineNo]);
GO
CREATE INDEX [IX_ORDERDETAIL_MbolKey] ON [dbo].[orderdetail] ([MBOLKey]);
GO
CREATE INDEX [IX_ORDERDETAIL_SKU] ON [dbo].[orderdetail] ([StorerKey], [Sku]);
GO
CREATE INDEX [ORDERDETAIL6] ON [dbo].[orderdetail] ([LoadKey], [Status]);
GO