CREATE TABLE [dbo].[orderinfo]
(
    [OrderKey] nvarchar(10) NOT NULL,
    [OrderInfo01] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo02] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo03] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo04] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo05] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo06] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo07] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo08] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo09] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo10] nvarchar(30) NULL DEFAULT (' '),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [TrafficCop] nchar(1) NULL,
    [ArchiveCop] nchar(1) NULL,
    [EcomOrderId] nvarchar(45) NULL DEFAULT (''),
    [ReferenceId] nvarchar(20) NULL DEFAULT (''),
    [StoreName] nvarchar(20) NULL DEFAULT (''),
    [Platform] nvarchar(20) NULL DEFAULT (''),
    [InvoiceType] nvarchar(20) NULL DEFAULT (''),
    [PmtDate] datetime NULL,
    [InsuredAmount] float NULL DEFAULT ((0)),
    [CarrierCharges] float NULL DEFAULT ((0)),
    [OtherCharges] float NULL DEFAULT ((0)),
    [PayableAmount] float NULL DEFAULT ((0)),
    [DeliveryMode] nvarchar(30) NULL DEFAULT ('LTL'),
    [CarrierName] nvarchar(100) NULL DEFAULT (''),
    [DeliveryCategory] nvarchar(30) NULL DEFAULT ('NORMAL'),
    [Notes] nvarchar(500) NULL DEFAULT (''),
    [Notes2] nvarchar(500) NULL DEFAULT (''),
    [OTM_OrderOwner] nvarchar(50) NULL DEFAULT (''),
    [OTM_BillTo] nvarchar(50) NULL DEFAULT (''),
    [OTM_NotifyParty] nvarchar(50) NULL DEFAULT (''),
    [CourierTimeStamp] nvarchar(30) NULL DEFAULT (''),
    CONSTRAINT [PK_OrderInfo] PRIMARY KEY ([OrderKey])
);
GO
