CREATE TABLE [dbo].[orders_pi_encrypted]
(
    [Rowrefkey] int IDENTITY(1,1) NOT NULL,
    [Orderkey] nvarchar(10) NULL,
    [C_Contact1] varbinary(1000) NULL,
    [C_Contact2] varbinary(1000) NULL,
    [C_Company] varbinary(1000) NULL,
    [C_Address1] varbinary(1000) NULL,
    [C_Address2] varbinary(1000) NULL,
    [C_Address3] varbinary(1000) NULL,
    [C_Address4] varbinary(1000) NULL,
    [C_City] varbinary(1000) NULL,
    [C_State] varbinary(1000) NULL,
    [C_Zip] varbinary(1000) NULL,
    [C_Country] varbinary(1000) NULL,
    [C_Phone1] varbinary(1000) NULL,
    [C_Phone2] varbinary(1000) NULL,
    [C_Fax1] varbinary(1000) NULL,
    [C_Fax2] varbinary(1000) NULL,
    [B_contact1] varbinary(1000) NULL,
    [B_Contact2] varbinary(1000) NULL,
    [B_Company] varbinary(1000) NULL,
    [B_Address1] varbinary(1000) NULL,
    [B_Address2] varbinary(1000) NULL,
    [B_Address3] varbinary(1000) NULL,
    [B_Address4] varbinary(1000) NULL,
    [B_City] varbinary(1000) NULL,
    [B_State] varbinary(1000) NULL,
    [B_Zip] varbinary(1000) NULL,
    [B_Country] varbinary(1000) NULL,
    [B_Phone1] varbinary(1000) NULL,
    [B_Phone2] varbinary(1000) NULL,
    [B_Fax1] varbinary(1000) NULL,
    [B_Fax2] varbinary(1000) NULL,
    [M_Contact1] varbinary(1000) NULL,
    [M_Contact2] varbinary(1000) NULL,
    [M_Company] varbinary(1000) NULL,
    [M_Address1] varbinary(1000) NULL,
    [M_Address2] varbinary(1000) NULL,
    [M_Address3] varbinary(1000) NULL,
    [M_Address4] varbinary(1000) NULL,
    [M_City] varbinary(1000) NULL,
    [M_State] varbinary(1000) NULL,
    [M_Zip] varbinary(1000) NULL,
    [M_Country] varbinary(1000) NULL,
    [M_Phone1] varbinary(1000) NULL,
    [M_Phone2] varbinary(1000) NULL,
    [M_Fax1] varbinary(1000) NULL,
    [M_Fax2] varbinary(1000) NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    CONSTRAINT [PKOrders_PI_Encrypted] PRIMARY KEY ([Rowrefkey])
);
GO

CREATE UNIQUE INDEX [IX_Orders_PI_Encrypted_Orderkey] ON [dbo].[orders_pi_encrypted] ([Orderkey]);
GO