CREATE TABLE [dbo].[orders]
(
    [OrderKey] nvarchar(10) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [ExternOrderKey] nvarchar(50) NOT NULL DEFAULT (' '),
    [OrderDate] datetime NOT NULL DEFAULT (getdate()),
    [DeliveryDate] datetime NOT NULL DEFAULT (getdate()),
    [Priority] nvarchar(10) NOT NULL DEFAULT ('5'),
    [ConsigneeKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [C_contact1] nvarchar(100) NULL,
    [C_Contact2] nvarchar(100) NULL,
    [C_Company] nvarchar(100) NULL,
    [C_Address1] nvarchar(45) NULL,
    [C_Address2] nvarchar(45) NULL,
    [C_Address3] nvarchar(45) NULL,
    [C_Address4] nvarchar(45) NULL,
    [C_City] nvarchar(45) NULL,
    [C_State] nvarchar(45) NULL,
    [C_Zip] nvarchar(18) NULL,
    [C_Country] nvarchar(30) NULL,
    [C_ISOCntryCode] nvarchar(10) NULL,
    [C_Phone1] nvarchar(18) NULL,
    [C_Phone2] nvarchar(18) NULL,
    [C_Fax1] nvarchar(18) NULL,
    [C_Fax2] nvarchar(18) NULL,
    [C_vat] nvarchar(18) NULL,
    [BuyerPO] nvarchar(20) NULL,
    [BillToKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [B_contact1] nvarchar(100) NULL,
    [B_Contact2] nvarchar(100) NULL,
    [B_Company] nvarchar(100) NULL,
    [B_Address1] nvarchar(45) NULL,
    [B_Address2] nvarchar(45) NULL,
    [B_Address3] nvarchar(45) NULL,
    [B_Address4] nvarchar(45) NULL,
    [B_City] nvarchar(45) NULL,
    [B_State] nvarchar(45) NULL,
    [B_Zip] nvarchar(18) NULL,
    [B_Country] nvarchar(30) NULL,
    [B_ISOCntryCode] nvarchar(10) NULL,
    [B_Phone1] nvarchar(18) NULL,
    [B_Phone2] nvarchar(18) NULL,
    [B_Fax1] nvarchar(18) NULL,
    [B_Fax2] nvarchar(18) NULL,
    [B_Vat] nvarchar(18) NULL,
    [IncoTerm] nvarchar(10) NULL,
    [PmtTerm] nvarchar(10) NULL,
    [OpenQty] int NULL DEFAULT ((0)),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [DischargePlace] nvarchar(30) NULL,
    [DeliveryPlace] nvarchar(30) NULL,
    [IntermodalVehicle] nvarchar(30) NOT NULL DEFAULT (' '),
    [CountryOfOrigin] nvarchar(30) NULL,
    [CountryDestination] nvarchar(30) NULL,
    [UpdateSource] nvarchar(10) NOT NULL DEFAULT ('0'),
    [Type] nvarchar(10) NOT NULL DEFAULT ('0'),
    [OrderGroup] nvarchar(20) NOT NULL DEFAULT (' '),
    [Door] nvarchar(10) NOT NULL DEFAULT ('99'),
    [Route] nvarchar(10) NOT NULL DEFAULT ('99'),
    [Stop] nvarchar(10) NOT NULL DEFAULT ('99'),
    [Notes] nvarchar(4000) NULL,
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [ContainerType] nvarchar(20) NULL,
    [ContainerQty] int NULL,
    [BilledContainerQty] int NULL DEFAULT ((0)),
    [SOStatus] nvarchar(10) NULL DEFAULT ('0'),
    [MBOLKey] nvarchar(10) NULL DEFAULT (' '),
    [InvoiceNo] nvarchar(20) NULL DEFAULT (' '),
    [InvoiceAmount] float NULL DEFAULT ((0.00)),
    [Salesman] nvarchar(30) NULL DEFAULT (' '),
    [GrossWeight] float NULL DEFAULT ((0)),
    [Capacity] float NULL DEFAULT ((0)),
    [PrintFlag] nvarchar(1) NULL DEFAULT ('N'),
    [LoadKey] nvarchar(10) NULL DEFAULT (' '),
    [Rdd] nvarchar(30) NULL DEFAULT (' '),
    [Notes2] nvarchar(4000) NULL,
    [SequenceNo] int NULL DEFAULT ((99999999)),
    [Rds] nvarchar(1) NULL DEFAULT ('N'),
    [SectionKey] nvarchar(10) NULL,
    [Facility] nvarchar(5) NULL,
    [PrintDocDate] datetime NULL,
    [LabelPrice] nvarchar(20) NULL,
    [POKey] nvarchar(10) NULL DEFAULT (' '),
    [ExternPOKey] nvarchar(20) NULL DEFAULT (' '),
    [XDockFlag] nvarchar(1) NOT NULL DEFAULT ('0'),
    [UserDefine01] nvarchar(50) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(40) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [Issued] nvarchar(1) NULL,
    [DeliveryNote] nvarchar(10) NULL,
    [PODCust] datetime NULL,
    [PODArrive] datetime NULL,
    [PODReject] datetime NULL,
    [PODUser] nvarchar(18) NULL DEFAULT (' '),
    [xdockpokey] nvarchar(20) NULL,
    [SpecialHandling] nvarchar(1) NULL DEFAULT ('N'),
    [RoutingTool] nvarchar(30) NULL,
    [MarkforKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [M_Contact1] nvarchar(100) NULL,
    [M_Contact2] nvarchar(100) NULL,
    [M_Company] nvarchar(100) NULL,
    [M_Address1] nvarchar(45) NULL,
    [M_Address2] nvarchar(45) NULL,
    [M_Address3] nvarchar(45) NULL,
    [M_Address4] nvarchar(45) NULL,
    [M_City] nvarchar(45) NULL,
    [M_State] nvarchar(45) NULL,
    [M_Zip] nvarchar(18) NULL,
    [M_Country] nvarchar(30) NULL,
    [M_ISOCntryCode] nvarchar(10) NULL,
    [M_Phone1] nvarchar(18) NULL,
    [M_Phone2] nvarchar(18) NULL,
    [M_Fax1] nvarchar(18) NULL,
    [M_Fax2] nvarchar(18) NULL,
    [M_vat] nvarchar(18) NULL,
    [ShipperKey] nvarchar(15) NULL DEFAULT (' '),
    [DocType] nvarchar(1) NULL DEFAULT ('N'),
    [TrackingNo] nvarchar(40) NULL DEFAULT (''),
    [ECOM_PRESALE_FLAG] nvarchar(2) NULL DEFAULT (''),
    [ECOM_SINGLE_Flag] nchar(1) NULL DEFAULT (''),
    [CurrencyCode] nvarchar(20) NULL DEFAULT (' '),
    [RTNTrackingNo] nvarchar(40) NULL DEFAULT (''),
    [BizUnit] nvarchar(50) NOT NULL DEFAULT (''),
    [HashValue] tinyint NULL DEFAULT ((1)),
    [ECOM_OAID] nvarchar(128) NULL DEFAULT (''),
    [ECOM_Platform] nvarchar(30) NULL DEFAULT (''),
    [CancelReasonCode] nvarchar(60) NULL,
    CONSTRAINT [PKOrders] PRIMARY KEY ([OrderKey]),
    CONSTRAINT [FK_ORDERS_STORER_01] FOREIGN KEY ([StorerKey]) REFERENCES [dbo].[STORER] ([StorerKey]),
    CONSTRAINT [CK_ORDERS_Status] CHECK ([Status]='W' OR [Status]='CANC' OR [Status]='9' OR [Status]='8' OR [Status]='7' OR [Status]='6' OR [Status]='5' OR [Status]='4' OR [Status]='3' OR [Status]='2' OR [Status]='1' OR [Status]='0')
);
GO

CREATE INDEX [IDX_Orders_01] ON [dbo].[orders] ([Type], [StorerKey], [ShipperKey], [C_Company], [OrderDate]);
GO
CREATE INDEX [IDX_ORDERS_ConsigneePackingKey] ON [dbo].[orders] ([xdockpokey], [ConsigneeKey], [Type]);
GO
CREATE INDEX [IDX_ORDERS_Storer_Status] ON [dbo].[orders] ([StorerKey], [SOStatus]);
GO
CREATE INDEX [Idx_Orders_StorerKey_ConsigneeKey_Status] ON [dbo].[orders] ([StorerKey], [ConsigneeKey]);
GO
CREATE INDEX [IX_ORDERS_ExternOrdKey] ON [dbo].[orders] ([ExternOrderKey]);
GO
CREATE INDEX [IX_Orders_Loadkey] ON [dbo].[orders] ([LoadKey], [Type]);
GO
CREATE INDEX [IX_ORDERS_MBOLKEY] ON [dbo].[orders] ([MBOLKey]);
GO
CREATE INDEX [IX_Orders_TrackingNo] ON [dbo].[orders] ([TrackingNo], [StorerKey]);
GO
CREATE INDEX [IX_ORDERS_USD04] ON [dbo].[orders] ([UserDefine04], [StorerKey], [ShipperKey], [Facility], [DocType]);
GO
CREATE INDEX [IX_ORDERS_UserDefine09] ON [dbo].[orders] ([UserDefine09], [StorerKey], [Facility], [DocType], [OpenQty], [Status], [UpdateSource], [LoadKey]);
GO