CREATE TABLE [dbo].[orderselection]
(
    [OrderSelectionKey] nvarchar(10) NOT NULL,
    [DefaultFlag] nvarchar(10) NOT NULL DEFAULT ('0'),
    [OrderDateStart] datetime NOT NULL DEFAULT ('JAN 01 1900'),
    [OrderDateEnd] datetime NOT NULL DEFAULT ('DEC 31 9999'),
    [DeliveryDateStart] datetime NOT NULL DEFAULT ('JAN 01 1900'),
    [DeliveryDateEnd] datetime NOT NULL DEFAULT ('DEC 31 9999'),
    [OrderTypeStart] nvarchar(10) NOT NULL DEFAULT (' '),
    [OrderTypeEnd] nvarchar(10) NOT NULL DEFAULT ('9'),
    [OrderGroupStart] nvarchar(20) NOT NULL DEFAULT (' '),
    [OrderGroupEnd] nvarchar(20) NOT NULL DEFAULT ('9'),
    [OrderPriorityStart] nvarchar(10) NOT NULL DEFAULT ('0'),
    [OrderPriorityEnd] nvarchar(10) NOT NULL DEFAULT ('9'),
    [StorerKeyStart] nvarchar(15) NOT NULL DEFAULT ('0'),
    [StorerKeyEnd] nvarchar(15) NOT NULL DEFAULT (replicate('Z',(15))),
    [OrderKeyStart] nvarchar(10) NOT NULL DEFAULT ('0'),
    [OrderKeyEnd] nvarchar(10) NOT NULL DEFAULT (replicate('Z',(20))),
    [ExternOrderKeyStart] nvarchar(30) NOT NULL DEFAULT (' '),
    [ExternOrderKeyEnd] nvarchar(30) NOT NULL DEFAULT (replicate('Z',(20))),
    [ConsigneeKeyStart] nvarchar(15) NOT NULL DEFAULT (' '),
    [ConsigneeKeyEnd] nvarchar(15) NOT NULL DEFAULT (replicate('Z',(30))),
    [CarrierKeyStart] nvarchar(15) NOT NULL DEFAULT (' '),
    [CarrierKeyEnd] nvarchar(15) NOT NULL DEFAULT (replicate('Z',(30))),
    [RouteStart] nvarchar(10) NOT NULL DEFAULT ('0'),
    [RouteEnd] nvarchar(10) NOT NULL DEFAULT (replicate('Z',(10))),
    [DoorStart] nvarchar(10) NOT NULL DEFAULT ('0'),
    [DoorEnd] nvarchar(10) NOT NULL DEFAULT (replicate('Z',(10))),
    [StopStart] nvarchar(10) NOT NULL DEFAULT ('0'),
    [StopEnd] nvarchar(10) NOT NULL DEFAULT (replicate('Z',(10))),
    [CartonizationGroup] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [RoutingKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [PickCode] nvarchar(10) NOT NULL DEFAULT ('USESKUTBL'),
    [DoCartonization] nvarchar(1) NOT NULL DEFAULT ('Y'),
    [DoRouting] nvarchar(1) NOT NULL DEFAULT ('N'),
    [MaxOrders] int NOT NULL DEFAULT ((0)),
    [PreAllocationGrouping] nvarchar(10) NOT NULL DEFAULT ('1'),
    [PreAllocationSort] nvarchar(10) NOT NULL DEFAULT ('1'),
    [WaveOption] nvarchar(10) NOT NULL DEFAULT ('DISCRETE'),
    [BatchPickMaxCube] int NOT NULL DEFAULT ((0)),
    [BatchPickMaxCount] int NOT NULL DEFAULT ((0)),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [Timestamp] timestamp NOT NULL,
    [BillToKeyStart] nvarchar(15) NULL DEFAULT ('0'),
    [BillToKeyEnd] nvarchar(15) NULL DEFAULT ('ZZZZZZZZZZ'),
    [InvoiceStart] nvarchar(10) NULL DEFAULT ('0'),
    [InvoiceEnd] nvarchar(10) NULL DEFAULT ('ZZZZZZZZZZ'),
    [facility] nvarchar(5) NULL DEFAULT (' '),
    [LoadingDateStart] datetime NULL DEFAULT ('JAN 01 1900'),
    [LoadingDateEnd] datetime NULL DEFAULT ('DEC 31 9999'),
    [XDockPOKeyStart] nvarchar(20) NULL DEFAULT (' '),
    [XDockPOKeyEnd] nvarchar(20) NULL DEFAULT ('ZZZZZZZZZZ'),
    [BuyerPOStart] nvarchar(20) NULL DEFAULT (' '),
    [BuyerPOEnd] nvarchar(20) NULL DEFAULT ('ZZZZZZZZZZ'),
    [DynamicPickSlipCode] nvarchar(30) NULL DEFAULT (''),
    [DocTypeStart] nchar(1) NULL DEFAULT (' '),
    [DocTypeEnd] nchar(1) NULL DEFAULT ('Z'),
    [M_ISOCntryCodeStart] nchar(10) NULL DEFAULT (' '),
    [M_ISOCntryCodeEnd] nchar(10) NULL DEFAULT ('ZZZZZZZZZZ'),
    [UserDefine05Start] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05End] nvarchar(20) NULL DEFAULT ('ZZZZZZZZZZZZZZZZZZZZ'),
    [SpecialHandlingStart] nchar(1) NULL DEFAULT (' '),
    [SpecialHandlingEnd] nchar(1) NULL DEFAULT ('Z'),
    [DeliveryNoteStart] nvarchar(10) NULL DEFAULT (' '),
    [DeliveryNoteEnd] nvarchar(10) NULL DEFAULT ('ZZZZZZZZZZ'),
    CONSTRAINT [PKOrderSelection] PRIMARY KEY ([OrderSelectionKey])
);
GO
