CREATE TABLE [dbo].[pack]
(
    [PackKey] nvarchar(10) NOT NULL,
    [PackDescr] nvarchar(45) NOT NULL,
    [PackUOM1] nvarchar(10) NOT NULL DEFAULT (' '),
    [CaseCnt] float NOT NULL DEFAULT ((0)),
    [ISWHQty1] nvarchar(1) NOT NULL DEFAULT (' '),
    [ReplenishUOM1] nvarchar(1) NOT NULL DEFAULT ('N'),
    [ReplenishZone1] nvarchar(10) NOT NULL DEFAULT ('N'),
    [CartonizeUOM1] nvarchar(1) NOT NULL DEFAULT ('N'),
    [LengthUOM1] float NOT NULL DEFAULT ((0)),
    [WidthUOM1] float NOT NULL DEFAULT ((0)),
    [HeightUOM1] float NOT NULL DEFAULT ((0)),
    [CubeUOM1] float NOT NULL DEFAULT ((0)),
    [PackUOM2] nvarchar(10) NOT NULL DEFAULT (' '),
    [InnerPack] float NOT NULL DEFAULT ((0)),
    [ISWHQty2] nvarchar(1) NOT NULL DEFAULT (' '),
    [ReplenishUOM2] nvarchar(1) NOT NULL DEFAULT ('N'),
    [ReplenishZone2] nvarchar(10) NOT NULL DEFAULT ('N'),
    [CartonizeUOM2] nvarchar(1) NOT NULL DEFAULT ('N'),
    [LengthUOM2] float NOT NULL DEFAULT ((0)),
    [WidthUOM2] float NOT NULL DEFAULT ((0)),
    [HeightUOM2] float NOT NULL DEFAULT ((0)),
    [CubeUOM2] float NOT NULL DEFAULT ((0)),
    [PackUOM3] nvarchar(10) NOT NULL DEFAULT (' '),
    [Qty] float NOT NULL DEFAULT ((0)),
    [ISWHQty3] nvarchar(1) NOT NULL DEFAULT (' '),
    [ReplenishUOM3] nvarchar(1) NOT NULL DEFAULT ('Y'),
    [ReplenishZone3] nvarchar(10) NOT NULL DEFAULT ('N'),
    [CartonizeUOM3] nvarchar(1) NOT NULL DEFAULT ('N'),
    [LengthUOM3] float NOT NULL DEFAULT ((0)),
    [WidthUOM3] float NOT NULL DEFAULT ((0)),
    [HeightUOM3] float NOT NULL DEFAULT ((0)),
    [CubeUOM3] float NOT NULL DEFAULT ((0)),
    [PackUOM4] nvarchar(10) NOT NULL DEFAULT (' '),
    [Pallet] float NOT NULL DEFAULT ((0)),
    [ISWHQty4] nvarchar(1) NOT NULL DEFAULT (' '),
    [ReplenishUOM4] nvarchar(1) NOT NULL DEFAULT ('N'),
    [ReplenishZone4] nvarchar(10) NOT NULL DEFAULT ('N'),
    [CartonizeUOM4] nvarchar(1) NOT NULL DEFAULT ('N'),
    [LengthUOM4] float NOT NULL DEFAULT ((0)),
    [WidthUOM4] float NOT NULL DEFAULT ((0)),
    [HeightUOM4] float NOT NULL DEFAULT ((0)),
    [CubeUOM4] float NOT NULL DEFAULT ((0)),
    [PalletWoodLength] float NOT NULL DEFAULT ((0)),
    [PalletWoodWidth] float NOT NULL DEFAULT ((0)),
    [PalletWoodHeight] float NOT NULL DEFAULT ((0)),
    [PalletTI] int NOT NULL DEFAULT ((0)),
    [PalletHI] int NOT NULL DEFAULT ((0)),
    [PackUOM5] nvarchar(10) NOT NULL DEFAULT (' '),
    [Cube] float NOT NULL DEFAULT ((0)),
    [ISWHQty5] nvarchar(1) NOT NULL DEFAULT (' '),
    [PackUOM6] nvarchar(10) NOT NULL DEFAULT (' '),
    [GrossWgt] float NOT NULL DEFAULT ((0)),
    [ISWHQty6] nvarchar(1) NOT NULL DEFAULT (' '),
    [PackUOM7] nvarchar(10) NOT NULL DEFAULT (' '),
    [NetWgt] float NOT NULL DEFAULT ((0)),
    [ISWHQty7] nvarchar(1) NOT NULL DEFAULT (' '),
    [PackUOM8] nvarchar(10) NULL DEFAULT (' '),
    [OtherUnit1] float NOT NULL DEFAULT ((0)),
    [ISWHQty8] nvarchar(1) NOT NULL DEFAULT (' '),
    [ReplenishUOM8] nvarchar(1) NOT NULL DEFAULT ('N'),
    [ReplenishZone8] nvarchar(10) NOT NULL DEFAULT ('N'),
    [CartonizeUOM8] nvarchar(1) NOT NULL DEFAULT ('N'),
    [LengthUOM8] float NOT NULL DEFAULT ((0)),
    [WidthUOM8] float NOT NULL DEFAULT ((0)),
    [HeightUOM8] float NOT NULL DEFAULT ((0)),
    [PackUOM9] nvarchar(10) NOT NULL DEFAULT (' '),
    [OtherUnit2] float NOT NULL DEFAULT ((0)),
    [ISWHQty9] nvarchar(1) NOT NULL DEFAULT (' '),
    [ReplenishUOM9] nvarchar(1) NOT NULL DEFAULT ('N'),
    [ReplenishZone9] nvarchar(10) NOT NULL DEFAULT ('N'),
    [CartonizeUOM9] nvarchar(1) NOT NULL DEFAULT ('N'),
    [LengthUOM9] float NOT NULL DEFAULT ((0)),
    [WidthUOM9] float NOT NULL DEFAULT ((0)),
    [HeightUOM9] float NOT NULL DEFAULT ((0)),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Timestamp] timestamp NOT NULL,
    CONSTRAINT [PKPack] PRIMARY KEY ([PackKey]),
    CONSTRAINT [CK_Pack_NoDuplicates1] CHECK (isnull(rtrim([PackUOM1]),' ')=' ' OR isnull(rtrim([PackUOM4]),' ')=' ' OR rtrim([PackUOM1])<>rtrim([PackUOM4])),
    CONSTRAINT [CK_Pack_NoDuplicates2] CHECK (isnull(rtrim([PackUOM2]),' ')=' ' OR isnull(rtrim([PackUOM3]),' ')=' ' OR rtrim([PackUOM2])<>rtrim([PackUOM3]))
);
GO
