CREATE TABLE [dbo].[palletmgmtdetail]
(
    [PMKey] nvarchar(10) NOT NULL DEFAULT (''),
    [PMLinenumber] nvarchar(5) NOT NULL DEFAULT (''),
    [Docketno] nvarchar(50) NULL,
    [FromStorerkey] nvarchar(15) NOT NULL DEFAULT (''),
    [ToStorerkey] nvarchar(15) NOT NULL DEFAULT (''),
    [PMAccountNo] nvarchar(30) NOT NULL DEFAULT (''),
    [Type] nvarchar(10) NOT NULL DEFAULT (''),
    [PalletType] nvarchar(30) NOT NULL DEFAULT (''),
    [Qty] int NOT NULL DEFAULT ((0)),
    [Orderkey] nvarchar(10) NOT NULL DEFAULT (''),
    [Notes] nvarchar(4000) NULL,
    [userdefine01] nvarchar(30) NULL,
    [userdefine02] nvarchar(30) NULL,
    [userdefine03] nvarchar(30) NULL,
    [userdefine04] nvarchar(30) NULL,
    [userdefine05] nvarchar(30) NULL,
    [userdefine06] datetime NULL,
    [userdefine07] datetime NULL,
    [userdefine08] nvarchar(30) NULL,
    [userdefine09] nvarchar(30) NULL,
    [userdefine10] nvarchar(30) NULL,
    [Status] nvarchar(10) NOT NULL DEFAULT (''),
    [Addwho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [Adddate] datetime NULL DEFAULT (getdate()),
    [Editwho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [Editdate] datetime NULL DEFAULT (getdate()),
    [Trafficcop] nvarchar(1) NULL,
    [Archivecop] nvarchar(1) NULL,
    CONSTRAINT [PK_PALLETMGMTDETAIL] PRIMARY KEY ([PMKey], [PMLinenumber]),
    CONSTRAINT [CK_PALLETMGMTDETAIL_Type] CHECK ([Type] = 'TRF' OR [Type] = 'WD' OR [Type] = 'DP' OR [Type] = '')
);
GO
