CREATE TABLE [dbo].[pod]
(
    [Mbolkey] nvarchar(10) NOT NULL,
    [Mbollinenumber] nvarchar(5) NOT NULL,
    [LoadKey] nvarchar(10) NULL,
    [OrderKey] nvarchar(10) NULL,
    [BuyerPO] nvarchar(20) NULL,
    [ExternOrderKey] nvarchar(50) NULL,
    [InvoiceNo] nvarchar(20) NULL,
    [Status] nvarchar(10) NULL,
    [ActualDeliveryDate] datetime NULL,
    [InvDespatchDate] datetime NULL,
    [PodReceivedDate] datetime NULL,
    [PodFiledDate] datetime NULL,
    [InvCancelDate] datetime NULL,
    [RedeliveryDate] datetime NULL,
    [RedeliveryCount] int NULL,
    [FullRejectDate] datetime NULL,
    [ReturnRefNo] nvarchar(30) NULL,
    [PartialRejectDate] datetime NULL,
    [RejectReasonCode] nvarchar(10) NULL,
    [PoisonFormDate] datetime NULL,
    [PoisonFormNo] nvarchar(10) NULL,
    [ChequeNo] nvarchar(10) NULL,
    [ChequeAmount] money NULL,
    [ChequeDate] datetime NULL,
    [Notes] nvarchar(4000) NULL,
    [Notes2] nvarchar(4000) NULL,
    [PODDef01] nvarchar(30) NULL,
    [PODDef02] nvarchar(30) NULL,
    [PODDef03] nvarchar(30) NULL,
    [PODDef04] nvarchar(30) NULL,
    [PODDef05] nvarchar(30) NULL,
    [PODDef06] nvarchar(30) NULL,
    [PODDef07] nvarchar(30) NULL,
    [PODDef08] nvarchar(30) NULL,
    [PODDef09] nvarchar(30) NULL,
    [PODDate01] datetime NULL,
    [PODDate02] datetime NULL,
    [PODDate03] datetime NULL,
    [PODDate04] datetime NULL,
    [PODDate05] datetime NULL,
    [TrackCol01] nvarchar(30) NULL,
    [TrackCol02] nvarchar(30) NULL,
    [TrackCol03] nvarchar(30) NULL,
    [TrackCol04] nvarchar(30) NULL,
    [TrackCol05] nvarchar(30) NULL,
    [TrackDate01] datetime NULL,
    [TrackDate02] datetime NULL,
    [TrackDate03] datetime NULL,
    [TrackDate04] datetime NULL,
    [TrackDate05] datetime NULL,
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [FinalizeFlag] nvarchar(1) NULL DEFAULT ('N'),
    [Storerkey] nvarchar(15) NULL,
    [SpecialHandling] nvarchar(1) NULL DEFAULT ('N'),
    [Latitude] nvarchar(15) NULL,
    [Longtitude] nvarchar(15) NULL,
    [ExternLoadKey] nvarchar(30) NULL DEFAULT (''),
    [RefDocID] nvarchar(110) NULL,
    CONSTRAINT [PK_POD] PRIMARY KEY ([Mbolkey], [Mbollinenumber])
);
GO

CREATE INDEX [IX_POD_ExtOrdKey] ON [dbo].[pod] ([ExternOrderKey]);
GO
CREATE INDEX [IX_POD_InvoiceNo] ON [dbo].[pod] ([InvoiceNo]);
GO
CREATE INDEX [IX_POD_OrderKey] ON [dbo].[pod] ([OrderKey]);
GO