CREATE TABLE [dbo].[podetail]
(
    [POKey] nvarchar(18) NOT NULL,
    [POLineNumber] nvarchar(5) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL,
    [PODetailKey] nvarchar(10) NULL DEFAULT (' '),
    [ExternPOKey] nvarchar(20) NULL DEFAULT (' '),
    [ExternLineNo] nvarchar(20) NULL DEFAULT (' '),
    [MarksContainer] nvarchar(18) NULL DEFAULT (' '),
    [Sku] nvarchar(20) NULL DEFAULT (' '),
    [SKUDescription] nvarchar(60) NULL DEFAULT (' '),
    [ManufacturerSku] nvarchar(20) NULL DEFAULT (' '),
    [RetailSku] nvarchar(20) NULL DEFAULT (' '),
    [AltSku] nvarchar(20) NULL DEFAULT (' '),
    [QtyOrdered] int NULL DEFAULT ((0)),
    [QtyAdjusted] int NULL DEFAULT ((0)),
    [QtyReceived] int NULL DEFAULT ((0)),
    [PackKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [UnitPrice] float NULL DEFAULT ((0)),
    [UOM] nvarchar(10) NULL DEFAULT (' '),
    [Notes] nvarchar(4000) NULL,
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [POLineStatus] nvarchar(10) NULL DEFAULT ('OPEN'),
    [Facility] nvarchar(5) NULL DEFAULT (' '),
    [shortcode] nvarchar(10) NULL,
    [Best_bf_Date] datetime NULL DEFAULT (getdate()),
    [Lottable01] nvarchar(18) NULL DEFAULT (' '),
    [Lottable02] nvarchar(18) NULL DEFAULT (' '),
    [Lottable03] nvarchar(18) NULL DEFAULT (' '),
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [UserDefine01] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine09] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(30) NULL DEFAULT (' '),
    [ToId] nvarchar(18) NULL DEFAULT (' '),
    [Lottable06] nvarchar(30) NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [Channel] nvarchar(20) NULL DEFAULT (''),
    CONSTRAINT [PKPODETAIL] PRIMARY KEY ([POKey], [POLineNumber]),
    CONSTRAINT [FK_PODETAIL_SKU_01] FOREIGN KEY ([StorerKey], [Sku]) REFERENCES [dbo].[SKU] ([StorerKey], [Sku])
);
GO

CREATE INDEX [AK_PODETAIL_01] ON [dbo].[podetail] ([StorerKey], [Sku], [POKey]);
GO
CREATE INDEX [IX_ExternPODETAIL] ON [dbo].[podetail] ([ExternPOKey], [ExternLineNo]);
GO