CREATE TABLE [dbo].[putawaystrategydetail]
(
    [PutawayStrategyKey] nvarchar(10) NOT NULL,
    [PutawayStrategyLineNumber] nvarchar(5) NOT NULL,
    [PAType] nvarchar(5) NOT NULL DEFAULT (' '),
    [FROMLOC] nvarchar(10) NOT NULL DEFAULT (' '),
    [TOLOC] nvarchar(10) NOT NULL DEFAULT (' '),
    [AreaKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [Zone] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocType] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocSearchType] nvarchar(10) NOT NULL DEFAULT ('1'),
    [DimensionRestriction01] nvarchar(5) NOT NULL DEFAULT ('0'),
    [DimensionRestriction02] nvarchar(5) NOT NULL DEFAULT ('0'),
    [DimensionRestriction03] nvarchar(5) NOT NULL DEFAULT ('0'),
    [DimensionRestriction04] nvarchar(5) NOT NULL DEFAULT ('0'),
    [DimensionRestriction05] nvarchar(5) NOT NULL DEFAULT ('0'),
    [DimensionRestriction06] nvarchar(5) NOT NULL DEFAULT ('0'),
    [LocationTypeExclude01] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationTypeExclude02] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationTypeExclude03] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationTypeExclude04] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationTypeExclude05] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationFlagExclude01] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationFlagExclude02] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationFlagExclude03] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationFlagInclude01] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationFlagInclude02] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationFlagInclude03] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationHandlingExclude01] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationHandlingExclude02] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationHandlingExclude03] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationHandlingInclude01] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationHandlingInclude02] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationHandlingInclude03] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationCategoryInclude01] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationCategoryInclude02] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationCategoryInclude03] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationCategoryExclude01] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationCategoryExclude02] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationCategoryExclude03] nvarchar(10) NOT NULL DEFAULT (' '),
    [AreaTypeExclude01] nvarchar(10) NOT NULL DEFAULT (' '),
    [AreaTypeExclude02] nvarchar(10) NOT NULL DEFAULT (' '),
    [AreaTypeExclude03] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationTypeRestriction01] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationTypeRestriction02] nvarchar(10) NOT NULL DEFAULT (' '),
    [LocationTypeRestriction03] nvarchar(10) NOT NULL DEFAULT (' '),
    [FitFullReceipt] nvarchar(5) NOT NULL DEFAULT ('N'),
    [OrderType] nvarchar(10) NOT NULL DEFAULT (' '),
    [NumberofDaysOffSet] int NOT NULL DEFAULT ((0)),
    [LocationStateRestriction01] nvarchar(5) NOT NULL DEFAULT ('0'),
    [LocationStateRestriction02] nvarchar(5) NOT NULL DEFAULT ('0'),
    [LocationStateRestriction03] nvarchar(5) NOT NULL DEFAULT ('0'),
    [AllowFullPallets] nvarchar(5) NOT NULL DEFAULT ('Y'),
    [AllowFullCases] nvarchar(5) NOT NULL DEFAULT ('Y'),
    [AllowPieces] nvarchar(5) NOT NULL DEFAULT ('Y'),
    [CheckEquipmentProfileKey] nvarchar(5) NOT NULL DEFAULT ('N'),
    [CheckRestrictions] nvarchar(5) NOT NULL DEFAULT ('Y'),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Timestamp] timestamp NOT NULL,
    [LocLevelInclude01] int NOT NULL DEFAULT ((0)),
    [LocLevelInclude02] int NOT NULL DEFAULT ((0)),
    [LocLevelInclude03] int NOT NULL DEFAULT ((0)),
    [LocLevelInclude04] int NOT NULL DEFAULT ((0)),
    [LocLevelInclude05] int NOT NULL DEFAULT ((0)),
    [LocLevelInclude06] int NOT NULL DEFAULT ((0)),
    [LocLevelExclude01] int NOT NULL DEFAULT ((0)),
    [LocLevelExclude02] int NOT NULL DEFAULT ((0)),
    [LocLevelExclude03] int NOT NULL DEFAULT ((0)),
    [LocLevelExclude04] int NOT NULL DEFAULT ((0)),
    [LocLevelExclude05] int NOT NULL DEFAULT ((0)),
    [LocLevelExclude06] int NOT NULL DEFAULT ((0)),
    [LocAisleInclude01] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleInclude02] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleInclude03] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleInclude04] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleInclude05] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleInclude06] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleExclude01] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleExclude02] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleExclude03] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleExclude04] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleExclude05] nvarchar(10) NOT NULL DEFAULT (''),
    [LocAisleExclude06] nvarchar(10) NOT NULL DEFAULT (''),
    [PutawayZone01] nvarchar(10) NULL DEFAULT (''),
    [PutawayZone02] nvarchar(10) NULL DEFAULT (''),
    [PutawayZone03] nvarchar(10) NULL DEFAULT (''),
    [PutawayZone04] nvarchar(10) NULL DEFAULT (''),
    [PutawayZone05] nvarchar(10) NULL DEFAULT (''),
    [PutCode] nvarchar(30) NULL DEFAULT (' '),
    CONSTRAINT [PKPutawayStrategyDetail] PRIMARY KEY ([PutawayStrategyKey], [PutawayStrategyLineNumber])
);
GO
