CREATE TABLE [dbo].[rcmreport]
(
    [ComputerName] nvarchar(30) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL,
    [ReportType] nvarchar(10) NOT NULL,
    [PB_Datawindow] nvarchar(40) NOT NULL,
    [Rpt_Printer] nvarchar(100) NOT NULL,
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [ExtendParmName1] nvarchar(30) NULL,
    [ExtendParmName2] nvarchar(30) NULL,
    [ExtendParmName3] nvarchar(30) NULL,
    [ExtendParmName4] nvarchar(30) NULL,
    [ExtendParmName5] nvarchar(30) NULL,
    [ExtendParmDefault1] nvarchar(30) NULL DEFAULT (''),
    [ExtendParmDefault2] nvarchar(30) NULL DEFAULT (''),
    [ExtendParmDefault3] nvarchar(30) NULL DEFAULT (''),
    [ExtendParmDefault4] nvarchar(30) NULL DEFAULT (''),
    [ExtendParmDefault5] nvarchar(30) NULL DEFAULT (''),
    [AutoPrint] nvarchar(10) NOT NULL DEFAULT ('N'),
    [JReportCatalog] nvarchar(100) NULL,
    [JReportFileName] nvarchar(250) NULL,
    [JReportFlag] nvarchar(10) NULL,
    [ExtendParmName6] nvarchar(30) NULL,
    [ExtendParmName7] nvarchar(30) NULL,
    [ExtendParmName8] nvarchar(30) NULL,
    [ExtendParmName9] nvarchar(30) NULL,
    [ExtendParmName10] nvarchar(30) NULL,
    [ExtendParmDefault6] nvarchar(30) NULL DEFAULT (''),
    [ExtendParmDefault7] nvarchar(30) NULL DEFAULT (''),
    [ExtendParmDefault8] nvarchar(30) NULL DEFAULT (''),
    [ExtendParmDefault9] nvarchar(30) NULL DEFAULT (''),
    [ExtendParmDefault10] nvarchar(30) NULL DEFAULT (''),
    CONSTRAINT [PKRCMReport] PRIMARY KEY ([ComputerName], [StorerKey], [ReportType])
);
GO
