CREATE TABLE [dbo].[rdsorderdetail]
(
    [rdsOrderNo] int NOT NULL,
    [rdsOrderLineNo] nvarchar(10) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL,
    [Style] nvarchar(20) NOT NULL DEFAULT (''),
    [Color] nvarchar(10) NOT NULL DEFAULT (''),
    [PackIndicator] nvarchar(10) NOT NULL DEFAULT (''),
    [Lottable01] nvarchar(10) NOT NULL DEFAULT (''),
    [Lottable02] nvarchar(18) NOT NULL DEFAULT (''),
    [Lottable03] nvarchar(18) NOT NULL DEFAULT (''),
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [Qty] int NOT NULL DEFAULT ((0)),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [ArchiveCop] nvarchar(1) NULL,
    [TrafficCop] nvarchar(1) NULL,
    [Lottable06] nvarchar(30) NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    CONSTRAINT [PK_rdsOrderDetail_1] PRIMARY KEY ([rdsOrderNo], [rdsOrderLineNo]),
    CONSTRAINT [FK_rdsOrderDetail_rdsORDERS] FOREIGN KEY ([rdsOrderNo]) REFERENCES [dbo].[rdsORDERS] ([rdsOrderNo])
);
GO
