CREATE TABLE [dbo].[rdsorders]
(
    [rdsOrderNo] int NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [ExternOrderKey] nvarchar(50) NOT NULL DEFAULT (' '),
    [Facility] nvarchar(5) NOT NULL,
    [OrderDate] datetime NOT NULL DEFAULT (getdate()),
    [DeliveryDate] datetime NOT NULL DEFAULT (getdate()),
    [Priority] nvarchar(10) NOT NULL DEFAULT ('5'),
    [ConsigneeKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [C_Contact1] nvarchar(30) NULL,
    [C_Contact2] nvarchar(30) NULL,
    [C_Company] nvarchar(45) NULL,
    [C_Address1] nvarchar(45) NULL,
    [C_Address2] nvarchar(45) NULL,
    [C_Address3] nvarchar(45) NULL,
    [C_Address4] nvarchar(45) NULL,
    [C_City] nvarchar(45) NULL,
    [C_State] nvarchar(2) NULL,
    [C_Zip] nvarchar(18) NULL,
    [C_Country] nvarchar(30) NULL,
    [C_ISOCntryCode] nvarchar(10) NULL,
    [C_Phone1] nvarchar(18) NULL,
    [C_Phone2] nvarchar(18) NULL,
    [C_Fax1] nvarchar(18) NULL,
    [C_Fax2] nvarchar(18) NULL,
    [C_vat] nvarchar(18) NULL,
    [BuyerPO] nvarchar(20) NULL,
    [BillToKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [B_contact1] nvarchar(30) NULL,
    [B_Contact2] nvarchar(30) NULL,
    [B_Company] nvarchar(45) NULL,
    [B_Address1] nvarchar(45) NULL,
    [B_Address2] nvarchar(45) NULL,
    [B_Address3] nvarchar(45) NULL,
    [B_Address4] nvarchar(45) NULL,
    [B_City] nvarchar(45) NULL,
    [B_State] nvarchar(2) NULL,
    [B_Zip] nvarchar(18) NULL,
    [B_Country] nvarchar(30) NULL,
    [B_ISOCntryCode] nvarchar(10) NULL,
    [B_Phone1] nvarchar(18) NULL,
    [B_Phone2] nvarchar(18) NULL,
    [B_Fax1] nvarchar(18) NULL,
    [B_Fax2] nvarchar(18) NULL,
    [B_Vat] nvarchar(18) NULL,
    [MarkforKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [M_Contact1] nvarchar(30) NULL,
    [M_Contact2] nvarchar(30) NULL,
    [M_Company] nvarchar(45) NULL,
    [M_Address1] nvarchar(45) NULL,
    [M_Address2] nvarchar(45) NULL,
    [M_Address3] nvarchar(45) NULL,
    [M_Address4] nvarchar(45) NULL,
    [M_City] nvarchar(45) NULL,
    [M_State] nvarchar(2) NULL,
    [M_Zip] nvarchar(18) NULL,
    [M_Country] nvarchar(30) NULL,
    [M_ISOCntryCode] nvarchar(10) NULL,
    [M_Phone1] nvarchar(18) NULL,
    [M_Phone2] nvarchar(18) NULL,
    [M_Fax1] nvarchar(18) NULL,
    [M_Fax2] nvarchar(18) NULL,
    [M_vat] nvarchar(18) NULL,
    [IncoTerm] nvarchar(10) NULL,
    [PmtTerm] nvarchar(10) NULL,
    [OpenQty] int NULL DEFAULT ((0)),
    [PlannedQty] int NULL DEFAULT ((0)),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [DischargePlace] nvarchar(30) NULL,
    [DeliveryPlace] nvarchar(30) NULL,
    [IntermodalVehicle] nvarchar(30) NOT NULL DEFAULT (' '),
    [CountryOfOrigin] nvarchar(30) NULL,
    [CountryDestination] nvarchar(30) NULL,
    [UpdateSource] nvarchar(10) NOT NULL DEFAULT ('0'),
    [Type] nvarchar(10) NOT NULL DEFAULT ('0'),
    [OrderGroup] nvarchar(20) NOT NULL DEFAULT (' '),
    [Door] nvarchar(10) NOT NULL DEFAULT ('99'),
    [Route] nvarchar(10) NOT NULL DEFAULT ('99'),
    [Stop] nvarchar(10) NOT NULL DEFAULT ('99'),
    [Notes] nvarchar(125) NULL,
    [Notes2] nvarchar(125) NULL,
    [StartDate] datetime NULL DEFAULT (getdate()),
    [EndDate] datetime NULL,
    [ContainerType] nvarchar(20) NULL,
    [ContainerQty] int NULL,
    [BilledContainerQty] int NULL DEFAULT ((0)),
    [SOStatus] nvarchar(10) NULL DEFAULT ('0'),
    [InvoiceNo] nvarchar(20) NULL DEFAULT (' '),
    [InvoiceAmount] float NULL DEFAULT ((0.00)),
    [Salesman] nvarchar(30) NULL DEFAULT (' '),
    [GrossWeight] float NULL DEFAULT ((0)),
    [Capacity] float NULL DEFAULT ((0)),
    [PrintFlag] nvarchar(1) NULL DEFAULT ('N'),
    [Rdd] nvarchar(30) NULL DEFAULT (' '),
    [SequenceNo] int NULL DEFAULT ((99999999)),
    [Rds] nvarchar(1) NULL DEFAULT ('N'),
    [SectionKey] nvarchar(10) NULL,
    [PrintDocDate] datetime NULL,
    [LabelPrice] nvarchar(5) NULL,
    [POKey] nvarchar(10) NULL DEFAULT (' '),
    [ExternPOKey] nvarchar(20) NULL DEFAULT (' '),
    [XDockFlag] nvarchar(1) NOT NULL DEFAULT ('0'),
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [Issued] nvarchar(1) NULL,
    [DeliveryNote] nvarchar(10) NULL,
    [PODCust] datetime NULL,
    [PODArrive] datetime NULL,
    [PODReject] datetime NULL,
    [PODUser] nvarchar(18) NULL DEFAULT (' '),
    [XDockPOKey] nvarchar(20) NULL,
    [SpecialHandling] nvarchar(1) NULL DEFAULT ('N'),
    [RoutingTool] nvarchar(30) NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Loadkey] nvarchar(10) NULL,
    [OrderKey] nvarchar(10) NULL,
    CONSTRAINT [PK_rdsORDERS_1] PRIMARY KEY ([rdsOrderNo])
);
GO

CREATE INDEX [IX_rdsORDERS_ExtOrd] ON [dbo].[rdsorders] ([StorerKey], [ExternOrderKey], [BuyerPO]);
GO