CREATE TABLE [dbo].[rdspo]
(
    [rdsPONo] int NOT NULL,
    [POKey] nvarchar(18) NULL,
    [ExternPOKey] nvarchar(20) NULL DEFAULT (' '),
    [PoGroup] nvarchar(20) NOT NULL DEFAULT (' '),
    [StorerKey] nvarchar(15) NOT NULL,
    [PODate] datetime NULL DEFAULT (getdate()),
    [SellersReference] nvarchar(18) NULL DEFAULT (' '),
    [BuyersReference] nvarchar(18) NULL DEFAULT (' '),
    [OtherReference] nvarchar(18) NULL DEFAULT (' '),
    [POType] nvarchar(10) NULL DEFAULT (' '),
    [SellerName] nvarchar(45) NULL DEFAULT (' '),
    [SellerAddress1] nvarchar(45) NULL DEFAULT (' '),
    [SellerAddress2] nvarchar(45) NULL DEFAULT (' '),
    [SellerAddress3] nvarchar(45) NULL DEFAULT (' '),
    [SellerAddress4] nvarchar(45) NULL DEFAULT (' '),
    [SellerCity] nvarchar(45) NULL DEFAULT (' '),
    [SellerState] nvarchar(2) NULL DEFAULT (' '),
    [SellerZip] nvarchar(18) NULL DEFAULT (' '),
    [SellerPhone] nvarchar(18) NULL DEFAULT (' '),
    [SellerVat] nvarchar(18) NULL DEFAULT (' '),
    [BuyerName] nvarchar(45) NULL DEFAULT (' '),
    [BuyerAddress1] nvarchar(45) NULL DEFAULT (' '),
    [BuyerAddress2] nvarchar(45) NULL DEFAULT (' '),
    [BuyerAddress3] nvarchar(45) NULL DEFAULT (' '),
    [BuyerAddress4] nvarchar(45) NULL DEFAULT (' '),
    [BuyerCity] nvarchar(45) NULL DEFAULT (' '),
    [BuyerState] nvarchar(2) NULL DEFAULT (' '),
    [BuyerZip] nvarchar(18) NULL DEFAULT (' '),
    [BuyerPhone] nvarchar(18) NULL DEFAULT (' '),
    [BuyerVAT] nvarchar(18) NULL DEFAULT (' '),
    [OriginCountry] nvarchar(30) NULL DEFAULT (' '),
    [DestinationCountry] nvarchar(30) NULL DEFAULT (' '),
    [Vessel] nvarchar(30) NULL DEFAULT (' '),
    [VesselDate] datetime NULL DEFAULT (' '),
    [PlaceOfLoading] nvarchar(18) NULL DEFAULT (' '),
    [PlaceOfDischarge] nvarchar(18) NULL DEFAULT (' '),
    [PlaceofDelivery] nvarchar(18) NULL DEFAULT (' '),
    [IncoTerms] nvarchar(10) NULL DEFAULT (' '),
    [Pmtterm] nvarchar(10) NULL DEFAULT (' '),
    [TransMethod] nvarchar(10) NULL DEFAULT (' '),
    [TermsNote] nvarchar(18) NULL DEFAULT (' '),
    [Signatory] nvarchar(18) NULL DEFAULT (' '),
    [PlaceofIssue] nvarchar(18) NULL DEFAULT (' '),
    [OpenQty] int NULL DEFAULT ((0)),
    [PlannedQty] int NULL DEFAULT ((0)),
    [Amount] float NULL DEFAULT ((0)),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [Notes] nvarchar(125) NULL,
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [ExternStatus] nvarchar(10) NULL DEFAULT ('0'),
    [LoadingDate] datetime NULL,
    [ReasonCode] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine01] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL DEFAULT (' '),
    [UserDefine07] datetime NULL DEFAULT (' '),
    [UserDefine08] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine09] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(30) NULL DEFAULT (' '),
    [xdockpokey] nvarchar(20) NULL,
    CONSTRAINT [PK_rdsPO] PRIMARY KEY ([rdsPONo])
);
GO
