CREATE TABLE [dbo].[receiptdetail]
(
    [ReceiptKey] nvarchar(10) NOT NULL,
    [ReceiptLineNumber] nvarchar(5) NOT NULL,
    [ExternReceiptKey] nvarchar(50) NULL DEFAULT (' '),
    [ExternLineNo] nvarchar(20) NOT NULL DEFAULT (' '),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [POKey] nvarchar(18) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [AltSku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Id] nvarchar(18) NOT NULL DEFAULT (' '),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [DateReceived] datetime NOT NULL DEFAULT (getdate()),
    [QtyExpected] int NOT NULL DEFAULT ((0)),
    [QtyAdjusted] int NOT NULL DEFAULT ((0)),
    [QtyReceived] int NOT NULL DEFAULT ((0)),
    [UOM] nvarchar(10) NOT NULL DEFAULT (' '),
    [PackKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [VesselKey] nvarchar(18) NULL DEFAULT (' '),
    [VoyageKey] nvarchar(18) NULL DEFAULT (' '),
    [XdockKey] nvarchar(18) NULL DEFAULT (' '),
    [ContainerKey] nvarchar(18) NULL DEFAULT (' '),
    [ToLoc] nvarchar(10) NOT NULL,
    [ToLot] nvarchar(10) NULL,
    [ToId] nvarchar(18) NULL DEFAULT (' '),
    [ConditionCode] nvarchar(10) NOT NULL DEFAULT ('OK'),
    [Lottable01] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable02] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable03] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [CaseCnt] int NOT NULL DEFAULT ((0)),
    [InnerPack] int NOT NULL DEFAULT ((0)),
    [Pallet] int NOT NULL DEFAULT ((0)),
    [Cube] float NOT NULL DEFAULT ((0)),
    [GrossWgt] float NOT NULL DEFAULT ((0)),
    [NetWgt] float NOT NULL DEFAULT ((0)),
    [OtherUnit1] float NOT NULL DEFAULT ((0)),
    [OtherUnit2] float NOT NULL DEFAULT ((0)),
    [UnitPrice] float NULL DEFAULT ((0)),
    [ExtendedPrice] float NULL DEFAULT ((0)),
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [TariffKey] nvarchar(10) NULL,
    [FreeGoodQtyExpected] int NULL DEFAULT ((0)),
    [FreeGoodQtyReceived] int NULL DEFAULT ((0)),
    [SubReasonCode] nvarchar(10) NULL DEFAULT (' '),
    [FinalizeFlag] nvarchar(1) NULL DEFAULT ('N'),
    [DuplicateFrom] nvarchar(5) NULL,
    [BeforeReceivedQty] int NULL DEFAULT ((0)),
    [PutawayLoc] nvarchar(10) NULL DEFAULT (' '),
    [ExportStatus] nvarchar(1) NULL DEFAULT ('0'),
    [SplitPalletFlag] nvarchar(1) NULL DEFAULT ('N'),
    [POLineNumber] nvarchar(5) NULL DEFAULT (' '),
    [LoadKey] nvarchar(10) NULL,
    [ExternPoKey] nvarchar(20) NULL DEFAULT (''),
    [UserDefine01] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine09] nvarchar(30) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(30) NULL DEFAULT (' '),
    [Lottable06] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable07] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable08] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable09] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable10] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable11] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable12] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [Channel] nvarchar(20) NULL DEFAULT (''),
    [Channel_ID] bigint NULL DEFAULT ((0)),
    [RowVer] timestamp NOT NULL,
    [PalletType] nvarchar(10) NOT NULL DEFAULT (''),
    [Notes] nvarchar(500) NULL DEFAULT (''),
    [Notes2] nvarchar(500) NULL DEFAULT (''),
    CONSTRAINT [PKReceiptDetail] PRIMARY KEY ([ReceiptKey], [ReceiptLineNumber]),
    CONSTRAINT [FK_RECEIPTDETAIL_SKU_01] FOREIGN KEY ([StorerKey], [Sku]) REFERENCES [dbo].[SKU] ([StorerKey], [Sku])
);
GO

CREATE INDEX [IDX_RECEIPTDETAIL_StorerkeyUDF] ON [dbo].[receiptdetail] ([StorerKey], [UserDefine01], [UserDefine08], [UserDefine09]);
GO
CREATE INDEX [IX_RECEIPTDETAIL_ExternReceiptKey] ON [dbo].[receiptdetail] ([ExternReceiptKey]);
GO
CREATE INDEX [IX_RECEIPTDETAIL_PO] ON [dbo].[receiptdetail] ([POKey], [POLineNumber]);
GO
CREATE INDEX [IX_RECEIPTDETAIL_STSKLot02XRecKey] ON [dbo].[receiptdetail] ([StorerKey], [Sku], [Lottable02], [ExternPoKey]);
GO
CREATE INDEX [RECEIPTDETAIL3] ON [dbo].[receiptdetail] ([ReceiptKey], [ReceiptLineNumber], [QtyReceived], [BeforeReceivedQty]);
GO