CREATE TABLE [dbo].[sce_dl_btb_fta]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [FormNo] nvarchar(40) NOT NULL DEFAULT (''),
    [FormType] nvarchar(10) NOT NULL DEFAULT (''),
    [CustomerCode] nvarchar(20) NOT NULL DEFAULT (''),
    [HSCode] nvarchar(20) NOT NULL DEFAULT (''),
    [COO] nvarchar(20) NOT NULL DEFAULT (''),
    [PermitNo] nvarchar(20) NOT NULL DEFAULT (''),
    [IssuedDate] datetime NOT NULL,
    [Storerkey] nvarchar(15) NOT NULL DEFAULT (''),
    [Sku] nvarchar(20) NOT NULL DEFAULT (''),
    [SkuDescr] nvarchar(60) NOT NULL DEFAULT (''),
    [UOM] nvarchar(20) NULL DEFAULT (''),
    [QtyImported] int NOT NULL DEFAULT ((0)),
    [QtyExported] int NOT NULL DEFAULT ((0)),
    [OriginCriterion] nvarchar(20) NULL,
    [EnabledFlag] nvarchar(1) NULL DEFAULT ('Y'),
    [UserDefine01] nvarchar(30) NULL DEFAULT (''),
    [UserDefine02] nvarchar(30) NULL DEFAULT (''),
    [UserDefine03] nvarchar(30) NULL DEFAULT (''),
    [UserDefine04] nvarchar(30) NULL DEFAULT (''),
    [UserDefine05] nvarchar(30) NULL DEFAULT (''),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(30) NULL DEFAULT (''),
    [UserDefine09] nvarchar(30) NULL DEFAULT (''),
    [UserDefine10] nvarchar(30) NULL DEFAULT (''),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [IssueCountry] nvarchar(30) NULL DEFAULT (''),
    [IssueAuthority] nvarchar(100) NULL DEFAULT (''),
    [BTBShipItem] nvarchar(50) NULL DEFAULT (''),
    [CustomLotNo] nvarchar(20) NULL DEFAULT (''),
    CONSTRAINT [PK_sce_dl_btb_fta] PRIMARY KEY ([RowRefNo])
);
GO
