CREATE TABLE [dbo].[sce_dl_iqc_stg]
(
    [RowRefNo] int IDENTITY(1,1) NOT NULL,
    [STG_BatchNo] int NOT NULL,
    [STG_SeqNo] int NOT NULL,
    [STG_Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [STG_ErrMsg] nvarchar(250) NOT NULL DEFAULT (''),
    [STG_AddDate] datetime NOT NULL DEFAULT (getdate()),
    [Storerkey] nvarchar(15) NULL,
    [HReason] nvarchar(10) NULL,
    [TradeReturnKey] nvarchar(10) NULL,
    [Refno] nvarchar(10) NULL,
    [from_facility] nvarchar(5) NULL,
    [to_facility] nvarchar(5) NULL,
    [HUdef01] nvarchar(20) NULL,
    [HUdef02] nvarchar(20) NULL,
    [HUdef03] nvarchar(20) NULL,
    [HUdef04] nvarchar(20) NULL,
    [HUdef05] nvarchar(20) NULL,
    [HUdef06] datetime NULL,
    [HUdef07] datetime NULL,
    [HUdef08] nvarchar(10) NULL,
    [HUdef09] nvarchar(10) NULL,
    [HUdef10] nvarchar(10) NULL,
    [Notes] nvarchar(255) NULL,
    [SKU] nvarchar(20) NULL,
    [Packkey] nvarchar(10) NULL,
    [UOM] nvarchar(10) NULL,
    [OriginalQty] int NULL,
    [Qty] int NULL,
    [FromLoc] nvarchar(10) NULL,
    [FromLot] nvarchar(10) NULL,
    [FromID] nvarchar(18) NULL,
    [ToQty] int NULL,
    [ToID] nvarchar(18) NULL,
    [ToLoc] nvarchar(10) NULL,
    [DReason] nvarchar(10) NULL,
    [DUdef01] nvarchar(20) NULL,
    [DUdef02] nvarchar(20) NULL,
    [DUdef03] nvarchar(20) NULL,
    [DUdef04] nvarchar(20) NULL,
    [DUdef05] nvarchar(20) NULL,
    [DUdef06] datetime NULL,
    [DUdef07] datetime NULL,
    [DUdef08] nvarchar(10) NULL,
    [DUdef09] nvarchar(10) NULL,
    [DUdef10] nvarchar(10) NULL,
    [AddWho] nvarchar(128) NULL,
    [AddDate] datetime NULL DEFAULT (getdate()),
    [Channel] nvarchar(20) NULL DEFAULT (''),
    [Channel_ID] bigint NULL DEFAULT ((0)),
    CONSTRAINT [PK_SCE_DL_IQC_STG] PRIMARY KEY ([RowRefNo])
);
GO

CREATE INDEX [SCE_DL_IQC_STG_Idx01] ON [dbo].[sce_dl_iqc_stg] ([STG_BatchNo]);
GO
CREATE INDEX [SCE_DL_IQC_STG_Idx02] ON [dbo].[sce_dl_iqc_stg] ([STG_BatchNo], [STG_SeqNo]);
GO