CREATE TABLE [dbo].[sce_dl_adj_stg]
(
    [RowRefNo] int IDENTITY(1,1) NOT NULL,
    [STG_BatchNo] int NOT NULL,
    [STG_SeqNo] int NOT NULL,
    [STG_Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [STG_ErrMsg] nvarchar(250) NOT NULL DEFAULT (''),
    [STG_AddDate] datetime NOT NULL DEFAULT (getdate()),
    [StorerKey] nvarchar(15) NULL,
    [Sku] nvarchar(20) NULL,
    [Loc] nvarchar(10) NULL,
    [Lot] nvarchar(10) NULL,
    [Id] nvarchar(18) NULL,
    [Facility] nvarchar(5) NULL,
    [ReasonCode] nvarchar(10) NULL,
    [UOM] nvarchar(10) NULL,
    [PackKey] nvarchar(10) NULL,
    [AdjustmentType] nvarchar(5) NULL,
    [CustomerRefNo] nvarchar(10) NULL,
    [Qty] int NULL,
    [UCCNo] nvarchar(20) NULL,
    [Channel] nvarchar(20) NULL DEFAULT (''),
    [DocType] nvarchar(1) NULL,
    [Remarks] nvarchar(400) NULL,
    [FromToWhse] nvarchar(12) NULL,
    [Lottable01] nvarchar(18) NULL,
    [Lottable02] nvarchar(18) NULL,
    [Lottable03] nvarchar(18) NULL,
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [Lottable06] nvarchar(30) NULL,
    [Lottable07] nvarchar(30) NULL,
    [Lottable08] nvarchar(30) NULL,
    [Lottable09] nvarchar(30) NULL,
    [Lottable10] nvarchar(30) NULL,
    [Lottable11] nvarchar(30) NULL,
    [Lottable12] nvarchar(30) NULL,
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [HUdef01] nvarchar(20) NULL,
    [HUdef02] nvarchar(20) NULL,
    [HUdef03] nvarchar(20) NULL,
    [HUdef04] nvarchar(20) NULL,
    [HUdef05] nvarchar(20) NULL,
    [HUdef06] datetime NULL,
    [HUdef07] datetime NULL,
    [HUdef08] nvarchar(10) NULL,
    [HUdef09] nvarchar(10) NULL,
    [HUdef10] nvarchar(10) NULL,
    [DUdef01] nvarchar(20) NULL,
    [DUdef02] nvarchar(20) NULL,
    [DUdef03] nvarchar(20) NULL,
    [DUdef04] nvarchar(20) NULL,
    [DUdef05] nvarchar(20) NULL,
    [DUdef06] datetime NULL,
    [DUdef07] datetime NULL,
    [DUdef08] nvarchar(10) NULL,
    [DUdef09] nvarchar(10) NULL,
    [DUdef10] nvarchar(10) NULL,
    [AddWho] nvarchar(128) NULL,
    [AddDate] datetime NULL DEFAULT (getdate()),
    CONSTRAINT [PK_SCE_DL_ADJ_STG] PRIMARY KEY ([RowRefNo])
);
GO

CREATE INDEX [SCE_DL_ADJ_STG_Idx01] ON [dbo].[sce_dl_adj_stg] ([STG_BatchNo]);
GO
CREATE INDEX [SCE_DL_ADJ_STG_Idx02] ON [dbo].[sce_dl_adj_stg] ([STG_BatchNo], [STG_SeqNo]);
GO