CREATE TABLE [dbo].[sce_dl_assignlane_stg]
(
    [RowRefNo] int IDENTITY(1,1) NOT NULL,
    [STG_BatchNo] int NOT NULL,
    [STG_SeqNo] int NOT NULL,
    [STG_Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [STG_ErrMsg] nvarchar(250) NOT NULL DEFAULT (''),
    [STG_AddDate] datetime NOT NULL DEFAULT (getdate()),
    [LoadKey] nvarchar(10) NULL DEFAULT (' '),
    [LoadLineNumber] nvarchar(5) NULL,
    [OrderKey] nvarchar(10) NULL DEFAULT (' '),
    [ExternOrderKey] nvarchar(50) NULL,
    [ConsigneeKey] nvarchar(15) NULL,
    [CustomerName] nvarchar(50) NULL,
    [Priority] nvarchar(10) NULL,
    [OrderDate] datetime NULL,
    [DeliveryDate] datetime NULL,
    [DeliveryPlace] nvarchar(30) NULL,
    [Type] nvarchar(10) NULL,
    [Door] nvarchar(10) NULL,
    [Stop] nvarchar(10) NULL,
    [Route] nvarchar(10) NULL,
    [Weight] float NULL DEFAULT ((0)),
    [Cube] float NULL,
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [CaseCnt] int NULL DEFAULT ((0)),
    [NoOfOrdLines] int NULL DEFAULT ((0)),
    [Rdd] nvarchar(30) NULL,
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [ExternLoadKey] nvarchar(30) NULL DEFAULT (' '),
    [ExternLineNo] nvarchar(20) NULL DEFAULT (' '),
    [LP_LaneNumber] nvarchar(5) NULL,
    [LocationCategory] nvarchar(10) NULL,
    [LOC] nvarchar(10) NULL,
    [Notes] nvarchar(215) NULL DEFAULT (''),
    [MBOLKey] nvarchar(10) NULL DEFAULT (' '),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [ArchiveCop] nvarchar(1) NULL,
    [TrafficCop] nvarchar(1) NULL,
    CONSTRAINT [PK_SCE_DL_AssignLane_STG] PRIMARY KEY ([RowRefNo])
);
GO

CREATE INDEX [SCE_DL_AssignLane_STG_Idx01] ON [dbo].[sce_dl_assignlane_stg] ([STG_BatchNo]);
GO
CREATE INDEX [SCE_DL_AssignLane_STG_Idx02] ON [dbo].[sce_dl_assignlane_stg] ([STG_BatchNo], [STG_SeqNo]);
GO