CREATE TABLE [dbo].[sce_dl_channeltransfer]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [FromStorerKey] nvarchar(15) NULL DEFAULT (' '),
    [ToStorerKey] nvarchar(15) NULL DEFAULT (' '),
    [Type] nvarchar(10) NULL DEFAULT (' '),
    [OpenQty] int NULL DEFAULT ((0)),
    [CTHStatus] nvarchar(10) NULL DEFAULT ('0'),
    [ReasonCode] nvarchar(10) NULL DEFAULT (' '),
    [CustomerRefNo] nvarchar(20) NULL DEFAULT (' '),
    [Remarks] nvarchar(200) NULL DEFAULT (' '),
    [Facility] nvarchar(5) NULL DEFAULT (' '),
    [ToFacility] nvarchar(15) NULL DEFAULT (' '),
    [HUdef01] nvarchar(30) NULL DEFAULT (' '),
    [HUdef02] nvarchar(30) NULL DEFAULT (' '),
    [HUdef03] nvarchar(30) NULL DEFAULT (' '),
    [HUdef04] nvarchar(30) NULL DEFAULT (' '),
    [HUdef05] nvarchar(30) NULL DEFAULT (' '),
    [ExternChannelTransferKey] nvarchar(20) NULL DEFAULT (' '),
    [ExternChannelTransferLineNo] nvarchar(5) NULL DEFAULT (' '),
    [FromSku] nvarchar(20) NULL DEFAULT (' '),
    [FromQty] int NULL DEFAULT ((0)),
    [FromPackKey] nvarchar(10) NULL DEFAULT ('STD'),
    [FromUOM] nvarchar(10) NULL DEFAULT (' '),
    [ToSku] nvarchar(20) NULL DEFAULT (' '),
    [ToQty] int NULL DEFAULT ((0)),
    [ToPackKey] nvarchar(10) NULL DEFAULT ('STD'),
    [ToUOM] nvarchar(10) NULL DEFAULT (' '),
    [CTDStatus] nvarchar(10) NULL DEFAULT ((0)),
    [FromChannel] nvarchar(20) NULL DEFAULT (' '),
    [ToChannel] nvarchar(20) NULL DEFAULT (' '),
    [FromChannel_ID] bigint NULL DEFAULT ((0)),
    [ToChannel_ID] bigint NULL DEFAULT ((0)),
    [FromC_Attribute01] nvarchar(30) NULL DEFAULT (' '),
    [FromC_Attribute02] nvarchar(30) NULL DEFAULT (' '),
    [FromC_Attribute03] nvarchar(30) NULL DEFAULT (' '),
    [FromC_Attribute04] nvarchar(30) NULL DEFAULT (' '),
    [FromC_Attribute05] nvarchar(30) NULL DEFAULT (' '),
    [ToC_Attribute01] nvarchar(30) NULL DEFAULT (' '),
    [ToC_Attribute02] nvarchar(30) NULL DEFAULT (' '),
    [ToC_Attribute03] nvarchar(30) NULL DEFAULT (' '),
    [ToC_Attribute04] nvarchar(30) NULL DEFAULT (' '),
    [ToC_Attribute05] nvarchar(30) NULL DEFAULT (' '),
    [DUdef01] nvarchar(30) NULL DEFAULT (' '),
    [DUdef02] nvarchar(30) NULL DEFAULT (' '),
    [DUdef03] nvarchar(30) NULL DEFAULT (' '),
    [DUdef04] nvarchar(30) NULL DEFAULT (' '),
    [DUdef05] nvarchar(30) NULL DEFAULT (' '),
    [AddWho] nvarchar(128) NOT NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    CONSTRAINT [PK_SCE_DL_CHANNELTRANSFER] PRIMARY KEY ([RowRefNo])
);
GO
