CREATE TABLE [dbo].[sce_dl_so]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [ExternOrderkey] nvarchar(50) NULL,
    [Storerkey] nvarchar(15) NULL,
    [Loadkey] nvarchar(10) NULL,
    [OrderDate] datetime NULL,
    [DeliveryDate] datetime NULL,
    [Priority] nvarchar(10) NULL,
    [Consigneekey] nvarchar(15) NULL,
    [C_Contact1] nvarchar(30) NULL,
    [C_Contact2] nvarchar(30) NULL,
    [C_Company] nvarchar(45) NULL,
    [C_Address1] nvarchar(45) NULL,
    [C_Address2] nvarchar(45) NULL,
    [C_Address3] nvarchar(45) NULL,
    [C_Address4] nvarchar(45) NULL,
    [C_City] nvarchar(45) NULL,
    [C_State] nvarchar(45) NULL,
    [C_Zip] nvarchar(18) NULL,
    [C_Country] nvarchar(30) NULL,
    [C_ISOCntryCode] nvarchar(10) NULL,
    [C_Phone1] nvarchar(18) NULL,
    [C_Phone2] nvarchar(18) NULL,
    [C_Fax1] nvarchar(18) NULL,
    [C_Fax2] nvarchar(18) NULL,
    [C_vat] nvarchar(18) NULL,
    [BuyerPO] nvarchar(20) NULL,
    [BillToKey] nvarchar(15) NULL,
    [B_Contact1] nvarchar(30) NULL,
    [B_Contact2] nvarchar(30) NULL,
    [B_Company] nvarchar(45) NULL,
    [B_Address1] nvarchar(45) NULL,
    [B_Address2] nvarchar(45) NULL,
    [B_Address3] nvarchar(45) NULL,
    [B_Address4] nvarchar(45) NULL,
    [B_City] nvarchar(45) NULL,
    [B_State] nvarchar(45) NULL,
    [B_Zip] nvarchar(18) NULL,
    [B_Country] nvarchar(30) NULL,
    [B_ISOCntryCode] nvarchar(10) NULL,
    [B_Phone1] nvarchar(18) NULL,
    [B_Phone2] nvarchar(18) NULL,
    [B_Fax1] nvarchar(18) NULL,
    [B_Fax2] nvarchar(18) NULL,
    [B_Vat] nvarchar(18) NULL,
    [IncoTerm] nvarchar(10) NULL,
    [PmtTerm] nvarchar(10) NULL,
    [DischargePlace] nvarchar(30) NULL,
    [DeliveryPlace] nvarchar(30) NULL,
    [IntermodalVehicle] nvarchar(30) NULL,
    [CountryOfOrigin] nvarchar(30) NULL,
    [CountryDestination] nvarchar(30) NULL,
    [UpdateSource] nvarchar(10) NULL,
    [Type] nvarchar(10) NULL,
    [OrderGroup] nvarchar(20) NULL,
    [Door] nvarchar(10) NULL,
    [Route] nvarchar(10) NULL,
    [Stop] nvarchar(10) NULL,
    [Notes] nvarchar(4000) NULL,
    [ContainerType] nvarchar(20) NULL,
    [ContainerQty] int NULL,
    [BilledContainerQty] int NULL,
    [InvoiceNo] nvarchar(20) NULL,
    [InvoiceAmount] float NULL,
    [Salesman] nvarchar(30) NULL,
    [HGrossWeight] float NULL,
    [HCapacity] float NULL,
    [Rdd] nvarchar(30) NULL,
    [Notes2] nvarchar(4000) NULL,
    [SectionKey] nvarchar(10) NULL,
    [Facility] nvarchar(5) NULL,
    [LabelPrice] nvarchar(5) NULL,
    [POKey] nvarchar(10) NULL,
    [ExternPOKey] nvarchar(20) NULL,
    [Shipperkey] nvarchar(15) NULL,
    [XDockFlag] nvarchar(1) NULL,
    [PODUser] nvarchar(18) NULL,
    [HUdef01] nvarchar(20) NULL,
    [HUdef02] nvarchar(20) NULL,
    [HUdef03] nvarchar(20) NULL,
    [HUdef04] nvarchar(20) NULL,
    [HUdef05] nvarchar(20) NULL,
    [HUdef06] datetime NULL,
    [HUdef07] datetime NULL,
    [HUdef08] nvarchar(10) NULL,
    [HUdef09] nvarchar(10) NULL,
    [HUdef10] nvarchar(10) NULL,
    [Issued] nvarchar(1) NULL,
    [DeliveryNote] nvarchar(10) NULL,
    [xdockpokey] varchar(20) NULL,
    [SpecialHandling] nvarchar(1) NULL,
    [RoutingTool] varchar(30) NULL,
    [Markforkey] nvarchar(15) NULL,
    [OrderLineNumber] nvarchar(5) NULL,
    [ExternLineNo] nvarchar(10) NULL,
    [SKU] nvarchar(20) NULL,
    [AltSKU] nvarchar(20) NULL,
    [RetailSKU] nvarchar(20) NULL,
    [UPC] nvarchar(30) NULL,
    [Style] nvarchar(20) NULL,
    [Color] nvarchar(10) NULL,
    [Size] nvarchar(5) NULL,
    [OpenQty] int NULL,
    [UOM] nvarchar(10) NULL,
    [Packkey] nvarchar(10) NULL,
    [CartonGroup] nvarchar(10) NULL,
    [Lot] nvarchar(10) NULL,
    [ID] nvarchar(18) NULL,
    [UnitPrice] float NULL,
    [Tax01] float NULL,
    [Tax02] float NULL,
    [ExtendedPrice] float NULL,
    [Lottable01] nvarchar(18) NULL,
    [Lottable02] nvarchar(18) NULL,
    [Lottable03] nvarchar(18) NULL,
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [DGrossWeight] float NULL,
    [DCapacity] float NULL,
    [MinShelfLife] int NULL,
    [DUdef01] nvarchar(18) NULL,
    [DUdef02] nvarchar(18) NULL,
    [DUdef03] nvarchar(18) NULL,
    [DUdef04] nvarchar(18) NULL,
    [DUdef05] nvarchar(18) NULL,
    [DUdef06] nvarchar(18) NULL,
    [DUdef07] nvarchar(18) NULL,
    [DUdef08] nvarchar(18) NULL,
    [DUdef09] nvarchar(18) NULL,
    [DUdef10] nvarchar(18) NULL,
    [AddWho] nvarchar(128) NOT NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [splitOrder] nvarchar(10) NULL,
    [PrintFlag] nvarchar(1) NULL,
    [M_Contact1] nvarchar(30) NULL,
    [M_Contact2] nvarchar(30) NULL,
    [M_Company] nvarchar(45) NULL,
    [M_Address1] nvarchar(45) NULL,
    [M_Address2] nvarchar(45) NULL,
    [M_Address3] nvarchar(45) NULL,
    [M_Address4] nvarchar(45) NULL,
    [M_City] nvarchar(45) NULL,
    [M_State] nvarchar(45) NULL,
    [M_Zip] nvarchar(18) NULL,
    [M_Country] nvarchar(30) NULL,
    [M_ISOCntryCode] nvarchar(10) NULL,
    [M_Phone1] nvarchar(18) NULL,
    [M_Phone2] nvarchar(18) NULL,
    [M_Fax1] nvarchar(18) NULL,
    [M_Fax2] nvarchar(18) NULL,
    [M_Vat] nvarchar(18) NULL,
    [ConsoOrderKey] nvarchar(30) NULL,
    [ExternConsoOrderKey] nvarchar(30) NULL,
    [ConsoOrderLineNo] nvarchar(5) NULL,
    [Editdate] datetime NULL,
    [ManufacturerSku] nvarchar(20) NULL,
    [Lottable06] nvarchar(30) NULL,
    [Lottable07] nvarchar(30) NULL,
    [Lottable08] nvarchar(30) NULL,
    [Lottable09] nvarchar(30) NULL,
    [Lottable10] nvarchar(30) NULL,
    [Lottable11] nvarchar(30) NULL,
    [Lottable12] nvarchar(30) NULL,
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [mbolkey] nvarchar(10) NULL,
    [PODArrive] datetime NULL,
    [PODCust] datetime NULL,
    [PODReject] datetime NULL,
    [DocType] nvarchar(1) NULL DEFAULT ('N'),
    [DNotes] nvarchar(500) NULL,
    [DNotes2] nvarchar(500) NULL,
    [DConsoOrderKey] nvarchar(30) NULL,
    [DExternConsoOrderKey] nvarchar(30) NULL,
    [DConsoOrderLineNo] nvarchar(5) NULL,
    [OrderKey] nvarchar(10) NULL,
    [OrderInfo01] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo02] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo03] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo04] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo05] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo06] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo07] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo08] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo09] nvarchar(30) NULL DEFAULT (' '),
    [OrderInfo10] nvarchar(30) NULL DEFAULT (' '),
    [EcomOrderId] nvarchar(45) NULL DEFAULT (''),
    [ReferenceId] nvarchar(20) NULL DEFAULT (''),
    [StoreName] nvarchar(20) NULL DEFAULT (''),
    [Platform] nvarchar(20) NULL DEFAULT (''),
    [InvoiceType] nvarchar(20) NULL DEFAULT (''),
    [PmtDate] datetime NULL,
    [InsuredAmount] float NULL DEFAULT ((0)),
    [CarrierCharges] float NULL DEFAULT ((0)),
    [OtherCharges] float NULL DEFAULT ((0)),
    [PayableAmount] float NULL DEFAULT ((0)),
    [DeliveryMode] nvarchar(30) NULL DEFAULT ('LTL'),
    [CarrierName] nvarchar(30) NULL DEFAULT (''),
    [DeliveryCategory] nvarchar(30) NULL DEFAULT ('NORMAL'),
    [INotes] nvarchar(500) NULL DEFAULT (''),
    [INotes2] nvarchar(500) NULL DEFAULT (''),
    [OTM_OrderOwner] nvarchar(50) NULL DEFAULT (''),
    [OTM_BillTo] nvarchar(50) NULL DEFAULT (''),
    [OTM_NotifyParty] nvarchar(50) NULL DEFAULT (''),
    [TrackingNo] nvarchar(30) NULL DEFAULT (' '),
    [ECOM_PRESALE_FLAG] nvarchar(2) NULL,
    [ECOM_SINGLE_Flag] nvarchar(1) NULL,
    [CurrencyCode] nvarchar(20) NULL,
    [TotalQty] int NULL DEFAULT ((0)),
    [Channel] nvarchar(20) NULL DEFAULT (''),
    [SOStatus] nvarchar(20) NULL,
    [RTNTrackingNo] nvarchar(30) NULL DEFAULT (''),
    [BizUnit] nvarchar(50) NULL DEFAULT (''),
    [HashValue] tinyint NULL DEFAULT (abs(checksum(newid())%(256))),
    [ECOM_Platform] nvarchar(30) NULL DEFAULT (''),
    CONSTRAINT [PK_SCE_DL_SO] PRIMARY KEY ([RowRefNo])
);
GO
