CREATE TABLE [dbo].[sce_dl_sku]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [StorerKey] nvarchar(15) NULL,
    [Sku] nvarchar(20) NULL,
    [DESCR] nvarchar(60) NULL,
    [SUSR1] nvarchar(18) NULL,
    [SUSR2] nvarchar(18) NULL,
    [SUSR3] nvarchar(18) NULL,
    [SUSR4] nvarchar(18) NULL,
    [SUSR5] nvarchar(18) NULL,
    [MANUFACTURERSKU] nvarchar(20) NULL,
    [RETAILSKU] nvarchar(20) NULL,
    [ALTSKU] nvarchar(20) NULL,
    [PACKKey] nvarchar(10) NULL,
    [STDGROSSWGT] float NULL,
    [STDNETWGT] float NULL,
    [STDCUBE] float NULL,
    [TARE] float NULL,
    [CLASS] nvarchar(10) NULL,
    [ACTIVE] nvarchar(10) NULL,
    [SKUGROUP] nvarchar(10) NULL,
    [Tariffkey] nvarchar(10) NULL,
    [NOTES1] nvarchar(4000) NULL,
    [NOTES2] nvarchar(4000) NULL,
    [PickCode] nvarchar(10) NULL,
    [StrategyKey] nvarchar(10) NULL,
    [CartonGroup] nvarchar(10) NULL,
    [PutCode] nvarchar(10) NULL,
    [PutawayLoc] nvarchar(10) NULL,
    [PutawayZone] nvarchar(10) NULL,
    [InnerPack] int NULL,
    [Cube] float NULL,
    [GrossWgt] float NULL,
    [NetWgt] float NULL,
    [ABC] nvarchar(5) NULL,
    [CycleCountFrequency] int NULL,
    [LastCycleCount] datetime NULL,
    [ReorderPoint] int NULL,
    [ReorderQty] int NULL,
    [StdOrderCost] float NULL,
    [CarryCost] float NULL,
    [Price] money NULL,
    [Cost] money NULL,
    [ReceiptHoldCode] nvarchar(10) NULL,
    [ReceiptInspectionLoc] nvarchar(10) NULL,
    [OnReceiptCopyPackkey] nvarchar(10) NULL,
    [IOFlag] nvarchar(1) NULL,
    [TareWeight] float NULL,
    [LotxIdDetailOtherlabel1] nvarchar(30) NULL,
    [LotxIdDetailOtherlabel2] nvarchar(30) NULL,
    [LotxIdDetailOtherlabel3] nvarchar(30) NULL,
    [AvgCaseWeight] float NULL,
    [TolerancePct] float NULL,
    [SkuStatus] nvarchar(10) NULL,
    [Length] float NULL,
    [Width] float NULL,
    [Height] float NULL,
    [weight] real NULL,
    [itemclass] nvarchar(10) NULL,
    [ShelfLife] int NULL,
    [Facility] nvarchar(5) NULL,
    [BUSR1] nvarchar(30) NULL,
    [BUSR2] nvarchar(30) NULL,
    [BUSR3] nvarchar(30) NULL,
    [BUSR4] nvarchar(200) NULL,
    [BUSR5] nvarchar(30) NULL,
    [BUSR6] nvarchar(30) NULL,
    [BUSR7] nvarchar(30) NULL,
    [BUSR8] nvarchar(30) NULL,
    [BUSR9] nvarchar(30) NULL,
    [BUSR10] nvarchar(30) NULL,
    [ReturnLoc] nvarchar(10) NULL,
    [ReceiptLoc] nvarchar(10) NULL,
    [XDockReceiptLoc] nvarchar(10) NULL,
    [PrePackIndicator] nvarchar(30) NULL,
    [PackQtyIndicator] int NULL,
    [StackFactor] int NULL,
    [IVAS] nvarchar(30) NULL,
    [OVAS] nvarchar(30) NULL,
    [Style] nvarchar(20) NULL,
    [Color] nvarchar(10) NULL,
    [Size] nvarchar(10) NULL,
    [Measurement] nvarchar(5) NULL,
    [AddWho] nvarchar(128) NOT NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [HazardousFlag] nvarchar(30) NULL DEFAULT (''),
    [TemperatureFlag] nvarchar(30) NULL DEFAULT (''),
    [ProductModel] nvarchar(30) NULL DEFAULT (''),
    [CtnPickQty] int NULL DEFAULT ((0)),
    [CountryOfOrigin] nvarchar(30) NULL DEFAULT (''),
    [IB_UOM] nvarchar(10) NULL DEFAULT (' '),
    [IB_RPT_UOM] nvarchar(10) NULL DEFAULT (' '),
    [OB_UOM] nvarchar(10) NULL DEFAULT (' '),
    [OB_RPT_UOM] nvarchar(10) NULL DEFAULT (' '),
    [ABCPL] nvarchar(5) NULL DEFAULT ('B'),
    [ABCCS] nvarchar(5) NULL DEFAULT ('B'),
    [ABCEA] nvarchar(5) NULL DEFAULT ('B'),
    [ABCStorerkey] nvarchar(15) NULL DEFAULT (' '),
    [ABCSku] nvarchar(20) NULL DEFAULT (' '),
    [OldStorerkey] nvarchar(15) NULL DEFAULT (' '),
    [OldSku] nvarchar(20) NULL DEFAULT (' '),
    [ABCPeriod] int NULL DEFAULT ((0)),
    [DisableABCCalc] nvarchar(1) NULL DEFAULT ('N'),
    [LOTTABLE01LABEL] nvarchar(20) NULL,
    [LOTTABLE02LABEL] nvarchar(20) NULL,
    [LOTTABLE03LABEL] nvarchar(20) NULL,
    [LOTTABLE04LABEL] nvarchar(20) NULL,
    [LOTTABLE05LABEL] nvarchar(20) NULL,
    [LOTTABLE06LABEL] nvarchar(20) NULL,
    [LOTTABLE07LABEL] nvarchar(20) NULL,
    [LOTTABLE08LABEL] nvarchar(20) NULL,
    [LOTTABLE09LABEL] nvarchar(20) NULL,
    [LOTTABLE10LABEL] nvarchar(20) NULL,
    [LOTTABLE11LABEL] nvarchar(20) NULL,
    [LOTTABLE12LABEL] nvarchar(20) NULL,
    [LOTTABLE13LABEL] nvarchar(20) NULL,
    [LOTTABLE14LABEL] nvarchar(20) NULL,
    [LOTTABLE15LABEL] nvarchar(20) NULL,
    [OTM_SKUGroup] nvarchar(50) NULL DEFAULT (''),
    [LottableCode] nvarchar(30) NULL DEFAULT (''),
    [Pressure] nvarchar(2) NULL DEFAULT ('0'),
    [SerialNoCapture] nvarchar(2) NULL DEFAULT (''),
    CONSTRAINT [PK_SCE_DL_SKU] PRIMARY KEY ([RowRefNo])
);
GO
