CREATE TABLE [dbo].[sce_dl_mbol]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [MbolKey] nvarchar(10) NULL,
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [ExternMbolKey] nvarchar(30) NULL DEFAULT (' '),
    [OriginCountry] nvarchar(30) NULL DEFAULT (' '),
    [DestinationCountry] nvarchar(30) NULL DEFAULT (' '),
    [VesselQualifier] nvarchar(10) NULL DEFAULT ('VM'),
    [Vessel] nvarchar(30) NULL DEFAULT (' '),
    [PlaceOfLoadingQualifier] nvarchar(10) NULL DEFAULT (' '),
    [PlaceOfLoading] nvarchar(30) NULL DEFAULT (' '),
    [PlaceOfdischargeQualifier] nvarchar(10) NULL DEFAULT (' '),
    [PlaceOfDischarge] nvarchar(30) NULL DEFAULT (' '),
    [PlaceOfdeliveryQualifier] nvarchar(10) NULL DEFAULT (' '),
    [PlaceOfdelivery] nvarchar(30) NULL DEFAULT (' '),
    [TransMethod] nvarchar(30) NULL DEFAULT (' '),
    [VoyageNumber] nvarchar(30) NULL DEFAULT (' '),
    [DepartureDate] datetime NULL DEFAULT (getdate()),
    [ArrivalDate] datetime NULL DEFAULT (getdate()),
    [ArrivalDateFinalDestination] datetime NULL DEFAULT (getdate()),
    [BookingReference] nvarchar(30) NULL DEFAULT (' '),
    [OtherReference] nvarchar(30) NULL DEFAULT (' '),
    [CarrierKey] nvarchar(10) NULL DEFAULT (' '),
    [Carrieragent] nvarchar(30) NULL DEFAULT (' '),
    [EffectiveDate] datetime NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [TimeStamp] nvarchar(18) NULL,
    [DRIVERName] nvarchar(30) NULL,
    [LoadingDate] datetime NULL,
    [CustomerReceivedDate] datetime NULL,
    [Remarks] nvarchar(4000) NULL DEFAULT (' '),
    [TotalInvoiceValue] float NULL DEFAULT (' '),
    [GrossWeight] float NULL DEFAULT ((0)),
    [Capacity] float NULL DEFAULT ((0)),
    [InvoiceAmount] float NULL DEFAULT ((0)),
    [Weight] float NULL DEFAULT ((0)),
    [Cube] float NULL DEFAULT ((0)),
    [CustCnt] int NULL DEFAULT ((0)),
    [PalletCnt] int NULL DEFAULT ((0)),
    [CaseCnt] int NULL DEFAULT ((0)),
    [Facility] nvarchar(5) NULL DEFAULT ('F1'),
    [COD_Status] nvarchar(1) NULL DEFAULT ('0'),
    [DepotStatus] nvarchar(10) NULL DEFAULT ('0'),
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [ShipCounter] int NULL DEFAULT ((0)),
    [CTNTYPE] nvarchar(30) NULL,
    [NoofContainer] int NULL,
    [CTNTYPE1] nvarchar(30) NULL,
    [CTNTYPE2] nvarchar(30) NULL,
    [CTNTYPE3] nvarchar(30) NULL,
    [CTNTYPE4] nvarchar(30) NULL,
    [CTNTYPE5] nvarchar(30) NULL,
    [CTNTYPE6] nvarchar(30) NULL,
    [CTNTYPE7] nvarchar(30) NULL,
    [CTNTYPE8] nvarchar(30) NULL,
    [CTNTYPE9] nvarchar(30) NULL,
    [CTNTYPE10] nvarchar(30) NULL,
    [PACKTYPE1] nvarchar(30) NULL,
    [PACKTYPE2] nvarchar(30) NULL,
    [PACKTYPE3] nvarchar(30) NULL,
    [PACKTYPE4] nvarchar(30) NULL,
    [PACKTYPE5] nvarchar(30) NULL,
    [PACKTYPE6] nvarchar(30) NULL,
    [PACKTYPE7] nvarchar(30) NULL,
    [PACKTYPE8] nvarchar(30) NULL,
    [PACKTYPE9] nvarchar(30) NULL,
    [PACKTYPE10] nvarchar(30) NULL,
    [CTNCNT1] int NULL,
    [CTNCNT2] int NULL,
    [CTNCNT3] int NULL,
    [CTNCNT4] int NULL,
    [CTNCNT5] int NULL,
    [CTNCNT6] int NULL,
    [CTNCNT7] int NULL,
    [CTNCNT8] int NULL,
    [CTNCNT9] int NULL,
    [CTNCNT10] int NULL,
    [CTNQTY1] int NULL,
    [CTNQTY2] int NULL,
    [CTNQTY3] int NULL,
    [CTNQTY4] int NULL,
    [CTNQTY5] int NULL,
    [CTNQTY6] int NULL,
    [CTNQTY7] int NULL,
    [CTNQTY8] int NULL,
    [CTNQTY9] int NULL,
    [CTNQTY10] int NULL,
    [NoOfMasterCtn] int NULL,
    [NoOfPrepacks] int NULL,
    [NoofReshippableCarton] int NULL,
    [NoofCartonPacked] int NULL,
    [NoofIDSCarton] int NULL,
    [NoofCustomerCarton] int NULL,
    [NoofPallets] int NULL,
    [CartonWeight] float NULL DEFAULT ((0)),
    [WeightUnit] nvarchar(20) NULL,
    [CartonCube] float NULL DEFAULT ((0)),
    [CubeUnit] nvarchar(20) NULL,
    [ShipperAccountCode] nvarchar(15) NULL DEFAULT (' '),
    [ConsigneeAccountCode] nvarchar(15) NULL DEFAULT (' '),
    [NotifyAccountCode] nvarchar(15) NULL DEFAULT (' '),
    [ContainerNo] nvarchar(11) NULL DEFAULT (' '),
    [Equipment] nvarchar(10) NULL DEFAULT (' '),
    [SealNo] nvarchar(8) NULL DEFAULT (' '),
    [GIS_ControlNo] nvarchar(20) NULL DEFAULT (''),
    [Cust_ISA_ControlNo] nvarchar(20) NULL DEFAULT (''),
    [Cust_GIS_ControlNo] nvarchar(20) NULL DEFAULT (''),
    [GIS_ProcessTime] datetime NULL,
    [Cust_EDIAckTime] datetime NULL,
    [CBOLKey] int NULL,
    [CBOLLineNumber] nvarchar(5) NULL,
    [ShipDate] datetime NULL DEFAULT (getdate()),
    [ValidatedFlag] nchar(1) NULL DEFAULT ('N'),
    [Route] nvarchar(10) NULL,
    [Vehicle_Type] nvarchar(20) NULL,
    [Delivery_Zone] nvarchar(10) NULL,
    [OTMShipmentID] nvarchar(20) NULL DEFAULT (''),
    [AddWho] nvarchar(128) NOT NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [FinalizeFlag] nvarchar(1) NULL DEFAULT ('N'),
    [ContainerKey] nvarchar(20) NULL DEFAULT (' '),
    [OrderKey] nvarchar(10) NULL DEFAULT (' '),
    [PalletKey] nvarchar(10) NULL DEFAULT (' '),
    [Description] nvarchar(30) NULL DEFAULT (' '),
    [DGrossWeight] float NULL DEFAULT ((0)),
    [DCapacity] float NULL DEFAULT ((0)),
    [DInvoiceNo] nvarchar(10) NULL,
    [UPSINum] nvarchar(12) NULL,
    [PCMNum] nvarchar(12) NULL,
    [ExternReason] nvarchar(60) NULL,
    [InvoiceStatus] nvarchar(10) NULL,
    [DInvoiceAmount] float NULL DEFAULT ((0)),
    [DeliveryTime] datetime NULL,
    [OfficialReceipt] nvarchar(12) NULL,
    [ITS] nvarchar(10) NULL,
    [LoadKey] nvarchar(10) NULL,
    [DWeight] float NULL DEFAULT ((0)),
    [DCube] float NULL DEFAULT ((0)),
    [OrderDate] datetime NULL,
    [ExternOrderKey] nvarchar(30) NULL,
    [DeliveryDate] datetime NULL,
    [DeliveryStatus] nvarchar(1) NULL DEFAULT ('0'),
    [TotalCartons] float NULL DEFAULT ((0)),
    [DUdef01] nvarchar(20) NULL DEFAULT (' '),
    [DUdef02] nvarchar(20) NULL DEFAULT (' '),
    [DUdef03] nvarchar(20) NULL DEFAULT (' '),
    [DUdef04] nvarchar(20) NULL DEFAULT (' '),
    [DUdef05] nvarchar(20) NULL DEFAULT (' '),
    [DUdef06] datetime NULL,
    [DUdef07] datetime NULL,
    [DUdef08] nvarchar(10) NULL DEFAULT ('N'),
    [DUdef09] nvarchar(10) NULL DEFAULT (' '),
    [DUdef10] nvarchar(10) NULL DEFAULT (' '),
    [DCtnCnt1] int NULL DEFAULT ((0)),
    [DCtnCnt2] int NULL DEFAULT ((0)),
    [DCtnCnt3] int NULL DEFAULT ((0)),
    [DCtnCnt4] int NULL DEFAULT ((0)),
    [DCtnCnt5] int NULL DEFAULT ((0)),
    [TotCtnCube] float NULL DEFAULT ((0)),
    [TotCtnWeight] float NULL DEFAULT ((0)),
    [DDriverName] nvarchar(150) NULL DEFAULT (''),
    [VehicleNo] nvarchar(150) NULL DEFAULT (''),
    [TruckType] nvarchar(50) NULL DEFAULT (''),
    [ServiceProvider] nvarchar(50) NULL DEFAULT (''),
    CONSTRAINT [PK_SCE_DL_MBOL] PRIMARY KEY ([RowRefNo])
);
GO
