CREATE TABLE [dbo].[sce_dl_pack_stg]
(
    [RowRefNo] int IDENTITY(1,1) NOT NULL,
    [STG_BatchNo] int NOT NULL,
    [STG_SeqNo] int NOT NULL,
    [STG_Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [STG_ErrMsg] nvarchar(250) NOT NULL DEFAULT (''),
    [STG_AddDate] datetime NOT NULL DEFAULT (getdate()),
    [Casecnt] float NULL DEFAULT ((0)),
    [InnerPack] float NULL DEFAULT ((0)),
    [Qty] float NULL DEFAULT ((1)),
    [Pallet] float NULL DEFAULT ((0)),
    [Cube] float NULL DEFAULT ((0)),
    [GrossWgt] float NULL DEFAULT ((0)),
    [NetWgt] float NULL DEFAULT ((0)),
    [OtherUnit1] float NULL DEFAULT ((0)),
    [OtherUnit2] float NULL DEFAULT ((0)),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [Packdescr] nvarchar(45) NULL,
    [PalletTI] int NULL,
    [PalletHI] int NULL,
    [ReplenishUOM1] nvarchar(1) NULL,
    [ReplenishZone1] nvarchar(10) NULL,
    [CartonizeUOM1] nvarchar(1) NULL,
    [LengthUOM1] float NULL,
    [WidthUOM1] float NULL,
    [HeightUOM1] float NULL,
    [CubeUOM1] float NULL,
    [ISWHQty2] nvarchar(1) NULL,
    [ReplenishUOM2] nvarchar(1) NULL,
    [ReplenishZone2] nvarchar(10) NULL,
    [CartonizeUOM2] nvarchar(1) NULL,
    [LengthUOM2] float NULL,
    [WidthUOM2] float NULL,
    [HeightUOM2] float NULL,
    [CubeUOM2] float NULL,
    [ISWHQty3] nvarchar(1) NULL,
    [ReplenishUOM3] nvarchar(1) NULL,
    [ReplenishZone3] nvarchar(10) NULL,
    [CartonizeUOM3] nvarchar(1) NULL,
    [LengthUOM3] float NULL,
    [WidthUOM3] float NULL,
    [HeightUOM3] float NULL,
    [CubeUOM3] float NULL,
    [ISWHQty4] nvarchar(1) NULL,
    [ReplenishUOM4] nvarchar(1) NULL,
    [ReplenishZone4] nvarchar(10) NULL,
    [CartonizeUOM4] nvarchar(1) NULL,
    [LengthUOM4] float NULL,
    [WidthUOM4] float NULL,
    [HeightUOM4] float NULL,
    [CubeUOM4] float NULL,
    [PalletWoodLength] float NULL,
    [PalletWoodWidth] float NULL,
    [PalletWoodHeight] float NULL,
    [ISWHQty5] nvarchar(1) NULL,
    [ISWHQty6] nvarchar(1) NULL,
    [ISWHQty7] nvarchar(1) NULL,
    [ISWHQty8] nvarchar(1) NULL,
    [ReplenishUOM8] nvarchar(1) NULL,
    [ReplenishZone8] nvarchar(10) NULL,
    [CartonizeUOM8] nvarchar(1) NULL,
    [LengthUOM8] float NULL,
    [WidthUOM8] float NULL,
    [HeightUOM8] float NULL,
    [ISWHQty9] nvarchar(1) NULL,
    [ReplenishUOM9] nvarchar(1) NULL,
    [ReplenishZone9] nvarchar(10) NULL,
    [CartonizeUOM9] nvarchar(1) NULL,
    [LengthUOM9] float NULL,
    [WidthUOM9] float NULL,
    [HeightUOM9] float NULL,
    [Packkey] nvarchar(10) NOT NULL DEFAULT (''),
    [PackUOM1] nvarchar(10) NULL DEFAULT (' '),
    [PackUOM2] nvarchar(10) NULL DEFAULT (' '),
    [PackUOM3] nvarchar(10) NULL DEFAULT (' '),
    [PackUOM4] nvarchar(10) NULL DEFAULT (' '),
    [PACKUOM5] nvarchar(10) NULL DEFAULT (' '),
    [PACKUOM6] nvarchar(10) NULL DEFAULT (' '),
    [PACKUOM7] nvarchar(10) NULL DEFAULT (' '),
    [PACKUOM8] nvarchar(10) NULL DEFAULT (' '),
    [PACKUOM9] nvarchar(10) NULL DEFAULT (' '),
    CONSTRAINT [PK_SCE_DL_PACK_STG] PRIMARY KEY ([RowRefNo])
);
GO

CREATE INDEX [SCE_DL_PACK_STG_Idx01] ON [dbo].[sce_dl_pack_stg] ([STG_BatchNo]);
GO
CREATE INDEX [SCE_DL_PACK_STG_Idx02] ON [dbo].[sce_dl_pack_stg] ([STG_BatchNo], [STG_SeqNo]);
GO