CREATE TABLE [dbo].[sce_dl_storer]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [StorerKey] nvarchar(15) NULL,
    [type] nvarchar(30) NULL,
    [Company] nvarchar(45) NULL,
    [VAT] nvarchar(18) NULL,
    [Address1] nvarchar(45) NULL,
    [Address2] nvarchar(45) NULL,
    [Address3] nvarchar(45) NULL,
    [Address4] nvarchar(45) NULL,
    [City] nvarchar(45) NULL,
    [State] nvarchar(45) NULL,
    [Zip] nvarchar(18) NULL,
    [Country] nvarchar(30) NULL,
    [ISOCntryCode] nvarchar(10) NULL,
    [Contact1] nvarchar(30) NULL,
    [Contact2] nvarchar(30) NULL,
    [Phone1] nvarchar(18) NULL,
    [Phone2] nvarchar(18) NULL,
    [Fax1] nvarchar(18) NULL,
    [Fax2] nvarchar(18) NULL,
    [Email1] nvarchar(60) NULL,
    [Email2] nvarchar(60) NULL,
    [B_contact1] nvarchar(30) NULL,
    [B_Contact2] nvarchar(30) NULL,
    [B_Company] nvarchar(45) NULL,
    [B_Address1] nvarchar(45) NULL,
    [B_Address2] nvarchar(45) NULL,
    [B_Address3] nvarchar(45) NULL,
    [B_Address4] nvarchar(45) NULL,
    [B_City] nvarchar(45) NULL,
    [B_State] nvarchar(45) NULL,
    [B_Zip] nvarchar(18) NULL,
    [B_Country] nvarchar(30) NULL,
    [B_ISOCntryCode] nvarchar(10) NULL,
    [B_Phone1] nvarchar(18) NULL,
    [B_Phone2] nvarchar(18) NULL,
    [B_Fax1] nvarchar(18) NULL,
    [B_Fax2] nvarchar(18) NULL,
    [Notes1] nvarchar(4000) NULL,
    [Notes2] nvarchar(4000) NULL,
    [CreditLimit] nvarchar(18) NULL,
    [CartonGroup] nvarchar(10) NULL,
    [PickCode] nvarchar(10) NULL,
    [CreatePATaskOnRFReceipt] nvarchar(10) NULL,
    [CalculatePutAwayLocation] nvarchar(10) NULL,
    [Status] nvarchar(18) NULL,
    [MinShelfLife] int NULL,
    [Logo] nvarchar(60) NULL,
    [Facility] nvarchar(5) NULL,
    [LabelPrice] nvarchar(5) NULL,
    [TolerancePctg] int NULL,
    [Pallet] nvarchar(10) NULL,
    [ConsigneeFor] nvarchar(15) NULL,
    [SUSR1] nvarchar(20) NULL,
    [SUSR2] nvarchar(20) NULL,
    [SUSR3] nvarchar(20) NULL,
    [SUSR4] nvarchar(20) NULL,
    [SUSR5] nvarchar(20) NULL,
    [Secondary] nvarchar(15) NULL,
    [XDockStrategykey] nvarchar(10) NULL,
    [AddWho] nvarchar(128) NOT NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [StrategyKey] nvarchar(10) NULL,
    [CtnPickQty] int NULL,
    [CustomerGroupCode] nvarchar(20) NULL DEFAULT (' '),
    [CustomerGroupName] nvarchar(60) NULL DEFAULT (' '),
    [MarketSegment] nvarchar(20) NULL DEFAULT (' '),
    [PickFaceMethod] nvarchar(10) NULL,
    [ProductGrouping] nvarchar(10) NULL,
    [ABCLogic] nvarchar(10) NULL DEFAULT (' '),
    [ABCPeriod] int NULL DEFAULT ((0)),
    [WorkDayPerWeek] int NULL DEFAULT ((0)),
    [PercentA] float NULL DEFAULT ((0)),
    [PercentB] float NULL DEFAULT ((0)),
    [PickLocFlag] nvarchar(1) NULL DEFAULT ('Y'),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    CONSTRAINT [PK_SCE_DL_STORER] PRIMARY KEY ([RowRefNo])
);
GO

CREATE INDEX [IDX_SCE_DL_STORER_StorerType] ON [dbo].[sce_dl_storer] ([StorerKey], [type]);
GO