CREATE TABLE [dbo].[sce_dl_taskdetail]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [TaskDetailKey] nvarchar(10) NULL DEFAULT (' '),
    [TaskType] nvarchar(10) NULL DEFAULT (' '),
    [Storerkey] nvarchar(15) NULL DEFAULT (' '),
    [Sku] nvarchar(20) NULL DEFAULT (' '),
    [Lot] nvarchar(10) NULL DEFAULT (' '),
    [UOM] nvarchar(5) NULL DEFAULT (' '),
    [UOMQty] int NULL DEFAULT ((0)),
    [Qty] int NULL DEFAULT ((0)),
    [FromLoc] nvarchar(10) NULL DEFAULT (' '),
    [LogicalFromLoc] nvarchar(10) NULL DEFAULT (' '),
    [FromID] nvarchar(18) NULL DEFAULT (' '),
    [ToLoc] nvarchar(10) NULL DEFAULT (' '),
    [LogicalToLoc] nvarchar(10) NULL DEFAULT (' '),
    [ToID] nvarchar(18) NULL DEFAULT (' '),
    [Caseid] nvarchar(20) NULL DEFAULT (' '),
    [PickMethod] nvarchar(10) NULL DEFAULT (' '),
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [StatusMsg] nvarchar(255) NULL DEFAULT (' '),
    [Priority] nvarchar(10) NULL DEFAULT (' '),
    [SourcePriority] nvarchar(10) NULL DEFAULT (' '),
    [Holdkey] nvarchar(10) NULL DEFAULT (' '),
    [UserKey] nvarchar(18) NULL DEFAULT (' '),
    [UserPosition] nvarchar(10) NULL DEFAULT ('1'),
    [UserKeyOverRide] nvarchar(18) NULL DEFAULT (' '),
    [StartTime] datetime NULL DEFAULT (getdate()),
    [EndTime] datetime NULL DEFAULT (getdate()),
    [SourceType] nvarchar(30) NULL DEFAULT (' '),
    [SourceKey] nvarchar(30) NULL DEFAULT (' '),
    [PickDetailKey] nvarchar(10) NULL DEFAULT (' '),
    [OrderKey] nvarchar(10) NULL DEFAULT (' '),
    [OrderLineNumber] nvarchar(5) NULL DEFAULT (' '),
    [ListKey] nvarchar(10) NULL DEFAULT (' '),
    [WaveKey] nvarchar(10) NULL DEFAULT (' '),
    [ReasonKey] nvarchar(10) NULL DEFAULT (' '),
    [Message01] nvarchar(20) NULL DEFAULT (' '),
    [Message02] nvarchar(20) NULL DEFAULT (' '),
    [Message03] nvarchar(20) NULL DEFAULT (' '),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [SystemQty] int NULL DEFAULT ((0)),
    [RefTaskKey] nvarchar(10) NULL DEFAULT (' '),
    [LoadKey] nvarchar(10) NULL DEFAULT (' '),
    [AreaKey] nvarchar(10) NULL DEFAULT (' '),
    [DropID] nvarchar(20) NULL DEFAULT (''),
    [TransitCount] int NULL DEFAULT ((0)),
    [TransitLOC] nvarchar(10) NULL DEFAULT (''),
    [FinalLOC] nvarchar(10) NULL DEFAULT (''),
    [FinalID] nvarchar(18) NULL DEFAULT (''),
    [Groupkey] nvarchar(10) NULL DEFAULT (''),
    [PendingMoveIn] int NULL DEFAULT ((0)),
    [QtyReplen] int NULL DEFAULT ((0)),
    [DeviceID] nvarchar(10) NULL DEFAULT (''),
    CONSTRAINT [PK_SCE_DL_TASKDETAIL] PRIMARY KEY ([RowRefNo])
);
GO
