CREATE TABLE [dbo].[sce_dl_eo]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [ExternOrderKey] nvarchar(50) NOT NULL,
    [OrderKey] nvarchar(10) NULL DEFAULT (''),
    [Storerkey] nvarchar(15) NOT NULL,
    [Source] nvarchar(10) NOT NULL DEFAULT (''),
    [BindingDate] datetime NULL DEFAULT (getdate()),
    [ShippedDate] datetime NULL DEFAULT (getdate()),
    [ExternLineNo] nvarchar(10) NOT NULL,
    [OrderLineNumber] nvarchar(5) NOT NULL,
    [SKU] nvarchar(20) NOT NULL,
    [QRCode] nvarchar(100) NOT NULL,
    [RFIDNo] nvarchar(100) NULL DEFAULT (''),
    [TIDNo] nvarchar(100) NULL DEFAULT (''),
    [PlatformName] nvarchar(100) NOT NULL DEFAULT (''),
    [PlatformOrderNo] nvarchar(50) NOT NULL DEFAULT (''),
    [Hdr_Status] nvarchar(10) NULL DEFAULT ('0'),
    [Det_Status] nvarchar(10) NULL DEFAULT ('0'),
    [Hdr_Userdefine01] nvarchar(20) NULL,
    [Hdr_Userdefine02] nvarchar(20) NULL,
    [Hdr_Userdefine03] nvarchar(20) NULL,
    [Hdr_Userdefine04] nvarchar(20) NULL,
    [Hdr_Userdefine05] nvarchar(20) NULL,
    [Hdr_Userdefine06] nvarchar(20) NULL,
    [Hdr_Userdefine07] nvarchar(20) NULL,
    [Hdr_Userdefine08] nvarchar(20) NULL,
    [Hdr_Userdefine09] nvarchar(20) NULL,
    [Hdr_Userdefine10] nvarchar(20) NULL,
    [Hdr_Notes] nvarchar(4000) NULL,
    [Det_Userdefine01] nvarchar(20) NULL,
    [Det_Userdefine02] nvarchar(20) NULL,
    [Det_Userdefine03] nvarchar(20) NULL,
    [Det_Userdefine04] nvarchar(20) NULL,
    [Det_Userdefine05] nvarchar(20) NULL,
    [Det_Userdefine06] nvarchar(20) NULL,
    [Det_Userdefine07] nvarchar(20) NULL,
    [Det_Userdefine08] nvarchar(20) NULL,
    [Det_Userdefine09] nvarchar(20) NULL,
    [Det_Userdefine10] nvarchar(20) NULL,
    [Det_Notes] nvarchar(4000) NULL,
    [Addwho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [Adddate] datetime NOT NULL DEFAULT (getdate()),
    [Editwho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [Editdate] datetime NOT NULL DEFAULT (getdate()),
    CONSTRAINT [PK_SCE_DL_EO] PRIMARY KEY ([RowRefNo])
);
GO
