CREATE TABLE [dbo].[sce_dl_tms_shp_tord]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [ShipmentGID] nvarchar(50) NOT NULL,
    [VehicleLPN] nvarchar(150) NULL,
    [EquipmentID] nvarchar(50) NOT NULL,
    [DriveName] nvarchar(100) NULL,
    [ShipmentPlannedStartDate] datetime NOT NULL,
    [ShipmentPlannedEndDate] datetime NOT NULL,
    [Route] nvarchar(150) NULL,
    [ServiceProviderID] nvarchar(50) NOT NULL,
    [ShipmentVolume] numeric(24, 6) NOT NULL DEFAULT ((0)),
    [ShipmentWeight] numeric(24, 6) NOT NULL DEFAULT ((0)),
    [ShipmentCartonCount] int NOT NULL DEFAULT ((0)),
    [ShipmentPalletCount] int NOT NULL DEFAULT ((0)),
    [OTMShipmentStatus] nvarchar(50) NOT NULL DEFAULT ((0)),
    [Banner] nvarchar(100) NULL,
    [SubBanner] nvarchar(100) NULL,
    [Wave] nvarchar(20) NULL,
    [ShipmentGroupProfile] nvarchar(100) NULL,
    [ShipmentGroup] nvarchar(100) NULL,
    [AppointmentID] nvarchar(20) NULL,
    [Principal] nvarchar(90) NULL,
    [BookingNo] int NULL,
    [ProvShipmentID] nvarchar(50) NULL,
    [OrderReleaseID] nvarchar(50) NOT NULL DEFAULT (''),
    [OrderSourceID] nvarchar(150) NOT NULL,
    [ClientReferenceID] nvarchar(150) NOT NULL,
    [Loadkey] nvarchar(10) NULL,
    [MBOLKey] nvarchar(10) NULL,
    [ParentSourceID] nvarchar(50) NULL,
    [SplitFlag] varchar(1) NULL,
    [OrderPrincipal] nvarchar(45) NOT NULL,
    [Country] nvarchar(5) NOT NULL,
    [FacilityID] nvarchar(50) NOT NULL,
    [StopSeq] int NULL,
    [IOIndicator] nvarchar(1) NULL,
    [StopServiceTime] int NULL,
    [OrderVolume] numeric(24, 6) NULL,
    [OrderWeight] numeric(24, 6) NULL,
    [OrderCartonCount] int NULL,
    [OrderPalletCount] int NULL,
    [PickPriority] nvarchar(10) NULL,
    [ErrorCode] nvarchar(50) NULL,
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    CONSTRAINT [PK_SCE_DL_TMS_SHP_TORD] PRIMARY KEY ([RowRefNo])
);
GO
