CREATE TABLE [dbo].[sce_dl_transfer]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [FromStorerKey] nvarchar(15) NULL DEFAULT (' '),
    [FromSku] nvarchar(20) NULL DEFAULT (' '),
    [FromLoc] nvarchar(10) NULL DEFAULT (' '),
    [FromLot] nvarchar(10) NULL DEFAULT (' '),
    [FromId] nvarchar(18) NULL DEFAULT (' '),
    [FromQty] int NULL DEFAULT ((0)),
    [FromPackKey] nvarchar(10) NULL DEFAULT ('STD'),
    [FromUOM] nvarchar(10) NULL DEFAULT (' '),
    [FromChannel] nvarchar(20) NULL DEFAULT (''),
    [FromChannel_ID] bigint NULL DEFAULT ((0)),
    [ToStorerKey] nvarchar(15) NULL DEFAULT (' '),
    [ToSku] nvarchar(20) NULL DEFAULT (' '),
    [ToLoc] nvarchar(10) NULL DEFAULT (' '),
    [ToLot] nvarchar(10) NULL DEFAULT (' '),
    [ToId] nvarchar(18) NULL DEFAULT (' '),
    [ToQty] int NULL DEFAULT ((0)),
    [ToPackKey] nvarchar(10) NULL DEFAULT ('STD'),
    [ToUOM] nvarchar(10) NULL DEFAULT (' '),
    [ToChannel] nvarchar(20) NULL DEFAULT (''),
    [ToChannel_ID] bigint NULL DEFAULT ((0)),
    [Facility] nvarchar(15) NULL DEFAULT (' '),
    [ToFacility] nvarchar(15) NULL DEFAULT (' '),
    [Type] nvarchar(12) NULL,
    [OpenQty] int NULL DEFAULT ((0)),
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [GenerateHOCharges] nvarchar(10) NULL DEFAULT ('1'),
    [GenerateIS_HICharges] nvarchar(10) NULL DEFAULT ('1'),
    [ReLot] nvarchar(10) NULL DEFAULT ('0'),
    [EffectiveDate] datetime NULL DEFAULT (getdate()),
    [ReasonCode] nvarchar(10) NULL,
    [CustomerRefNo] nvarchar(20) NULL DEFAULT (' '),
    [Remarks] nvarchar(200) NULL DEFAULT (' '),
    [PrintFlag] nvarchar(1) NULL,
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [LOTTABLE01] nvarchar(18) NULL DEFAULT (' '),
    [LOTTABLE02] nvarchar(18) NULL DEFAULT (' '),
    [LOTTABLE03] nvarchar(18) NULL DEFAULT (' '),
    [LOTTABLE04] datetime NULL,
    [LOTTABLE05] datetime NULL,
    [LOTTABLE06] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE07] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE08] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE09] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE10] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE11] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE12] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE13] datetime NULL,
    [LOTTABLE14] datetime NULL,
    [LOTTABLE15] datetime NULL,
    [TOLOTTABLE01] nvarchar(18) NULL DEFAULT (' '),
    [TOLOTTABLE02] nvarchar(18) NULL DEFAULT (' '),
    [TOLOTTABLE03] nvarchar(18) NULL DEFAULT (' '),
    [TOLOTTABLE04] datetime NULL,
    [TOLOTTABLE05] datetime NULL,
    [TOLOTTABLE06] nvarchar(30) NULL DEFAULT (''),
    [TOLOTTABLE07] nvarchar(30) NULL DEFAULT (''),
    [TOLOTTABLE08] nvarchar(30) NULL DEFAULT (''),
    [TOLOTTABLE09] nvarchar(30) NULL DEFAULT (''),
    [TOLOTTABLE10] nvarchar(30) NULL DEFAULT (''),
    [TOLOTTABLE11] nvarchar(30) NULL DEFAULT (''),
    [TOLOTTABLE12] nvarchar(30) NULL DEFAULT (''),
    [TOLOTTABLE13] datetime NULL,
    [TOLOTTABLE14] datetime NULL,
    [TOLOTTABLE15] datetime NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    CONSTRAINT [PK_SCE_DL_TRANSFER] PRIMARY KEY ([RowRefNo])
);
GO
