CREATE TABLE [dbo].[sce_dl_workord]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [WorkOrderKey] nvarchar(10) NULL,
    [ExternWorkOrderKey] nvarchar(20) NULL,
    [StorerKey] nvarchar(15) NULL,
    [Facility] nvarchar(5) NULL,
    [WHStatus] nvarchar(10) NULL,
    [ExternStatus] nvarchar(10) NULL,
    [Type] nvarchar(12) NULL,
    [Reason] nvarchar(10) NULL,
    [TotalPrice] nvarchar(16) NULL,
    [GenerateCharges] nvarchar(10) NULL,
    [WHRemarks] nvarchar(215) NULL,
    [Notes1] nvarchar(215) NULL,
    [Notes2] nvarchar(215) NULL,
    [WkOrdUdef1] nvarchar(18) NULL,
    [WkOrdUdef2] nvarchar(18) NULL,
    [WkOrdUdef3] nvarchar(18) NULL,
    [WkOrdUdef4] nvarchar(18) NULL,
    [WkOrdUdef5] nvarchar(18) NULL,
    [WorkOrderLineNumber] nvarchar(5) NULL,
    [ExternLineNo] nvarchar(5) NULL,
    [WDType] nvarchar(12) NULL,
    [WDReason] nvarchar(10) NULL,
    [Unit] nvarchar(10) NULL,
    [Qty] nvarchar(10) NULL,
    [Price] nvarchar(16) NULL,
    [LineValue] nvarchar(10) NULL,
    [WDRemarks] nvarchar(215) NULL,
    [WDWkOrdUdef1] nvarchar(18) NULL,
    [WDWkOrdUdef2] nvarchar(18) NULL,
    [WDWkOrdUdef3] nvarchar(18) NULL,
    [WDWkOrdUdef4] nvarchar(18) NULL,
    [WDWkOrdUdef5] nvarchar(18) NULL,
    [WDStatus] nvarchar(10) NULL,
    [AddWho] nvarchar(128) NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [WDWkOrdUdef6] datetime NULL DEFAULT (' '),
    [WDWkOrdUdef7] datetime NULL DEFAULT (' '),
    [WDWkOrdUdef8] nvarchar(30) NULL DEFAULT (' '),
    [WDWkOrdUdef9] nvarchar(30) NULL DEFAULT (' '),
    [WDWkOrdUdef10] nvarchar(30) NULL DEFAULT (' '),
    [WkOrdUdef6] datetime NULL DEFAULT (' '),
    [WkOrdUdef7] datetime NULL DEFAULT (' '),
    [WkOrdUdef8] nvarchar(30) NULL DEFAULT (' '),
    [WkOrdUdef9] nvarchar(30) NULL DEFAULT (' '),
    [WkOrdUdef10] nvarchar(30) NULL DEFAULT (' '),
    [SKU] nvarchar(20) NULL DEFAULT (''),
    CONSTRAINT [PK_SCE_DL_WORKORD] PRIMARY KEY ([RowRefNo])
);
GO
