CREATE TABLE [dbo].[sce_dl_ucc]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [UCCNo] nvarchar(40) NULL,
    [Storerkey] nvarchar(40) NULL,
    [ExternKey] nvarchar(40) NULL DEFAULT (''),
    [SKU] nvarchar(40) NULL DEFAULT (''),
    [Qty] int NULL,
    [SourceKey] nvarchar(40) NULL,
    [SourceType] nvarchar(40) NULL,
    [Userdefined01] nvarchar(15) NULL,
    [Userdefined02] nvarchar(15) NULL,
    [Userdefined03] nvarchar(20) NULL,
    [Userdefined04] nvarchar(30) NULL DEFAULT (''),
    [Userdefined05] nvarchar(30) NULL DEFAULT (''),
    [Userdefined06] nvarchar(30) NULL DEFAULT (''),
    [Userdefined07] nvarchar(30) NULL DEFAULT (''),
    [Userdefined08] nvarchar(30) NULL DEFAULT (''),
    [Userdefined09] nvarchar(30) NULL DEFAULT (''),
    [Userdefined10] nvarchar(30) NULL DEFAULT (''),
    [Status] nvarchar(20) NULL,
    [Lot] nvarchar(10) NULL DEFAULT (''),
    [Loc] nvarchar(10) NULL DEFAULT (''),
    [Id] nvarchar(18) NULL DEFAULT (''),
    [Receiptkey] nvarchar(10) NULL DEFAULT (' '),
    [ReceiptLineNumber] nvarchar(5) NULL DEFAULT (' '),
    [Orderkey] nvarchar(10) NULL DEFAULT (' '),
    [OrderLineNumber] nvarchar(5) NULL DEFAULT (' '),
    [WaveKey] nvarchar(10) NULL DEFAULT (' '),
    [PickDetailKey] nvarchar(18) NULL DEFAULT (' '),
    [UCC_RowRef] int NULL DEFAULT ((0)),
    [AddWho] nvarchar(128) NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    CONSTRAINT [PK_SCE_DL_UCC] PRIMARY KEY ([RowRefNo])
);
GO
