CREATE TABLE [dbo].[sce_dl_loc_stg]
(
    [RowRefNo] int IDENTITY(1,1) NOT NULL,
    [STG_BatchNo] int NOT NULL,
    [STG_SeqNo] int NOT NULL,
    [STG_Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [STG_ErrMsg] nvarchar(250) NOT NULL DEFAULT (''),
    [STG_AddDate] datetime NOT NULL DEFAULT (getdate()),
    [Loc] nvarchar(20) NULL,
    [Cube] float NULL,
    [Length] float NULL,
    [Width] float NULL,
    [Height] float NULL,
    [LocationType] nvarchar(20) NULL,
    [LocationFlag] nvarchar(20) NULL,
    [LocationHandling] nvarchar(20) NULL,
    [LocationCategory] nvarchar(20) NULL,
    [LogicalLocation] nvarchar(36) NULL,
    [CubicCapacity] float NULL,
    [WeightCapacity] float NULL,
    [Status] nvarchar(20) NULL,
    [LoseId] nvarchar(2) NULL,
    [Facility] nvarchar(10) NULL,
    [ABC] nvarchar(2) NULL,
    [PickZone] nvarchar(20) NULL,
    [PutawayZone] nvarchar(36) NULL,
    [SectionKey] nvarchar(20) NULL,
    [PickMethod] nvarchar(2) NULL,
    [CommingleSku] nvarchar(2) NULL,
    [CommingleLot] nvarchar(2) NULL,
    [LocLevel] int NULL,
    [Xcoord] int NULL,
    [Ycoord] int NULL,
    [Zcoord] int NULL,
    [MaxPallet] int NULL,
    [LocAisle] nvarchar(20) NULL,
    [HOSTWHCODE] nvarchar(20) NULL,
    [CCLogicalLoc] nvarchar(36) NULL,
    [ChargingPallet] float NULL,
    [AddWho] nvarchar(128) NULL,
    [AddDate] datetime NULL DEFAULT (getdate()),
    [LastCycleCount] datetime NULL,
    [CycleCountFrequency] int NULL,
    [LoseUCC] nchar(1) NULL DEFAULT ('0'),
    [NoMixLottable01] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable02] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable03] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable04] nvarchar(1) NULL DEFAULT ('0'),
    [LocBay] nvarchar(10) NULL,
    [PALogicalLoc] nvarchar(10) NULL,
    [LocCheckDigit] nvarchar(10) NULL,
    [Score] int NULL DEFAULT ((0)),
    [LocationRoom] nvarchar(30) NULL,
    [LocationGroup] nvarchar(30) NULL,
    [NoMixLottable05] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable06] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable07] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable08] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable09] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable10] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable11] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable12] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable13] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable14] nvarchar(1) NULL DEFAULT ('0'),
    [NoMixLottable15] nvarchar(1) NULL DEFAULT ('0'),
    [Floor] nvarchar(3) NULL DEFAULT (' '),
    [CycleCounter] int NULL,
    [Descr] nvarchar(60) NULL,
    [MaxCarton] int NULL,
    [MaxSKU] int NULL,
    [DisableCheckDigitAutoCompute] nvarchar(5) NULL DEFAULT ('False'),
    [ColorCode] nvarchar(20) NULL,
    CONSTRAINT [PK_SCE_DL_LOC_STG] PRIMARY KEY ([RowRefNo])
);
GO

CREATE INDEX [SCE_DL_LOC_STG_Idx01] ON [dbo].[sce_dl_loc_stg] ([STG_BatchNo]);
GO
CREATE INDEX [SCE_DL_LOC_STG_Idx02] ON [dbo].[sce_dl_loc_stg] ([STG_BatchNo], [STG_SeqNo]);
GO