CREATE TABLE [dbo].[sce_dl_kit]
(
    [RowRefNo] bigint IDENTITY(1,1) NOT NULL,
    [Storerkey] nvarchar(15) NULL,
    [ToStorerkey] nvarchar(15) NULL,
    [HType] nvarchar(12) NULL,
    [EffectiveDate] datetime NULL,
    [ReasonCode] nvarchar(10) NULL,
    [CustomerRefNo] nvarchar(10) NULL,
    [Remarks] nvarchar(200) NULL,
    [Facility] nvarchar(5) NULL,
    [HUdef01] nvarchar(18) NULL,
    [HUdef02] nvarchar(18) NULL,
    [HUdef03] nvarchar(18) NULL,
    [ExternKitKey] nvarchar(20) NULL,
    [DType] nvarchar(5) NULL,
    [SKU] nvarchar(20) NULL,
    [Lot] nvarchar(10) NULL,
    [Loc] nvarchar(10) NULL,
    [ID] nvarchar(18) NULL,
    [ExpectedQty] int NULL,
    [ExternLineNo] nvarchar(10) NULL,
    [LOTTABLE01] nvarchar(18) NULL,
    [LOTTABLE02] nvarchar(18) NULL,
    [LOTTABLE03] nvarchar(18) NULL,
    [LOTTABLE04] datetime NULL,
    [LOTTABLE05] datetime NULL,
    [LOTTABLE06] nvarchar(30) NULL,
    [LOTTABLE07] nvarchar(30) NULL,
    [LOTTABLE08] nvarchar(30) NULL,
    [LOTTABLE09] nvarchar(30) NULL,
    [LOTTABLE10] nvarchar(30) NULL,
    [LOTTABLE11] nvarchar(30) NULL,
    [LOTTABLE12] nvarchar(30) NULL,
    [LOTTABLE13] datetime NULL,
    [LOTTABLE14] datetime NULL,
    [LOTTABLE15] datetime NULL,
    [AddWho] nvarchar(128) NOT NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [Qty] int NULL,
    CONSTRAINT [PK_SCE_DL_KIT] PRIMARY KEY ([RowRefNo])
);
GO
