CREATE TABLE [dbo].[sce_dl_tms_shp_tord_stg]
(
    [RowRefNo] int IDENTITY(1,1) NOT NULL,
    [STG_BatchNo] int NOT NULL,
    [STG_SeqNo] int NOT NULL,
    [STG_Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [STG_ErrMsg] nvarchar(250) NOT NULL DEFAULT (''),
    [STG_AddDate] datetime NOT NULL DEFAULT (getdate()),
    [ShipmentGID] nvarchar(50) NULL,
    [VehicleLPN] nvarchar(150) NULL,
    [EquipmentID] nvarchar(50) NULL,
    [DriveName] nvarchar(100) NULL,
    [ShipmentPlannedStartDate] datetime NULL,
    [ShipmentPlannedEndDate] datetime NULL,
    [Route] nvarchar(150) NULL,
    [ServiceProviderID] nvarchar(50) NULL,
    [ShipmentVolume] numeric(18, 0) NULL DEFAULT ((0)),
    [ShipmentWeight] numeric(18, 0) NULL DEFAULT ((0)),
    [ShipmentCartonCount] int NULL DEFAULT ((0)),
    [ShipmentPalletCount] int NULL DEFAULT ((0)),
    [OTMShipmentStatus] nvarchar(50) NULL DEFAULT ((0)),
    [Banner] nvarchar(100) NULL,
    [SubBanner] nvarchar(100) NULL,
    [Wave] nvarchar(20) NULL,
    [ShipmentGroupProfile] nvarchar(100) NULL,
    [ShipmentGroup] nvarchar(100) NULL,
    [AppointmentID] nvarchar(20) NULL,
    [Principal] nvarchar(90) NULL,
    [BookingNo] int NULL,
    [ProvShipmentID] nvarchar(50) NULL,
    [OrderReleaseID] nvarchar(50) NULL DEFAULT (''),
    [OrderSourceID] nvarchar(150) NULL,
    [ClientReferenceID] nvarchar(150) NULL,
    [Loadkey] nvarchar(10) NULL,
    [MBOLKey] nvarchar(10) NULL,
    [ParentSourceID] nvarchar(50) NULL,
    [SplitFlag] varchar(1) NULL,
    [OrderPrincipal] nvarchar(45) NULL,
    [Country] nvarchar(5) NULL,
    [FacilityID] nvarchar(50) NULL,
    [StopSeq] int NULL,
    [IOIndicator] nvarchar(1) NULL,
    [StopServiceTime] int NULL,
    [OrderVolume] numeric(18, 0) NULL,
    [OrderWeight] numeric(18, 0) NULL,
    [OrderCartonCount] int NULL,
    [OrderPalletCount] int NULL,
    [PickPriority] nvarchar(10) NULL,
    [ErrorCode] nvarchar(50) NULL,
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    CONSTRAINT [PK_SCE_DL_TMS_SHP_TORD_STG] PRIMARY KEY ([RowRefNo])
);
GO

CREATE INDEX [SCE_DL_TMS_SHP_TORD_STG_Idx01] ON [dbo].[sce_dl_tms_shp_tord_stg] ([STG_BatchNo]);
GO
CREATE INDEX [SCE_DL_TMS_SHP_TORD_STG_Idx02] ON [dbo].[sce_dl_tms_shp_tord_stg] ([STG_BatchNo], [STG_SeqNo]);
GO