CREATE TABLE [dbo].[sce_dl_asn_stg]
(
    [RowRefNo] int IDENTITY(1,1) NOT NULL,
    [STG_BatchNo] int NOT NULL,
    [STG_SeqNo] int NOT NULL,
    [STG_Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [STG_ErrMsg] nvarchar(250) NOT NULL DEFAULT (''),
    [STG_AddDate] datetime NOT NULL DEFAULT (getdate()),
    [ExternReceiptkey] nvarchar(50) NULL,
    [ReceiptGroup] nvarchar(20) NULL,
    [Storerkey] nvarchar(15) NULL,
    [ReceiptDate] datetime NULL,
    [POKey] nvarchar(18) NULL,
    [CarrierKey] nvarchar(15) NULL,
    [CarrierName] nvarchar(30) NULL,
    [CarrierAddress1] nvarchar(45) NULL,
    [CarrierAddress2] nvarchar(45) NULL,
    [CarrierCity] nvarchar(45) NULL,
    [CarrierState] nvarchar(45) NULL,
    [CarrierZip] nvarchar(10) NULL,
    [CarrierReference] nvarchar(18) NULL,
    [WarehouseReference] nvarchar(18) NULL,
    [OriginCountry] nvarchar(30) NULL,
    [DestinationCountry] nvarchar(30) NULL,
    [VehicleNumber] nvarchar(18) NULL,
    [VehicleDate] nvarchar(18) NULL,
    [PlaceOfLoading] nvarchar(18) NULL,
    [PlaceOfDischarge] nvarchar(18) NULL,
    [PlaceOfDelivery] nvarchar(18) NULL,
    [IncoTerms] nvarchar(10) NULL,
    [TermsNote] nvarchar(18) NULL,
    [ContainerKey] nvarchar(18) NULL,
    [Signatory] nvarchar(18) NULL,
    [PlaceofIssue] nvarchar(18) NULL,
    [Notes] nvarchar(4000) NULL,
    [ContainerType] nvarchar(20) NULL,
    [ContainerQty] int NULL,
    [BilledContainerQty] int NULL,
    [RECType] nvarchar(10) NULL,
    [ASNReason] nvarchar(10) NULL,
    [Facility] nvarchar(15) NULL,
    [Appointment_No] nvarchar(10) NULL,
    [xDockFlag] nvarchar(1) NULL,
    [Receiptkey] nvarchar(10) NULL,
    [HUSR01] nvarchar(30) NULL,
    [HUSR02] nvarchar(30) NULL,
    [HUSR03] nvarchar(30) NULL,
    [HUSR04] nvarchar(30) NULL,
    [HUSR05] nvarchar(30) NULL,
    [HUSR06] datetime NULL,
    [HUSR07] datetime NULL,
    [HUSR08] nvarchar(30) NULL,
    [HUSR09] nvarchar(30) NULL,
    [HUSR10] nvarchar(30) NULL,
    [DOCTYPE] nvarchar(1) NULL,
    [RoutingTool] nvarchar(30) NULL,
    [NoOfMasterCtn] int NULL,
    [NoOfTTLUnit] int NULL,
    [NoOfPallet] int NULL,
    [HWeight] float NULL,
    [WeightUnit] nvarchar(20) NULL,
    [HCube] float NULL,
    [CubeUnit] nvarchar(20) NULL,
    [ExternLineNo] nvarchar(20) NULL,
    [SKU] nvarchar(20) NULL,
    [AltSKU] nvarchar(20) NULL,
    [RetailSKU] nvarchar(20) NULL,
    [UPC] nvarchar(30) NULL,
    [Style] nvarchar(20) NULL,
    [Color] nvarchar(10) NULL,
    [Size] nvarchar(5) NULL,
    [ID] nvarchar(18) NULL,
    [DateReceived] datetime NULL,
    [QtyExpected] int NULL,
    [BeforeReceivedQty] int NULL,
    [UOM] nvarchar(10) NULL,
    [Packkey] nvarchar(10) NULL,
    [VesselKey] nvarchar(18) NULL,
    [VoyageKey] nvarchar(18) NULL,
    [XdockKey] nvarchar(18) NULL,
    [ToLoc] nvarchar(10) NULL,
    [ToLot] nvarchar(10) NULL,
    [ToID] nvarchar(18) NULL,
    [ConditionCode] nvarchar(10) NULL,
    [Lottable01] nvarchar(18) NULL,
    [Lottable02] nvarchar(18) NULL,
    [Lottable03] nvarchar(18) NULL,
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [CaseCnt] int NULL,
    [InnerPack] int NULL,
    [Pallet] int NULL,
    [DCube] float NULL,
    [DGrossWgt] float NULL,
    [DNetWgt] float NULL,
    [OtherUnit1] float NULL,
    [OtherUnit2] float NULL,
    [UnitPrice] float NULL,
    [ExtendedPrice] float NULL,
    [SubReasonCode] nvarchar(10) NULL,
    [PutawayLoc] nvarchar(10) NULL,
    [POLineNumber] nvarchar(5) NULL,
    [ExternPOKey] nvarchar(20) NULL,
    [DUSR01] nvarchar(30) NULL,
    [DUSR02] nvarchar(30) NULL,
    [DUSR03] nvarchar(30) NULL,
    [DUSR04] nvarchar(30) NULL,
    [DUSR05] nvarchar(30) NULL,
    [DUSR06] datetime NULL,
    [DUSR07] datetime NULL,
    [DUSR08] nvarchar(30) NULL,
    [DUSR09] nvarchar(30) NULL,
    [DUSR10] nvarchar(30) NULL,
    [AddWho] nvarchar(128) NULL,
    [AddDate] datetime NULL DEFAULT (getdate()),
    [Lottable06] nvarchar(30) NULL,
    [Lottable07] nvarchar(30) NULL,
    [Lottable08] nvarchar(30) NULL,
    [Lottable09] nvarchar(30) NULL,
    [Lottable10] nvarchar(30) NULL,
    [Lottable11] nvarchar(30) NULL,
    [Lottable12] nvarchar(30) NULL,
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [ReceiptLineNumber] nvarchar(5) NULL,
    [PROCESSTYPE] nvarchar(1) NULL,
    [SellerName] nvarchar(45) NULL DEFAULT (''),
    [SellerCompany] nvarchar(45) NULL DEFAULT (''),
    [SellerAddress1] nvarchar(45) NULL DEFAULT (''),
    [SellerAddress2] nvarchar(45) NULL DEFAULT (''),
    [SellerAddress3] nvarchar(45) NULL DEFAULT (''),
    [SellerAddress4] nvarchar(45) NULL DEFAULT (''),
    [SellerCity] nvarchar(45) NULL DEFAULT (''),
    [SellerState] nvarchar(45) NULL DEFAULT (''),
    [SellerZip] nvarchar(18) NULL DEFAULT (''),
    [SellerCountry] nvarchar(30) NULL DEFAULT (''),
    [SellerContact1] nvarchar(30) NULL DEFAULT (''),
    [SellerContact2] nvarchar(30) NULL DEFAULT (''),
    [SellerPhone1] nvarchar(18) NULL DEFAULT (''),
    [SellerPhone2] nvarchar(18) NULL DEFAULT (''),
    [SellerEmail1] nvarchar(60) NULL DEFAULT (''),
    [SellerEmail2] nvarchar(60) NULL DEFAULT (''),
    [SellerFax1] nvarchar(18) NULL DEFAULT (''),
    [SellerFax2] nvarchar(18) NULL DEFAULT (''),
    [CTNTYPE1] nvarchar(30) NULL,
    [CTNTYPE2] nvarchar(30) NULL,
    [CTNTYPE3] nvarchar(30) NULL,
    [CTNTYPE4] nvarchar(30) NULL,
    [CTNTYPE5] nvarchar(30) NULL,
    [CTNTYPE6] nvarchar(30) NULL,
    [CTNTYPE7] nvarchar(30) NULL,
    [CTNTYPE8] nvarchar(30) NULL,
    [CTNTYPE9] nvarchar(30) NULL,
    [CTNTYPE10] nvarchar(30) NULL,
    [PACKTYPE1] nvarchar(30) NULL,
    [PACKTYPE2] nvarchar(30) NULL,
    [PACKTYPE3] nvarchar(30) NULL,
    [PACKTYPE4] nvarchar(30) NULL,
    [PACKTYPE5] nvarchar(30) NULL,
    [PACKTYPE6] nvarchar(30) NULL,
    [PACKTYPE7] nvarchar(30) NULL,
    [PACKTYPE8] nvarchar(30) NULL,
    [PACKTYPE9] nvarchar(30) NULL,
    [PACKTYPE10] nvarchar(30) NULL,
    [CTNCNT1] int NULL,
    [CTNCNT2] int NULL,
    [CTNCNT3] int NULL,
    [CTNCNT4] int NULL,
    [CTNCNT5] int NULL,
    [CTNCNT6] int NULL,
    [CTNCNT7] int NULL,
    [CTNCNT8] int NULL,
    [CTNCNT9] int NULL,
    [CTNCNT10] int NULL,
    [CTNQTY1] int NULL,
    [CTNQTY2] int NULL,
    [CTNQTY3] int NULL,
    [CTNQTY4] int NULL,
    [CTNQTY5] int NULL,
    [CTNQTY6] int NULL,
    [CTNQTY7] int NULL,
    [CTNQTY8] int NULL,
    [CTNQTY9] int NULL,
    [CTNQTY10] int NULL,
    [GIS_ControlNo] nvarchar(20) NULL,
    [Cust_ISA_ControlNo] nvarchar(20) NULL DEFAULT (''),
    [Cust_GIS_ControlNo] nvarchar(20) NULL DEFAULT (''),
    [GIS_ProcessTime] datetime NULL,
    [Cust_EDIAckTime] datetime NULL,
    [FinalizeDate] datetime NULL DEFAULT (getdate()),
    [RIEcomReceiveId] nvarchar(45) NULL DEFAULT (''),
    [RIEcomOrderId] nvarchar(45) NULL DEFAULT (''),
    [RIReceiptAmount] float NULL DEFAULT ((0)),
    [RINotes] nvarchar(500) NULL DEFAULT (''),
    [RINotes2] nvarchar(500) NULL DEFAULT (''),
    [Channel] nvarchar(20) NULL DEFAULT (''),
    [Channel_ID] bigint NULL DEFAULT ((0)),
    [OpenQty] int NULL,
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [EffectiveDate] datetime NULL,
    [MBOLKey] nvarchar(10) NULL,
    [LoadKey] nvarchar(10) NULL,
    [HoldChannel] nvarchar(1) NULL DEFAULT ('0'),
    [QtyAdjusted] int NULL DEFAULT ((0)),
    [QtyReceived] int NULL DEFAULT ((0)),
    [FreeGoodQtyExpected] int NULL DEFAULT ((0)),
    [FreeGoodQtyReceived] int NULL DEFAULT ((0)),
    [ExportStatus] nvarchar(1) NULL DEFAULT ('0'),
    [SplitPalletFlag] nvarchar(1) NULL DEFAULT ('N'),
    [TrackingNo] nvarchar(40) NULL DEFAULT (''),
    [RIStoreName] nvarchar(40) NULL,
    [PalletType] nvarchar(10) NULL,
    CONSTRAINT [PK_SCE_DL_ASN_STG] PRIMARY KEY ([RowRefNo])
);
GO

CREATE INDEX [SCE_DL_ASN_STG_Idx01] ON [dbo].[sce_dl_asn_stg] ([STG_BatchNo]);
GO
CREATE INDEX [SCE_DL_ASN_STG_Idx02] ON [dbo].[sce_dl_asn_stg] ([STG_BatchNo], [STG_SeqNo]);
GO