CREATE TABLE [dbo].[shortpicklog]
(
    [Rowref] int IDENTITY(1,1) NOT NULL,
    [MbolKey] nvarchar(10) NULL,
    [DeleteWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [DeleteDate] datetime NOT NULL DEFAULT (getdate()),
    [PickDetailKey] nvarchar(18) NOT NULL,
    [CaseID] nvarchar(20) NULL,
    [PickHeaderKey] nvarchar(18) NULL,
    [OrderKey] nvarchar(10) NULL,
    [OrderLineNumber] nvarchar(5) NULL,
    [Lot] nvarchar(10) NULL,
    [Storerkey] nvarchar(15) NULL,
    [Sku] nvarchar(20) NULL,
    [AltSku] nvarchar(20) NULL,
    [UOM] nvarchar(10) NULL,
    [UOMQty] int NULL,
    [Qty] int NULL,
    [QtyMoved] int NULL,
    [Status] nvarchar(10) NULL,
    [DropID] nvarchar(20) NULL,
    [Loc] nvarchar(10) NULL,
    [ID] nvarchar(18) NULL,
    [PackKey] nvarchar(10) NULL,
    [UpdateSource] nvarchar(10) NULL,
    [CartonGroup] nvarchar(10) NULL,
    [CartonType] nvarchar(10) NULL,
    [ToLoc] nvarchar(10) NULL,
    [DoReplenish] nvarchar(1) NULL,
    [ReplenishZone] nvarchar(10) NULL,
    [DoCartonize] nvarchar(1) NULL,
    [PickMethod] nvarchar(1) NULL,
    [WaveKey] nvarchar(10) NULL,
    [EffectiveDate] datetime NULL,
    [AddDate] datetime NULL,
    [AddWho] nvarchar(128) NULL,
    [EditDate] datetime NULL,
    [EditWho] nvarchar(128) NULL,
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [OptimizeCop] nvarchar(1) NULL,
    [ShipFlag] nvarchar(1) NULL,
    [PickSlipNo] nvarchar(10) NULL,
    [TaskDetailKey] nvarchar(10) NULL,
    [TaskManagerReasonKey] nvarchar(10) NULL,
    [Notes] nvarchar(MAX) NULL,
    CONSTRAINT [PK_ShortPickLog] PRIMARY KEY ([Rowref])
);
GO

CREATE INDEX [IX_ShortPickLog] ON [dbo].[shortpicklog] ([PickDetailKey]);
GO