CREATE TABLE [dbo].[skuinfo]
(
    [Storerkey] nvarchar(15) NOT NULL,
    [Sku] nvarchar(20) NOT NULL,
    [ExtendedField01] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField02] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField03] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField04] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField05] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField06] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField07] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField08] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField09] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField10] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField11] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField12] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField13] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField14] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField15] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField16] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField17] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField18] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField19] nvarchar(30) NULL DEFAULT (' '),
    [ExtendedField20] nvarchar(30) NULL DEFAULT (' '),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [ExtendedField21] nvarchar(4000) NULL,
    [ExtendedField22] nvarchar(4000) NULL,
    CONSTRAINT [PK_SkuInfo] PRIMARY KEY ([Storerkey], [Sku])
);
GO
