CREATE TABLE [dbo].[stg_docstatustrack]
(
    [RecordID] bigint IDENTITY(1,1) NOT NULL,
    [STG_BatchNo] int NOT NULL,
    [No] int NOT NULL,
    [STG_Status] nvarchar(1) NOT NULL DEFAULT ('0'),
    [STG_ErrMsg] nvarchar(250) NOT NULL DEFAULT (''),
    [STG_AddDate] datetime NOT NULL DEFAULT (getdate()),
    [TableName] nvarchar(30) NOT NULL DEFAULT (''),
    [DocumentNo] nvarchar(20) NOT NULL DEFAULT (''),
    [Key1] nvarchar(20) NOT NULL DEFAULT (''),
    [Key2] nvarchar(20) NOT NULL DEFAULT (''),
    [DocStatus] nvarchar(10) NULL DEFAULT ((0)),
    [TransDate] datetime NULL DEFAULT (getdate()),
    [Userdefine01] nvarchar(30) NULL,
    [Userdefine02] nvarchar(30) NULL,
    [Userdefine03] nvarchar(30) NULL,
    [Userdefine04] nvarchar(30) NULL,
    [Userdefine05] nvarchar(30) NULL,
    [Userdefine06] datetime NULL,
    [Userdefine07] datetime NULL,
    [Userdefine08] nvarchar(30) NULL,
    [Userdefine09] nvarchar(30) NULL,
    [Userdefine10] nvarchar(30) NULL,
    [Finalized] nchar(1) NULL DEFAULT ('N'),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [TrafficCop] nchar(1) NULL,
    [ArchiveCop] nchar(1) NULL,
    [StorerKey] nvarchar(15) NULL DEFAULT (' '),
    [HashValue] tinyint NOT NULL DEFAULT (abs(checksum(newid())%(256))),
    [Facility] nvarchar(5) NOT NULL DEFAULT (''),
    CONSTRAINT [PK_STG_DocStatusTrack] PRIMARY KEY ([RecordID])
);
GO
