CREATE TABLE [dbo].[stocktakesheetparameters]
(
    [StockTakeKey] nvarchar(10) NOT NULL,
    [Facility] nvarchar(5) NOT NULL,
    [StorerKey] nvarchar(60) NOT NULL,
    [ZoneParm] nvarchar(60) NULL DEFAULT ('ALL'),
    [AisleParm] nvarchar(60) NULL DEFAULT ('ALL'),
    [LevelParm] nvarchar(60) NULL DEFAULT ('0 - 99'),
    [HostWHCodeParm] nvarchar(60) NULL DEFAULT ('ALL'),
    [SKUParm] nvarchar(125) NULL DEFAULT ('ALL'),
    [AgencyParm] nvarchar(125) NULL DEFAULT ('ALL'),
    [ABCParm] nvarchar(60) NULL DEFAULT ('ALL'),
    [Protect] nvarchar(1) NULL DEFAULT ('N'),
    [Password] nvarchar(10) NULL DEFAULT (' '),
    [WithQuantity] nvarchar(1) NULL DEFAULT ('Y'),
    [ClearHistory] nvarchar(1) NULL DEFAULT ('Y'),
    [EmptyLocation] nvarchar(1) NULL DEFAULT ('Y'),
    [LinesPerPage] int NULL,
    [FinalizeStage] int NOT NULL DEFAULT ((0)),
    [PopulateStage] int NOT NULL DEFAULT ((0)),
    [GroupLottable05] nvarchar(10) NULL DEFAULT (' '),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [AdjReasonCode] nvarchar(10) NULL DEFAULT (' '),
    [AdjType] nvarchar(3) NULL DEFAULT (' '),
    [ArchiveCop] nvarchar(1) NULL,
    [BlankCSheetHideLoc] nvarchar(1) NULL DEFAULT ('N'),
    [BlankCSheetNoOfPage] int NULL DEFAULT ((0)),
    [SkugroupParm] nvarchar(125) NULL DEFAULT ('ALL'),
    [ExcludeQtyPicked] nvarchar(1) NULL DEFAULT ('N'),
    [CountType] nvarchar(10) NULL DEFAULT (''),
    [ExtendedParm1Field] nvarchar(50) NULL DEFAULT (''),
    [ExtendedParm1] nvarchar(125) NULL DEFAULT (''),
    [ExtendedParm2Field] nvarchar(50) NULL DEFAULT (''),
    [ExtendedParm2] nvarchar(125) NULL DEFAULT (''),
    [ExtendedParm3Field] nvarchar(50) NULL DEFAULT (''),
    [ExtendedParm3] nvarchar(125) NULL DEFAULT (''),
    [ExcludeQtyAllocated] nvarchar(1) NULL DEFAULT ('N'),
    [StrategyKey] nvarchar(30) NOT NULL DEFAULT (''),
    [Parameter01] nvarchar(125) NULL DEFAULT (''),
    [Parameter02] nvarchar(125) NULL DEFAULT (''),
    [Parameter03] nvarchar(125) NULL DEFAULT (''),
    [Parameter04] nvarchar(125) NULL DEFAULT (''),
    [Parameter05] nvarchar(125) NULL DEFAULT (''),
    [CountSheetGroupBy01] nvarchar(50) NULL DEFAULT ('LOC.PutawayZone'),
    [CountSheetGroupBy02] nvarchar(50) NULL DEFAULT ('LOC.LocAisle'),
    [CountSheetGroupBy03] nvarchar(50) NULL DEFAULT ('LOC.LocLevel'),
    [CountSheetGroupBy04] nvarchar(50) NULL DEFAULT (''),
    [CountSheetGroupBy05] nvarchar(50) NULL DEFAULT (''),
    [CountSheetSortBy01] nvarchar(50) NULL DEFAULT ('LOC.CCLogicalLoc'),
    [CountSheetSortBy02] nvarchar(50) NULL DEFAULT ('LOC.Loc'),
    [CountSheetSortBy03] nvarchar(50) NULL DEFAULT ('LOTxLOCxID.ID'),
    [CountSheetSortBy04] nvarchar(50) NULL DEFAULT ('LOTxLOCxID.Sku'),
    [CountSheetSortBy05] nvarchar(50) NULL DEFAULT ('LOTxLOCxID.Lot'),
    [CountSheetSortBy06] nvarchar(50) NULL DEFAULT (''),
    [CountSheetSortBy07] nvarchar(50) NULL DEFAULT (''),
    [CountSheetSortBy08] nvarchar(50) NULL DEFAULT (''),
    [BlankCSheetLineByMaxPLT] nvarchar(1) NULL DEFAULT ('N'),
    [BlankCSheetDPTRNOnly] nvarchar(1) NULL DEFAULT ('N'),
    [QueryinJSON] nvarchar(4000) NOT NULL DEFAULT (''),
    [Status] nvarchar(10) NOT NULL DEFAULT (''),
    [LocPerPage] int NULL DEFAULT ((0)),
    CONSTRAINT [PK_StockTakeSheetParameters] PRIMARY KEY ([StockTakeKey])
);
GO
