CREATE TABLE [dbo].[storer]
(
    [StorerKey] nvarchar(15) NOT NULL,
    [type] nvarchar(30) NULL DEFAULT ('1'),
    [Company] nvarchar(45) NULL,
    [VAT] nvarchar(18) NULL,
    [Address1] nvarchar(45) NULL,
    [Address2] nvarchar(45) NULL,
    [Address3] nvarchar(45) NULL,
    [Address4] nvarchar(45) NULL,
    [City] nvarchar(45) NULL,
    [State] nvarchar(45) NULL,
    [Zip] nvarchar(18) NULL,
    [Country] nvarchar(30) NULL,
    [ISOCntryCode] nvarchar(10) NULL,
    [Contact1] nvarchar(30) NULL,
    [Contact2] nvarchar(30) NULL,
    [Phone1] nvarchar(18) NULL,
    [Phone2] nvarchar(18) NULL,
    [Fax1] nvarchar(18) NULL,
    [Fax2] nvarchar(18) NULL,
    [Email1] nvarchar(60) NULL,
    [Email2] nvarchar(60) NULL,
    [B_contact1] nvarchar(30) NULL,
    [B_Contact2] nvarchar(30) NULL,
    [B_Company] nvarchar(45) NULL,
    [B_Address1] nvarchar(45) NULL,
    [B_Address2] nvarchar(45) NULL,
    [B_Address3] nvarchar(45) NULL,
    [B_Address4] nvarchar(45) NULL,
    [B_City] nvarchar(45) NULL,
    [B_State] nvarchar(45) NULL,
    [B_Zip] nvarchar(18) NULL,
    [B_Country] nvarchar(30) NULL,
    [B_ISOCntryCode] nvarchar(10) NULL,
    [B_Phone1] nvarchar(18) NULL,
    [B_Phone2] nvarchar(18) NULL,
    [B_Fax1] nvarchar(18) NULL,
    [B_Fax2] nvarchar(18) NULL,
    [Notes1] nvarchar(4000) NULL,
    [Notes2] nvarchar(4000) NULL,
    [CreditLimit] nvarchar(18) NOT NULL DEFAULT ('0'),
    [CartonGroup] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [PickCode] nvarchar(10) NOT NULL DEFAULT ('NSPFIFO'),
    [CreatePATaskOnRFReceipt] nvarchar(10) NOT NULL DEFAULT ('0'),
    [CalculatePutAwayLocation] nvarchar(10) NOT NULL DEFAULT ('2'),
    [Status] nvarchar(18) NOT NULL DEFAULT ('ACTIVE'),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [MinShelfLife] int NULL DEFAULT ((0)),
    [Logo] nvarchar(60) NULL DEFAULT (' '),
    [Facility] nvarchar(5) NULL,
    [LabelPrice] nvarchar(5) NULL,
    [TolerancePctg] int NULL,
    [Pallet] nvarchar(10) NULL,
    [ConsigneeFor] nvarchar(15) NULL,
    [SUSR1] nvarchar(20) NULL DEFAULT (' '),
    [SUSR2] nvarchar(20) NULL DEFAULT (' '),
    [SUSR3] nvarchar(20) NULL DEFAULT (' '),
    [SUSR4] nvarchar(20) NULL DEFAULT (' '),
    [SUSR5] nvarchar(20) NULL DEFAULT (' '),
    [Secondary] nvarchar(15) NULL DEFAULT (' '),
    [XDockStrategykey] nvarchar(10) NULL DEFAULT ('STD'),
    [StrategyKey] nvarchar(10) NULL DEFAULT (' '),
    [CtnPickQty] int NOT NULL DEFAULT ((0)),
    [CustomerGroupCode] nvarchar(20) NOT NULL DEFAULT (' '),
    [CustomerGroupName] nvarchar(60) NULL DEFAULT (' '),
    [MarketSegment] nvarchar(20) NOT NULL DEFAULT (' '),
    [ABCLogic] nvarchar(10) NOT NULL DEFAULT (' '),
    [ABCPeriod] int NOT NULL DEFAULT ((0)),
    [WorkDayPerWeek] int NOT NULL DEFAULT ((0)),
    [PercentA] float NOT NULL DEFAULT ((0)),
    [PercentB] float NOT NULL DEFAULT ((0)),
    [PickFaceMethod] nvarchar(10) NULL,
    [ProductGrouping] nvarchar(10) NULL,
    [PickLocFlag] nvarchar(1) NOT NULL DEFAULT ('Y'),
    [TransportChargeGroup] nvarchar(6) NULL,
    [PalletMgmtFlag] nvarchar(10) NULL,
    [PMAccountNo] nvarchar(30) NULL,
    [ABCCalendarKey] nvarchar(10) NULL DEFAULT (''),
    [AutoFinalizeABC] nvarchar(1) NULL DEFAULT ('N'),
    [UpdateCCDay] nvarchar(1) NULL DEFAULT ('N'),
    [CalcZeroMoveAsC] nvarchar(1) NULL DEFAULT ('N'),
    [ABCCalcByPickQty] nvarchar(1) NULL DEFAULT ('N'),
    [SalesChannel] nvarchar(50) NULL DEFAULT (''),
    [CMDCode] nvarchar(20) NOT NULL DEFAULT (''),
    [ConcernCode] nvarchar(20) NULL DEFAULT (''),
    [TradingName] nvarchar(127) NULL DEFAULT (''),
    [ArcheType] nvarchar(40) NULL DEFAULT (''),
    CONSTRAINT [PKStorer] PRIMARY KEY ([StorerKey])
);
GO

CREATE INDEX [ConsigneeFor_SUSR1] ON [dbo].[storer] ([ConsigneeFor], [SUSR1]);
GO
CREATE INDEX [IX_STORER_CustomerGroupCode] ON [dbo].[storer] ([CustomerGroupCode]);
GO