CREATE TABLE [dbo].[storersodefault]
(
    [StorerKey] nvarchar(15) NOT NULL,
    [BillTo] nvarchar(15) NULL,
    [OrderType] nvarchar(10) NULL,
    [Priority] nvarchar(10) NULL,
    [Route] nvarchar(10) NULL,
    [Door] nvarchar(10) NULL,
    [Stop] nvarchar(10) NULL,
    [Destination] nvarchar(30) NULL,
    [Terms] nvarchar(30) NULL,
    [DeliveryPlace] nvarchar(30) NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [xDockLane] nvarchar(10) NULL DEFAULT (' '),
    [XDockRoute] nvarchar(10) NULL,
    [XDockSTOP] nvarchar(10) NULL,
    [CutOffHour] nvarchar(2) NULL,
    [CutOffMin] nvarchar(2) NULL,
    [DeliveryTerm] int NULL DEFAULT ((0)),
    [Mon] nvarchar(1) NULL DEFAULT ((0)),
    [Tue] nvarchar(1) NULL DEFAULT ((0)),
    [Wed] nvarchar(1) NULL DEFAULT ((0)),
    [Thu] nvarchar(1) NULL DEFAULT ((0)),
    [Fri] nvarchar(1) NULL DEFAULT ((0)),
    [Sat] nvarchar(1) NULL DEFAULT ((0)),
    [Sun] nvarchar(1) NULL DEFAULT ((0)),
    [HolidayKey] nvarchar(10) NULL,
    [ScheduleKey] nvarchar(30) NULL DEFAULT (' '),
    [AddrOvrFlag] nvarchar(1) NULL DEFAULT (' '),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [ReasonCodeReqForSOCancel] nvarchar(3) NOT NULL DEFAULT ('No'),
    CONSTRAINT [PK_StorerSODefault] PRIMARY KEY ([StorerKey])
);
GO
