CREATE TABLE [dbo].[storerbilling]
(
    [StorerKey] nvarchar(15) NOT NULL,
    [RSMinimumInvoiceCharge] decimal(22, 6) NOT NULL DEFAULT ((0.0)),
    [RSMinimumInvoiceTaxGroup] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [RSMinimumInvoiceGLDist] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [ISMinimumInvoiceCharge] decimal(22, 6) NOT NULL DEFAULT ((0.0)),
    [ISMinimumInvoiceTaxGroup] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [ISMinimumInvoiceGLDist] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [HIMinimumInvoiceCharge] decimal(22, 6) NOT NULL DEFAULT ((0.0)),
    [HIMinimumInvoiceTaxGroup] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [HIMinimumInvoiceGLDist] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [HOMinimumShipmentCharge] decimal(22, 6) NOT NULL DEFAULT ((0.0)),
    [HOMinimumShipmentTaxGroup] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [HOMinimumShipmentGLDist] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [ISMinimumReceiptCharge] decimal(22, 6) NOT NULL DEFAULT ((0.0)),
    [ISMinimumReceiptTaxGroup] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [ISMinimumReceiptGLDist] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [HIMinimumReceiptCharge] decimal(22, 6) NOT NULL DEFAULT ((0.0)),
    [HIMinimumReceiptTaxGroup] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [HIMinimumReceiptGLDist] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [InvoiceNumberStrategy] nvarchar(10) NOT NULL DEFAULT ('0'),
    [BillingGroup] nvarchar(10) NULL DEFAULT ('1'),
    [LockBatch] nvarchar(10) NULL DEFAULT (' '),
    [LockWho] nvarchar(18) NULL DEFAULT (' '),
    [AddDate] datetime NULL,
    [AddWho] nvarchar(128) NULL,
    [EditDate] datetime NULL,
    [EditWho] nvarchar(128) NULL,
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    CONSTRAINT [PKStorerBilling] PRIMARY KEY ([StorerKey]),
    CONSTRAINT [FK_STORERBILLING_STORER_01] FOREIGN KEY ([StorerKey]) REFERENCES [dbo].[STORER] ([StorerKey])
);
GO
