CREATE TABLE [dbo].[tariffdetail]
(
    [TariffDetailKey] nvarchar(10) NOT NULL,
    [TariffKey] nvarchar(10) NOT NULL,
    [ChargeType] nvarchar(10) NOT NULL,
    [Descrip] nvarchar(30) NOT NULL DEFAULT (' '),
    [Rate] decimal(22, 6) NOT NULL,
    [Base] nvarchar(1) NOT NULL DEFAULT ('Q'),
    [MasterUnits] decimal(12, 6) NOT NULL DEFAULT ((1.0)),
    [RoundMasterUnits] nvarchar(10) NOT NULL DEFAULT ('0'),
    [UOMShow] nvarchar(10) NOT NULL DEFAULT (' '),
    [TaxGroupKey] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [GLDistributionKey] nvarchar(10) NOT NULL DEFAULT ('XXXXXXXXXX'),
    [MinimumCharge] decimal(22, 6) NOT NULL DEFAULT ((0.0)),
    [MinimumGroup] nvarchar(10) NOT NULL DEFAULT ('LOT'),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [CostRate] decimal(22, 6) NULL DEFAULT ((0.0)),
    [CostBase] nvarchar(1) NULL DEFAULT ('Q'),
    [CostMasterUnits] decimal(12, 6) NULL DEFAULT ((1.0)),
    [CostUOMShow] nvarchar(10) NULL DEFAULT (' '),
    [UOM1Mult] decimal(12, 6) NULL DEFAULT ((1.0)),
    [UOM2Mult] decimal(12, 6) NULL DEFAULT ((1.0)),
    [UOM3Mult] decimal(12, 6) NULL DEFAULT ((1.0)),
    [UOM4Mult] decimal(12, 6) NULL DEFAULT ((1.0)),
    CONSTRAINT [PKTariffDetail] PRIMARY KEY ([TariffDetailKey]),
    CONSTRAINT [FK_TariffDetail_GLDist_01] FOREIGN KEY ([GLDistributionKey]) REFERENCES [dbo].[GLDistribution] ([GLDistributionKey]),
    CONSTRAINT [FK_TariffDetail_TaxGroupKey_01] FOREIGN KEY ([TaxGroupKey]) REFERENCES [dbo].[TaxGroup] ([TaxGroupKey]),
    CONSTRAINT [FKTariffDetail] FOREIGN KEY ([TariffKey]) REFERENCES [dbo].[Tariff] ([TariffKey]),
    CONSTRAINT [CK_TariffDetail_Base] CHECK ([Base]='R' OR [Base]='P' OR [Base]='F' OR [Base]='C' OR [Base]='G' OR [Base]='Q'),
    CONSTRAINT [CK_TariffDetail_CostBase] CHECK ([CostBase]='R' OR [CostBase]='P' OR [CostBase]='F' OR [CostBase]='C' OR [CostBase]='G' OR [CostBase]='Q'),
    CONSTRAINT [CK_TariffDetail_CostMU] CHECK ([CostMasterUnits]>(0.0)),
    CONSTRAINT [CK_TariffDetail_M_U] CHECK ([MasterUnits]>(0.0)),
    CONSTRAINT [CK_TariffDetailChargeType] CHECK ([ChargeType]='MR' OR [ChargeType]='DO' OR [ChargeType]='DI' OR [ChargeType]='SP' OR [ChargeType]='AC' OR [ChargeType]='MI' OR [ChargeType]='HO' OR [ChargeType]='HI' OR [ChargeType]='RS' OR [ChargeType]='IS'),
    CONSTRAINT [CK_TariffDetail_MinimumGroup01] CHECK ([MinimumGroup]='LOTTABLE06' OR [MinimumGroup]='LOTTABLE07' OR [MinimumGroup]='LOTTABLE08' OR [MinimumGroup]='LOTTABLE09' OR [MinimumGroup]='LOTTABLE10' OR [MinimumGroup]='LOTTABLE11' OR [MinimumGroup]='LOTTABLE12' OR [MinimumGroup]='LOTTABLE03' OR [MinimumGroup]='LOTTABLE02' OR [MinimumGroup]='LOTTABLE01' OR [MinimumGroup]='LOT')
);
GO
