CREATE TABLE [dbo].[taskdetail_wip]
(
    [RowID] bigint IDENTITY(1,1) NOT NULL,
    [TaskWIPBatchNo] nvarchar(10) NOT NULL DEFAULT (''),
    [TaskDetailKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [TaskType] nvarchar(10) NOT NULL DEFAULT (' '),
    [Storerkey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Lot] nvarchar(10) NOT NULL DEFAULT (' '),
    [UOM] nvarchar(5) NOT NULL DEFAULT (' '),
    [UOMQty] int NOT NULL DEFAULT ((0)),
    [Qty] int NOT NULL DEFAULT ((0)),
    [FromLoc] nvarchar(10) NOT NULL DEFAULT (' '),
    [LogicalFromLoc] nvarchar(10) NOT NULL DEFAULT (' '),
    [FromID] nvarchar(18) NOT NULL DEFAULT (' '),
    [ToLoc] nvarchar(10) NOT NULL DEFAULT (' '),
    [LogicalToLoc] nvarchar(10) NOT NULL DEFAULT (' '),
    [ToID] nvarchar(18) NOT NULL DEFAULT (' '),
    [Caseid] nvarchar(20) NOT NULL DEFAULT (' '),
    [PickMethod] nvarchar(10) NOT NULL DEFAULT (' '),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [StatusMsg] nvarchar(255) NOT NULL DEFAULT (' '),
    [Priority] nvarchar(10) NOT NULL DEFAULT (' '),
    [SourcePriority] nvarchar(10) NOT NULL DEFAULT (' '),
    [Holdkey] nvarchar(10) NOT NULL DEFAULT (' '),
    [UserKey] nvarchar(18) NOT NULL DEFAULT (' '),
    [UserPosition] nvarchar(10) NOT NULL DEFAULT ('1'),
    [UserKeyOverRide] nvarchar(18) NOT NULL DEFAULT (' '),
    [StartTime] datetime NOT NULL DEFAULT (getdate()),
    [EndTime] datetime NOT NULL DEFAULT (getdate()),
    [SourceType] nvarchar(30) NOT NULL DEFAULT (' '),
    [SourceKey] nvarchar(30) NOT NULL DEFAULT (' '),
    [PickDetailKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [OrderKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [OrderLineNumber] nvarchar(5) NOT NULL DEFAULT (' '),
    [ListKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [WaveKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [ReasonKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [Message01] nvarchar(20) NOT NULL DEFAULT (' '),
    [Message02] nvarchar(20) NOT NULL DEFAULT (' '),
    [Message03] nvarchar(20) NOT NULL DEFAULT (' '),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [SystemQty] int NOT NULL DEFAULT ((0)),
    [RefTaskKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [LoadKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [AreaKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [DropID] nvarchar(20) NOT NULL DEFAULT (''),
    [TransitCount] int NOT NULL DEFAULT ((0)),
    [TransitLOC] nvarchar(10) NOT NULL DEFAULT (''),
    [FinalLOC] nvarchar(10) NOT NULL DEFAULT (''),
    [FinalID] nvarchar(18) NOT NULL DEFAULT (''),
    [Groupkey] nvarchar(10) NOT NULL DEFAULT (''),
    [PendingMoveIn] int NOT NULL DEFAULT ((0)),
    [QtyReplen] int NOT NULL DEFAULT ((0)),
    CONSTRAINT [PKTaskDetail_WIP] PRIMARY KEY ([RowID])
);
GO

CREATE INDEX [IDX_BTB_TaskDetail_WIP_BatchNo] ON [dbo].[taskdetail_wip] ([TaskWIPBatchNo]);
GO