CREATE TABLE [dbo].[tblsku]
(
    [StorerKey] nvarchar(15) NOT NULL,
    [Sku] nvarchar(20) NOT NULL,
    [DESCR] nvarchar(60) NULL,
    [SUSR1] nvarchar(18) NULL,
    [SUSR2] nvarchar(18) NULL,
    [SUSR3] nvarchar(18) NULL DEFAULT (' '),
    [SUSR4] nvarchar(18) NULL,
    [SUSR5] nvarchar(18) NULL,
    [MANUFACTURERSKU] nvarchar(20) NULL,
    [RETAILSKU] nvarchar(20) NULL,
    [ALTSKU] nvarchar(20) NULL,
    [PACKKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [STDGROSSWGT] float NOT NULL DEFAULT ((0)),
    [STDNETWGT] float NOT NULL DEFAULT ((0)),
    [STDCUBE] float NOT NULL DEFAULT ((0)),
    [TARE] float NOT NULL DEFAULT ((0)),
    [CLASS] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [ACTIVE] nvarchar(10) NOT NULL DEFAULT ('1'),
    [SKUGROUP] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [Tariffkey] nvarchar(10) NULL DEFAULT ('XXXXXXXXXX'),
    [BUSR1] nvarchar(30) NULL,
    [BUSR2] nvarchar(30) NULL,
    [BUSR3] nvarchar(30) NULL,
    [BUSR4] nvarchar(30) NULL,
    [BUSR5] nvarchar(30) NULL,
    [LOTTABLE01LABEL] nvarchar(20) NOT NULL DEFAULT (' '),
    [LOTTABLE02LABEL] nvarchar(20) NOT NULL DEFAULT (' '),
    [LOTTABLE03LABEL] nvarchar(20) NOT NULL DEFAULT (' '),
    [LOTTABLE04LABEL] nvarchar(20) NOT NULL DEFAULT (' '),
    [LOTTABLE05LABEL] nvarchar(20) NOT NULL DEFAULT (' '),
    [NOTES1] nvarchar(4000) NULL,
    [NOTES2] nvarchar(4000) NULL,
    [PickCode] nvarchar(10) NOT NULL DEFAULT ('NSPFIFO'),
    [StrategyKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [CartonGroup] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [PutCode] nvarchar(10) NOT NULL DEFAULT ('NSPPASTD'),
    [PutawayLoc] nvarchar(10) NULL DEFAULT ('UNKNOWN'),
    [PutawayZone] nvarchar(10) NULL DEFAULT ('BULK'),
    [InnerPack] int NOT NULL DEFAULT ((0)),
    [Cube] float NOT NULL DEFAULT ((0)),
    [GrossWgt] float NOT NULL DEFAULT ((0)),
    [NetWgt] float NOT NULL DEFAULT ((0)),
    [ABC] nvarchar(5) NULL,
    [CycleCountFrequency] int NULL,
    [LastCycleCount] datetime NULL,
    [ReorderPoint] int NULL,
    [ReorderQty] int NULL,
    [StdOrderCost] float NULL,
    [CarryCost] float NULL,
    [Price] money NULL,
    [Cost] money NULL,
    [ReceiptHoldCode] nvarchar(10) NOT NULL DEFAULT (' '),
    [ReceiptInspectionLoc] nvarchar(10) NOT NULL DEFAULT ('QC'),
    [OnReceiptCopyPackkey] nvarchar(10) NOT NULL DEFAULT ('0'),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [IOFlag] nvarchar(1) NULL,
    [TareWeight] float NULL DEFAULT ((0)),
    [LotxIdDetailOtherlabel1] nvarchar(30) NULL DEFAULT ('Ser#'),
    [LotxIdDetailOtherlabel2] nvarchar(30) NULL DEFAULT ('CSID'),
    [LotxIdDetailOtherlabel3] nvarchar(30) NULL DEFAULT ('Other'),
    [AvgCaseWeight] float NULL DEFAULT ((0)),
    [TolerancePct] float NULL DEFAULT ((0)),
    [SkuStatus] nvarchar(10) NULL DEFAULT ('ACTIVE'),
    [Length] float NULL DEFAULT ((0.00)),
    [Width] float NULL DEFAULT ((0.00)),
    [Height] float NULL DEFAULT ((0.00)),
    [weight] real NULL,
    [itemclass] nvarchar(10) NULL DEFAULT (' '),
    [ShelfLife] int NULL DEFAULT ((0)),
    [Facility] nvarchar(5) NULL,
    [BUSR6] nvarchar(30) NULL DEFAULT (' '),
    [BUSR7] nvarchar(30) NULL DEFAULT (' '),
    [BUSR8] nvarchar(30) NULL DEFAULT (' '),
    [BUSR9] nvarchar(30) NULL DEFAULT (' '),
    [BUSR10] nvarchar(30) NULL DEFAULT (' '),
    [ReturnLoc] nvarchar(10) NULL,
    [ReceiptLoc] nvarchar(10) NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (user_name()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (user_name()),
    [archiveqty] nvarchar(30) NULL DEFAULT ((0)),
    [XDockReceiptLoc] nvarchar(10) NULL,
    [PrePackIndicator] nvarchar(30) NULL DEFAULT (' '),
    [PackQtyIndicator] int NULL DEFAULT ((0)),
    [StackFactor] int NULL DEFAULT ((0)),
    [IVAS] nvarchar(30) NULL,
    [OVAS] nvarchar(30) NULL,
    [ColorDescr] nvarchar(35) NULL DEFAULT (''),
    [ProductName] nvarchar(50) NULL DEFAULT (''),
    [UpperMaterial] nvarchar(100) NULL DEFAULT (''),
    [OutsoleMaterial] nvarchar(25) NULL DEFAULT (''),
    [ITCNST] nvarchar(50) NULL DEFAULT (''),
    [ITEXP5] float NULL DEFAULT ((0)),
    [ITEXP6] float NULL DEFAULT ((0)),
    [ITEXP7] nvarchar(10) NULL DEFAULT (''),
    [ITEXP8] nvarchar(25) NULL DEFAULT (''),
    CONSTRAINT [PKTBLSKU] PRIMARY KEY ([Sku])
);
GO
