CREATE TABLE [dbo].[tempstkvar]
(
    [STORERKEY] nvarchar(10) NOT NULL,
    [CCKey] nvarchar(10) NOT NULL,
    [Sku] nvarchar(20) NOT NULL,
    [Descr] nvarchar(60) NULL,
    [TagNo] nvarchar(10) NULL,
    [CCSheetNo] nvarchar(10) NULL,
    [SUSR3] nvarchar(18) NULL,
    [Cost] money NULL,
    [Facility] nvarchar(5) NULL,
    [Lot] nvarchar(10) NULL,
    [Id] nvarchar(18) NULL,
    [Loc] nvarchar(10) NULL,
    [Lottable02] nvarchar(18) NULL,
    [Lottable02_Cnt2] nvarchar(18) NULL,
    [Lottable02_Cnt3] nvarchar(18) NULL,
    [Lottable04] datetime NULL,
    [Lottable04_Cnt2] datetime NULL,
    [Lottable04_Cnt3] datetime NULL,
    [Qty] int NOT NULL,
    [Qty_Cnt2] int NOT NULL,
    [Qty_Cnt3] int NOT NULL,
    [PackUOM3] nvarchar(10) NULL,
    [PackQty] float NOT NULL,
    [LotXLocXId_Qty] int NOT NULL,
    [VarQty_cal] int NOT NULL,
    [VarHKD_cal] float NULL,
    [SkuGroup] nvarchar(10) NULL,
    [ItemClass] nvarchar(10) NULL,
    [CompanyName] nvarchar(45) NULL,
    [Currency] nvarchar(45) NULL,
    [Lottable05] datetime NULL,
    [Lottable05_Cnt2] datetime NULL,
    [Lottable05_Cnt3] datetime NULL
);
GO
