CREATE TABLE [dbo].[tm_picklog]
(
    [SeqNo] int IDENTITY(1,1) NOT NULL,
    [Mobile] nvarchar(10) NULL DEFAULT (''),
    [Func] nvarchar(10) NULL DEFAULT (''),
    [StorerKey] nvarchar(15) NULL DEFAULT (''),
    [UserName] nvarchar(128) NULL DEFAULT (''),
    [Facility] nvarchar(5) NULL DEFAULT (''),
    [TaskDetailKey] nvarchar(10) NULL DEFAULT (''),
    [PickDetailKey] nvarchar(10) NULL DEFAULT (''),
    [LoadKey] nvarchar(10) NULL DEFAULT (''),
    [SKU] nvarchar(20) NULL DEFAULT (''),
    [AltSKU] nvarchar(20) NULL DEFAULT (''),
    [LOC] nvarchar(10) NULL DEFAULT (''),
    [ToLOC] nvarchar(10) NULL DEFAULT (''),
    [ID] nvarchar(18) NULL DEFAULT (''),
    [DropID] nvarchar(20) NULL DEFAULT (''),
    [PickQty] nvarchar(10) NULL DEFAULT (''),
    [PDQty] nvarchar(10) NULL DEFAULT (''),
    [Status] nvarchar(1) NULL DEFAULT (''),
    [Areakey] nvarchar(10) NULL DEFAULT (''),
    [Col1] nvarchar(30) NULL DEFAULT (''),
    [Col2] nvarchar(30) NULL DEFAULT (''),
    [Col3] nvarchar(30) NULL DEFAULT (''),
    [Col4] nvarchar(30) NULL DEFAULT (''),
    [Col5] nvarchar(30) NULL DEFAULT (''),
    [Col6] nvarchar(30) NULL DEFAULT (''),
    [Col7] nvarchar(30) NULL DEFAULT (''),
    [Col8] nvarchar(30) NULL DEFAULT (''),
    [Col9] nvarchar(30) NULL DEFAULT (''),
    [Col10] nvarchar(30) NULL DEFAULT (''),
    [AddDate] datetime NULL DEFAULT (getdate()),
    CONSTRAINT [PK_TM_PickLog] PRIMARY KEY ([SeqNo])
);
GO
