CREATE TABLE [dbo].[tpprintjob]
(
    [JobNo] bigint IDENTITY(1,1) NOT NULL,
    [Module] nvarchar(20) NULL,
    [ReportType] nvarchar(10) NULL,
    [Storerkey] nvarchar(15) NULL,
    [PrinterID] nvarchar(10) NULL,
    [Printer] nvarchar(128) NULL,
    [Shipperkey] nvarchar(15) NULL,
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [Message] nvarchar(2000) NULL,
    [KeyFieldName] nvarchar(30) NULL,
    [Parm01] nvarchar(30) NULL,
    [Parm02] nvarchar(30) NULL,
    [Parm03] nvarchar(30) NULL,
    [Parm04] nvarchar(30) NULL,
    [Parm05] nvarchar(30) NULL,
    [Parm06] nvarchar(30) NULL,
    [Parm07] nvarchar(30) NULL,
    [Parm08] nvarchar(30) NULL,
    [Parm09] nvarchar(500) NULL,
    [Parm10] nvarchar(4000) NULL,
    [UDF01] nvarchar(200) NULL,
    [UDF02] nvarchar(200) NULL,
    [UDF03] nvarchar(4000) NULL,
    [UDF04] nvarchar(4000) NULL,
    [UDF05] nvarchar(4000) NULL,
    [SourceType] nvarchar(30) NULL,
    [Platform] nvarchar(30) NULL,
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    CONSTRAINT [PK_TPPRINTJOB] PRIMARY KEY ([JobNo])
);
GO
