CREATE TABLE [dbo].[transferdetail]
(
    [TransferKey] nvarchar(10) NOT NULL,
    [TransferLineNumber] nvarchar(5) NOT NULL,
    [FromStorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [FromSku] nvarchar(20) NOT NULL DEFAULT (' '),
    [FromLoc] nvarchar(10) NOT NULL DEFAULT (' '),
    [FromLot] nvarchar(10) NOT NULL DEFAULT (' '),
    [FromId] nvarchar(18) NOT NULL DEFAULT (' '),
    [FromQty] int NOT NULL DEFAULT ((0)),
    [FromPackKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [FromUOM] nvarchar(10) NOT NULL DEFAULT (' '),
    [LOTTABLE01] nvarchar(18) NOT NULL DEFAULT (' '),
    [LOTTABLE02] nvarchar(18) NOT NULL DEFAULT (' '),
    [LOTTABLE03] nvarchar(18) NOT NULL DEFAULT (' '),
    [LOTTABLE04] datetime NULL,
    [LOTTABLE05] datetime NULL,
    [ToStorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [ToSku] nvarchar(20) NOT NULL DEFAULT (' '),
    [ToLoc] nvarchar(10) NOT NULL DEFAULT (' '),
    [ToLot] nvarchar(10) NOT NULL DEFAULT (' '),
    [ToId] nvarchar(18) NOT NULL DEFAULT (' '),
    [ToQty] int NOT NULL DEFAULT ((0)),
    [ToPackKey] nvarchar(10) NOT NULL DEFAULT ('STD'),
    [ToUOM] nvarchar(10) NOT NULL DEFAULT (' '),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Timestamp] timestamp NOT NULL,
    [tolottable01] nvarchar(18) NULL DEFAULT (' '),
    [tolottable02] nvarchar(18) NULL DEFAULT (' '),
    [tolottable03] nvarchar(18) NULL DEFAULT (' '),
    [tolottable04] datetime NULL,
    [tolottable05] datetime NULL,
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [Lottable06] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NOT NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [ToLottable06] nvarchar(30) NULL DEFAULT (''),
    [ToLottable07] nvarchar(30) NULL DEFAULT (''),
    [ToLottable08] nvarchar(30) NULL DEFAULT (''),
    [ToLottable09] nvarchar(30) NULL DEFAULT (''),
    [ToLottable10] nvarchar(30) NULL DEFAULT (''),
    [ToLottable11] nvarchar(30) NULL DEFAULT (''),
    [ToLottable12] nvarchar(30) NULL DEFAULT (''),
    [ToLottable13] datetime NULL,
    [ToLottable14] datetime NULL,
    [ToLottable15] datetime NULL,
    [FromChannel] nvarchar(20) NULL DEFAULT (''),
    [ToChannel] nvarchar(20) NULL DEFAULT (''),
    [FromChannel_ID] bigint NULL DEFAULT ((0)),
    [ToChannel_ID] bigint NULL DEFAULT ((0)),
    [FromSerialNo] nvarchar(30) NOT NULL DEFAULT (' '),
    [ToSerialNo] nvarchar(30) NOT NULL DEFAULT (' '),
    [FromPalletType] nvarchar(10) NOT NULL DEFAULT (''),
    [ToPalletType] nvarchar(10) NOT NULL DEFAULT (''),
    CONSTRAINT [PKTRANSFERDETAIL] PRIMARY KEY ([TransferKey], [TransferLineNumber]),
    CONSTRAINT [FK_TRFDET_LOC_01] FOREIGN KEY ([FromLoc]) REFERENCES [dbo].[LOC] ([Loc]),
    CONSTRAINT [FK_TRFDET_LOC_02] FOREIGN KEY ([ToLoc]) REFERENCES [dbo].[LOC] ([Loc]),
    CONSTRAINT [FK_TRFDET_SKU_01] FOREIGN KEY ([FromStorerKey], [FromSku]) REFERENCES [dbo].[SKU] ([StorerKey], [Sku]),
    CONSTRAINT [FK_TRFDET_SKU_02] FOREIGN KEY ([ToStorerKey], [ToSku]) REFERENCES [dbo].[SKU] ([StorerKey], [Sku]),
    CONSTRAINT [CK_TRFDET_Status] CHECK (rtrim([Status]) like '[0-9]' OR rtrim([Status])='CANC')
);
GO

CREATE INDEX [IX_TRANSFERDETAIL_FromLot] ON [dbo].[transferdetail] ([FromLot]);
GO