CREATE TABLE [dbo].[transfer]
(
    [TransferKey] nvarchar(10) NOT NULL,
    [FromStorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [ToStorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Type] nvarchar(12) NOT NULL,
    [OpenQty] int NOT NULL DEFAULT ((0)),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [GenerateHOCharges] nvarchar(10) NOT NULL DEFAULT ('1'),
    [GenerateIS_HICharges] nvarchar(10) NOT NULL DEFAULT ('1'),
    [ReLot] nvarchar(10) NULL DEFAULT ('0'),
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Timestamp] timestamp NOT NULL,
    [ReasonCode] nvarchar(10) NULL,
    [CustomerRefNo] nvarchar(20) NULL DEFAULT (' '),
    [Remarks] nvarchar(200) NULL DEFAULT (' '),
    [Facility] nvarchar(15) NULL DEFAULT (' '),
    [PrintFlag] nvarchar(1) NULL,
    [UserDefine01] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine02] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine03] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine04] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine05] nvarchar(20) NULL DEFAULT (' '),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT ('N'),
    [UserDefine09] nvarchar(10) NULL DEFAULT (' '),
    [UserDefine10] nvarchar(10) NULL DEFAULT (' '),
    [ToFacility] nvarchar(15) NULL DEFAULT (' '),
    CONSTRAINT [PKTRANSFER] PRIMARY KEY ([TransferKey]),
    CONSTRAINT [FK_TRANSFER_STORER_01] FOREIGN KEY ([FromStorerKey]) REFERENCES [dbo].[STORER] ([StorerKey]),
    CONSTRAINT [FK_TRANSFER_STORER_02] FOREIGN KEY ([ToStorerKey]) REFERENCES [dbo].[STORER] ([StorerKey]),
    CONSTRAINT [CK_TRANSFER_Status] CHECK (rtrim([Status]) like '[0-9]' OR rtrim([Status])='CANC')
);
GO
