CREATE TABLE [dbo].[upstracking_out]
(
    [RowID] int IDENTITY(1,1) NOT NULL,
    [CartonID] nvarchar(20) NOT NULL DEFAULT (''),
    [CartonType] nvarchar(1) NULL DEFAULT ('D'),
    [WMS_RefKey] nvarchar(30) NOT NULL DEFAULT (''),
    [WMS_RefType] nvarchar(2) NULL DEFAULT (''),
    [ShipToName] nvarchar(30) NULL DEFAULT (''),
    [ShipToCompany] nvarchar(45) NULL DEFAULT (''),
    [ShipToAddress1] nvarchar(45) NULL DEFAULT (''),
    [ShipToAddress2] nvarchar(45) NULL DEFAULT (''),
    [ShipToAddress3] nvarchar(45) NULL DEFAULT (''),
    [City] nvarchar(45) NULL DEFAULT (''),
    [State] nvarchar(2) NULL DEFAULT (''),
    [Zip] nvarchar(18) NULL DEFAULT (''),
    [Country] nvarchar(30) NULL DEFAULT (''),
    [Phone] nvarchar(18) NULL,
    [ServiceIndicator] nvarchar(18) NULL DEFAULT (''),
    [PaymentType] nvarchar(10) NULL,
    [PriAcctNo] nvarchar(18) NULL,
    [ScdAcctNo] nvarchar(18) NULL,
    [BillToCompany] nvarchar(45) NULL,
    [BillToAddress1] nvarchar(45) NULL,
    [BillToAddress2] nvarchar(45) NULL,
    [BillToAddress3] nvarchar(45) NULL,
    [BillToCity] nvarchar(45) NULL,
    [BillToState] nvarchar(45) NULL,
    [BillToZip] nvarchar(18) NULL,
    [BillToCountry] nvarchar(30) NULL,
    [InsuranceFlag] nvarchar(18) NULL,
    [RetailPrice] money NULL DEFAULT ((0)),
    [PLD_RefNo1] nvarchar(30) NULL DEFAULT ((0)),
    [PLD_RefNo2] nvarchar(30) NULL DEFAULT ((0)),
    [PLD_RefNo3] nvarchar(30) NULL,
    [PLD_RefNo4] nvarchar(30) NULL,
    [AddDate] datetime NULL DEFAULT (getdate()),
    CONSTRAINT [PK_UPSTracking_Out] PRIMARY KEY ([RowID])
);
GO
