CREATE TABLE [dbo].[vas]
(
    [VASKey] nvarchar(10) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Facility] nvarchar(5) NOT NULL DEFAULT (' '),
    [Type] nvarchar(10) NOT NULL DEFAULT (' '),
    [Vendor] nvarchar(45) NOT NULL DEFAULT (' '),
    [Brand] nvarchar(30) NOT NULL DEFAULT (' '),
    [Division] nvarchar(10) NOT NULL DEFAULT (' '),
    [ItemClass] nvarchar(10) NOT NULL DEFAULT (' '),
    [SkuGroup] nvarchar(10) NOT NULL DEFAULT (' '),
    [CustomerID] nvarchar(20) NOT NULL DEFAULT (' '),
    [ConsigneeKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [MarkForKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [OrdSpecHdlgCode] nvarchar(10) NOT NULL DEFAULT (' '),
    [Lottable01] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable02] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable03] nvarchar(18) NOT NULL DEFAULT (' '),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(18) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(18) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Lottable06] nvarchar(30) NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    CONSTRAINT [PK_VAS] PRIMARY KEY ([VASKey])
);
GO
