CREATE TABLE [dbo].[vehicledispatch]
(
    [VehicleDispatchKey] nvarchar(10) NOT NULL DEFAULT (''),
    [Facility] nvarchar(5) NULL DEFAULT (''),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [DepotStatus] nvarchar(10) NULL DEFAULT ('0'),
    [ExpectedDepartureDate] datetime NOT NULL DEFAULT (getdate()),
    [ActualDepartureDate] datetime NOT NULL DEFAULT (getdate()),
    [ExpectedDeliveryDate] datetime NOT NULL DEFAULT (getdate()),
    [ActualDeliveryDate] datetime NOT NULL DEFAULT (getdate()),
    [Bookingno] int NULL DEFAULT ((0)),
    [BookingDate] datetime NULL,
    [Bay] nvarchar(10) NULL DEFAULT (''),
    [Lane] nvarchar(10) NULL DEFAULT (''),
    [VesselQualifier] nvarchar(10) NOT NULL DEFAULT ('VM'),
    [Vessel] nvarchar(30) NOT NULL DEFAULT (''),
    [VesselType] nvarchar(10) NOT NULL DEFAULT (''),
    [DriverName] nvarchar(30) NULL DEFAULT (''),
    [SealNo] nvarchar(8) NULL DEFAULT (''),
    [VoyageNumber] nvarchar(30) NOT NULL DEFAULT (''),
    [Transmethod] nvarchar(30) NOT NULL DEFAULT (''),
    [BookingReference] nvarchar(30) NOT NULL DEFAULT (''),
    [OtherReference] nvarchar(30) NOT NULL DEFAULT (''),
    [Carrierkey] nvarchar(10) NOT NULL DEFAULT (''),
    [CarrierAgent] nvarchar(30) NOT NULL DEFAULT (''),
    [PlaceOfLoadingQualifier] nvarchar(10) NOT NULL DEFAULT (''),
    [PlaceofLoading] nvarchar(30) NOT NULL DEFAULT (''),
    [PlaceOfDischargeQualifier] nvarchar(10) NOT NULL DEFAULT (''),
    [PlaceOfDischarge] nvarchar(30) NOT NULL DEFAULT (''),
    [PlaceOfDeliveryQualifier] nvarchar(10) NOT NULL DEFAULT (''),
    [PlaceOfDelivery] nvarchar(30) NOT NULL DEFAULT (''),
    [OriginCountry] nvarchar(30) NOT NULL DEFAULT (''),
    [DestinationCountry] nvarchar(30) NOT NULL DEFAULT (''),
    [ContainerNo] nvarchar(30) NOT NULL DEFAULT (''),
    [NoOfOrders] int NULL DEFAULT ((0)),
    [NoOfStops] int NULL DEFAULT ((0)),
    [NoOfCustomers] int NULL DEFAULT ((0)),
    [TotalCube] float NULL DEFAULT ((0.00)),
    [TotalWeight] float NULL DEFAULT ((0.00)),
    [TotalPallets] int NULL DEFAULT ((0)),
    [TotalCartons] int NULL DEFAULT ((0)),
    [TotalDropIDs] int NULL DEFAULT ((0)),
    [Notes] nvarchar(4000) NULL DEFAULT (''),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(18) NOT NULL DEFAULT (suser_name()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(18) NOT NULL DEFAULT (suser_name()),
    CONSTRAINT [PK_VehicleDispatch] PRIMARY KEY ([VehicleDispatchKey]),
    CONSTRAINT [CK_VehicleDispatch_Status] CHECK ([Status]='0' OR [Status]='9')
);
GO

CREATE INDEX [IDX_VehicleDispatch_Facility] ON [dbo].[vehicledispatch] ([Facility]);
GO