CREATE TABLE [dbo].[wave]
(
    [WaveKey] nvarchar(10) NOT NULL,
    [WaveType] nvarchar(18) NOT NULL DEFAULT ('0'),
    [Descr] nvarchar(60) NOT NULL DEFAULT (' '),
    [DispatchPalletPickMethod] nvarchar(10) NOT NULL DEFAULT ('1'),
    [DispatchCasePickMethod] nvarchar(10) NOT NULL DEFAULT ('1'),
    [DispatchPiecePickMethod] nvarchar(10) NOT NULL DEFAULT ('1'),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [UserDefine01] nvarchar(20) NULL DEFAULT (''),
    [UserDefine02] nvarchar(20) NULL DEFAULT (''),
    [UserDefine03] nvarchar(20) NULL DEFAULT (''),
    [UserDefine04] nvarchar(20) NULL DEFAULT (''),
    [UserDefine05] nvarchar(20) NULL DEFAULT (''),
    [UserDefine06] datetime NULL,
    [UserDefine07] datetime NULL,
    [UserDefine08] nvarchar(10) NULL DEFAULT (''),
    [UserDefine09] nvarchar(10) NULL DEFAULT (''),
    [UserDefine10] nvarchar(10) NULL DEFAULT (''),
    [LoadplanGroup] nvarchar(10) NULL,
    [MBOLGroupMethod] nvarchar(10) NULL,
    [BatchNo] bigint NOT NULL DEFAULT ((0)),
    [TMSStatus] nvarchar(10) NOT NULL DEFAULT ('0'),
    [DoorBookStatus] nvarchar(10) NOT NULL DEFAULT ('0'),
    [ReplenishStatus] nvarchar(10) NOT NULL DEFAULT ('0'),
    [TMReleaseFlag] nvarchar(10) NOT NULL DEFAULT ('N'),
    [GenDynamicPickSlipCode] nvarchar(30) NOT NULL DEFAULT (''),
    [Strategykey] nvarchar(10) NOT NULL DEFAULT (''),
    [WaveGenloadflag] nvarchar(1) NOT NULL DEFAULT ('N'),
    CONSTRAINT [PKWave] PRIMARY KEY ([WaveKey]),
    CONSTRAINT [CK_WAVE_WaveKey_Numeric] CHECK (isnumeric([WaveKey])=(1))
);
GO
