CREATE TABLE [dbo].[wcstran]
(
    [MessageID] int IDENTITY(1,1) NOT NULL,
    [MessageName] nvarchar(15) NOT NULL,
    [MessageType] nvarchar(10) NOT NULL,
    [MessageNum] nvarchar(10) NULL DEFAULT (''),
    [TaskDetailKey] nvarchar(10) NULL DEFAULT (''),
    [WCSMessageID] nvarchar(10) NULL DEFAULT (''),
    [OrigMessageID] nvarchar(10) NULL DEFAULT (''),
    [PalletID] nvarchar(18) NOT NULL,
    [FromLoc] nvarchar(10) NULL DEFAULT (''),
    [ToLoc] nvarchar(10) NULL DEFAULT (''),
    [Priority] nvarchar(1) NULL DEFAULT (''),
    [Status] nvarchar(10) NULL DEFAULT (''),
    [ReasonCode] nvarchar(10) NULL DEFAULT (''),
    [ErrMsg] nvarchar(100) NULL DEFAULT (''),
    [UD1] nvarchar(20) NULL DEFAULT (''),
    [UD2] nvarchar(20) NULL DEFAULT (''),
    [UD3] nvarchar(20) NULL DEFAULT (''),
    [UD4] nvarchar(20) NULL DEFAULT (''),
    [UD5] nvarchar(20) NULL DEFAULT (''),
    [ImgFolderPath] nvarchar(100) NULL DEFAULT (''),
    [ImgFileName1] nvarchar(60) NULL DEFAULT (''),
    [ImgFileName2] nvarchar(60) NULL DEFAULT (''),
    [ImgFileName3] nvarchar(60) NULL DEFAULT (''),
    [ImgFileName4] nvarchar(60) NULL DEFAULT (''),
    [ImgFileName5] nvarchar(60) NULL DEFAULT (''),
    [Param1] nvarchar(20) NULL DEFAULT (''),
    [Param2] nvarchar(20) NULL DEFAULT (''),
    [Param3] nvarchar(20) NULL DEFAULT (''),
    [Param4] nvarchar(20) NULL DEFAULT (''),
    [Param5] nvarchar(20) NULL DEFAULT (''),
    [Param6] nvarchar(20) NULL DEFAULT (''),
    [Param7] nvarchar(20) NULL DEFAULT (''),
    [Param8] nvarchar(20) NULL DEFAULT (''),
    [Param9] nvarchar(20) NULL DEFAULT (''),
    [Param10] nvarchar(20) NULL DEFAULT (''),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    CONSTRAINT [PK_WCSTran] PRIMARY KEY ([MessageID])
);
GO
