CREATE TABLE [dbo].[wmreport]
(
    [ReportID] nvarchar(10) NOT NULL DEFAULT (''),
    [ReportTitle] nvarchar(60) NOT NULL DEFAULT (''),
    [ModuleID] nvarchar(30) NOT NULL DEFAULT (''),
    [PrintMethod] nvarchar(10) NOT NULL DEFAULT (''),
    [ReportType] nvarchar(30) NOT NULL DEFAULT (''),
    [NoOfKeyFieldParms] int NOT NULL DEFAULT ((0)),
    [KeyFieldName1] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName2] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName3] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName4] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName5] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName6] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName7] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName8] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName9] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName10] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName11] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName12] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName13] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName14] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldName15] nvarchar(200) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel1] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel2] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel3] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel4] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel5] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel6] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel7] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel8] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel9] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel10] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel11] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel12] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel13] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel14] nvarchar(60) NOT NULL DEFAULT (''),
    [KeyFieldParmLabel15] nvarchar(60) NOT NULL DEFAULT (''),
    [ExtendedParm1] nvarchar(60) NOT NULL DEFAULT (''),
    [ExtendedParm2] nvarchar(60) NOT NULL DEFAULT (''),
    [ExtendedParm3] nvarchar(60) NOT NULL DEFAULT (''),
    [ExtendedParm4] nvarchar(60) NOT NULL DEFAULT (''),
    [ExtendedParm5] nvarchar(60) NOT NULL DEFAULT (''),
    [ExtendedParmDefault1] nvarchar(200) NOT NULL DEFAULT (''),
    [ExtendedParmDefault2] nvarchar(200) NOT NULL DEFAULT (''),
    [ExtendedParmDefault3] nvarchar(200) NOT NULL DEFAULT (''),
    [ExtendedParmDefault4] nvarchar(200) NOT NULL DEFAULT (''),
    [ExtendedParmDefault5] nvarchar(200) NOT NULL DEFAULT (''),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [TrafficCop] nchar(1) NULL,
    [ArchiveCop] nchar(1) NULL,
    CONSTRAINT [PK_WMREPORT] PRIMARY KEY ([ReportID])
);
GO

CREATE INDEX [IDX_WMREPORT_MODULEID] ON [dbo].[wmreport] ([ModuleID]);
GO