CREATE TABLE [dbo].[wms_tpb_base]
(
    [SEQ] bigint IDENTITY(1,1) NOT NULL,
    [INSERT_DATE] datetime NOT NULL DEFAULT (getdate()),
    [UPDATE_DATE] datetime NOT NULL DEFAULT (getdate()),
    [STATUS] nvarchar(5) NOT NULL DEFAULT ('0'),
    [BatchNo] bigint NOT NULL DEFAULT ('0'),
    [CONFIG_ID] nvarchar(5) NOT NULL DEFAULT ('0'),
    [TPB_UPLOADED_DATE] datetime NOT NULL DEFAULT (''),
    [TPB_UPLOADED_STATUS] nvarchar(1) NOT NULL DEFAULT (''),
    [TRANSACTION_TYPE] nvarchar(50) NOT NULL DEFAULT ('A'),
    [CODE] nvarchar(50) NULL DEFAULT (''),
    [COUNTRY] nvarchar(50) NULL DEFAULT (''),
    [SITE_ID] nvarchar(50) NULL DEFAULT (''),
    [TO_SITE_ID] nvarchar(50) NULL DEFAULT (''),
    [CLIENT_SITE_ID] nvarchar(50) NULL DEFAULT (''),
    [ADD_DATE] datetime NOT NULL DEFAULT (getdate()),
    [ADD_WHO] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EDIT_DATE] datetime NOT NULL DEFAULT (getdate()),
    [EDIT_WHO] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [DOC_SOURCE] nvarchar(30) NULL DEFAULT (''),
    [DOC_STATUS] nvarchar(5) NULL DEFAULT (''),
    [DOC_PRE_STATUS] nvarchar(5) NULL DEFAULT (''),
    [DOC_TYPE] nvarchar(30) NULL DEFAULT (''),
    [DOC_SUB_TYPE] nvarchar(30) NULL DEFAULT (''),
    [DOC_GROUPING_1] nvarchar(30) NULL DEFAULT (''),
    [DOC_GROUPING_2] nvarchar(30) NULL DEFAULT (''),
    [DOC_REASON] nvarchar(150) NULL DEFAULT (''),
    [DOCUMENT_ID] nvarchar(150) NULL DEFAULT (''),
    [DOCUMENT_LINE_NO] nvarchar(5) NULL DEFAULT (''),
    [CLIENT_REF] nvarchar(150) NULL DEFAULT (''),
    [CLIENT_REF_LINE_NO] nvarchar(20) NULL DEFAULT (''),
    [CLIENT_ID] nvarchar(50) NULL DEFAULT (''),
    [TO_CLIENT_ID] nvarchar(50) NULL DEFAULT (''),
    [SHIP_FROM_ID] nvarchar(50) NULL DEFAULT (''),
    [SHIP_FROM_COMPANY] nvarchar(100) NULL DEFAULT (''),
    [SHIP_FROM_COUNTRY] nvarchar(50) NULL DEFAULT (''),
    [SHIP_TO_ID] nvarchar(50) NULL DEFAULT (''),
    [SHIP_TO_COMPANY] nvarchar(100) NULL DEFAULT (''),
    [SHIP_TO_COUNTRY] nvarchar(50) NULL DEFAULT (''),
    [LOAD_PLAN_NO] nvarchar(50) NULL DEFAULT (''),
    [MBOL_NO] nvarchar(50) NULL DEFAULT (''),
    [OTHER_REFERENCE_1] nvarchar(100) NULL DEFAULT (''),
    [OTHER_REFERENCE_2] nvarchar(30) NULL DEFAULT (''),
    [PRIORITY] nvarchar(30) NULL DEFAULT (''),
    [PO_NO] nvarchar(100) NULL DEFAULT (''),
    [CLIENT_PO_NO] nvarchar(100) NULL DEFAULT (''),
    [REFERENCE_DATE] datetime NULL DEFAULT (''),
    [SKU_ID] nvarchar(50) NULL DEFAULT (''),
    [LOCATION_TYPE] nvarchar(50) NULL DEFAULT (''),
    [BILLABLE_NO_OF_LOC] numeric(20, 6) NULL DEFAULT ((0)),
    [BILLABLE_QUANTITY] numeric(20, 6) NULL DEFAULT ((0)),
    [QTY_UOM] nvarchar(30) NULL DEFAULT (''),
    [BILLABLE_CARTON] numeric(20, 6) NULL DEFAULT ((0)),
    [CARTON_UOM] nvarchar(30) NULL DEFAULT (''),
    [BILLABLE_WEIGHT] float NULL DEFAULT ((0)),
    [WEIGHT_UOM] nvarchar(30) NULL DEFAULT (''),
    [BILLABLE_CBM] numeric(20, 6) NULL DEFAULT ((0)),
    [CBM_UOM] nvarchar(30) NULL DEFAULT (''),
    [BILLABLE_PALLET] numeric(20, 6) NULL DEFAULT ((0)),
    [BILLABLE_DROP] numeric(20, 6) NULL DEFAULT ((0)),
    [BILLABLE_CONTAINER] numeric(20, 6) NULL DEFAULT ((0)),
    [VESSEL_ID] nvarchar(150) NULL DEFAULT (''),
    [VOYAGE_ID] nvarchar(150) NULL DEFAULT (''),
    [VEHICLE_NO] nvarchar(150) NULL DEFAULT (''),
    [VEHICLE_DATE] nvarchar(18) NULL DEFAULT (''),
    [CONTAINER_TYPE] nvarchar(50) NULL DEFAULT (''),
    [CONTAINER_ID] nvarchar(150) NULL DEFAULT (''),
    [PALLET_ID] nvarchar(100) NULL DEFAULT (''),
    [LOTTABLE_01] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE_02] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE_03] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE_04] datetime NULL DEFAULT (''),
    [LOTTABLE_05] datetime NULL DEFAULT (''),
    [LOTTABLE_06] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE_07] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE_08] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE_09] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE_10] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE_11] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE_12] nvarchar(30) NULL DEFAULT (''),
    [LOTTABLE_13] datetime NULL DEFAULT (''),
    [LOTTABLE_14] datetime NULL DEFAULT (''),
    [LOTTABLE_15] datetime NULL DEFAULT (''),
    [H_USD_01] nvarchar(50) NULL DEFAULT (''),
    [H_USD_02] nvarchar(50) NULL DEFAULT (''),
    [H_USD_03] nvarchar(50) NULL DEFAULT (''),
    [H_USD_04] nvarchar(50) NULL DEFAULT (''),
    [H_USD_05] nvarchar(50) NULL DEFAULT (''),
    [H_USD_06] nvarchar(50) NULL DEFAULT (''),
    [H_USD_07] nvarchar(50) NULL DEFAULT (''),
    [H_USD_08] nvarchar(50) NULL DEFAULT (''),
    [H_USD_09] nvarchar(50) NULL DEFAULT (''),
    [H_USD_10] nvarchar(50) NULL DEFAULT (''),
    [D_USD_01] nvarchar(50) NULL DEFAULT (''),
    [D_USD_02] nvarchar(50) NULL DEFAULT (''),
    [D_USD_03] nvarchar(50) NULL DEFAULT (''),
    [D_USD_04] nvarchar(50) NULL DEFAULT (''),
    [D_USD_05] nvarchar(50) NULL DEFAULT (''),
    [D_USD_06] nvarchar(50) NULL DEFAULT (''),
    [D_USD_07] nvarchar(50) NULL DEFAULT (''),
    [D_USD_08] nvarchar(50) NULL DEFAULT (''),
    [D_USD_09] nvarchar(50) NULL DEFAULT (''),
    [D_USD_10] nvarchar(50) NULL DEFAULT (''),
    [LP_TRF_ROOM] nvarchar(50) NULL DEFAULT (''),
    [LP_DELIVERY_ZONE] nvarchar(50) NULL DEFAULT (''),
    [PICK_SLIP_NO] nvarchar(50) NULL DEFAULT (''),
    [PICK_METHOD] nvarchar(5) NULL DEFAULT (''),
    [PCS_PICK_METHOD] nvarchar(10) NULL DEFAULT (''),
    [LOC] nvarchar(30) NULL DEFAULT (''),
    [TO_LOC] nvarchar(30) NULL DEFAULT (''),
    [LOT] nvarchar(30) NULL DEFAULT (''),
    [TO_LOT] nvarchar(30) NULL DEFAULT (''),
    [ID] nvarchar(30) NULL DEFAULT (''),
    [TO_ID] nvarchar(30) NULL DEFAULT (''),
    [DROP_ID] nvarchar(50) NULL DEFAULT (''),
    [CASE_ID] nvarchar(50) NULL DEFAULT (''),
    [STR_SUSR1] nvarchar(50) NULL DEFAULT (''),
    [STR_SUSR2] nvarchar(50) NULL DEFAULT (''),
    [STR_SUSR3] nvarchar(50) NULL DEFAULT (''),
    [STR_SUSR4] nvarchar(50) NULL DEFAULT (''),
    [STR_SUSR5] nvarchar(50) NULL DEFAULT (''),
    [STR_CLIENT_GROUP] nvarchar(50) NULL DEFAULT (''),
    [STR_SEGMENT] nvarchar(50) NULL DEFAULT (''),
    [SKU_DESCRIPTION] nvarchar(60) NULL DEFAULT (''),
    [SKU_SUSR1] nvarchar(50) NULL DEFAULT (''),
    [SKU_SUSR2] nvarchar(50) NULL DEFAULT (''),
    [SKU_SUSR3] nvarchar(50) NULL DEFAULT (''),
    [SKU_SUSR4] nvarchar(50) NULL DEFAULT (''),
    [SKU_SUSR5] nvarchar(50) NULL DEFAULT (''),
    [SKU_STDGROSSWGT] nvarchar(50) NULL DEFAULT (''),
    [SKU_STDNETWGT] nvarchar(50) NULL DEFAULT (''),
    [SKU_STDCUBE] nvarchar(50) NULL DEFAULT (''),
    [SKU_CLASS] nvarchar(50) NULL DEFAULT (''),
    [SKU_GROUP] nvarchar(50) NULL DEFAULT (''),
    [SKU_ITEM_CLASS] nvarchar(50) NULL DEFAULT (''),
    [SKU_STYLE] nvarchar(50) NULL DEFAULT (''),
    [SKU_COLOR] nvarchar(50) NULL DEFAULT (''),
    [SKU_SIZE] nvarchar(50) NULL DEFAULT (''),
    [SKU_MEASUREMENT] nvarchar(50) NULL DEFAULT (''),
    [SKU_VAS] nvarchar(50) NULL DEFAULT (''),
    [SKU_OVAS] nvarchar(50) NULL DEFAULT (''),
    [SKU_HAZARDOUSFLAG] nvarchar(50) NULL DEFAULT (''),
    [SKU_TEMPERATUREFLAG] nvarchar(50) NULL DEFAULT (''),
    [SKU_PRODUCTMODEL] nvarchar(50) NULL DEFAULT (''),
    [SKU_PREPACKINDICATOR] nvarchar(50) NULL DEFAULT (''),
    [SKU_BUSR1] nvarchar(200) NULL DEFAULT (''),
    [SKU_BUSR2] nvarchar(200) NULL DEFAULT (''),
    [SKU_BUSR3] nvarchar(200) NULL DEFAULT (''),
    [SKU_BUSR4] nvarchar(200) NULL DEFAULT (''),
    [SKU_BUSR5] nvarchar(200) NULL DEFAULT (''),
    [SKU_BUSR6] nvarchar(200) NULL DEFAULT (''),
    [SKU_BUSR7] nvarchar(200) NULL DEFAULT (''),
    [SKU_BUSR8] nvarchar(200) NULL DEFAULT (''),
    [SKU_BUSR9] nvarchar(200) NULL DEFAULT (''),
    [SKU_BUSR10] nvarchar(200) NULL DEFAULT (''),
    [SKU_CASECNT] nvarchar(30) NULL DEFAULT (''),
    [FT_USD_01] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_02] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_03] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_04] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_05] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_06] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_07] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_08] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_09] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_10] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_11] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_12] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_13] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_14] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_15] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_16] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_17] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_18] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_19] nvarchar(50) NULL DEFAULT (''),
    [FT_USD_20] nvarchar(50) NULL DEFAULT (''),
    [LOT_LOTTABLE_01] nvarchar(30) NULL DEFAULT (''),
    [LOT_LOTTABLE_02] nvarchar(30) NULL DEFAULT (''),
    [LOT_LOTTABLE_03] nvarchar(30) NULL DEFAULT (''),
    [LOT_LOTTABLE_04] datetime NULL DEFAULT (''),
    [LOT_LOTTABLE_05] datetime NULL DEFAULT (''),
    [LOT_LOTTABLE_06] nvarchar(30) NULL DEFAULT (''),
    [LOT_LOTTABLE_07] nvarchar(30) NULL DEFAULT (''),
    [LOT_LOTTABLE_08] nvarchar(30) NULL DEFAULT (''),
    [LOT_LOTTABLE_09] nvarchar(30) NULL DEFAULT (''),
    [LOT_LOTTABLE_10] nvarchar(30) NULL DEFAULT (''),
    [LOT_LOTTABLE_11] nvarchar(30) NULL DEFAULT (''),
    [LOT_LOTTABLE_12] nvarchar(30) NULL DEFAULT (''),
    [LOT_LOTTABLE_13] datetime NULL DEFAULT (''),
    [LOT_LOTTABLE_14] datetime NULL DEFAULT (''),
    [LOT_LOTTABLE_15] datetime NULL DEFAULT (''),
    [BILLABLE_DATE] datetime NULL DEFAULT (''),
    [R_SKU_COUNT] numeric(14, 0) NULL DEFAULT ((0)),
    [R_LABEL_COUNT] numeric(14, 0) NULL DEFAULT ((0)),
    [R_CC_WMS_QTY] numeric(20, 6) NULL DEFAULT ((0)),
    [R_SERVICE_PROVIDER] nvarchar(50) NULL DEFAULT (''),
    [R_SHIPMENT_ID] nvarchar(50) NULL DEFAULT (''),
    [R_LINE_PRICE] numeric(20, 6) NULL DEFAULT ((0)),
    [R_LINE_TOTAL] numeric(20, 6) NULL DEFAULT ((0)),
    [ArchiveCop] nvarchar(1) NULL,
    [DBID] nvarchar(20) NULL DEFAULT (db_name()),
    CONSTRAINT [PK_WMS_TPB_BASE_SEQ] PRIMARY KEY ([SEQ])
);
GO

CREATE INDEX [IDX_WMS_TPB_BASE_01] ON [dbo].[wms_tpb_base] ([BatchNo], [CODE], [DOCUMENT_ID]);
GO
CREATE INDEX [IDX_WMS_TPB_BASE_02] ON [dbo].[wms_tpb_base] ([BatchNo], [STATUS]);
GO