CREATE TABLE [dbo].[wmsorm]
(
    [ORDERKEY] nvarchar(10) NOT NULL,
    [STORERKEY] nvarchar(15) NOT NULL,
    [EXTERNORDERKEY] nvarchar(50) NOT NULL,
    [ORDERDATE] decimal(8, 0) NOT NULL,
    [DELIVERYDATE] decimal(8, 0) NOT NULL,
    [PRIORITY] nvarchar(10) NOT NULL,
    [CONSIGNEEKEY] nvarchar(15) NOT NULL,
    [C_CONTACT1] nvarchar(30) NOT NULL,
    [C_CONTACT2] nvarchar(30) NOT NULL,
    [C_COMPANY] nvarchar(45) NOT NULL,
    [C_ADDRESS1] nvarchar(45) NOT NULL,
    [C_ADDRESS2] nvarchar(45) NOT NULL,
    [C_ADDRESS3] nvarchar(45) NOT NULL,
    [C_ADDRESS4] nvarchar(45) NOT NULL,
    [C_CITY] nvarchar(45) NOT NULL,
    [C_STATE] nvarchar(2) NOT NULL,
    [C_ZIP] nvarchar(18) NOT NULL,
    [C_COUNTRY] nvarchar(30) NOT NULL,
    [C_ISOCNTRYCODE] nvarchar(10) NOT NULL,
    [C_PHONE1] nvarchar(18) NOT NULL,
    [C_PHONE2] nvarchar(18) NOT NULL,
    [C_FAX1] nvarchar(18) NOT NULL,
    [C_FAX2] nvarchar(18) NOT NULL,
    [C_VAT] nvarchar(18) NOT NULL,
    [BUYERPO] nvarchar(20) NOT NULL,
    [BILLTOKEY] nvarchar(15) NOT NULL,
    [B_CONTACT1] nvarchar(30) NOT NULL,
    [B_CONTACT2] nvarchar(30) NOT NULL,
    [B_COMPANY] nvarchar(45) NOT NULL,
    [B_ADDRESS1] nvarchar(45) NOT NULL,
    [B_ADDRESS2] nvarchar(45) NOT NULL,
    [B_ADDRESS3] nvarchar(45) NOT NULL,
    [B_ADDRESS4] nvarchar(45) NOT NULL,
    [B_CITY] nvarchar(45) NOT NULL,
    [B_STATE] nvarchar(2) NOT NULL,
    [B_ZIP] nvarchar(18) NOT NULL,
    [B_COUNTRY] nvarchar(30) NOT NULL,
    [B_ISOCNTRYCODE] nvarchar(10) NOT NULL,
    [B_PHONE1] nvarchar(18) NOT NULL,
    [B_PHONE2] nvarchar(18) NOT NULL,
    [B_FAX1] nvarchar(18) NOT NULL,
    [B_FAX2] nvarchar(18) NOT NULL,
    [B_VAT] nvarchar(18) NOT NULL,
    [INCOTERM] nvarchar(10) NOT NULL,
    [PMTTERM] nvarchar(10) NOT NULL,
    [OPENQTY] decimal(7, 0) NOT NULL,
    [STATUS] nvarchar(10) NOT NULL,
    [DISCHARGEPLACE] nvarchar(30) NOT NULL,
    [DELIVERYPLACE] nvarchar(30) NOT NULL,
    [INTERMODALVEHICLE] nvarchar(30) NOT NULL,
    [COUNTRYOFORIGIN] nvarchar(30) NOT NULL,
    [COUNTRYDESTINATION] nvarchar(30) NOT NULL,
    [UPDATESOURCE] nvarchar(10) NOT NULL,
    [TYPE] nvarchar(10) NOT NULL,
    [ORDERGROUP] nvarchar(20) NOT NULL,
    [DOOR] nvarchar(10) NOT NULL,
    [ROUTE] nvarchar(10) NOT NULL,
    [STOP] nvarchar(10) NOT NULL,
    [NOTES] nvarchar(70) NOT NULL,
    [EFFECTIVEDATE] decimal(8, 0) NOT NULL,
    [ADDDATE] decimal(8, 0) NOT NULL,
    [ADDWHO] nvarchar(128) NOT NULL,
    [EDITDATE] decimal(8, 0) NOT NULL,
    [EDITWHO] nvarchar(128) NOT NULL,
    [TRAFFICCOP] nvarchar(1) NOT NULL,
    [ARCHIVECOP] nvarchar(1) NOT NULL,
    [CONTAINERTYPE] nvarchar(20) NOT NULL,
    [CONTAINERQTY] decimal(7, 0) NOT NULL,
    [BILLEDCONTAINERQTY] decimal(7, 0) NOT NULL,
    [SOSTATUS] nvarchar(10) NOT NULL,
    [MBOLKEY] nvarchar(10) NOT NULL,
    [INVOICENO] nvarchar(10) NOT NULL,
    [INVOICEAMOUNT] decimal(11, 4) NOT NULL,
    [SALESMAN] nvarchar(30) NOT NULL,
    [GROSSWEIGHT] decimal(11, 4) NOT NULL,
    [CAPACITY] decimal(11, 4) NOT NULL,
    [PRINTFLAG] nvarchar(1) NOT NULL,
    [LOADKEY] nvarchar(10) NOT NULL,
    [RDD] nvarchar(30) NOT NULL,
    [NOTES2] nvarchar(70) NOT NULL,
    [SEQUENCENO] decimal(7, 0) NOT NULL,
    [RDS] nvarchar(1) NOT NULL,
    [SECTIONKEY] nvarchar(10) NOT NULL,
    [WMS_FLAG] nvarchar(2) NOT NULL,
    [FACILITY] nvarchar(5) NULL,
    [AddDateSys] datetime NOT NULL DEFAULT (getdate()),
    [RoutingTool] nvarchar(30) NULL,
    CONSTRAINT [PK_WMSORM] PRIMARY KEY ([EXTERNORDERKEY])
);
GO

CREATE INDEX [IX_WMSORM_WMSFLAG] ON [dbo].[wmsorm] ([WMS_FLAG]);
GO