CREATE TABLE [dbo].[wmspak]
(
    [PACKKEY] nvarchar(10) NOT NULL,
    [PACKDESCR] nvarchar(45) NOT NULL,
    [PACKUOM1] nvarchar(10) NOT NULL,
    [CASECNT] decimal(8, 0) NOT NULL,
    [ISWHQTY1] nvarchar(1) NOT NULL,
    [REPLENISHUOM1] nvarchar(1) NOT NULL,
    [REPLENISHZONE1] nvarchar(10) NOT NULL,
    [CARTONIZEUOM1] nvarchar(1) NOT NULL,
    [LENGTHUOM1] decimal(8, 2) NOT NULL,
    [WIDTHUOM1] decimal(8, 2) NOT NULL,
    [HEIGHTUOM1] decimal(8, 2) NOT NULL,
    [CUBEUOM1] decimal(8, 2) NOT NULL,
    [PACKUOM2] nvarchar(10) NOT NULL,
    [INNERPACK] decimal(8, 0) NOT NULL,
    [ISWHQTY2] nvarchar(1) NOT NULL,
    [REPLENISHUOM2] nvarchar(1) NOT NULL,
    [REPLENISHZONE2] nvarchar(10) NOT NULL,
    [CARTONIZEUOM2] nvarchar(1) NOT NULL,
    [LENGTHUOM2] decimal(8, 2) NOT NULL,
    [WIDTHUOM2] decimal(8, 2) NOT NULL,
    [HEIGHTUOM2] decimal(8, 2) NOT NULL,
    [CUBEUOM2] decimal(8, 2) NOT NULL,
    [PACKUOM3] nvarchar(10) NOT NULL,
    [QTY] decimal(8, 0) NOT NULL,
    [ISWHQTY3] nvarchar(1) NOT NULL,
    [REPLENISHUOM3] nvarchar(1) NOT NULL,
    [REPLENISHZONE3] nvarchar(10) NOT NULL,
    [CARTONIZEUOM3] nvarchar(1) NOT NULL,
    [LENGTHUOM3] decimal(8, 2) NOT NULL,
    [WIDTHUOM3] decimal(8, 2) NOT NULL,
    [HEIGHTUOM3] decimal(8, 2) NOT NULL,
    [CUBEUOM3] decimal(8, 2) NOT NULL,
    [PACKUOM4] nvarchar(10) NOT NULL,
    [PALLET] decimal(8, 0) NOT NULL,
    [ISWHQTY4] nvarchar(1) NOT NULL,
    [REPLENISHUOM4] nvarchar(1) NOT NULL,
    [REPLENISHZONE4] nvarchar(10) NOT NULL,
    [CARTONIZEUOM4] nvarchar(1) NOT NULL,
    [LENGTHUOM4] decimal(8, 2) NOT NULL,
    [WIDTHUOM4] decimal(8, 2) NOT NULL,
    [HEIGHTUOM4] decimal(8, 2) NOT NULL,
    [CUBEUOM4] decimal(8, 2) NOT NULL,
    [PALLETWOODLENGTH] decimal(8, 2) NOT NULL,
    [PALLETWOODWIDTH] decimal(8, 2) NOT NULL,
    [PALLETWOODHEIGHT] decimal(8, 2) NOT NULL,
    [PALLETTI] decimal(4, 0) NOT NULL,
    [PALLETHI] decimal(4, 0) NOT NULL,
    [PACKUOM5] nvarchar(10) NOT NULL,
    [CUBE] decimal(8, 2) NOT NULL,
    [ISWHQTY5] nvarchar(1) NOT NULL,
    [PACKUOM6] nvarchar(10) NOT NULL,
    [GROSSWGT] decimal(8, 2) NOT NULL,
    [ISWHQTY6] nvarchar(1) NOT NULL,
    [PACKUOM7] nvarchar(10) NOT NULL,
    [NETWGT] decimal(8, 2) NOT NULL,
    [ISWHQTY7] nvarchar(1) NOT NULL,
    [PACKUOM8] nvarchar(10) NOT NULL,
    [OTHERUNIT1] decimal(8, 0) NOT NULL,
    [ISWHQTY8] nvarchar(1) NOT NULL,
    [REPLENISHUOM8] nvarchar(1) NOT NULL,
    [REPLENISHZONE8] nvarchar(10) NOT NULL,
    [CARTONIZEUOM8] nvarchar(1) NOT NULL,
    [LENGTHUOM8] decimal(8, 2) NOT NULL,
    [WIDTHUOM8] decimal(8, 2) NOT NULL,
    [HEIGHTUOM8] decimal(8, 2) NOT NULL,
    [PACKUOM9] nvarchar(10) NOT NULL,
    [OTHERUNIT2] decimal(8, 0) NOT NULL,
    [ISWHQTY9] nvarchar(1) NOT NULL,
    [REPLENISHUOM9] nvarchar(1) NOT NULL,
    [REPLENISHZONE9] nvarchar(10) NOT NULL,
    [CARTONIZEUOM9] nvarchar(1) NOT NULL,
    [LENGTHUOM9] decimal(8, 2) NOT NULL,
    [WIDTHUOM9] decimal(8, 2) NOT NULL,
    [HEIGHTUOM9] decimal(8, 2) NOT NULL,
    [ADDDATE] decimal(8, 0) NOT NULL,
    [ADDWHO] nvarchar(128) NOT NULL,
    [EDITDATE] decimal(8, 0) NOT NULL,
    [EDITWHO] nvarchar(128) NOT NULL,
    [TRAFFICCOP] nvarchar(1) NOT NULL,
    [ARCHIVECOP] nvarchar(1) NOT NULL,
    [TIMESTAMP] nvarchar(8) NOT NULL
);
GO
