CREATE TABLE [dbo].[wmsrcm]
(
    [RECEIPTKEY] nvarchar(10) NOT NULL,
    [EXTERNRECEIPTKEY] nvarchar(20) NOT NULL,
    [RECEIPTGROUP] nvarchar(20) NOT NULL,
    [STORERKEY] nvarchar(15) NOT NULL,
    [RECEIPTDATE] decimal(8, 0) NOT NULL,
    [POKEY] nvarchar(18) NOT NULL,
    [CARRIERKEY] nvarchar(15) NOT NULL,
    [CARRIERNAME] nvarchar(30) NOT NULL,
    [CARRIERADDRESS1] nvarchar(45) NOT NULL,
    [CARRIERADDRESS2] nvarchar(45) NOT NULL,
    [CARRIERCITY] nvarchar(45) NOT NULL,
    [CARRIERSTATE] nvarchar(2) NOT NULL,
    [CARRIERZIP] nvarchar(10) NOT NULL,
    [CARRIERREFERENCE] nvarchar(18) NOT NULL,
    [WAREHOUSEREFERENCE] nvarchar(18) NOT NULL,
    [ORIGINCOUNTRY] nvarchar(30) NOT NULL,
    [DESTINATIONCOUNTRY] nvarchar(30) NOT NULL,
    [VEHICLENUMBER] nvarchar(18) NOT NULL,
    [VEHICLEDATE] nvarchar(18) NOT NULL,
    [PLACEOFLOADING] nvarchar(18) NOT NULL,
    [PLACEOFDISCHARGE] nvarchar(18) NOT NULL,
    [PLACEOFDELIVERY] nvarchar(18) NOT NULL,
    [INCOTERMS] nvarchar(10) NOT NULL,
    [TERMSNOTE] nvarchar(18) NOT NULL,
    [CONTAINERKEY] nvarchar(18) NOT NULL,
    [SIGNATORY] nvarchar(18) NOT NULL,
    [PLACEOFISSUE] nvarchar(18) NOT NULL,
    [OPENQTY] numeric(18, 0) NOT NULL,
    [STATUS] nvarchar(10) NOT NULL,
    [NOTES] nvarchar(16) NOT NULL,
    [EFFECTIVEDATE] decimal(8, 0) NOT NULL,
    [ADDDATE] decimal(8, 0) NOT NULL,
    [ADDWHO] nvarchar(128) NOT NULL,
    [EDITDATE] decimal(8, 0) NOT NULL,
    [EDITWHO] nvarchar(128) NOT NULL,
    [TRAFFICCOP] nvarchar(1) NOT NULL,
    [ARCHIVECOP] nvarchar(1) NOT NULL,
    [CONTAINERTYPE] nvarchar(20) NOT NULL,
    [CONTAINERQTY] numeric(18, 0) NOT NULL,
    [BILLEDCONTAINERQTY] decimal(4, 0) NOT NULL,
    [RECTYPE] nvarchar(10) NOT NULL,
    [ASNSTATUS] nvarchar(10) NOT NULL,
    [ASNREASON] nvarchar(10) NOT NULL,
    [WMS_FLAG] nvarchar(2) NOT NULL
);
GO
