CREATE TABLE [dbo].[workorderjobdetail]
(
    [JobKey] nvarchar(10) NOT NULL DEFAULT (''),
    [Facility] nvarchar(5) NOT NULL DEFAULT (''),
    [Storerkey] nvarchar(15) NOT NULL DEFAULT (''),
    [MasterWorkOrder] nvarchar(50) NOT NULL DEFAULT (''),
    [JobStatus] nvarchar(10) NOT NULL DEFAULT ('0'),
    [Priority] nvarchar(10) NOT NULL DEFAULT ('9'),
    [EstJobStartTime] datetime NULL DEFAULT (getdate()),
    [EstJobDuration] int NULL DEFAULT ((0)),
    [EstCompletionTime] datetime NULL,
    [ActualJobStartTime] datetime NULL,
    [ActualJobDuration] int NULL DEFAULT ((0)),
    [ActualCompletionTime] datetime NULL,
    [RemainingDuration] int NULL DEFAULT ((0)),
    [QAType] nvarchar(20) NULL,
    [QAValue] int NULL DEFAULT ((0)),
    [QALocation] nvarchar(10) NULL,
    [TempStaging] nvarchar(10) NULL,
    [WORelease] nvarchar(50) NULL,
    [NoOfWorkStation] int NOT NULL DEFAULT ((0)),
    [NoOfAssignedWorker] int NOT NULL DEFAULT ((0)),
    [EstUnitPerHour] int NOT NULL DEFAULT ((0)),
    [ActualUnitPerHour] int NOT NULL DEFAULT ((0)),
    [AvgUnitPerWorker] float NOT NULL DEFAULT ((0.00)),
    [QtyJob] int NULL DEFAULT ((0)),
    [QtyReleased] int NULL DEFAULT ((0)),
    [QtyRemaining] int NULL DEFAULT ((0)),
    [QtyCompleted] int NULL DEFAULT ((0)),
    [QtyItemsOrd] int NULL DEFAULT ((0)),
    [QtyItemsRes] int NULL DEFAULT ((0)),
    [QtyItemsNeed] int NULL DEFAULT ((0)),
    [QtyNonInvOrd] int NULL DEFAULT ((0)),
    [QtyNonInvRes] int NULL DEFAULT ((0)),
    [QtyNonInvNeed] int NULL DEFAULT ((0)),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [UOMQtyJob] int NULL DEFAULT ((0)),
    CONSTRAINT [PK_WorkOrderJobDetail] PRIMARY KEY ([JobKey])
);
GO
