CREATE TABLE [dbo].[workorderrequestinputs]
(
    [WkOrdReqInputsKey] nvarchar(10) NOT NULL DEFAULT (''),
    [WorkOrderKey] nvarchar(10) NOT NULL DEFAULT (''),
    [WkOrdInputsKey] nvarchar(10) NOT NULL DEFAULT (''),
    [StepNumber] nvarchar(5) NOT NULL DEFAULT (''),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (''),
    [SKU] nvarchar(20) NOT NULL DEFAULT (''),
    [PackKey] nvarchar(10) NOT NULL DEFAULT (''),
    [UOM] nvarchar(10) NOT NULL DEFAULT (''),
    [Qty] int NULL DEFAULT ((0)),
    [QtyRequired] int NULL DEFAULT ((0)),
    [QtyJob] int NULL DEFAULT ((0)),
    [QtyReleased] int NULL DEFAULT ((0)),
    [QtyCompleted] int NULL DEFAULT ((0)),
    [QtyRemaining] int NULL DEFAULT ((0)),
    [InLocation] nvarchar(10) NOT NULL DEFAULT (''),
    [Wastage] decimal(18, 2) NULL DEFAULT ((0.00)),
    [Rotation] nvarchar(10) NULL DEFAULT (''),
    [MinShelf] int NULL DEFAULT ((0)),
    [PullType] nvarchar(10) NULL DEFAULT ((0)),
    [MinQty] int NULL DEFAULT ((0)),
    [MinUOM] nvarchar(10) NULL DEFAULT (''),
    [PullQty] int NULL DEFAULT ((0)),
    [PullUOM] nvarchar(10) NULL DEFAULT (''),
    [Lottable01] nvarchar(20) NULL,
    [Lottable02] nvarchar(20) NULL,
    [Lottable03] nvarchar(20) NULL,
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [NonInvSKU] nvarchar(80) NOT NULL DEFAULT (''),
    [NonInvLocation] nvarchar(10) NOT NULL DEFAULT (''),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Lottable06] nvarchar(30) NULL,
    [Lottable07] nvarchar(30) NULL,
    [Lottable08] nvarchar(30) NULL,
    [Lottable09] nvarchar(30) NULL,
    [Lottable10] nvarchar(30) NULL,
    [Lottable11] nvarchar(30) NULL,
    [Lottable12] nvarchar(30) NULL,
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [JobKey] nvarchar(10) NULL DEFAULT (''),
    [QtyAddOn] int NOT NULL DEFAULT ((0)),
    CONSTRAINT [PK_WorkOrderRequestInputs] PRIMARY KEY ([WkOrdReqInputsKey])
);
GO
