CREATE TABLE [dbo].[workorderoutputs]
(
    [WkOrdOutputsKey] nvarchar(10) NOT NULL DEFAULT (''),
    [MasterWorkOrder] nvarchar(50) NULL,
    [WorkOrderName] nvarchar(50) NULL,
    [StepNumber] nvarchar(5) NULL,
    [StorerKey] nvarchar(15) NULL,
    [SKU] nvarchar(20) NULL,
    [PackKey] nvarchar(10) NULL,
    [UOM] nvarchar(10) NULL,
    [OutLocation] nvarchar(10) NULL,
    [Qty] int NULL DEFAULT ((0)),
    [InventoryStatus] nvarchar(10) NULL DEFAULT ('0'),
    [NonInvSKU] nvarchar(80) NULL,
    [BillingUOMQty] int NULL DEFAULT ((0)),
    [BillingUOM] nvarchar(20) NULL,
    [BillingRate] money NULL DEFAULT ((0.00)),
    [PrimaryStorer] nvarchar(15) NULL,
    [PrimarySKU] nvarchar(20) NULL,
    [Lottable01Rules] nvarchar(20) NULL,
    [Lottable02Rules] nvarchar(20) NULL,
    [Lottable03Rules] nvarchar(20) NULL,
    [Lottable04Rules] nvarchar(20) NULL,
    [Lottable05Rules] nvarchar(20) NULL,
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Lottable06Rules] nvarchar(20) NULL,
    [Lottable07Rules] nvarchar(20) NULL,
    [Lottable08Rules] nvarchar(20) NULL,
    [Lottable09Rules] nvarchar(20) NULL,
    [Lottable10Rules] nvarchar(20) NULL,
    [Lottable11Rules] nvarchar(20) NULL,
    [Lottable12Rules] nvarchar(20) NULL,
    [Lottable13Rules] nvarchar(20) NULL,
    [Lottable14Rules] nvarchar(20) NULL,
    [Lottable15Rules] nvarchar(20) NULL,
    CONSTRAINT [PK_WORKORDEROUTPUTS] PRIMARY KEY ([WkOrdOutputsKey])
);
GO
