CREATE TABLE [dbo].[workorderrequest]
(
    [WorkOrderKey] nvarchar(10) NOT NULL DEFAULT (''),
    [Facility] nvarchar(5) NOT NULL DEFAULT (''),
    [Storerkey] nvarchar(15) NOT NULL DEFAULT (''),
    [MasterWorkOrder] nvarchar(50) NOT NULL DEFAULT (''),
    [WorkOrderName] nvarchar(50) NOT NULL DEFAULT (''),
    [StartDate] datetime NULL DEFAULT (getdate()),
    [DueDate] datetime NULL DEFAULT (getdate()),
    [ExternalReference] nvarchar(30) NULL DEFAULT (''),
    [Qty] int NULL DEFAULT ((0)),
    [QtyJob] int NULL DEFAULT ((0)),
    [QtyReleased] int NULL DEFAULT ((0)),
    [QtyCompleted] int NULL DEFAULT ((0)),
    [QtyRemaining] int NULL DEFAULT ((0)),
    [WOStatus] nvarchar(20) NOT NULL DEFAULT ('0'),
    [Priority] nvarchar(5) NOT NULL DEFAULT ('9'),
    [WorkStation] nvarchar(50) NULL DEFAULT (''),
    [Notes] nvarchar(2000) NULL DEFAULT (''),
    [UDF1] nvarchar(20) NOT NULL DEFAULT (''),
    [UDF2] nvarchar(20) NOT NULL DEFAULT (''),
    [UDF3] nvarchar(20) NOT NULL DEFAULT (''),
    [UDF4] nvarchar(20) NOT NULL DEFAULT (''),
    [UDF5] nvarchar(20) NOT NULL DEFAULT (''),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [UOMQty] int NULL DEFAULT ((0)),
    [UOMQtyRemaining] int NULL DEFAULT ((0)),
    [PackQty] int NULL DEFAULT ((0)),
    CONSTRAINT [PK_WorkOrderRequest] PRIMARY KEY ([WorkOrderKey])
);
GO
