CREATE TABLE [dbo].[workorderrequestoutputs]
(
    [WkOrdReqOutputsKey] nvarchar(10) NOT NULL DEFAULT (''),
    [WorkOrderKey] nvarchar(10) NOT NULL DEFAULT (''),
    [WkOrdOutputsKey] nvarchar(10) NOT NULL DEFAULT (''),
    [StepNumber] nvarchar(5) NOT NULL DEFAULT (''),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (''),
    [SKU] nvarchar(20) NOT NULL DEFAULT (''),
    [PackKey] nvarchar(10) NOT NULL DEFAULT (''),
    [UOM] nvarchar(10) NOT NULL DEFAULT (''),
    [OutLocation] nvarchar(10) NOT NULL DEFAULT (''),
    [Qty] int NULL DEFAULT ((0)),
    [QtyCompleted] int NULL DEFAULT ((0)),
    [QtyRemaining] int NULL DEFAULT ((0)),
    [InventoryStatus] nvarchar(10) NOT NULL DEFAULT ('0'),
    [NonInvSKU] nvarchar(80) NOT NULL DEFAULT (''),
    [BillingUOMQty] int NULL DEFAULT ((0)),
    [BillingUOM] nvarchar(20) NULL DEFAULT (''),
    [BillingRate] money NULL DEFAULT ((0.00)),
    [PrimaryStorer] nvarchar(15) NOT NULL DEFAULT (''),
    [PrimarySKU] nvarchar(20) NOT NULL DEFAULT (''),
    [Lottable01Rules] nvarchar(20) NULL,
    [Lottable02Rules] nvarchar(20) NULL,
    [Lottable03Rules] nvarchar(20) NULL,
    [Lottable04Rules] nvarchar(20) NULL,
    [Lottable05Rules] nvarchar(20) NULL,
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Lottable06Rules] nvarchar(20) NULL,
    [Lottable07Rules] nvarchar(20) NULL,
    [Lottable08Rules] nvarchar(20) NULL,
    [Lottable09Rules] nvarchar(20) NULL,
    [Lottable10Rules] nvarchar(20) NULL,
    [Lottable11Rules] nvarchar(20) NULL,
    [Lottable12Rules] nvarchar(20) NULL,
    [Lottable13Rules] nvarchar(20) NULL,
    [Lottable14Rules] nvarchar(20) NULL,
    [Lottable15Rules] nvarchar(20) NULL,
    CONSTRAINT [PK_WorkOrderRequestOutputs] PRIMARY KEY ([WkOrdReqOutputsKey])
);
GO
