CREATE TABLE [dbo].[workorderjoboperation]
(
    [JobKey] nvarchar(10) NOT NULL DEFAULT (''),
    [JobLine] nvarchar(5) NOT NULL DEFAULT (''),
    [MinStep] nvarchar(5) NOT NULL DEFAULT (''),
    [WOOperation] nvarchar(30) NOT NULL DEFAULT (''),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (''),
    [SKU] nvarchar(20) NOT NULL DEFAULT (''),
    [NonInvSku] nvarchar(80) NOT NULL DEFAULT (''),
    [NonInvLocation] nvarchar(10) NOT NULL DEFAULT (''),
    [PackKey] nvarchar(10) NOT NULL DEFAULT (''),
    [UOM] nvarchar(10) NOT NULL DEFAULT (''),
    [StepQty] int NULL DEFAULT ((0)),
    [QtyReserved] int NULL DEFAULT ((0)),
    [QtyToProcess] int NULL DEFAULT ((0)),
    [QtyInProcess] int NULL DEFAULT ((0)),
    [QtyCompleted] int NULL DEFAULT ((0)),
    [PendingTasks] int NULL DEFAULT ((0)),
    [InProcessTasks] int NULL DEFAULT ((0)),
    [CompletedTasks] int NULL DEFAULT ((0)),
    [CurrentLPN] nvarchar(18) NULL,
    [Instructions] nvarchar(4000) NULL DEFAULT (''),
    [FromLoc] nvarchar(10) NULL DEFAULT (''),
    [ToLoc] nvarchar(10) NULL DEFAULT (''),
    [CopyInputFromStep] nvarchar(5) NULL,
    [JobStatus] nvarchar(10) NULL DEFAULT ('0'),
    [PullType] nvarchar(10) NULL DEFAULT (''),
    [MinQty] int NULL DEFAULT ((0)),
    [MinUOM] nvarchar(10) NULL DEFAULT (''),
    [PullQty] int NULL DEFAULT ((0)),
    [PullUOM] nvarchar(10) NULL DEFAULT (''),
    [InLocation] nvarchar(10) NULL DEFAULT (''),
    [Rotation] nvarchar(10) NULL DEFAULT (''),
    [MinShelf] int NULL DEFAULT ((0)),
    [Lottable01] nvarchar(20) NULL,
    [Lottable02] nvarchar(20) NULL,
    [Lottable03] nvarchar(20) NULL,
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [STDTime] decimal(18, 6) NULL DEFAULT ((0.000000)),
    [EstimatedDuration] int NULL DEFAULT ((0)),
    [ActualDuration] int NULL DEFAULT ((0)),
    [RemainingDuration] int NULL DEFAULT ((0)),
    [ActualJobStartTime] datetime NULL,
    [ActualJobDuration] int NULL DEFAULT ((0)),
    [ActualCompletionTime] datetime NULL,
    [BillingUOMQty] int NULL DEFAULT ((0)),
    [BillingUOM] nvarchar(20) NULL DEFAULT (''),
    [BillingRate] money NULL DEFAULT ((0.00)),
    [ExtendedBillingQty] int NULL DEFAULT ((0)),
    [TotalBillingAmount] money NULL DEFAULT ((0.00)),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Lottable06] nvarchar(30) NULL,
    [Lottable07] nvarchar(30) NULL,
    [Lottable08] nvarchar(30) NULL,
    [Lottable09] nvarchar(30) NULL,
    [Lottable10] nvarchar(30) NULL,
    [Lottable11] nvarchar(30) NULL,
    [Lottable12] nvarchar(30) NULL,
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    CONSTRAINT [PK_WorkOrderJobOperation] PRIMARY KEY ([JobKey], [JobLine])
);
GO
