CREATE TABLE [dbo].[workorder_uncasing]
(
    [RowRef] int IDENTITY(1,1) NOT NULL,
    [WorkStation] nvarchar(50) NOT NULL,
    [JobKey] nvarchar(10) NOT NULL,
    [WorkOrderKey] nvarchar(10) NOT NULL,
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (''),
    [SKU] nvarchar(20) NOT NULL DEFAULT (''),
    [Qty] int NOT NULL DEFAULT ((0)),
    [QtyCompleted] int NOT NULL DEFAULT ((0)),
    [QtyRemaining] int NOT NULL DEFAULT ((0)),
    [ID] nvarchar(18) NOT NULL DEFAULT (''),
    [SSCC] nvarchar(20) NOT NULL DEFAULT (''),
    [InLOC] nvarchar(10) NOT NULL DEFAULT (''),
    [OutLoc] nvarchar(10) NOT NULL DEFAULT (''),
    [Lot] nvarchar(10) NOT NULL DEFAULT (''),
    [Lottable01] nvarchar(20) NULL,
    [Lottable02] nvarchar(20) NULL,
    [Lottable03] nvarchar(20) NULL,
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [Lottable06] nvarchar(30) NULL,
    [Lottable07] nvarchar(30) NULL,
    [Lottable08] nvarchar(30) NULL,
    [Lottable09] nvarchar(30) NULL,
    [Lottable10] nvarchar(30) NULL,
    [Lottable11] nvarchar(30) NULL,
    [Lottable12] nvarchar(30) NULL,
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [StartDate] datetime NOT NULL DEFAULT (getdate()),
    [EndDate] datetime NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [ArchiveCop] nvarchar(1) NULL,
    [SystemQty] int NOT NULL DEFAULT ((0)),
    CONSTRAINT [PK_WorkOrder_UnCasing] PRIMARY KEY ([RowRef])
);
GO
