CREATE TABLE [dbo].[xdockdetail]
(
    [XDOCKKEY] nvarchar(10) NOT NULL,
    [XDOCKLineNumber] nvarchar(5) NOT NULL DEFAULT (' '),
    [ReceivedQty] int NOT NULL DEFAULT ((1)),
    [ReceivedGrossWeight] float NOT NULL DEFAULT ((0)),
    [ReceivedNetWeight] float NOT NULL DEFAULT ((0)),
    [ReceivedCube] float NOT NULL DEFAULT ((0)),
    [ExpectedQty] int NOT NULL DEFAULT ((0)),
    [ExpectedGrossWeight] float NOT NULL DEFAULT ((0)),
    [ExpectedNetWeight] float NOT NULL DEFAULT ((0)),
    [ExpectedCube] float NOT NULL DEFAULT ((0)),
    [ShippedQty] int NOT NULL DEFAULT ((0)),
    [ShippedGrossWeight] float NOT NULL DEFAULT ((0)),
    [ShippedNetWeight] float NOT NULL DEFAULT ((0)),
    [ShippedCube] float NOT NULL DEFAULT ((0)),
    [UOMWeight] nvarchar(10) NOT NULL DEFAULT (' '),
    [UOMCube] nvarchar(10) NOT NULL DEFAULT (' '),
    [RateClass] nvarchar(10) NOT NULL DEFAULT (' '),
    [Storerkey] nvarchar(15) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [SkuDescription] nvarchar(45) NOT NULL DEFAULT (' '),
    [Lottable01] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable02] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable03] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [ToLoc] nvarchar(10) NOT NULL,
    [ToId] nvarchar(18) NULL DEFAULT (' '),
    [ConditionCode] nvarchar(10) NOT NULL DEFAULT ('OK'),
    [ChargeableWeight] float NOT NULL DEFAULT ((0)),
    [Rate] float NOT NULL DEFAULT ((0)),
    [Extension] float NOT NULL DEFAULT ((0)),
    [UOMVolume] nvarchar(10) NOT NULL DEFAULT (' '),
    [Length] float NOT NULL DEFAULT ((0)),
    [Width] float NOT NULL DEFAULT ((0)),
    [Height] float NOT NULL DEFAULT ((0)),
    [Notes] nvarchar(4000) NULL,
    [EffectiveDate] datetime NOT NULL DEFAULT (getdate()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Lottable06] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable07] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable08] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable09] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable10] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable11] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable12] nvarchar(30) NOT NULL DEFAULT (' '),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    CONSTRAINT [PKXdockDetail] PRIMARY KEY ([XDOCKKEY], [XDOCKLineNumber]),
    CONSTRAINT [FK_XDOCKDETAIL_SKU_01] FOREIGN KEY ([Storerkey], [Sku]) REFERENCES [dbo].[SKU] ([StorerKey], [Sku]),
    CONSTRAINT [FK_XDOCKDETAIL_STORER_01] FOREIGN KEY ([Storerkey]) REFERENCES [dbo].[STORER] ([StorerKey])
);
GO
