SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
CREATE FUNCTION [dbo].[fnc_LTRIM] (@cString NVARCHAR(max))  
RETURNS NVARCHAR(max) AS  
BEGIN 
   RETURN CASE WHEN LTRIM(@cString) = '' THEN NULL ELSE LTRIM(@cString) END
END

GO