SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
CREATE FUNCTION [dbo].[fnc_RTRIM] (@cString NVARCHAR(max))  
RETURNS NVARCHAR(max) AS  
BEGIN 
   RETURN CASE WHEN RTRIM(@cString) = '' THEN NULL ELSE RTRIM(@cString) END
END

GO