SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO
-- [CN] WMS Add View To BI Schema For JReport - CONTAINERDETAIL https://jiralfl.atlassian.net/browse/WMS-19568

CREATE   VIEW [BI].[V_CONTAINERDETAIL] AS 
SELECT * 
   FROM dbo.CONTAINERDETAIL WITH (NOLOCK)  

GO