SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO

CREATE   VIEW [BI].[V_MBOL] AS
SELECT MbolKey
, Status
, ExternMbolKey
, OriginCountry
, DestinationCountry
, VesselQualifier
, Vessel
, PlaceOfLoadingQualifier
, PlaceOfLoading
, PlaceOfdischargeQualifier
, PlaceOfDischarge
, PlaceOfdeliveryQualifier
, PlaceOfdelivery
, TransMethod
, VoyageNumber
, DepartureDate
, ArrivalDate
, ArrivalDateFinalDestination
, BookingReference
, OtherReference
, CarrierKey
, Carrieragent
, EffectiveDate
, AddDate
, AddWho
, EditDate
, EditWho
, TrafficCop
, ArchiveCop
, TimeStamp
, DRIVERName
, LoadingDate
, CustomerReceivedDate
, Remarks
, TotalInvoiceValue
, GrossWeight
, Capacity
, InvoiceAmount
, Weight
, Cube
, CustCnt
, PalletCnt
, CaseCnt
, Facility
, COD_Status
, DepotStatus
, UserDefine01
, UserDefine02
, UserDefine03
, UserDefine04
, UserDefine05
, UserDefine06
, UserDefine07
, UserDefine08
, UserDefine09
, UserDefine10
, ShipCounter
, CTNTYPE
, NoofContainer
, CTNTYPE1
, CTNTYPE2
, CTNTYPE3
, CTNTYPE4
, CTNTYPE5
, CTNTYPE6
, CTNTYPE7
, CTNTYPE8
, CTNTYPE9
, CTNTYPE10
, PACKTYPE1
, PACKTYPE2
, PACKTYPE3
, PACKTYPE4
, PACKTYPE5
, PACKTYPE6
, PACKTYPE7
, PACKTYPE8
, PACKTYPE9
, PACKTYPE10
, CTNCNT1
, CTNCNT2
, CTNCNT3
, CTNCNT4
, CTNCNT5
, CTNCNT6
, CTNCNT7
, CTNCNT8
, CTNCNT9
, CTNCNT10
, CTNQTY1
, CTNQTY2
, CTNQTY3
, CTNQTY4
, CTNQTY5
, CTNQTY6
, CTNQTY7
, CTNQTY8
, CTNQTY9
, CTNQTY10
, NoOfMasterCtn
, NoOfPrepacks
, NoofReshippableCarton
, NoofCartonPacked
, NoofIDSCarton
, NoofCustomerCarton
, NoofPallets
, CartonWeight
, WeightUnit
, CartonCube
, CubeUnit
, ShipperAccountCode
, ConsigneeAccountCode
, NotifyAccountCode
, ContainerNo
, Equipment
, SealNo
, GIS_ControlNo
, Cust_ISA_ControlNo
, Cust_GIS_ControlNo
, GIS_ProcessTime
, Cust_EDIAckTime
, CBOLKey
, CBOLLineNumber
, ShipDate
, FinalizeFlag
, ValidatedFlag=CAST(ValidatedFlag AS NVARCHAR)
, Route
, Vehicle_Type
, Delivery_Zone
, OTMShipmentID
   FROM [dbo].[MBOL] WITH (NOLOCK)

GO