SET ANSI_NULLS OFF;
GO
SET QUOTED_IDENTIFIER OFF;
GO

--https://jiralfl.atlassian.net/browse/WMS-20039
CREATE   VIEW  [BI].[V_TMS_SHIPMENT] AS
SELECT *
FROM dbo.TMS_SHIPMENT WITH (NOLOCK)

GO