CREATE TABLE [rdt].[rdtcclock]
(
    [RowRef] int IDENTITY(1,1) NOT NULL,
    [Mobile] int NOT NULL,
    [CCKey] nvarchar(10) NOT NULL,
    [CCDetailKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [SheetNo] nvarchar(10) NOT NULL DEFAULT (' '),
    [CountNo] nvarchar(10) NOT NULL DEFAULT (' '),
    [Zone1] nvarchar(10) NOT NULL DEFAULT (' '),
    [Zone2] nvarchar(10) NOT NULL DEFAULT (' '),
    [Zone3] nvarchar(10) NOT NULL DEFAULT (' '),
    [Zone4] nvarchar(10) NOT NULL DEFAULT (' '),
    [Zone5] nvarchar(10) NOT NULL DEFAULT (' '),
    [Aisle] nvarchar(10) NOT NULL DEFAULT (' '),
    [Level] nvarchar(10) NOT NULL DEFAULT (' '),
    [Storerkey] nvarchar(10) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Lot] nvarchar(10) NOT NULL DEFAULT (' '),
    [Loc] nvarchar(10) NOT NULL DEFAULT (' '),
    [Id] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable01] nvarchar(18) NULL,
    [Lottable02] nvarchar(18) NULL,
    [Lottable03] nvarchar(18) NULL,
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [SystemQty] int NOT NULL DEFAULT ((0)),
    [CountedQty] int NOT NULL DEFAULT ((0)),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [RefNo] nvarchar(20) NULL DEFAULT (' '),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [Lottable06] nvarchar(30) NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    CONSTRAINT [PK_RDTCCLock] PRIMARY KEY ([RowRef])
);
GO

CREATE INDEX [IDX_RDTCCLock_CCKey_LOC] ON [rdt].[rdtcclock] ([CCKey], [Loc], [Status]);
GO