CREATE TABLE [rdt].[rdtmobrec_log]
(
    [Rowref] int IDENTITY(1,1) NOT NULL,
    [Mobile] int NOT NULL,
    [Func] int NOT NULL,
    [Scn] int NOT NULL,
    [Step] int NOT NULL,
    [Menu] int NOT NULL,
    [Lang_Code] nvarchar(3) NULL,
    [InputKey] int NOT NULL,
    [ErrMsg] nvarchar(125) NULL,
    [StorerKey] nvarchar(15) NULL,
    [Facility] nvarchar(5) NULL,
    [UserName] nvarchar(128) NOT NULL,
    [Printer] nvarchar(10) NULL,
    [MsgQueueNo] int NULL,
    [V_ReceiptKey] nvarchar(10) NULL,
    [V_POKey] nvarchar(10) NULL,
    [V_LoadKey] nvarchar(10) NULL,
    [V_OrderKey] nvarchar(10) NULL,
    [V_PickSlipNo] nvarchar(10) NULL,
    [V_Zone] nvarchar(10) NULL,
    [V_Loc] nvarchar(10) NULL,
    [V_SKU] nvarchar(20) NULL,
    [V_UOM] nvarchar(10) NULL,
    [V_ID] nvarchar(20) NULL,
    [V_ConsigneeKey] nvarchar(15) NULL,
    [V_CaseID] nvarchar(20) NULL,
    [V_SKUDescr] nvarchar(60) NULL,
    [V_QTY] int NULL,
    [V_UCC] nvarchar(20) NULL,
    [V_Lot] nvarchar(10) NULL,
    [V_Lottable01] nvarchar(18) NULL,
    [V_Lottable02] nvarchar(18) NULL,
    [V_Lottable03] nvarchar(18) NULL,
    [V_Lottable04] datetime NULL,
    [V_Lottable05] datetime NULL,
    [V_Lottable06] nvarchar(30) NULL,
    [V_Lottable07] nvarchar(30) NULL,
    [V_Lottable08] nvarchar(30) NULL,
    [V_Lottable09] nvarchar(30) NULL,
    [V_Lottable10] nvarchar(30) NULL,
    [V_Lottable11] nvarchar(30) NULL,
    [V_Lottable12] nvarchar(30) NULL,
    [V_Lottable13] datetime NULL,
    [V_Lottable14] datetime NULL,
    [V_Lottable15] datetime NULL,
    [V_LottableLabel01] nvarchar(20) NULL,
    [V_LottableLabel02] nvarchar(20) NULL,
    [V_LottableLabel03] nvarchar(20) NULL,
    [V_LottableLabel04] nvarchar(20) NULL,
    [V_LottableLabel05] nvarchar(20) NULL,
    [V_LottableLabel06] nvarchar(20) NULL,
    [V_LottableLabel07] nvarchar(20) NULL,
    [V_LottableLabel08] nvarchar(20) NULL,
    [V_LottableLabel09] nvarchar(20) NULL,
    [V_LottableLabel10] nvarchar(20) NULL,
    [V_LottableLabel11] nvarchar(20) NULL,
    [V_LottableLabel12] nvarchar(20) NULL,
    [V_LottableLabel13] nvarchar(20) NULL,
    [V_LottableLabel14] nvarchar(20) NULL,
    [V_LottableLabel15] nvarchar(20) NULL,
    [I_Field01] nvarchar(60) NULL,
    [I_Field02] nvarchar(60) NULL,
    [I_Field03] nvarchar(60) NULL,
    [I_Field04] nvarchar(60) NULL,
    [I_Field05] nvarchar(60) NULL,
    [I_Field06] nvarchar(60) NULL,
    [I_Field07] nvarchar(60) NULL,
    [I_Field08] nvarchar(60) NULL,
    [I_Field09] nvarchar(60) NULL,
    [I_Field10] nvarchar(60) NULL,
    [I_Field11] nvarchar(60) NULL,
    [I_Field12] nvarchar(60) NULL,
    [I_Field13] nvarchar(60) NULL,
    [I_Field14] nvarchar(60) NULL,
    [I_Field15] nvarchar(60) NULL,
    [O_Field01] nvarchar(60) NULL,
    [O_Field02] nvarchar(60) NULL,
    [O_Field03] nvarchar(60) NULL,
    [O_Field04] nvarchar(60) NULL,
    [O_Field05] nvarchar(60) NULL,
    [O_Field06] nvarchar(60) NULL,
    [O_Field07] nvarchar(60) NULL,
    [O_Field08] nvarchar(60) NULL,
    [O_Field09] nvarchar(60) NULL,
    [O_Field10] nvarchar(60) NULL,
    [O_Field11] nvarchar(60) NULL,
    [O_Field12] nvarchar(60) NULL,
    [O_Field13] nvarchar(60) NULL,
    [O_Field14] nvarchar(60) NULL,
    [O_Field15] nvarchar(60) NULL,
    [V_String1] nvarchar(20) NULL,
    [V_String2] nvarchar(20) NULL,
    [V_String3] nvarchar(20) NULL,
    [V_String4] nvarchar(20) NULL,
    [V_String5] nvarchar(20) NULL,
    [V_String6] nvarchar(20) NULL,
    [V_String7] nvarchar(20) NULL,
    [V_String8] nvarchar(20) NULL,
    [V_String9] nvarchar(20) NULL,
    [V_String10] nvarchar(20) NULL,
    [V_String11] nvarchar(20) NULL,
    [V_String12] nvarchar(20) NULL,
    [V_String13] nvarchar(20) NULL,
    [V_String14] nvarchar(20) NULL,
    [V_String15] nvarchar(20) NULL,
    [V_String16] nvarchar(20) NULL,
    [V_String17] nvarchar(20) NULL,
    [V_String18] nvarchar(20) NULL,
    [V_String19] nvarchar(20) NULL,
    [V_String20] nvarchar(20) NULL,
    [V_String21] nvarchar(20) NULL,
    [V_String22] nvarchar(20) NULL,
    [V_String23] nvarchar(20) NULL,
    [V_String24] nvarchar(20) NULL,
    [V_String25] nvarchar(20) NULL,
    [V_String26] nvarchar(20) NULL,
    [V_String27] nvarchar(20) NULL,
    [V_String28] nvarchar(20) NULL,
    [V_String29] nvarchar(20) NULL,
    [V_String30] nvarchar(20) NULL,
    [V_String31] nvarchar(20) NULL,
    [V_String32] nvarchar(20) NULL,
    [V_String33] nvarchar(20) NULL,
    [V_String34] nvarchar(20) NULL,
    [V_String35] nvarchar(20) NULL,
    [V_String36] nvarchar(20) NULL,
    [V_String37] nvarchar(20) NULL,
    [V_String38] nvarchar(20) NULL,
    [V_String39] nvarchar(20) NULL,
    [V_String40] nvarchar(20) NULL,
    [FieldAttr01] nvarchar(1) NULL,
    [FieldAttr02] nvarchar(1) NULL,
    [FieldAttr03] nvarchar(1) NULL,
    [FieldAttr04] nvarchar(1) NULL,
    [FieldAttr05] nvarchar(1) NULL,
    [FieldAttr06] nvarchar(1) NULL,
    [FieldAttr07] nvarchar(1) NULL,
    [FieldAttr08] nvarchar(1) NULL,
    [FieldAttr09] nvarchar(1) NULL,
    [FieldAttr10] nvarchar(1) NULL,
    [FieldAttr11] nvarchar(1) NULL,
    [FieldAttr12] nvarchar(1) NULL,
    [FieldAttr13] nvarchar(1) NULL,
    [FieldAttr14] nvarchar(1) NULL,
    [FieldAttr15] nvarchar(1) NULL,
    [AddDate] datetime NULL,
    [EditDate] datetime NULL,
    [Printer_Paper] nvarchar(10) NULL,
    [MenuStack] nvarchar(60) NULL,
    [V_TaskDetailKey] nvarchar(10) NULL,
    [V_Max] nvarchar(MAX) NOT NULL,
    [RemotePrint] int NULL,
    [DeviceID] nvarchar(20) NULL,
    [LightMode] nvarchar(10) NULL,
    [StorerGroup] nvarchar(20) NOT NULL,
    [V_StorerKey] nvarchar(15) NOT NULL,
    [V_String41] nvarchar(60) NULL,
    [V_String42] nvarchar(60) NULL,
    [V_String43] nvarchar(60) NULL,
    [V_String44] nvarchar(60) NULL,
    [V_String45] nvarchar(60) NULL,
    [V_String46] nvarchar(60) NULL,
    [V_String47] nvarchar(60) NULL,
    [V_String48] nvarchar(60) NULL,
    [V_String49] nvarchar(60) NULL,
    [V_String50] nvarchar(60) NULL,
    [V_WaveKey] nvarchar(10) NOT NULL,
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [LogDate] datetime NOT NULL DEFAULT (getdate()),
    [LogWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [AppName] nvarchar(1000) NOT NULL DEFAULT (''),
    [ProcID] nvarchar(1000) NOT NULL DEFAULT (''),
    [UserNameAfterLog] nvarchar(128) NOT NULL DEFAULT (''),
    [V_Cartonno] int NULL,
    [V_PUOM_Div] int NULL,
    [V_MQTY] int NULL,
    [V_PQTY] int NULL,
    [V_FromScn] int NULL,
    [V_FromStep] int NULL,
    [V_MTaskQty] int NULL,
    [V_PTaskQty] int NULL,
    [V_TaskQTY] int NULL,
    [V_Integer1] int NULL,
    [V_Integer2] int NULL,
    [V_Integer3] int NULL,
    [V_Integer4] int NULL,
    [V_Integer5] int NULL,
    [V_Integer6] int NULL,
    [V_Integer7] int NULL,
    [V_Integer8] int NULL,
    [V_Integer9] int NULL,
    [V_Integer10] int NULL,
    [V_Integer11] int NULL,
    [V_Integer12] int NULL,
    [V_Integer13] int NULL,
    [V_Integer14] int NULL,
    [V_Integer15] int NULL,
    [V_DateTime1] datetime NULL,
    [V_DateTime2] datetime NULL,
    [V_DateTime3] datetime NULL,
    [V_DateTime4] datetime NULL,
    [V_DateTime5] datetime NULL,
    [I_Field16] nvarchar(60) NOT NULL,
    [I_Field17] nvarchar(60) NOT NULL,
    [I_Field18] nvarchar(60) NOT NULL,
    [I_Field19] nvarchar(60) NOT NULL,
    [I_Field20] nvarchar(60) NOT NULL,
    [O_Field16] nvarchar(60) NOT NULL,
    [O_Field17] nvarchar(60) NOT NULL,
    [O_Field18] nvarchar(60) NOT NULL,
    [O_Field19] nvarchar(60) NOT NULL,
    [O_Field20] nvarchar(60) NOT NULL,
    [FieldAttr16] nvarchar(1) NOT NULL,
    [FieldAttr17] nvarchar(1) NOT NULL,
    [FieldAttr18] nvarchar(1) NOT NULL,
    [FieldAttr19] nvarchar(1) NOT NULL,
    [FieldAttr20] nvarchar(1) NOT NULL,
    [V_DropID] nvarchar(20) NOT NULL DEFAULT (''),
    [V_Barcode] nvarchar(MAX) NULL DEFAULT (''),
    CONSTRAINT [PK_rdtmobrec_log] PRIMARY KEY ([Rowref])
);
GO
