CREATE TABLE [rdt].[rdtmobrec]
(
    [Mobile] int NOT NULL,
    [Func] int NOT NULL DEFAULT ((0)),
    [Scn] int NOT NULL DEFAULT ((0)),
    [Step] int NOT NULL DEFAULT ((0)),
    [Menu] int NOT NULL DEFAULT ((0)),
    [Lang_Code] nvarchar(3) NULL,
    [InputKey] int NOT NULL,
    [ErrMsg] nvarchar(125) NULL,
    [StorerKey] nvarchar(15) NULL DEFAULT (''),
    [Facility] nvarchar(5) NULL,
    [UserName] nvarchar(128) NOT NULL DEFAULT ('RDT'),
    [Printer] nvarchar(10) NULL,
    [MsgQueueNo] int NULL DEFAULT ((0)),
    [V_ReceiptKey] nvarchar(10) NULL DEFAULT (''),
    [V_POKey] nvarchar(10) NULL,
    [V_LoadKey] nvarchar(10) NULL DEFAULT (''),
    [V_OrderKey] nvarchar(10) NULL DEFAULT (''),
    [V_PickSlipNo] nvarchar(10) NULL DEFAULT (''),
    [V_Zone] nvarchar(10) NULL DEFAULT (''),
    [V_Loc] nvarchar(10) NULL DEFAULT (''),
    [V_SKU] nvarchar(20) NULL DEFAULT (''),
    [V_UOM] nvarchar(10) NULL DEFAULT (''),
    [V_ID] nvarchar(20) NULL DEFAULT (''),
    [V_ConsigneeKey] nvarchar(15) NULL DEFAULT (''),
    [V_CaseID] nvarchar(20) NULL DEFAULT (''),
    [V_SKUDescr] nvarchar(60) NULL DEFAULT (''),
    [V_QTY] int NULL DEFAULT ((0)),
    [V_UCC] nvarchar(20) NULL DEFAULT (''),
    [V_Lot] nvarchar(10) NULL DEFAULT (''),
    [V_Lottable01] nvarchar(18) NULL DEFAULT (''),
    [V_Lottable02] nvarchar(18) NULL DEFAULT (''),
    [V_Lottable03] nvarchar(18) NULL DEFAULT (''),
    [V_Lottable04] datetime NULL,
    [V_Lottable05] datetime NULL,
    [V_Lottable06] nvarchar(30) NULL DEFAULT (''),
    [V_Lottable07] nvarchar(30) NULL DEFAULT (''),
    [V_Lottable08] nvarchar(30) NULL DEFAULT (''),
    [V_Lottable09] nvarchar(30) NULL DEFAULT (''),
    [V_Lottable10] nvarchar(30) NULL DEFAULT (''),
    [V_Lottable11] nvarchar(30) NULL DEFAULT (''),
    [V_Lottable12] nvarchar(30) NULL,
    [V_Lottable13] datetime NULL,
    [V_Lottable14] datetime NULL,
    [V_Lottable15] datetime NULL,
    [V_LottableLabel01] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel02] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel03] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel04] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel05] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel06] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel07] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel08] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel09] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel10] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel11] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel12] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel13] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel14] nvarchar(20) NULL DEFAULT (''),
    [V_LottableLabel15] nvarchar(20) NULL DEFAULT (''),
    [I_Field01] nvarchar(60) NULL,
    [I_Field02] nvarchar(60) NULL,
    [I_Field03] nvarchar(60) NULL,
    [I_Field04] nvarchar(60) NULL,
    [I_Field05] nvarchar(60) NULL,
    [I_Field06] nvarchar(60) NULL,
    [I_Field07] nvarchar(60) NULL,
    [I_Field08] nvarchar(60) NULL,
    [I_Field09] nvarchar(60) NULL,
    [I_Field10] nvarchar(60) NULL,
    [I_Field11] nvarchar(60) NULL,
    [I_Field12] nvarchar(60) NULL,
    [I_Field13] nvarchar(60) NULL,
    [I_Field14] nvarchar(60) NULL,
    [I_Field15] nvarchar(60) NULL,
    [O_Field01] nvarchar(60) NULL,
    [O_Field02] nvarchar(60) NULL,
    [O_Field03] nvarchar(60) NULL,
    [O_Field04] nvarchar(60) NULL,
    [O_Field05] nvarchar(60) NULL,
    [O_Field06] nvarchar(60) NULL,
    [O_Field07] nvarchar(60) NULL,
    [O_Field08] nvarchar(60) NULL,
    [O_Field09] nvarchar(60) NULL,
    [O_Field10] nvarchar(60) NULL,
    [O_Field11] nvarchar(60) NULL,
    [O_Field12] nvarchar(60) NULL,
    [O_Field13] nvarchar(60) NULL,
    [O_Field14] nvarchar(60) NULL,
    [O_Field15] nvarchar(60) NULL,
    [V_String1] nvarchar(20) NULL DEFAULT (''),
    [V_String2] nvarchar(20) NULL DEFAULT (''),
    [V_String3] nvarchar(20) NULL DEFAULT (''),
    [V_String4] nvarchar(20) NULL DEFAULT (''),
    [V_String5] nvarchar(20) NULL DEFAULT (''),
    [V_String6] nvarchar(20) NULL DEFAULT (''),
    [V_String7] nvarchar(20) NULL DEFAULT (''),
    [V_String8] nvarchar(20) NULL DEFAULT (''),
    [V_String9] nvarchar(20) NULL DEFAULT (''),
    [V_String10] nvarchar(20) NULL DEFAULT (''),
    [V_String11] nvarchar(20) NULL DEFAULT (''),
    [V_String12] nvarchar(20) NULL DEFAULT (''),
    [V_String13] nvarchar(20) NULL DEFAULT (''),
    [V_String14] nvarchar(20) NULL DEFAULT (''),
    [V_String15] nvarchar(20) NULL DEFAULT (''),
    [V_String16] nvarchar(20) NULL DEFAULT (''),
    [V_String17] nvarchar(20) NULL DEFAULT (''),
    [V_String18] nvarchar(20) NULL DEFAULT (''),
    [V_String19] nvarchar(20) NULL DEFAULT (''),
    [V_String20] nvarchar(20) NULL DEFAULT (''),
    [V_String21] nvarchar(20) NULL DEFAULT (''),
    [V_String22] nvarchar(20) NULL DEFAULT (''),
    [V_String23] nvarchar(20) NULL DEFAULT (''),
    [V_String24] nvarchar(20) NULL DEFAULT (''),
    [V_String25] nvarchar(20) NULL DEFAULT (''),
    [V_String26] nvarchar(20) NULL DEFAULT (''),
    [V_String27] nvarchar(20) NULL DEFAULT (''),
    [V_String28] nvarchar(20) NULL DEFAULT (''),
    [V_String29] nvarchar(20) NULL DEFAULT (''),
    [V_String30] nvarchar(20) NULL DEFAULT (''),
    [V_String31] nvarchar(20) NULL DEFAULT (''),
    [V_String32] nvarchar(20) NULL DEFAULT (''),
    [V_String33] nvarchar(20) NULL DEFAULT (''),
    [V_String34] nvarchar(20) NULL DEFAULT (''),
    [V_String35] nvarchar(20) NULL DEFAULT (''),
    [V_String36] nvarchar(20) NULL DEFAULT (''),
    [V_String37] nvarchar(20) NULL DEFAULT (''),
    [V_String38] nvarchar(20) NULL DEFAULT (''),
    [V_String39] nvarchar(20) NULL DEFAULT (''),
    [V_String40] nvarchar(20) NULL DEFAULT (''),
    [FieldAttr01] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr02] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr03] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr04] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr05] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr06] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr07] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr08] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr09] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr10] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr11] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr12] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr13] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr14] nvarchar(1) NULL DEFAULT (''),
    [FieldAttr15] nvarchar(1) NULL DEFAULT (''),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [Printer_Paper] nvarchar(10) NULL,
    [MenuStack] nvarchar(60) NULL DEFAULT (''),
    [V_TaskDetailKey] nvarchar(10) NULL DEFAULT (''),
    [V_Max] nvarchar(MAX) NOT NULL DEFAULT (''),
    [RemotePrint] int NULL DEFAULT ((0)),
    [DeviceID] nvarchar(20) NULL DEFAULT (''),
    [LightMode] nvarchar(10) NULL DEFAULT (''),
    [StorerGroup] nvarchar(20) NOT NULL DEFAULT (''),
    [V_StorerKey] nvarchar(15) NOT NULL DEFAULT (''),
    [V_String41] nvarchar(60) NULL DEFAULT (''),
    [V_String42] nvarchar(60) NULL DEFAULT (''),
    [V_String43] nvarchar(60) NULL DEFAULT (''),
    [V_String44] nvarchar(60) NULL DEFAULT (''),
    [V_String45] nvarchar(60) NULL DEFAULT (''),
    [V_String46] nvarchar(60) NULL DEFAULT (''),
    [V_String47] nvarchar(60) NULL DEFAULT (''),
    [V_String48] nvarchar(60) NULL DEFAULT (''),
    [V_String49] nvarchar(60) NULL DEFAULT (''),
    [V_String50] nvarchar(60) NULL DEFAULT (''),
    [V_WaveKey] nvarchar(10) NOT NULL DEFAULT (''),
    [V_Cartonno] int NULL DEFAULT ((0)),
    [V_PUOM_Div] int NULL DEFAULT ((0)),
    [V_MQTY] int NULL DEFAULT ((0)),
    [V_PQTY] int NULL DEFAULT ((0)),
    [V_FromScn] int NULL DEFAULT ((0)),
    [V_FromStep] int NULL DEFAULT ((0)),
    [V_MTaskQty] int NULL DEFAULT ((0)),
    [V_PTaskQty] int NULL DEFAULT ((0)),
    [V_TaskQTY] int NULL DEFAULT ((0)),
    [V_Integer1] int NULL DEFAULT ((0)),
    [V_Integer2] int NULL DEFAULT ((0)),
    [V_Integer3] int NULL DEFAULT ((0)),
    [V_Integer4] int NULL DEFAULT ((0)),
    [V_Integer5] int NULL DEFAULT ((0)),
    [V_Integer6] int NULL DEFAULT ((0)),
    [V_Integer7] int NULL DEFAULT ((0)),
    [V_Integer8] int NULL DEFAULT ((0)),
    [V_Integer9] int NULL DEFAULT ((0)),
    [V_Integer10] int NULL DEFAULT ((0)),
    [V_Integer11] int NULL DEFAULT ((0)),
    [V_Integer12] int NULL DEFAULT ((0)),
    [V_Integer13] int NULL DEFAULT ((0)),
    [V_Integer14] int NULL DEFAULT ((0)),
    [V_Integer15] int NULL DEFAULT ((0)),
    [V_DateTime1] datetime NULL DEFAULT (NULL),
    [V_DateTime2] datetime NULL DEFAULT (NULL),
    [V_DateTime3] datetime NULL DEFAULT (NULL),
    [V_DateTime4] datetime NULL DEFAULT (NULL),
    [V_DateTime5] datetime NULL DEFAULT (NULL),
    [I_Field16] nvarchar(60) NOT NULL DEFAULT (''),
    [I_Field17] nvarchar(60) NOT NULL DEFAULT (''),
    [I_Field18] nvarchar(60) NOT NULL DEFAULT (''),
    [I_Field19] nvarchar(60) NOT NULL DEFAULT (''),
    [I_Field20] nvarchar(60) NOT NULL DEFAULT (''),
    [O_Field16] nvarchar(60) NOT NULL DEFAULT (''),
    [O_Field17] nvarchar(60) NOT NULL DEFAULT (''),
    [O_Field18] nvarchar(60) NOT NULL DEFAULT (''),
    [O_Field19] nvarchar(60) NOT NULL DEFAULT (''),
    [O_Field20] nvarchar(60) NOT NULL DEFAULT (''),
    [FieldAttr16] nvarchar(1) NOT NULL DEFAULT (''),
    [FieldAttr17] nvarchar(1) NOT NULL DEFAULT (''),
    [FieldAttr18] nvarchar(1) NOT NULL DEFAULT (''),
    [FieldAttr19] nvarchar(1) NOT NULL DEFAULT (''),
    [FieldAttr20] nvarchar(1) NOT NULL DEFAULT (''),
    [V_DropID] nvarchar(20) NOT NULL DEFAULT (''),
    [V_SerialNo] nvarchar(30) NOT NULL DEFAULT (''),
    [V_Barcode] nvarchar(MAX) NOT NULL DEFAULT (''),
    [C_String1] nvarchar(250) NULL DEFAULT (''),
    [C_String2] nvarchar(250) NULL DEFAULT (''),
    [C_String3] nvarchar(250) NULL DEFAULT (''),
    [C_String4] nvarchar(250) NULL DEFAULT (''),
    [C_String5] nvarchar(250) NULL DEFAULT (''),
    [C_String6] nvarchar(250) NULL DEFAULT (''),
    [C_String7] nvarchar(250) NULL DEFAULT (''),
    [C_String8] nvarchar(250) NULL DEFAULT (''),
    [C_String9] nvarchar(250) NULL DEFAULT (''),
    [C_String10] nvarchar(250) NULL DEFAULT (''),
    [C_String11] nvarchar(250) NULL DEFAULT (''),
    [C_String12] nvarchar(250) NULL DEFAULT (''),
    [C_String13] nvarchar(250) NULL DEFAULT (''),
    [C_String14] nvarchar(250) NULL DEFAULT (''),
    [C_String15] nvarchar(250) NULL DEFAULT (''),
    [C_String16] nvarchar(250) NULL DEFAULT (''),
    [C_String17] nvarchar(250) NULL DEFAULT (''),
    [C_String18] nvarchar(250) NULL DEFAULT (''),
    [C_String19] nvarchar(250) NULL DEFAULT (''),
    [C_String20] nvarchar(250) NULL DEFAULT (''),
    [C_String21] nvarchar(250) NULL DEFAULT (''),
    [C_String22] nvarchar(250) NULL DEFAULT (''),
    [C_String23] nvarchar(250) NULL DEFAULT (''),
    [C_String24] nvarchar(250) NULL DEFAULT (''),
    [C_String25] nvarchar(250) NULL DEFAULT (''),
    [C_String26] nvarchar(250) NULL DEFAULT (''),
    [C_String27] nvarchar(250) NULL DEFAULT (''),
    [C_String28] nvarchar(250) NULL DEFAULT (''),
    [C_String29] nvarchar(250) NULL DEFAULT (''),
    [C_String30] nvarchar(250) NULL DEFAULT (''),
    [C_Integer1] int NOT NULL DEFAULT ((0)),
    [C_Integer2] int NOT NULL DEFAULT ((0)),
    [C_Integer3] int NOT NULL DEFAULT ((0)),
    [C_Integer4] int NOT NULL DEFAULT ((0)),
    [C_Integer5] int NOT NULL DEFAULT ((0)),
    [C_DateTime1] datetime NULL DEFAULT (NULL),
    [C_DateTime2] datetime NULL DEFAULT (NULL),
    [C_DateTime3] datetime NULL DEFAULT (NULL),
    [C_DateTime4] datetime NULL DEFAULT (NULL),
    [C_DateTime5] datetime NULL DEFAULT (NULL),
    [V_String51] nvarchar(60) NULL DEFAULT (''),
    CONSTRAINT [PK_RDTMOBREC] PRIMARY KEY ([Mobile])
);
GO

CREATE INDEX [IX_rdtMobRec_Username] ON [rdt].[rdtmobrec] ([UserName]);
GO