CREATE TABLE [rdt].[rdtprintjob]
(
    [JobId] int IDENTITY(1,1) NOT NULL,
    [JobName] nvarchar(50) NULL DEFAULT (''),
    [ReportID] nvarchar(10) NULL DEFAULT (''),
    [JobStatus] nvarchar(1) NULL DEFAULT ('0'),
    [NextRun] datetime NULL,
    [LastRun] datetime NULL,
    [Datawindow] nvarchar(50) NULL DEFAULT (''),
    [NoOfParms] int NULL DEFAULT ((0)),
    [Parm1] nvarchar(30) NULL,
    [Parm2] nvarchar(30) NULL,
    [Parm3] nvarchar(30) NULL,
    [Parm4] nvarchar(30) NULL,
    [Parm5] nvarchar(30) NULL,
    [Parm6] nvarchar(30) NULL,
    [Parm7] nvarchar(30) NULL,
    [Parm8] nvarchar(30) NULL,
    [Parm9] nvarchar(30) NULL,
    [Parm10] nvarchar(30) NULL,
    [Printer] nvarchar(50) NULL,
    [NoOfCopy] int NULL,
    [Mobile] int NULL,
    [TargetDB] nvarchar(20) NULL,
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL,
    [EditWho] nvarchar(128) NULL,
    [PrintCount] int NULL DEFAULT ((0)),
    [PrintData] nvarchar(MAX) NULL DEFAULT (''),
    [JobType] nvarchar(10) NULL DEFAULT ('DATAWINDOW'),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (''),
    [ExportFileName] nvarchar(50) NULL DEFAULT (''),
    [Function_ID] int NOT NULL DEFAULT ((0)),
    [Parm11] nvarchar(30) NULL,
    [Parm12] nvarchar(30) NULL,
    [Parm13] nvarchar(30) NULL,
    [Parm14] nvarchar(30) NULL,
    [Parm15] nvarchar(30) NULL,
    [Parm16] nvarchar(30) NULL,
    [Parm17] nvarchar(30) NULL,
    [Parm18] nvarchar(30) NULL,
    [Parm19] nvarchar(30) NULL,
    [Parm20] nvarchar(30) NULL,
    [ReportLineNo] nvarchar(5) NULL,
    [PDFPreview] char(1) NOT NULL DEFAULT ('N'),
    [CloudClientPrinterID] nvarchar(30) NOT NULL DEFAULT (''),
    [PaperSizeWxH] nvarchar(15) NOT NULL DEFAULT (''),
    [DCropWidth] nvarchar(10) NOT NULL DEFAULT ('0'),
    [DCropHeight] nvarchar(10) NOT NULL DEFAULT ('0'),
    [IsLandScape] nvarchar(1) NOT NULL DEFAULT ('0'),
    [IsColor] nvarchar(1) NOT NULL DEFAULT ('0'),
    [IsDuplex] nvarchar(1) NOT NULL DEFAULT ('0'),
    [IsCollate] nvarchar(1) NOT NULL DEFAULT ('0'),
    CONSTRAINT [PK_RDTPrintJob] PRIMARY KEY ([JobId])
);
GO

CREATE INDEX [IDX_RDTPrintJob_01] ON [rdt].[rdtprintjob] ([Mobile], [Printer]);
GO
CREATE INDEX [IDX_RDTPrintJob_03] ON [rdt].[rdtprintjob] ([JobStatus], [JobType], [JobId]);
GO