CREATE TABLE [rdt].[rdtpicklog]
(
    [RowRef] int IDENTITY(1,1) NOT NULL,
    [WaveKey] nvarchar(10) NULL,
    [LoadKey] nvarchar(10) NULL,
    [OrderKey] nvarchar(10) NULL,
    [PutawayZone] nvarchar(10) NULL,
    [PickZone] nvarchar(10) NULL,
    [OrderLineNumber] nvarchar(5) NULL,
    [PickDetailKey] nvarchar(10) NULL,
    [PickMethod] nvarchar(10) NULL,
    [StorerKey] nvarchar(15) NULL,
    [Sku] nvarchar(20) NULL,
    [Descr] nvarchar(60) NULL,
    [Loc] nvarchar(10) NULL,
    [Lot] nvarchar(10) NULL,
    [Id] nvarchar(18) NULL,
    [ActQty] int NULL DEFAULT ((0)),
    [PickLockQty] int NULL DEFAULT ((0)),
    [PickQty] int NULL DEFAULT ((0)),
    [TotalPickQty] int NULL DEFAULT ((0)),
    [UOM] nvarchar(10) NULL,
    [UOMQty] int NULL DEFAULT ((0)),
    [PackKey] nvarchar(10) NULL,
    [Lottable01] nvarchar(18) NULL,
    [Lottable02] nvarchar(18) NULL,
    [Lottable03] nvarchar(18) NULL,
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [PickSlipNo] nvarchar(10) NULL,
    [LogicalLocation] nvarchar(18) NULL,
    [Status] nvarchar(1) NULL DEFAULT ('0'),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [AddDate] datetime NULL DEFAULT (getdate()),
    [DropID] nvarchar(18) NULL,
    [Mobile] int NULL,
    [Remarks] nvarchar(60) NULL,
    [Lottable06] nvarchar(30) NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    CONSTRAINT [PKrdtPickLog] PRIMARY KEY ([RowRef])
);
GO
