CREATE TABLE [rdt].[rdtprintjob_log]
(
    [JobId] bigint NOT NULL,
    [JobName] nvarchar(50) NOT NULL DEFAULT (''),
    [ReportID] nvarchar(10) NOT NULL DEFAULT (''),
    [JobStatus] nvarchar(1) NOT NULL DEFAULT ('0'),
    [JobErrMsg] nvarchar(1000) NOT NULL DEFAULT (''),
    [NextRun] datetime NULL,
    [LastRun] datetime NULL,
    [Datawindow] nvarchar(50) NOT NULL DEFAULT (''),
    [NoOfParms] int NOT NULL DEFAULT ((0)),
    [Parm1] nvarchar(30) NULL,
    [Parm2] nvarchar(30) NULL,
    [Parm3] nvarchar(30) NULL,
    [Parm4] nvarchar(30) NULL,
    [Parm5] nvarchar(30) NULL,
    [Parm6] nvarchar(30) NULL,
    [Parm7] nvarchar(30) NULL,
    [Parm8] nvarchar(30) NULL,
    [Parm9] nvarchar(30) NULL,
    [Parm10] nvarchar(30) NULL,
    [Printer] nvarchar(50) NULL,
    [NoOfCopy] int NULL,
    [Mobile] int NULL,
    [TargetDB] nvarchar(20) NULL,
    [PrintCount] int NOT NULL DEFAULT ((0)),
    [PrintData] nvarchar(MAX) NOT NULL DEFAULT (''),
    [JobType] nvarchar(10) NOT NULL DEFAULT ('DATAWINDOW'),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (''),
    [ExportFileName] nvarchar(50) NOT NULL DEFAULT (''),
    [Parm11] nvarchar(30) NULL,
    [Parm12] nvarchar(30) NULL,
    [Parm13] nvarchar(30) NULL,
    [Parm14] nvarchar(30) NULL,
    [Parm15] nvarchar(30) NULL,
    [Parm16] nvarchar(30) NULL,
    [Parm17] nvarchar(30) NULL,
    [Parm18] nvarchar(30) NULL,
    [Parm19] nvarchar(30) NULL,
    [Parm20] nvarchar(30) NULL,
    [Function_ID] int NOT NULL DEFAULT ((0)),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nchar(1) NULL,
    [ArchiveCop] nchar(1) NULL,
    [RowRef] int IDENTITY(1,1) NOT NULL,
    [ReportLineNo] nvarchar(5) NULL,
    [PDFPreview] char(1) NOT NULL DEFAULT ('N'),
    [CloudClientPrinterID] nvarchar(30) NOT NULL DEFAULT (''),
    [PaperSizeWxH] nvarchar(15) NOT NULL DEFAULT (''),
    [DCropWidth] nvarchar(10) NOT NULL DEFAULT ('0'),
    [DCropHeight] nvarchar(10) NOT NULL DEFAULT ('0'),
    [IsLandScape] nvarchar(1) NOT NULL DEFAULT ('0'),
    [IsColor] nvarchar(1) NOT NULL DEFAULT ('0'),
    [IsDuplex] nvarchar(1) NOT NULL DEFAULT ('0'),
    [IsCollate] nvarchar(1) NOT NULL DEFAULT ('0'),
    CONSTRAINT [PK_RDTPrintJob_Log] PRIMARY KEY ([RowRef])
);
GO

CREATE INDEX [IX_RDTPrintJob_Log_JobID] ON [rdt].[rdtprintjob_log] ([JobId]);
GO