CREATE TABLE [rdt].[rdtreportdetail]
(
    [StorerKey] nvarchar(15) NOT NULL,
    [ReportType] nvarchar(10) NOT NULL,
    [RptDesc] nvarchar(60) NULL,
    [SUBPlatform] nvarchar(20) NOT NULL,
    [DataWindow] nvarchar(50) NOT NULL DEFAULT (''),
    [TargetDB] nvarchar(20) NULL,
    [AddDate] datetime NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditWho] nvarchar(128) NULL DEFAULT (suser_sname()),
    [EditDate] datetime NULL DEFAULT (getdate()),
    [parm1_label] nvarchar(30) NULL,
    [parm2_label] nvarchar(30) NULL,
    [parm3_label] nvarchar(30) NULL,
    [parm4_label] nvarchar(30) NULL,
    [parm5_label] nvarchar(30) NULL,
    [parm6_label] nvarchar(30) NULL,
    [parm7_label] nvarchar(30) NULL,
    [parm8_label] nvarchar(30) NULL,
    [parm9_label] nvarchar(30) NULL,
    [parm10_label] nvarchar(30) NULL,
    [PrintTemplate] nvarchar(MAX) NULL DEFAULT (''),
    [PrintTemplateSP] nvarchar(40) NULL DEFAULT (''),
    [Function_ID] int NOT NULL DEFAULT ((0)),
    [ProcessType] nvarchar(15) NOT NULL DEFAULT (''),
    [ProcessSP] nvarchar(50) NOT NULL DEFAULT (''),
    [PaperType] nvarchar(10) NOT NULL DEFAULT (''),
    [NoOfCopy] int NOT NULL DEFAULT ((1)),
    [Facility] nvarchar(5) NOT NULL DEFAULT (''),
    [JReportCatalog] nvarchar(100) NULL,
    [JReportFileName] nvarchar(250) NULL,
    [JReportFlag] nvarchar(10) NULL,
    [ReportLineDesc] nvarchar(60) NULL DEFAULT (''),
    [ReportFormat] nvarchar(1) NOT NULL DEFAULT (''),
    [ReportParmName1] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName2] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName3] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName4] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName5] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName6] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName7] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName8] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName9] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName10] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName11] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName12] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName13] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName14] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName15] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName16] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName17] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName18] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName19] nvarchar(100) NOT NULL DEFAULT (''),
    [ReportParmName20] nvarchar(100) NOT NULL DEFAULT (''),
    [PreGenRptDataSP] nvarchar(50) NOT NULL DEFAULT (''),
    [AutoPrint] nvarchar(1) NOT NULL DEFAULT ('N'),
    [PrintSettings] nvarchar(4000) NOT NULL DEFAULT (''),
    [PostPrintSP] nvarchar(50) NULL,
    [PaperSizeWxH] nvarchar(15) NOT NULL DEFAULT (''),
    [DCropWidth] nvarchar(10) NOT NULL DEFAULT ('0'),
    [DCropHeight] nvarchar(10) NOT NULL DEFAULT ('0'),
    [IsLandScape] nvarchar(1) NOT NULL DEFAULT ('0'),
    [IsColor] nvarchar(1) NOT NULL DEFAULT ('0'),
    [IsDuplex] nvarchar(1) NOT NULL DEFAULT ('0'),
    [IsCollate] nvarchar(1) NOT NULL DEFAULT ('0'),
    [IsPaperPrinter] nvarchar(1) NOT NULL DEFAULT (''),
    [DefaultPrinterID] nvarchar(30) NOT NULL DEFAULT (''),
    [PrintNextOnFail] int NOT NULL DEFAULT ((0)),
    [FileFolder] nvarchar(200) NOT NULL DEFAULT (''),
    [SQL_Select] nvarchar(MAX) NOT NULL DEFAULT (''),
    CONSTRAINT [PK_RDTReportDetail] PRIMARY KEY ([StorerKey], [ReportType], [SUBPlatform], [Function_ID], [Facility])
);
GO
