CREATE TABLE [rdt].[rdtreceiptlog]
(
    [ReceiptKey] nvarchar(10) NOT NULL,
    [ReceiptLineNumber] nvarchar(5) NOT NULL DEFAULT (' '),
    [ExternReceiptKey] nvarchar(20) NOT NULL DEFAULT (' '),
    [ExternPOKey] nvarchar(20) NULL DEFAULT (' '),
    [ExternLineNo] nvarchar(20) NOT NULL DEFAULT (' '),
    [StorerKey] nvarchar(15) NOT NULL DEFAULT (' '),
    [POKey] nvarchar(18) NOT NULL DEFAULT (' '),
    [Sku] nvarchar(20) NOT NULL DEFAULT (' '),
    [AltSku] nvarchar(20) NOT NULL DEFAULT (' '),
    [Id] nvarchar(18) NOT NULL DEFAULT (' '),
    [Status] nvarchar(10) NOT NULL DEFAULT ('0'),
    [QtyExpected] int NOT NULL DEFAULT ((0)),
    [QtyReceived] int NOT NULL DEFAULT ((0)),
    [UOM] nvarchar(10) NOT NULL DEFAULT (' '),
    [PackKey] nvarchar(10) NOT NULL DEFAULT (' '),
    [ToLoc] nvarchar(10) NOT NULL,
    [ToLot] nvarchar(10) NULL,
    [ToId] nvarchar(18) NULL DEFAULT (' '),
    [DropID] nvarchar(20) NULL DEFAULT (' '),
    [ConditionCode] nvarchar(10) NOT NULL DEFAULT (' '),
    [Lottable01] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable02] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable03] nvarchar(18) NOT NULL DEFAULT (' '),
    [Lottable04] datetime NULL,
    [Lottable05] datetime NULL,
    [PutawayLoc] nvarchar(10) NULL DEFAULT (' '),
    [RefNo] nvarchar(20) NULL DEFAULT (' '),
    [AddDate] datetime NOT NULL DEFAULT (getdate()),
    [AddWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [EditDate] datetime NOT NULL DEFAULT (getdate()),
    [EditWho] nvarchar(128) NOT NULL DEFAULT (suser_sname()),
    [TrafficCop] nvarchar(1) NULL,
    [ArchiveCop] nvarchar(1) NULL,
    [Lottable06] nvarchar(30) NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    CONSTRAINT [PK_rdtReceiptLog] PRIMARY KEY ([ReceiptKey], [ReceiptLineNumber], [StorerKey], [Sku])
);
GO
