CREATE TABLE [rdt].[rdtstdeventlog]
(
    [EventNum] int IDENTITY(1,1) NOT NULL,
    [EventType] int NOT NULL DEFAULT ((0)),
    [ActionType] nvarchar(30) NOT NULL DEFAULT (''),
    [EventDateTime] datetime NOT NULL DEFAULT (getdate()),
    [UserID] nvarchar(128) NULL DEFAULT (''),
    [MobileNo] int NULL DEFAULT ((0)),
    [FunctionID] int NULL DEFAULT ((0)),
    [Facility] nvarchar(5) NULL DEFAULT (''),
    [StorerKey] nvarchar(15) NULL DEFAULT (''),
    [Location] nvarchar(30) NULL DEFAULT (''),
    [ToLocation] nvarchar(10) NULL DEFAULT (''),
    [PutawayZone] nvarchar(10) NULL DEFAULT (''),
    [PickZone] nvarchar(10) NULL DEFAULT (''),
    [ID] nvarchar(18) NULL DEFAULT (''),
    [ToID] nvarchar(18) NULL DEFAULT (''),
    [SKU] nvarchar(20) NULL DEFAULT (''),
    [ComponentSKU] nvarchar(20) NULL DEFAULT (''),
    [UOM] nvarchar(10) NULL DEFAULT (''),
    [QTY] int NULL DEFAULT ((0)),
    [Lot] nvarchar(10) NULL DEFAULT (''),
    [ToLot] nvarchar(10) NULL DEFAULT (''),
    [Lottable01] nvarchar(18) NULL DEFAULT (''),
    [Lottable02] nvarchar(18) NULL DEFAULT (''),
    [Lottable03] nvarchar(18) NULL DEFAULT (''),
    [Lottable04] datetime NULL DEFAULT (''),
    [Lottable05] datetime NULL DEFAULT (''),
    [RefNo1] nvarchar(20) NULL DEFAULT (''),
    [RefNo2] nvarchar(20) NULL DEFAULT (''),
    [RefNo3] nvarchar(20) NULL DEFAULT (''),
    [RefNo4] nvarchar(20) NULL DEFAULT (''),
    [RefNo5] nvarchar(20) NULL DEFAULT (''),
    [ArchiveCop] nvarchar(1) NULL,
    [RowRef] int NULL DEFAULT ((0)),
    [ReceiptKey] nvarchar(10) NULL DEFAULT (''),
    [POKey] nvarchar(10) NULL DEFAULT (''),
    [LoadKey] nvarchar(10) NULL DEFAULT (''),
    [OrderKey] nvarchar(10) NULL DEFAULT (''),
    [PickSlipNo] nvarchar(10) NULL DEFAULT (''),
    [DropID] nvarchar(20) NULL DEFAULT (''),
    [TaskDetailKey] nvarchar(10) NULL DEFAULT (''),
    [Lottable06] nvarchar(30) NULL DEFAULT (''),
    [Lottable07] nvarchar(30) NULL DEFAULT (''),
    [Lottable08] nvarchar(30) NULL DEFAULT (''),
    [Lottable09] nvarchar(30) NULL DEFAULT (''),
    [Lottable10] nvarchar(30) NULL DEFAULT (''),
    [Lottable11] nvarchar(30) NULL DEFAULT (''),
    [Lottable12] nvarchar(30) NULL DEFAULT (''),
    [Lottable13] datetime NULL,
    [Lottable14] datetime NULL,
    [Lottable15] datetime NULL,
    [WaveKey] nvarchar(10) NULL DEFAULT (''),
    [TrackingNo] nvarchar(30) NULL DEFAULT (''),
    [AreaKey] nvarchar(10) NULL DEFAULT (''),
    [TTMStrategyKey] nvarchar(10) NULL DEFAULT (''),
    [ListKey] nvarchar(10) NULL DEFAULT (''),
    [UCC] nvarchar(20) NULL DEFAULT (''),
    [ReplenishmentKey] nvarchar(10) NULL DEFAULT (''),
    [DeviceID] nvarchar(20) NULL DEFAULT (''),
    [DevicePosition] nvarchar(10) NULL DEFAULT (''),
    [ToUCC] nvarchar(20) NULL DEFAULT (''),
    [SourceKey] nvarchar(20) NULL DEFAULT (''),
    [LabelNo] nvarchar(20) NULL DEFAULT (''),
    [CCKey] nvarchar(10) NULL DEFAULT (''),
    [SuggestedLOC] nvarchar(10) NULL DEFAULT (''),
    [CaseID] nvarchar(20) NULL DEFAULT (''),
    [ReasonKey] nvarchar(10) NULL DEFAULT (''),
    [TaskType] nvarchar(10) NULL DEFAULT (''),
    [ExpectedQty] int NULL DEFAULT ('0'),
    [SerialNo] nvarchar(50) NULL DEFAULT (''),
    [PickMethod] nvarchar(10) NULL DEFAULT (''),
    [Step] int NULL DEFAULT ('0'),
    [Status] nvarchar(10) NULL DEFAULT ('0'),
    [RDTOption] nvarchar(1) NULL DEFAULT (''),
    [PUOM_Desc] nvarchar(5) NULL DEFAULT (''),
    [MUOM_Desc] nvarchar(5) NULL DEFAULT (''),
    [PQTY] int NULL DEFAULT ('0'),
    [ConsigneeKey] nvarchar(15) NULL DEFAULT (''),
    [CCSheetNo] nvarchar(10) NULL DEFAULT (''),
    [SealNo] nvarchar(20) NULL DEFAULT (''),
    [MBOLKey] nvarchar(10) NULL DEFAULT (''),
    [ContainerNo] nvarchar(20) NULL DEFAULT (''),
    [LicenseNo] nvarchar(20) NULL DEFAULT (''),
    [TruckID] nvarchar(40) NULL DEFAULT (''),
    [Remark] nvarchar(20) NULL DEFAULT (''),
    [ToLabelNo] nvarchar(20) NULL DEFAULT (''),
    [ExternKitKey] nvarchar(20) NULL DEFAULT (''),
    [ChildID] nvarchar(20) NULL DEFAULT (''),
    [Lane] nvarchar(20) NULL DEFAULT (''),
    [SSCC] nvarchar(20) NULL DEFAULT (''),
    [SerialNoKey] nvarchar(10) NULL DEFAULT (''),
    [Scn] int NULL DEFAULT ('0'),
    [CartonType] nvarchar(10) NULL DEFAULT (''),
    [Weight] float NULL DEFAULT ('0'),
    [ReplenishmentGroup] nvarchar(10) NULL DEFAULT (''),
    [Length] float NULL DEFAULT ('0'),
    [Width] float NULL DEFAULT ('0'),
    [Height] float NULL DEFAULT ('0'),
    [OptionDefinition] nvarchar(50) NULL DEFAULT (''),
    [TransType] nvarchar(128) NULL DEFAULT (''),
    [CountNo] int NULL DEFAULT ((0)),
    [CartonID] nvarchar(20) NULL DEFAULT (''),
    [Barcode] nvarchar(100) NULL DEFAULT (''),
    [ContainerKey] nvarchar(20) NULL DEFAULT (''),
    [CartonNo] int NULL DEFAULT ((0)),
    [Cube] float NULL DEFAULT ((0)),
    CONSTRAINT [PK_rdtSTDEventLog] PRIMARY KEY ([EventNum])
);
GO

CREATE INDEX [idx_rdtSTDEventLog] ON [rdt].[rdtstdeventlog] ([Facility], [StorerKey], [EventType], [FunctionID], [MobileNo], [UserID]);
GO
CREATE INDEX [idx_rdtSTDEventLog_Func] ON [rdt].[rdtstdeventlog] ([FunctionID], [Facility], [StorerKey], [ActionType], [MobileNo]);
GO