CREATE TABLE [rdt].[rdtuser]
(
    [UserName] nvarchar(128) NOT NULL,
    [Password] nvarchar(32) NOT NULL,
    [FullName] nvarchar(80) NULL,
    [DefaultStorer] nvarchar(15) NULL,
    [DefaultFacility] nvarchar(5) NULL,
    [DefaultLangCode] nvarchar(3) NULL,
    [DefaultMenu] int NULL,
    [DefaultUOM] nvarchar(10) NULL,
    [LastLogin] datetime NULL DEFAULT (getdate()),
    [MultiLogin] nvarchar(1) NULL DEFAULT ('Y'),
    [DefaultPrinter] nvarchar(10) NULL,
    [MobileNo_Display] nvarchar(1) NULL DEFAULT ('Y'),
    [Date_Format] nvarchar(3) NULL DEFAULT (' '),
    [SQLUserAddDate] datetime NULL,
    [DefaultPrinter_Paper] nvarchar(10) NULL,
    [Active] nvarchar(1) NULL DEFAULT ('1'),
    [DefaultLightColor] nvarchar(10) NULL DEFAULT (''),
    [DefaultStorerGroup] nvarchar(20) NOT NULL DEFAULT (''),
    [VoiceProfileNo] nvarchar(10) NULL,
    [DefaultDeviceID] nvarchar(20) NOT NULL DEFAULT (''),
    [AreaKey] nvarchar(10) NOT NULL DEFAULT (''),
    [ModulesDirectAccess] nvarchar(1) NULL DEFAULT ('0'),
    [OPSPosition] nvarchar(60) NOT NULL DEFAULT (''),
    [AllowResumeSession] nvarchar(1) NULL DEFAULT (''),
    [SCEPrinterGroup] nvarchar(20) NOT NULL DEFAULT (''),
    [ScreenFormat] nvarchar(20) NOT NULL DEFAULT (''),
    [SoundLevel] nvarchar(10) NOT NULL DEFAULT (''),
    [VibrationLevel] nvarchar(10) NOT NULL DEFAULT (''),
    [FirstDayOfWeek] tinyint NULL,
    CONSTRAINT [PK_RDTUser] PRIMARY KEY ([UserName]),
    CONSTRAINT [CK_RDTUser_FirstDayOfWeek] CHECK ([FirstDayOfWeek]=(1) OR [FirstDayOfWeek]=(7) OR [FirstDayOfWeek]=NULL)
);
GO
